SELECT MAX(salary) OVER (PARTITION BY depname), salary, empno, depname from empsalary3 where empno < 10000;
SELECT MAX(salary) OVER (PARTITION BY depname ORDER BY empno), salary, empno, depname from empsalary3 where empno < 10000;
SELECT MAX(salary) OVER (PARTITION BY depname ORDER BY salary NULLS FIRST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT MAX(salary) OVER (PARTITION BY depname ORDER BY salary NULLS LAST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT MAX(salary) OVER (PARTITION BY depname ORDER BY salary RANGE UNBOUNDED PRECEDING), salary, empno, depname from empsalary3 where empno < 10000;
SELECT MAX(salary) OVER (PARTITION BY depname ORDER BY empno ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT MAX(salary) OVER (PARTITION BY depname ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT MIN(salary) OVER (PARTITION BY depname), salary, empno, depname from empsalary3 where empno < 10000;
SELECT MIN(salary) OVER (PARTITION BY depname ORDER BY empno), salary, empno, depname from empsalary3 where empno < 10000;
SELECT MIN(salary) OVER (PARTITION BY depname ORDER BY salary NULLS FIRST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT MIN(salary) OVER (PARTITION BY depname ORDER BY salary NULLS LAST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT MIN(salary) OVER (PARTITION BY depname ORDER BY salary RANGE 200 preceding), salary, empno, depname from empsalary3 where empno < 10000;
SELECT MIN(salary) OVER (PARTITION BY depname ORDER BY empno ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT MIN(salary) OVER (PARTITION BY depname ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT COUNT(*) OVER (PARTITION BY depname), salary, empno, depname from empsalary3 where empno < 10000;
SELECT COUNT(*) OVER (PARTITION BY depname ORDER BY empno), salary, empno, depname from empsalary3 where empno < 10000;
SELECT COUNT(*) OVER (PARTITION BY depname ORDER BY salary NULLS FIRST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT COUNT(*) OVER (PARTITION BY depname ORDER BY salary NULLS LAST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT COUNT(*) OVER (PARTITION BY depname ORDER BY salary RANGE 200 preceding), salary, empno, depname from empsalary3 where empno < 10000;
SELECT COUNT(*) OVER (PARTITION BY depname ORDER BY empno ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT COUNT(*) OVER (PARTITION BY depname ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT COUNT(DISTINCT salary) OVER (PARTITION BY depname), salary, empno, depname from empsalary3 where empno < 10000;
SELECT COUNT(DISTINCT salary) OVER (PARTITION BY depname ORDER BY empno), salary, empno, depname from empsalary3 where empno < 10000;
SELECT COUNT(DISTINCT salary) OVER (PARTITION BY depname ORDER BY salary NULLS FIRST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT COUNT(DISTINCT salary) OVER (PARTITION BY depname ORDER BY salary NULLS LAST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT COUNT(DISTINCT salary) OVER (PARTITION BY depname ORDER BY salary RANGE 200 preceding), salary, empno, depname from empsalary3 where empno < 10000;
SELECT COUNT(DISTINCT salary) OVER (PARTITION BY depname ORDER BY empno ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT COUNT(DISTINCT salary) OVER (PARTITION BY depname ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT SUM(salary) OVER (PARTITION BY depname), salary, empno, depname from empsalary3 where empno < 10000;
SELECT SUM(salary) OVER (PARTITION BY depname ORDER BY empno), salary, empno, depname from empsalary3 where empno < 10000;
SELECT SUM(salary) OVER (PARTITION BY depname ORDER BY salary NULLS FIRST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT SUM(salary) OVER (PARTITION BY depname ORDER BY salary NULLS LAST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT SUM(salary) OVER (PARTITION BY depname ORDER BY salary RANGE 200 preceding), salary, empno, depname from empsalary3 where empno < 10000;
SELECT SUM(salary) OVER (PARTITION BY depname ORDER BY empno ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT SUM(salary) OVER (PARTITION BY depname ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT AVG(salary) OVER (PARTITION BY depname), salary, empno, depname from empsalary3 where empno < 10000;
SELECT AVG(salary) OVER (PARTITION BY depname ORDER BY empno), salary, empno, depname from empsalary3 where empno < 10000;
SELECT AVG(salary) OVER (PARTITION BY depname ORDER BY salary NULLS FIRST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT AVG(salary) OVER (PARTITION BY depname ORDER BY salary NULLS LAST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT AVG(salary) OVER (PARTITION BY depname ORDER BY salary RANGE 200 preceding), salary, empno, depname from empsalary3 where empno < 10000;
SELECT AVG(salary) OVER (PARTITION BY depname ORDER BY empno ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT AVG(salary) OVER (PARTITION BY depname ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT AVG(DISTINCT salary) OVER (PARTITION BY depname), salary, empno, depname from empsalary3 where empno < 10000;
SELECT AVG(DISTINCT salary) OVER (PARTITION BY depname ORDER BY empno), salary, empno, depname from empsalary3 where empno < 10000;
SELECT AVG(DISTINCT salary) OVER (PARTITION BY depname ORDER BY salary NULLS FIRST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT AVG(DISTINCT salary) OVER (PARTITION BY depname ORDER BY salary NULLS LAST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT AVG(DISTINCT salary) OVER (PARTITION BY depname ORDER BY salary RANGE 200 preceding), salary, empno, depname from empsalary3 where empno < 10000;
SELECT AVG(DISTINCT salary) OVER (PARTITION BY depname ORDER BY empno ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT AVG(DISTINCT salary) OVER (PARTITION BY depname ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;

SELECT MAX(salary) OVER (PARTITION BY depname ORDER BY enroll_date ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING ), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT MIN(salary) OVER (PARTITION BY depname ORDER BY empno ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT COUNT(*) OVER (PARTITION BY depname ORDER BY enroll_date ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT COUNT(DISTINCT salary) OVER (PARTITION BY depname ORDER BY empno ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT SUM(salary) OVER (PARTITION BY depname ORDER BY enroll_date ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT AVG(salary) OVER (PARTITION BY depname ORDER BY  enroll_date ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT AVG(DISTINCT salary) OVER (PARTITION BY depname ORDER BY  enroll_date ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;

SELECT MAX(salary) OVER (PARTITION BY depname ORDER BY enroll_date ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING ), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT MAX(salary) OVER (PARTITION BY depname ORDER BY enroll_date RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING ), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT MIN(salary) OVER (PARTITION BY depname ORDER BY empno ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT MIN(salary) OVER (PARTITION BY depname ORDER BY empno RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT COUNT(*) OVER (PARTITION BY depname ORDER BY enroll_date ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT COUNT(*) OVER (PARTITION BY depname ORDER BY enroll_date RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT SUM(salary) OVER (PARTITION BY depname ORDER BY enroll_date ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT SUM(salary) OVER (PARTITION BY depname ORDER BY enroll_date RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT AVG(salary) OVER (PARTITION BY depname ORDER BY  enroll_date ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT AVG(salary) OVER (PARTITION BY depname ORDER BY  enroll_date RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
