--
-- Second field of record 11 contains:
--   gn-generic-Hoo'H,a\``a"182243987
--
-- Note that this is a string with an enclosed backslash.
-- When this sql is executed in MySQL, or by running MySQL client with -e,
-- the output is:
--   gn-generic-Hoo'H,a\``a"182243987
--
-- However this regression test is setup to run the MySQL client by reading
-- the sql from STDIN.   In this mode MySQL inserts an extra backslash in
-- front of the backslash embedded in record 11.   The output ends up being:
--   gn-generic-Hoo'H,a\\``a"182243987
--
select * from bug4916enclosedbdry;
