drop table if exists stringtest;
create table stringtest (c1 char(10), c2 varchar(10), c3 varchar(6))engine=infinidb;
insert into stringtest values ('abc','cde','abc'), ('cde','abc','cde');
select * from stringtest where c1='abc' or c2='abc';
select * from stringtest where c1= 'abc ';
select * from stringtest where c2='abc  ';
select * from stringtest where c1='abc ' or c2='abc  ';
select * from stringtest where c1 = 'abc' or c3='cde  ';
select concat('abc ', c2), concat('cde ', c3) from stringtest;
drop table stringtest;
