drop table if exists looooooooooooooooooooooooooooooooooooooooong_tb_name;
create table looooooooooooooooooooooooooooooooooooooooong_tb_name (looooooooooooooooooooooooooooooooooooooooong_col_name int)engine=infinidb;
insert into looooooooooooooooooooooooooooooooooooooooong_tb_name values (10);
select looooooooooooooooooooooooooooooooooooooooong_col_name from looooooooooooooooooooooooooooooooooooooooong_tb_name 
order by isnull(looooooooooooooooooooooooooooooooooooooooong_col_name);
select concat('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', looooooooooooooooooooooooooooooooooooooooong_col_name) from looooooooooooooooooooooooooooooooooooooooong_tb_name;
drop table looooooooooooooooooooooooooooooooooooooooong_tb_name;
