-- From http://www.fluffycat.com/SQL/Subselect/.
drop table if exists director_film_table;
drop table if exists film_table;
drop table if exists thespian_table;
drop table if exists thespian_film_table;

create table director_film_table (
director_last_name varchar(30),
director_first_name varchar(30),
film_title varchar(60)
)engine=infinidb;

create table film_table (
Film_Title varchar(60),
Film_Year int,
film_length int
)engine=infinidb;

create table thespian_table (
Thespian_Last_Name varchar(30), 
Thespian_First_Name varchar(30)
)engine=infinidb;

create table thespian_Film_Table (
Thespian_Last_Name varchar(30),
Thespian_First_Name varchar(30),
film_title varchar(60)
)engine=infinidb;


insert into director_film_table values
("Cameron", "James", "Aliens"),
("Coppola", "Francis Ford", "The Godfather"),
("Coppola", "Francis Ford", "The Godfather Part II"),
("Coppola", "Francis Ford", "The Godfather Part III"),
("Lucas", "George", "American Graffiti"),
("Lucas", "George", "Star Wars"),
("Stanley", "Kubrick", "A Clockwork Orange"),
("Stanley", "Kubrick", "Barry Lyndon"),
("Stanley", "Kubrick", "Dr. Strangelove"),
("Stanley", "Kubrick", "Eyes Wide Shut"),
("Stanley", "Kubrick", "Full Metal Jacket"),
("Stanley", "Kubrick", "Killer's Kiss"),
("Stanley", "Kubrick", "The Killing"),
("Stanley", "Kubrick", "Lolita"),
("Stanley", "Kubrick", "Paths of Glory"),
("Stanley", "Kubrick", "The Shining"),
("Stanley", "Kubrick", "Spartacus"),
("Stanley", "Kubrick", "2001: A Space Odyssey"),
("Waters", "John", "A Dirty Shame"),
("Waters", "John", "Cecil B. DeMented"),
("Waters", "John", "Cry-Baby"),
("Waters", "John", "Desperate Living"),
("Waters", "John", "Female Trouble"),
("Waters", "John", "Hairspray"),
("Waters", "John", "Pecker"),
("Waters", "John", "Pink Flamingos"),
("Waters", "John", "Polyester"),
("Waters", "John", "Serial Mom");

show warnings;

insert into film_table values
("A Nous la Liberteus", 1932, 87),
("Aaron Loves Angela", 1975, 99),
("Abbott and Costello go to Mars", 1953, 77),
("Abbott and Costello in Hollywood", 1945, 111),
("Abbott and Costello in the Foreign Legion", 1950, 80),
("Abbott and Costello Meet Captain Kidd", 1952, 70),
("Abbott and Costello Meet Dr. Jeckyl and Mr. Hyde", 1952, 77),
("Abbott and Costello Meet Frankenstein", 1948, 83),
("Abbott and Costello Meet the Invisible Man", 1951, 82),
("Abbott and Costello Meet the Keystone Cops", 1954, 79),
("American Pie", 1999, 99),
("American Pie 2", 2001, 115),
("Andy Hard Meets Debutante", 1940, 120),
("As Good As It Gets", 1997, 123),
("Babes in Arms", 1939, 120),
("Babes on Broadway", 1941, 120),
("Big Daddy", 1999, 115),
("A Child is Waiting", 1963, 120),
("Caddyshack", 1980, 121),
("Clock - The", 1945, 120),
("Easter Parade", 1948, 120),
("Everybody Sing", 1938, 120),
("For Me and my Gal", 1942, 120),
("Ghostbusters", 1984, 120),
("Girl Crazy", 1943, 120),
("Harvey Girls - The", 1946, 120),
("Hercules", 1997, 90),
("I Could Go on Singing", 1963, 120),
("In the Good Old Summertime", 1949, 120),
("Indiana Jones and the Temple of Doom", 1984, 130),
("Judgement at Nuremberg", 1961, 120),
("Life Begins for Andy Hardy", 1941, 120),
("Listen - Darling", 1938, 120),
("Little Nelly Kelly", 1940, 120),
("Love Finds Andy Hardy", 1938, 120),
("Mars Attacks", 1995, 120),
("Meet Me in St. Louis", 1944, 120),
("Mulan", 1998, 90),
("Pinocchio", 1940, 80),
("Pirate - The", 1948, 120),
("Presenting Lily Mars", 1943, 120),
("Rushmore", 1998, 99),
("Star is Born - A", 1954, 120),
("Strictly G.I.", 1944, 120),
("Strike Up the Band", 1940, 120),
("The Waterboy", 1998, 110),
("The Wedding Singer", 1998, 120),
("Thoroughbreads Don't Cry", 1937, 120),
("Thousands Cheer", 1943, 120),
("Till the Clouds Roll By", 1946, 120),
("The Lady and the Tramp", 1955, 80),
("The Little Mermaid", 1989, 85),
("The Godfather", 1973, 180),
("The Godfather Part II", 1975, 167),
("The Godfather Part III", 1978, 177),
("Twister", 1996, 120),
("Wizard of Oz - The", 1939, 120),
("Ziegfield Follies", 1946, 120),
("Ziegfeld Girl", 1941, 120);

show warnings;

insert into thespian_film_table values
("Bergman", "Ingrid", "A Matter of Time"),
("Bergman", "Ingrid", "A Woman's Face"),
("Bergman", "Ingrid", "Adam Had Four Sons"),
("Bergman", "Ingrid", "American Creed"),
("Bergman", "Ingrid", "Anastasia"),
("Bergman", "Ingrid", "Arch of Triumph"),
("Bergman", "Ingrid", "Autumn Sonata"),
("Bergman", "Ingrid", "Cactus Flower"),
("Bergman", "Ingrid", "Casablanca"),
("Bergman", "Ingrid", "Dollar"),
("Bergman", "Ingrid", "Dr. Jekyll and Mr. Hyde"),
("Bergman", "Ingrid", "Fear"),
("Bergman", "Ingrid", "For Whom the Bell Tolls"),
("Bergman", "Ingrid", "From the Mixed-Up Files of Mrs. Basil E. Frankweiler"),
("Bergman", "Ingrid", "Gaslight"),
("Bergman", "Ingrid", "Goodbye Again"),
("Bergman", "Ingrid", "Indiscreet"),
("Bergman", "Ingrid", "Intermezzo: A Love Story"),
("Bergman", "Ingrid", "Joan at the Stake"),
("Bergman", "Ingrid", "Joan of Arc"),
("Bergman", "Ingrid", "June Night"),
("Bergman", "Ingrid", "Murder on the Orient Express"),
("Bergman", "Ingrid", "Notorious"),
("Bergman", "Ingrid", "On the Sunny Side"),
("Bergman", "Ingrid", "Only One Night"),
("Bergman", "Ingrid", "Paris Does Strange Things"),
("Bergman", "Ingrid", "Rage in Heaven"),
("Bergman", "Ingrid", "Saratoga Trunk"),
("Bergman", "Ingrid", "Spellbound"),
("Bergman", "Ingrid", "Stimulantia"),
("Bergman", "Ingrid", "Stromboli"),
("Bergman", "Ingrid", "The Bells of St. Mary's"),
("Bergman", "Ingrid", "The Four Companions"),
("Bergman", "Ingrid", "The Greatest Love"),
("Bergman", "Ingrid", "The Inn of the Sixth Happiness"),
("Bergman", "Ingrid", "The Visit"),
("Bergman", "Ingrid", "The Yellow Rolls-Royce"),
("Bergman", "Ingrid", "Under Capricorn"),
("Bergman", "Ingrid", "Viaggio in Italia"),
("Bergman", "Ingrid", "Walk in the Spring Rain"),
("Bogart", "Humphrey", "A Devil with Women"),
("Bogart", "Humphrey", "A Holy Terror"),
("Bogart", "Humphrey", "Across the Pacific"),
("Bogart", "Humphrey", "All Through the Night"),
("Bogart", "Humphrey", "Action in the North Atlantic"),
("Bogart", "Humphrey", "Angels with Dirty Faces"),
("Bogart", "Humphrey", "Battle Circus"),
("Bogart", "Humphrey", "Beat the Devil"),
("Bogart", "Humphrey", "Black Legion"),
("Bogart", "Humphrey", "Body and Soul"),
("Bogart", "Humphrey", "Brother Orchid"),
("Bogart", "Humphrey", "Bullets or Ballots"),
("Bogart", "Humphrey", "Casablanca"),
("Bogart", "Humphrey", "Chain Lightning"),
("Bogart", "Humphrey", "China Clipper"),
("Bogart", "Humphrey", "Conflict"),
("Bogart", "Humphrey", "Crime School"),
("Bogart", "Humphrey", "Dark Passage"),
("Bogart", "Humphrey", "Dark Victory"),
("Bogart", "Humphrey", "Dead End"),
("Bogart", "Humphrey", "Dead Reckoning"),
("Bogart", "Humphrey", "Deadline - U.S.A."),
("Bogart", "Humphrey", "High Sierra"),
("Bogart", "Humphrey", "In a Lonely Place"),
("Bogart", "Humphrey", "Invisible Stripes"),
("Bogart", "Humphrey", "Isle of Fury"),
("Bogart", "Humphrey", "It All Came True"),
("Bogart", "Humphrey", "Key Largo"),
("Bogart", "Humphrey", "Kid Galahad"),
("Bogart", "Humphrey", "King of the Underworld"),
("Bogart", "Humphrey", "Knock on Any Door"),
("Bogart", "Humphrey", "Love Affair"),
("Bogart", "Humphrey", "Marked Woman"),
("Bogart", "Humphrey", "Men Are Such Fools"),
("Bogart", "Humphrey", "Midnight"),
("Bogart", "Humphrey", "Passage to Marseille"),
("Bogart", "Humphrey", "Racket Busters"),
("Bogart", "Humphrey", "Sabrina"),
("Bogart", "Humphrey", "Sahara"),
("Bogart", "Humphrey", "San Quentin"),
("Bogart", "Humphrey", "Sirocco"),
("Bogart", "Humphrey", "Stand-In"),
("Bogart", "Humphrey", "Swing Your Lady"),
("Bogart", "Humphrey", "The African Queen"),
("Bogart", "Humphrey", "The Amazing Dr. Clitterhouse"),
("Bogart", "Humphrey", "The Bad Sister"),
("Bogart", "Humphrey", "The Barefoot Contessa"),
("Bogart", "Humphrey", "The Big Shot"),
("Bogart", "Humphrey", "The Big Sleep"),
("Bogart", "Humphrey", "The Caine Mutiny"),
("Bogart", "Humphrey", "The Desperate Hours"),
("Bogart", "Humphrey", "The Enforcer"),
("Bogart", "Humphrey", "The Great O'Malley"),
("Bogart", "Humphrey", "The Harder They Fall"),
("Bogart", "Humphrey", "The Left Hand of God"),
("Bogart", "Humphrey", "The Maltese Falcon"),
("Bogart", "Humphrey", "The Oklahoma Kid"),
("Bogart", "Humphrey", "The Petrified Forest"),
("Bogart", "Humphrey", "The Return of Doctor X"),
("Bogart", "Humphrey", "The Roaring Twenties"),
("Bogart", "Humphrey", "The Treasure of the Sierra Madre"),
("Bogart", "Humphrey", "The Two Mrs. Carrolls"),
("Bogart", "Humphrey", "The Wagons Roll at Night"),
("Bogart", "Humphrey", "They Drive by Night"),
("Bogart", "Humphrey", "Three on a Match"),
("Bogart", "Humphrey", "To Have and Have Not"),
("Bogart", "Humphrey", "Tokyo Joe"),
("Bogart", "Humphrey", "Two Against the World"),
("Bogart", "Humphrey", "Up the River"),
("Bogart", "Humphrey", "Virginia City"),
("Bogart", "Humphrey", "We're No Angels"),
("Bogart", "Humphrey", "You Can't Get Away with Murder"),
("Broderick", "Matthew", "The Cable Guy"),
("Carrey", "Jim", "The Cable Guy"),
("Carrey", "Jim", "The Mask"),
("Chapman", "Graham", "Monty Python and the Holy Grail"),
("Cleese", "John", "Monty Python and the Holy Grail"),
("DeNiro", "Robert", "Brazil"),
("Diaz", "Cameron", "Something About Mary"),
("Diaz", "Cameron", "The Mask"),
("Ford", "Harrison", "Air Force One"),
("Ford", "Harrison", "American Graffiti"),
("Ford", "Harrison", "Apocalypse Now"),
("Ford", "Harrison", "Blade Runner"),
("Ford", "Harrison", "Clear and Present Danger"),
("Ford", "Harrison", "Frantic"),
("Ford", "Harrison", "Hanover Street"),
("Ford", "Harrison", "Heroes"),
("Ford", "Harrison", "Indiana Jones and the Last Crusade"),
("Ford", "Harrison", "Indiana Jones and the Temple of Doom"),
("Ford", "Harrison", "Patriot Games"),
("Ford", "Harrison", "Presumed Innocent"),
("Ford", "Harrison", "Raiders of the Lost Ark"),
("Ford", "Harrison", "Regarding Henry"),
("Ford", "Harrison", "Return of the Jedi"),
("Ford", "Harrison", "Six Days Seven Nights"),
("Ford", "Harrison", "Star Wars"),
("Ford", "Harrison", "The Empire Strikes Back"),
("Ford", "Harrison", "The Frisco Kid"),
("Ford", "Harrison", "The Fugitive"),
("Ford", "Harrison", "The Mosquito Coast"),
("Ford", "Harrison", "Working Girl"),
("Hanks", "Tom", "Apollo 13"),
("Hanks", "Tom", "Bachelor Party"),
("Hanks", "Tom", "Big"),
("Hanks", "Tom", "Bonfire of the Vanities"),
("Hanks", "Tom", "Dragnet"),
("Hanks", "Tom", "Forrest Gump"),
("Hanks", "Tom", "Joe Versus the Volcano"),
("Hanks", "Tom", "Nothing in Common"),
("Hanks", "Tom", "Philadelphia"),
("Hanks", "Tom", "Punchline"),
("Hanks", "Tom", "Saving Private Ryan"),
("Hanks", "Tom", "Sleepless in Seattle"),
("Hanks", "Tom", "Splash"),
("Hanks", "Tom", "The Burbs"),
("Hanks", "Tom", "The Man with one Red Shoe"),
("Hanks", "Tom", "The Moneypit"),
("Hanks", "Tom", "Turner and Hooch"),
("Hanks", "Tom", "You've got Mail"),
("Hanks", "Tom", "Volunteers"),
("Hannah", "Daryl", "Blade Runner"),
("Hauer", "Rutger", "Blade Runner"),
("Hunt", "Helen", "As Good As It Gets"),
("Hunt", "Helen", "Twister"),
("Hurley", "Elizabeth", "Austin Powers: International Man of Mystery"),
("Garland", "Judy", "Andy Hard Meets Debutante"),
("Garland", "Judy", "Babes in Arms"),
("Garland", "Judy", "Babes on Broadway"),
("Garland", "Judy", "A Child is Waiting"),
("Garland", "Judy", "Clock - The"),
("Garland", "Judy", "Easter Parade"),
("Garland", "Judy", "Everybody Sing"),
("Garland", "Judy", "For Me and my Gal"),
("Garland", "Judy", "Girl Crazy"),
("Garland", "Judy", "Harvey Girls - The"),
("Garland", "Judy", "I Could Go on Singing"),
("Garland", "Judy", "In the Good Old Summertime"),
("Garland", "Judy", "Judgement at Nuremberg"),
("Garland", "Judy", "Life Begins for Andy Hardy"),
("Garland", "Judy", "Listen - Darling"),
("Garland", "Judy", "Little Nelly Kelly"),
("Garland", "Judy", "Love Finds Andy Hardy"),
("Garland", "Judy", "Meet Me in St. Louis"),
("Garland", "Judy", "Pirate - The"),
("Garland", "Judy", "Presenting Lily Mars"),
("Garland", "Judy", "Star is Born - A"),
("Garland", "Judy", "Strictly G.I."),
("Garland", "Judy", "Strike Up the Band"),
("Garland", "Judy", "Thoroughbreads Don't Cry"),
("Garland", "Judy", "Thousands Cheer"),
("Garland", "Judy", "Till the Clouds Roll By"),
("Garland", "Judy", "Wizard of Oz - The"),
("Garland", "Judy", "Ziegfield Follies"),
("Garland", "Judy", "Ziegfeld Girl"),
("Gilliam", "Terry", "Monty Python and the Holy Grail"),
("Graham", "Heather", "Austin Powers: The Spy Who Shagged Me"),
("Greene", "Seth", "Austin Powers: International Man of Mystery"),
("Greene", "Seth", "Austin Powers: The Spy Who Shagged Me"),
("Idle", "Eric", "Monty Python and the Holy Grail"),
("Jones", "Terry", "Monty Python and the Holy Grail"),
("Murray", "Bill", "Broken Flowers"),
("Murray", "Bill", "Caddyshack"),
("Murray", "Bill", "Charlie's Angels"),
("Murray", "Bill", "Ed Wood"),
("Murray", "Bill", "Ghostbusters"),
("Murray", "Bill", "Groundhog Day"),
("Murray", "Bill", "Kingpin"),
("Murray", "Bill", "Little Shop of Horrors"),
("Murray", "Bill", "Mad Dog and Glory"),
("Murray", "Bill", "Quick Change"),
("Murray", "Bill", "Rushmore"),
("Murray", "Bill", "Scrooged"),
("Murray", "Bill", "The Life Aquatic with Steve Zissou"),
("Murray", "Bill", "The Razor's Edge"),
("Murray", "Bill", "The Royal Tenenbaums"),
("Murray", "Bill", "What About Bob?"),
("Murray", "Bill", "Where the Buffalo Roam"),
("Myers", "Mike", "Austin Powers: International Man of Mystery"),
("Myers", "Mike", "Austin Powers: The Spy Who Shagged Me"),
("Nicholson", "Jack", "Mars Attacks"),
("Nicholson", "Jack", "As Good As It Gets"),
("Palin", "Michael", "Brazil"),
("Palin", "Michael", "Monty Python and the Holy Grail"),
("Platrow", "Gwenth", "Proof"),
("Platrow", "Gwenth", "Sky Captain and the World of Tomorrow"),
("Platrow", "Gwenth", "Sylvia"),
("Platrow", "Gwenth", "View from the Top"),
("Platrow", "Gwenth", "Possession"),
("Platrow", "Gwenth", "Shallow Hal"),
("Platrow", "Gwenth", "The Royal Tenenbaums"),
("Platrow", "Gwenth", "The Anniversary Party"),
("Platrow", "Gwenth", "Bounce"),
("Platrow", "Gwenth", "Duets"),
("Platrow", "Gwenth", "The Talented Mr. Ripley"),
("Platrow", "Gwenth", "Shakespeare in Love"),
("Platrow", "Gwenth", "A Perfect Murder"),
("Platrow", "Gwenth", "Hush"),
("Platrow", "Gwenth", "Great Expectations"),
("Platrow", "Gwenth", "Sliding Doors"),
("Platrow", "Gwenth", "Emma"),
("Platrow", "Gwenth", "The Pallbearer"),
("Platrow", "Gwenth", "Sydney"),
("Platrow", "Gwenth", "Moonlight and Valentino"),
("Platrow", "Gwenth", "Se7en"),
("Platrow", "Gwenth", "Jefferson in Paris"),
("Platrow", "Gwenth", "Mrs. Parker and the Vicious Circle"),
("Platrow", "Gwenth", "Flesh and Bone"),
("Platrow", "Gwenth", "Malice"),
("Platrow", "Gwenth", "Hook"),
("Platrow", "Gwenth", "Shout"),
("Pryce", "Jonathan", "Brazil"),
("Reeves", "Keanu", "The Matrix"),
("Sandler", "Adam", "Big Daddy"),
("Sandler", "Adam", "The Waterboy"),
("Sandler", "Adam", "The Wedding Singer"),
("Stiller", "Ben", "Something About Mary"),
("Travolta", "John", "Pulp Fiction"),
("Young", "Sean", "Blade Runner");

show warnings;

insert into thespian_table values
("Nicholson", "Jack"),
("Nicholson", "Nick");


select Film_Title
   From Thespian_Film_Table
  Where Thespian_Last_Name  = "Ford"
    and Thespian_First_Name = "Harrison"
    and Film_Title in
         (Select Film_Title
            From Film_Table
            Where Film_Year = "1984") order by 1;

Select Film_Title
   From Thespian_Film_Table
  Where Thespian_Last_Name  = "Ford"
    and Thespian_First_Name = "Harrison"
    and Film_Title not in
         (Select Film_Title
            From Film_Table
           Where Film_Year = "1984") order by 1;

Select Thespian_Film_Table.Film_Title
   From Thespian_Film_Table
  Where Thespian_Last_Name  = "Ford"
    and Thespian_First_Name = "Harrison"
    and exists
         (Select *
            From Director_Film_Table
           Where Director_Last_Name  = "Lucas"
             and Director_First_Name = "George"
             and Director_Film_Table.Film_Title 
               = Thespian_Film_Table.Film_Title) order by 1;

/*
drop table if exists director_film_table;
drop table if exists film_table;
drop table if exists thespian_table;
drop table if exists thespian_film_table;
*/
