select cidx, CCHAR1, CAST(CCHAR1 AS CHAR(1)) from datatypetestm;
select cidx, CCHAR1, CAST(CCHAR1 AS CHAR(2)) from datatypetestm;
select cidx, CCHAR1, CAST(CCHAR1 AS CHAR(3)) from datatypetestm;
select cidx, CCHAR1, CAST(CCHAR1 AS CHAR(4)) from datatypetestm;
select cidx, CCHAR1, CAST(CCHAR1 AS CHAR(5)) from datatypetestm;
select cidx, CCHAR1, CAST(CCHAR1 AS CHAR(6)) from datatypetestm;
select cidx, CCHAR1, CAST(CCHAR1 AS CHAR(7)) from datatypetestm;
select cidx, CCHAR1, CAST(CCHAR1 AS CHAR(8)) from datatypetestm;
select cidx, CCHAR1, CAST(CCHAR1 AS CHAR(9)) from datatypetestm;
select cidx, CCHAR1, CAST(CCHAR1 AS CHAR(20)) from datatypetestm;
select cidx, CCHAR2, CAST(CCHAR2 AS CHAR(1)) from datatypetestm;
select cidx, CCHAR2, CAST(CCHAR2 AS CHAR(2)) from datatypetestm;
select cidx, CCHAR2, CAST(CCHAR2 AS CHAR(3)) from datatypetestm;
select cidx, CCHAR2, CAST(CCHAR2 AS CHAR(4)) from datatypetestm;
select cidx, CCHAR2, CAST(CCHAR2 AS CHAR(5)) from datatypetestm;
select cidx, CCHAR2, CAST(CCHAR2 AS CHAR(6)) from datatypetestm;
select cidx, CCHAR2, CAST(CCHAR2 AS CHAR(7)) from datatypetestm;
select cidx, CCHAR2, CAST(CCHAR2 AS CHAR(8)) from datatypetestm;
select cidx, CCHAR2, CAST(CCHAR2 AS CHAR(9)) from datatypetestm;
select cidx, CCHAR2, CAST(CCHAR2 AS CHAR(20)) from datatypetestm;
select cidx, CCHAR3, CAST(CCHAR3 AS CHAR(1)) from datatypetestm;
select cidx, CCHAR3, CAST(CCHAR3 AS CHAR(2)) from datatypetestm;
select cidx, CCHAR3, CAST(CCHAR3 AS CHAR(3)) from datatypetestm;
select cidx, CCHAR3, CAST(CCHAR3 AS CHAR(4)) from datatypetestm;
select cidx, CCHAR3, CAST(CCHAR3 AS CHAR(5)) from datatypetestm;
select cidx, CCHAR3, CAST(CCHAR3 AS CHAR(6)) from datatypetestm;
select cidx, CCHAR3, CAST(CCHAR3 AS CHAR(7)) from datatypetestm;
select cidx, CCHAR3, CAST(CCHAR3 AS CHAR(8)) from datatypetestm;
select cidx, CCHAR3, CAST(CCHAR3 AS CHAR(9)) from datatypetestm;
select cidx, CCHAR3, CAST(CCHAR3 AS CHAR(20)) from datatypetestm;
select cidx, CCHAR4, CAST(CCHAR4 AS CHAR(1)) from datatypetestm;
select cidx, CCHAR4, CAST(CCHAR4 AS CHAR(2)) from datatypetestm;
select cidx, CCHAR4, CAST(CCHAR4 AS CHAR(3)) from datatypetestm;
select cidx, CCHAR4, CAST(CCHAR4 AS CHAR(4)) from datatypetestm;
select cidx, CCHAR4, CAST(CCHAR4 AS CHAR(5)) from datatypetestm;
select cidx, CCHAR4, CAST(CCHAR4 AS CHAR(6)) from datatypetestm;
select cidx, CCHAR4, CAST(CCHAR4 AS CHAR(7)) from datatypetestm;
select cidx, CCHAR4, CAST(CCHAR4 AS CHAR(8)) from datatypetestm;
select cidx, CCHAR4, CAST(CCHAR4 AS CHAR(9)) from datatypetestm;
select cidx, CCHAR4, CAST(CCHAR4 AS CHAR(20)) from datatypetestm;
select cidx, CCHAR5, CAST(CCHAR5 AS CHAR(1)) from datatypetestm;
select cidx, CCHAR5, CAST(CCHAR5 AS CHAR(2)) from datatypetestm;
select cidx, CCHAR5, CAST(CCHAR5 AS CHAR(3)) from datatypetestm;
select cidx, CCHAR5, CAST(CCHAR5 AS CHAR(4)) from datatypetestm;
select cidx, CCHAR5, CAST(CCHAR5 AS CHAR(5)) from datatypetestm;
select cidx, CCHAR5, CAST(CCHAR5 AS CHAR(6)) from datatypetestm;
select cidx, CCHAR5, CAST(CCHAR5 AS CHAR(7)) from datatypetestm;
select cidx, CCHAR5, CAST(CCHAR5 AS CHAR(8)) from datatypetestm;
select cidx, CCHAR5, CAST(CCHAR5 AS CHAR(9)) from datatypetestm;
select cidx, CCHAR5, CAST(CCHAR5 AS CHAR(20)) from datatypetestm;
select cidx, CCHAR6, CAST(CCHAR6 AS CHAR(1)) from datatypetestm;
select cidx, CCHAR6, CAST(CCHAR6 AS CHAR(2)) from datatypetestm;
select cidx, CCHAR6, CAST(CCHAR6 AS CHAR(3)) from datatypetestm;
select cidx, CCHAR6, CAST(CCHAR6 AS CHAR(4)) from datatypetestm;
select cidx, CCHAR6, CAST(CCHAR6 AS CHAR(5)) from datatypetestm;
select cidx, CCHAR6, CAST(CCHAR6 AS CHAR(6)) from datatypetestm;
select cidx, CCHAR6, CAST(CCHAR6 AS CHAR(7)) from datatypetestm;
select cidx, CCHAR6, CAST(CCHAR6 AS CHAR(8)) from datatypetestm;
select cidx, CCHAR6, CAST(CCHAR6 AS CHAR(9)) from datatypetestm;
select cidx, CCHAR6, CAST(CCHAR6 AS CHAR(20)) from datatypetestm;
select cidx, CCHAR7, CAST(CCHAR7 AS CHAR(1)) from datatypetestm;
select cidx, CCHAR7, CAST(CCHAR7 AS CHAR(2)) from datatypetestm;
select cidx, CCHAR7, CAST(CCHAR7 AS CHAR(3)) from datatypetestm;
select cidx, CCHAR7, CAST(CCHAR7 AS CHAR(4)) from datatypetestm;
select cidx, CCHAR7, CAST(CCHAR7 AS CHAR(5)) from datatypetestm;
select cidx, CCHAR7, CAST(CCHAR7 AS CHAR(6)) from datatypetestm;
select cidx, CCHAR7, CAST(CCHAR7 AS CHAR(7)) from datatypetestm;
select cidx, CCHAR7, CAST(CCHAR7 AS CHAR(8)) from datatypetestm;
select cidx, CCHAR7, CAST(CCHAR7 AS CHAR(9)) from datatypetestm;
select cidx, CCHAR7, CAST(CCHAR7 AS CHAR(20)) from datatypetestm;
select cidx, CCHAR8, CAST(CCHAR8 AS CHAR(1)) from datatypetestm;
select cidx, CCHAR8, CAST(CCHAR8 AS CHAR(2)) from datatypetestm;
select cidx, CCHAR8, CAST(CCHAR8 AS CHAR(3)) from datatypetestm;
select cidx, CCHAR8, CAST(CCHAR8 AS CHAR(4)) from datatypetestm;
select cidx, CCHAR8, CAST(CCHAR8 AS CHAR(5)) from datatypetestm;
select cidx, CCHAR8, CAST(CCHAR8 AS CHAR(6)) from datatypetestm;
select cidx, CCHAR8, CAST(CCHAR8 AS CHAR(7)) from datatypetestm;
select cidx, CCHAR8, CAST(CCHAR8 AS CHAR(8)) from datatypetestm;
select cidx, CCHAR8, CAST(CCHAR8 AS CHAR(9)) from datatypetestm;
select cidx, CCHAR8, CAST(CCHAR8 AS CHAR(20)) from datatypetestm;
select cidx, CCHAR9, CAST(CCHAR9 AS CHAR(1)) from datatypetestm;
select cidx, CCHAR9, CAST(CCHAR9 AS CHAR(2)) from datatypetestm;
select cidx, CCHAR9, CAST(CCHAR9 AS CHAR(3)) from datatypetestm;
select cidx, CCHAR9, CAST(CCHAR9 AS CHAR(4)) from datatypetestm;
select cidx, CCHAR9, CAST(CCHAR9 AS CHAR(5)) from datatypetestm;
select cidx, CCHAR9, CAST(CCHAR9 AS CHAR(6)) from datatypetestm;
select cidx, CCHAR9, CAST(CCHAR9 AS CHAR(7)) from datatypetestm;
select cidx, CCHAR9, CAST(CCHAR9 AS CHAR(8)) from datatypetestm;
select cidx, CCHAR9, CAST(CCHAR9 AS CHAR(9)) from datatypetestm;
select cidx, CCHAR9, CAST(CCHAR9 AS CHAR(20)) from datatypetestm;
select cidx, CCHAR255, CAST(CCHAR255 AS CHAR(1)) from datatypetestm;
select cidx, CCHAR255, CAST(CCHAR255 AS CHAR(2)) from datatypetestm;
select cidx, CCHAR255, CAST(CCHAR255 AS CHAR(3)) from datatypetestm;
select cidx, CCHAR255, CAST(CCHAR255 AS CHAR(4)) from datatypetestm;
select cidx, CCHAR255, CAST(CCHAR255 AS CHAR(5)) from datatypetestm;
select cidx, CCHAR255, CAST(CCHAR255 AS CHAR(6)) from datatypetestm;
select cidx, CCHAR255, CAST(CCHAR255 AS CHAR(7)) from datatypetestm;
select cidx, CCHAR255, CAST(CCHAR255 AS CHAR(8)) from datatypetestm;
select cidx, CCHAR255, CAST(CCHAR255 AS CHAR(9)) from datatypetestm;
select cidx, CCHAR255, CAST(CCHAR255 AS CHAR(20)) from datatypetestm;
select cidx, CVCHAR1, CAST(CVCHAR1 AS CHAR(1)) from datatypetestm;
select cidx, CVCHAR1, CAST(CVCHAR1 AS CHAR(2)) from datatypetestm;
select cidx, CVCHAR1, CAST(CVCHAR1 AS CHAR(3)) from datatypetestm;
select cidx, CVCHAR1, CAST(CVCHAR1 AS CHAR(4)) from datatypetestm;
select cidx, CVCHAR1, CAST(CVCHAR1 AS CHAR(5)) from datatypetestm;
select cidx, CVCHAR1, CAST(CVCHAR1 AS CHAR(6)) from datatypetestm;
select cidx, CVCHAR1, CAST(CVCHAR1 AS CHAR(7)) from datatypetestm;
select cidx, CVCHAR1, CAST(CVCHAR1 AS CHAR(8)) from datatypetestm;
select cidx, CVCHAR1, CAST(CVCHAR1 AS CHAR(9)) from datatypetestm;
select cidx, CVCHAR1, CAST(CVCHAR1 AS CHAR(20)) from datatypetestm;
select cidx, CVCHAR2, CAST(CVCHAR2 AS CHAR(1)) from datatypetestm;
select cidx, CVCHAR2, CAST(CVCHAR2 AS CHAR(2)) from datatypetestm;
select cidx, CVCHAR2, CAST(CVCHAR2 AS CHAR(3)) from datatypetestm;
select cidx, CVCHAR2, CAST(CVCHAR2 AS CHAR(4)) from datatypetestm;
select cidx, CVCHAR2, CAST(CVCHAR2 AS CHAR(5)) from datatypetestm;
select cidx, CVCHAR2, CAST(CVCHAR2 AS CHAR(6)) from datatypetestm;
select cidx, CVCHAR2, CAST(CVCHAR2 AS CHAR(7)) from datatypetestm;
select cidx, CVCHAR2, CAST(CVCHAR2 AS CHAR(8)) from datatypetestm;
select cidx, CVCHAR2, CAST(CVCHAR2 AS CHAR(9)) from datatypetestm;
select cidx, CVCHAR2, CAST(CVCHAR2 AS CHAR(20)) from datatypetestm;
select cidx, CVCHAR3, CAST(CVCHAR3 AS CHAR(1)) from datatypetestm;
select cidx, CVCHAR3, CAST(CVCHAR3 AS CHAR(2)) from datatypetestm;
select cidx, CVCHAR3, CAST(CVCHAR3 AS CHAR(3)) from datatypetestm;
select cidx, CVCHAR3, CAST(CVCHAR3 AS CHAR(4)) from datatypetestm;
select cidx, CVCHAR3, CAST(CVCHAR3 AS CHAR(5)) from datatypetestm;
select cidx, CVCHAR3, CAST(CVCHAR3 AS CHAR(6)) from datatypetestm;
select cidx, CVCHAR3, CAST(CVCHAR3 AS CHAR(7)) from datatypetestm;
select cidx, CVCHAR3, CAST(CVCHAR3 AS CHAR(8)) from datatypetestm;
select cidx, CVCHAR3, CAST(CVCHAR3 AS CHAR(9)) from datatypetestm;
select cidx, CVCHAR3, CAST(CVCHAR3 AS CHAR(20)) from datatypetestm;
select cidx, CVCHAR4, CAST(CVCHAR4 AS CHAR(1)) from datatypetestm;
select cidx, CVCHAR4, CAST(CVCHAR4 AS CHAR(2)) from datatypetestm;
select cidx, CVCHAR4, CAST(CVCHAR4 AS CHAR(3)) from datatypetestm;
select cidx, CVCHAR4, CAST(CVCHAR4 AS CHAR(4)) from datatypetestm;
select cidx, CVCHAR4, CAST(CVCHAR4 AS CHAR(5)) from datatypetestm;
select cidx, CVCHAR4, CAST(CVCHAR4 AS CHAR(6)) from datatypetestm;
select cidx, CVCHAR4, CAST(CVCHAR4 AS CHAR(7)) from datatypetestm;
select cidx, CVCHAR4, CAST(CVCHAR4 AS CHAR(8)) from datatypetestm;
select cidx, CVCHAR4, CAST(CVCHAR4 AS CHAR(9)) from datatypetestm;
select cidx, CVCHAR4, CAST(CVCHAR4 AS CHAR(20)) from datatypetestm;
select cidx, CVCHAR5, CAST(CVCHAR5 AS CHAR(1)) from datatypetestm;
select cidx, CVCHAR5, CAST(CVCHAR5 AS CHAR(2)) from datatypetestm;
select cidx, CVCHAR5, CAST(CVCHAR5 AS CHAR(3)) from datatypetestm;
select cidx, CVCHAR5, CAST(CVCHAR5 AS CHAR(4)) from datatypetestm;
select cidx, CVCHAR5, CAST(CVCHAR5 AS CHAR(5)) from datatypetestm;
select cidx, CVCHAR5, CAST(CVCHAR5 AS CHAR(6)) from datatypetestm;
select cidx, CVCHAR5, CAST(CVCHAR5 AS CHAR(7)) from datatypetestm;
select cidx, CVCHAR5, CAST(CVCHAR5 AS CHAR(8)) from datatypetestm;
select cidx, CVCHAR5, CAST(CVCHAR5 AS CHAR(9)) from datatypetestm;
select cidx, CVCHAR5, CAST(CVCHAR5 AS CHAR(20)) from datatypetestm;
select cidx, CVCHAR6, CAST(CVCHAR6 AS CHAR(1)) from datatypetestm;
select cidx, CVCHAR6, CAST(CVCHAR6 AS CHAR(2)) from datatypetestm;
select cidx, CVCHAR6, CAST(CVCHAR6 AS CHAR(3)) from datatypetestm;
select cidx, CVCHAR6, CAST(CVCHAR6 AS CHAR(4)) from datatypetestm;
select cidx, CVCHAR6, CAST(CVCHAR6 AS CHAR(5)) from datatypetestm;
select cidx, CVCHAR6, CAST(CVCHAR6 AS CHAR(6)) from datatypetestm;
select cidx, CVCHAR6, CAST(CVCHAR6 AS CHAR(7)) from datatypetestm;
select cidx, CVCHAR6, CAST(CVCHAR6 AS CHAR(8)) from datatypetestm;
select cidx, CVCHAR6, CAST(CVCHAR6 AS CHAR(9)) from datatypetestm;
select cidx, CVCHAR6, CAST(CVCHAR6 AS CHAR(20)) from datatypetestm;
select cidx, CVCHAR7, CAST(CVCHAR7 AS CHAR(1)) from datatypetestm;
select cidx, CVCHAR7, CAST(CVCHAR7 AS CHAR(2)) from datatypetestm;
select cidx, CVCHAR7, CAST(CVCHAR7 AS CHAR(3)) from datatypetestm;
select cidx, CVCHAR7, CAST(CVCHAR7 AS CHAR(4)) from datatypetestm;
select cidx, CVCHAR7, CAST(CVCHAR7 AS CHAR(5)) from datatypetestm;
select cidx, CVCHAR7, CAST(CVCHAR7 AS CHAR(6)) from datatypetestm;
select cidx, CVCHAR7, CAST(CVCHAR7 AS CHAR(7)) from datatypetestm;
select cidx, CVCHAR7, CAST(CVCHAR7 AS CHAR(8)) from datatypetestm;
select cidx, CVCHAR7, CAST(CVCHAR7 AS CHAR(9)) from datatypetestm;
select cidx, CVCHAR7, CAST(CVCHAR7 AS CHAR(20)) from datatypetestm;
select cidx, CVCHAR8, CAST(CVCHAR8 AS CHAR(1)) from datatypetestm;
select cidx, CVCHAR8, CAST(CVCHAR8 AS CHAR(2)) from datatypetestm;
select cidx, CVCHAR8, CAST(CVCHAR8 AS CHAR(3)) from datatypetestm;
select cidx, CVCHAR8, CAST(CVCHAR8 AS CHAR(4)) from datatypetestm;
select cidx, CVCHAR8, CAST(CVCHAR8 AS CHAR(5)) from datatypetestm;
select cidx, CVCHAR8, CAST(CVCHAR8 AS CHAR(6)) from datatypetestm;
select cidx, CVCHAR8, CAST(CVCHAR8 AS CHAR(7)) from datatypetestm;
select cidx, CVCHAR8, CAST(CVCHAR8 AS CHAR(8)) from datatypetestm;
select cidx, CVCHAR8, CAST(CVCHAR8 AS CHAR(9)) from datatypetestm;
select cidx, CVCHAR8, CAST(CVCHAR8 AS CHAR(20)) from datatypetestm;
select cidx, CVCHAR255, CAST(CVCHAR255 AS CHAR(1)) from datatypetestm;
select cidx, CVCHAR255, CAST(CVCHAR255 AS CHAR(2)) from datatypetestm;
select cidx, CVCHAR255, CAST(CVCHAR255 AS CHAR(3)) from datatypetestm;
select cidx, CVCHAR255, CAST(CVCHAR255 AS CHAR(4)) from datatypetestm;
select cidx, CVCHAR255, CAST(CVCHAR255 AS CHAR(5)) from datatypetestm;
select cidx, CVCHAR255, CAST(CVCHAR255 AS CHAR(6)) from datatypetestm;
select cidx, CVCHAR255, CAST(CVCHAR255 AS CHAR(7)) from datatypetestm;
select cidx, CVCHAR255, CAST(CVCHAR255 AS CHAR(8)) from datatypetestm;
select cidx, CVCHAR255, CAST(CVCHAR255 AS CHAR(9)) from datatypetestm;
select cidx, CVCHAR255, CAST(CVCHAR255 AS CHAR(20)) from datatypetestm;
select cidx, CCHAR1 from datatypetestm where CAST(CCHAR1 AS CHAR(1)) <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where CAST(CCHAR1 AS CHAR(2)) <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where CAST(CCHAR1 AS CHAR(3)) <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where CAST(CCHAR1 AS CHAR(4)) <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where CAST(CCHAR1 AS CHAR(5)) <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where CAST(CCHAR1 AS CHAR(6)) <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where CAST(CCHAR1 AS CHAR(7)) <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where CAST(CCHAR1 AS CHAR(8)) <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where CAST(CCHAR1 AS CHAR(9)) <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where CAST(CCHAR1 AS CHAR(20)) <> CCHAR1;
select cidx, CCHAR2 from datatypetestm where CAST(CCHAR2 AS CHAR(1)) <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where CAST(CCHAR2 AS CHAR(2)) <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where CAST(CCHAR2 AS CHAR(3)) <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where CAST(CCHAR2 AS CHAR(4)) <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where CAST(CCHAR2 AS CHAR(5)) <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where CAST(CCHAR2 AS CHAR(6)) <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where CAST(CCHAR2 AS CHAR(7)) <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where CAST(CCHAR2 AS CHAR(8)) <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where CAST(CCHAR2 AS CHAR(9)) <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where CAST(CCHAR2 AS CHAR(20)) <> CCHAR2;
select cidx, CCHAR3 from datatypetestm where CAST(CCHAR3 AS CHAR(1)) <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where CAST(CCHAR3 AS CHAR(2)) <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where CAST(CCHAR3 AS CHAR(3)) <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where CAST(CCHAR3 AS CHAR(4)) <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where CAST(CCHAR3 AS CHAR(5)) <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where CAST(CCHAR3 AS CHAR(6)) <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where CAST(CCHAR3 AS CHAR(7)) <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where CAST(CCHAR3 AS CHAR(8)) <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where CAST(CCHAR3 AS CHAR(9)) <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where CAST(CCHAR3 AS CHAR(20)) <> CCHAR3;
select cidx, CCHAR4 from datatypetestm where CAST(CCHAR4 AS CHAR(1)) <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where CAST(CCHAR4 AS CHAR(2)) <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where CAST(CCHAR4 AS CHAR(3)) <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where CAST(CCHAR4 AS CHAR(4)) <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where CAST(CCHAR4 AS CHAR(5)) <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where CAST(CCHAR4 AS CHAR(6)) <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where CAST(CCHAR4 AS CHAR(7)) <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where CAST(CCHAR4 AS CHAR(8)) <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where CAST(CCHAR4 AS CHAR(9)) <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where CAST(CCHAR4 AS CHAR(20)) <> CCHAR4;
select cidx, CCHAR5 from datatypetestm where CAST(CCHAR5 AS CHAR(1)) <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where CAST(CCHAR5 AS CHAR(2)) <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where CAST(CCHAR5 AS CHAR(3)) <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where CAST(CCHAR5 AS CHAR(4)) <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where CAST(CCHAR5 AS CHAR(5)) <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where CAST(CCHAR5 AS CHAR(6)) <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where CAST(CCHAR5 AS CHAR(7)) <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where CAST(CCHAR5 AS CHAR(8)) <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where CAST(CCHAR5 AS CHAR(9)) <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where CAST(CCHAR5 AS CHAR(20)) <> CCHAR5;
select cidx, CCHAR6 from datatypetestm where CAST(CCHAR6 AS CHAR(1)) <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where CAST(CCHAR6 AS CHAR(2)) <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where CAST(CCHAR6 AS CHAR(3)) <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where CAST(CCHAR6 AS CHAR(4)) <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where CAST(CCHAR6 AS CHAR(5)) <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where CAST(CCHAR6 AS CHAR(6)) <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where CAST(CCHAR6 AS CHAR(7)) <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where CAST(CCHAR6 AS CHAR(8)) <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where CAST(CCHAR6 AS CHAR(9)) <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where CAST(CCHAR6 AS CHAR(20)) <> CCHAR6;
select cidx, CCHAR7 from datatypetestm where CAST(CCHAR7 AS CHAR(1)) <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where CAST(CCHAR7 AS CHAR(2)) <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where CAST(CCHAR7 AS CHAR(3)) <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where CAST(CCHAR7 AS CHAR(4)) <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where CAST(CCHAR7 AS CHAR(5)) <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where CAST(CCHAR7 AS CHAR(6)) <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where CAST(CCHAR7 AS CHAR(7)) <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where CAST(CCHAR7 AS CHAR(8)) <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where CAST(CCHAR7 AS CHAR(9)) <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where CAST(CCHAR7 AS CHAR(20)) <> CCHAR7;
select cidx, CCHAR8 from datatypetestm where CAST(CCHAR8 AS CHAR(1)) <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where CAST(CCHAR8 AS CHAR(2)) <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where CAST(CCHAR8 AS CHAR(3)) <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where CAST(CCHAR8 AS CHAR(4)) <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where CAST(CCHAR8 AS CHAR(5)) <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where CAST(CCHAR8 AS CHAR(6)) <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where CAST(CCHAR8 AS CHAR(7)) <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where CAST(CCHAR8 AS CHAR(8)) <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where CAST(CCHAR8 AS CHAR(9)) <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where CAST(CCHAR8 AS CHAR(20)) <> CCHAR8;
select cidx, CCHAR9 from datatypetestm where CAST(CCHAR9 AS CHAR(1)) <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where CAST(CCHAR9 AS CHAR(2)) <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where CAST(CCHAR9 AS CHAR(3)) <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where CAST(CCHAR9 AS CHAR(4)) <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where CAST(CCHAR9 AS CHAR(5)) <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where CAST(CCHAR9 AS CHAR(6)) <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where CAST(CCHAR9 AS CHAR(7)) <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where CAST(CCHAR9 AS CHAR(8)) <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where CAST(CCHAR9 AS CHAR(9)) <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where CAST(CCHAR9 AS CHAR(20)) <> CCHAR9;
select cidx, CCHAR255 from datatypetestm where CAST(CCHAR255 AS CHAR(1)) <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where CAST(CCHAR255 AS CHAR(2)) <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where CAST(CCHAR255 AS CHAR(3)) <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where CAST(CCHAR255 AS CHAR(4)) <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where CAST(CCHAR255 AS CHAR(5)) <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where CAST(CCHAR255 AS CHAR(6)) <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where CAST(CCHAR255 AS CHAR(7)) <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where CAST(CCHAR255 AS CHAR(8)) <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where CAST(CCHAR255 AS CHAR(9)) <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where CAST(CCHAR255 AS CHAR(20)) <> CCHAR255;
select cidx, CVCHAR1 from datatypetestm where CAST(CVCHAR1 AS CHAR(1)) <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where CAST(CVCHAR1 AS CHAR(2)) <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where CAST(CVCHAR1 AS CHAR(3)) <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where CAST(CVCHAR1 AS CHAR(4)) <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where CAST(CVCHAR1 AS CHAR(5)) <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where CAST(CVCHAR1 AS CHAR(6)) <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where CAST(CVCHAR1 AS CHAR(7)) <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where CAST(CVCHAR1 AS CHAR(8)) <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where CAST(CVCHAR1 AS CHAR(9)) <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where CAST(CVCHAR1 AS CHAR(20)) <> CVCHAR1;
select cidx, CVCHAR2 from datatypetestm where CAST(CVCHAR2 AS CHAR(1)) <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where CAST(CVCHAR2 AS CHAR(2)) <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where CAST(CVCHAR2 AS CHAR(3)) <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where CAST(CVCHAR2 AS CHAR(4)) <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where CAST(CVCHAR2 AS CHAR(5)) <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where CAST(CVCHAR2 AS CHAR(6)) <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where CAST(CVCHAR2 AS CHAR(7)) <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where CAST(CVCHAR2 AS CHAR(8)) <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where CAST(CVCHAR2 AS CHAR(9)) <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where CAST(CVCHAR2 AS CHAR(20)) <> CVCHAR2;
select cidx, CVCHAR3 from datatypetestm where CAST(CVCHAR3 AS CHAR(1)) <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where CAST(CVCHAR3 AS CHAR(2)) <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where CAST(CVCHAR3 AS CHAR(3)) <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where CAST(CVCHAR3 AS CHAR(4)) <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where CAST(CVCHAR3 AS CHAR(5)) <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where CAST(CVCHAR3 AS CHAR(6)) <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where CAST(CVCHAR3 AS CHAR(7)) <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where CAST(CVCHAR3 AS CHAR(8)) <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where CAST(CVCHAR3 AS CHAR(9)) <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where CAST(CVCHAR3 AS CHAR(20)) <> CVCHAR3;
select cidx, CVCHAR4 from datatypetestm where CAST(CVCHAR4 AS CHAR(1)) <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where CAST(CVCHAR4 AS CHAR(2)) <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where CAST(CVCHAR4 AS CHAR(3)) <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where CAST(CVCHAR4 AS CHAR(4)) <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where CAST(CVCHAR4 AS CHAR(5)) <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where CAST(CVCHAR4 AS CHAR(6)) <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where CAST(CVCHAR4 AS CHAR(7)) <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where CAST(CVCHAR4 AS CHAR(8)) <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where CAST(CVCHAR4 AS CHAR(9)) <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where CAST(CVCHAR4 AS CHAR(20)) <> CVCHAR4;
select cidx, CVCHAR5 from datatypetestm where CAST(CVCHAR5 AS CHAR(1)) <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where CAST(CVCHAR5 AS CHAR(2)) <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where CAST(CVCHAR5 AS CHAR(3)) <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where CAST(CVCHAR5 AS CHAR(4)) <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where CAST(CVCHAR5 AS CHAR(5)) <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where CAST(CVCHAR5 AS CHAR(6)) <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where CAST(CVCHAR5 AS CHAR(7)) <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where CAST(CVCHAR5 AS CHAR(8)) <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where CAST(CVCHAR5 AS CHAR(9)) <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where CAST(CVCHAR5 AS CHAR(20)) <> CVCHAR5;
select cidx, CVCHAR6 from datatypetestm where CAST(CVCHAR6 AS CHAR(1)) <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where CAST(CVCHAR6 AS CHAR(2)) <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where CAST(CVCHAR6 AS CHAR(3)) <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where CAST(CVCHAR6 AS CHAR(4)) <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where CAST(CVCHAR6 AS CHAR(5)) <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where CAST(CVCHAR6 AS CHAR(6)) <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where CAST(CVCHAR6 AS CHAR(7)) <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where CAST(CVCHAR6 AS CHAR(8)) <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where CAST(CVCHAR6 AS CHAR(9)) <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where CAST(CVCHAR6 AS CHAR(20)) <> CVCHAR6;
select cidx, CVCHAR7 from datatypetestm where CAST(CVCHAR7 AS CHAR(1)) <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where CAST(CVCHAR7 AS CHAR(2)) <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where CAST(CVCHAR7 AS CHAR(3)) <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where CAST(CVCHAR7 AS CHAR(4)) <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where CAST(CVCHAR7 AS CHAR(5)) <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where CAST(CVCHAR7 AS CHAR(6)) <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where CAST(CVCHAR7 AS CHAR(7)) <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where CAST(CVCHAR7 AS CHAR(8)) <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where CAST(CVCHAR7 AS CHAR(9)) <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where CAST(CVCHAR7 AS CHAR(20)) <> CVCHAR7;
select cidx, CVCHAR8 from datatypetestm where CAST(CVCHAR8 AS CHAR(1)) <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where CAST(CVCHAR8 AS CHAR(2)) <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where CAST(CVCHAR8 AS CHAR(3)) <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where CAST(CVCHAR8 AS CHAR(4)) <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where CAST(CVCHAR8 AS CHAR(5)) <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where CAST(CVCHAR8 AS CHAR(6)) <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where CAST(CVCHAR8 AS CHAR(7)) <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where CAST(CVCHAR8 AS CHAR(8)) <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where CAST(CVCHAR8 AS CHAR(9)) <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where CAST(CVCHAR8 AS CHAR(20)) <> CVCHAR8;
select cidx, CVCHAR255 from datatypetestm where CAST(CVCHAR255 AS CHAR(1)) <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where CAST(CVCHAR255 AS CHAR(2)) <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where CAST(CVCHAR255 AS CHAR(3)) <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where CAST(CVCHAR255 AS CHAR(4)) <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where CAST(CVCHAR255 AS CHAR(5)) <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where CAST(CVCHAR255 AS CHAR(6)) <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where CAST(CVCHAR255 AS CHAR(7)) <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where CAST(CVCHAR255 AS CHAR(8)) <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where CAST(CVCHAR255 AS CHAR(9)) <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where CAST(CVCHAR255 AS CHAR(20)) <> CVCHAR255;
