select cidx, CBIGINT, CEIL(CBIGINT) from datatypetestm;
select cidx, CDECIMAL1, CEIL(CDECIMAL1) from datatypetestm;
select cidx, CDECIMAL4, CEIL(CDECIMAL4) from datatypetestm;
select cidx, CDECIMAL4_2, CEIL(CDECIMAL4_2) from datatypetestm;
select cidx, CDECIMAL5, CEIL(CDECIMAL5) from datatypetestm;
select cidx, CDECIMAL9, CEIL(CDECIMAL9) from datatypetestm;
select cidx, CDECIMAL9_2, CEIL(CDECIMAL9_2) from datatypetestm;
select cidx, CDECIMAL10, CEIL(CDECIMAL10) from datatypetestm;
select cidx, CDECIMAL18, CEIL(CDECIMAL18) from datatypetestm;
select cidx, CDECIMAL18_2, CEIL(CDECIMAL18_2) from datatypetestm;
select cidx, CINTEGER, CEIL(CINTEGER) from datatypetestm;
select cidx, CSMALLINT, CEIL(CSMALLINT) from datatypetestm;
select cidx, CTINYINT, CEIL(CTINYINT) from datatypetestm;
select cidx, CEIL(1.23) from datatypetestm;
select cidx, CEIL(-1.23) from datatypetestm;
select cidx, CEIL(0) from datatypetestm;
select cidx, CBIGINT from datatypetestm where CEIL(CBIGINT) <> CBIGINT;
select cidx, CDECIMAL1 from datatypetestm where CEIL(CDECIMAL1) <> CDECIMAL1;
select cidx, CDECIMAL4 from datatypetestm where CEIL(CDECIMAL4) <> CDECIMAL4;
select cidx, CDECIMAL4_2 from datatypetestm where CEIL(CDECIMAL4_2) <> CDECIMAL4_2;
select cidx, CDECIMAL5 from datatypetestm where CEIL(CDECIMAL5) <> CDECIMAL5;
select cidx, CDECIMAL9 from datatypetestm where CEIL(CDECIMAL9) <> CDECIMAL9;
select cidx, CDECIMAL9_2 from datatypetestm where CEIL(CDECIMAL9_2) <> CDECIMAL9_2;
select cidx, CDECIMAL10 from datatypetestm where CEIL(CDECIMAL10) <> CDECIMAL10;
select cidx, CDECIMAL18 from datatypetestm where CEIL(CDECIMAL18) <> CDECIMAL18;
select cidx, CDECIMAL18_2 from datatypetestm where CEIL(CDECIMAL18_2) <> CDECIMAL18_2;
select cidx, CINTEGER from datatypetestm where CEIL(CINTEGER) <> CINTEGER;
select cidx, CSMALLINT from datatypetestm where CEIL(CSMALLINT) <> CSMALLINT;
select cidx, CTINYINT from datatypetestm where CEIL(CTINYINT) <> CTINYINT;
select cidx, CBIGINT from datatypetestm where CEIL(CBIGINT) is null;
select cidx, CBIGINT from datatypetestm where isnull(CEIL(CBIGINT));
#select cidx, CDATE, CEIL(CDATE) from datatypetestm;
#select cidx, CDATETIME, CEIL(CDATETIME) from datatypetestm;
#select * from datatypetestm where ceil(CDATETIME) < 20091232;
#select * from datatypetestm where ceil(CDATE) < 20091232;
