SELECT cidx,CBIGINT,char(CBIGINT) from datatypetestm3;
SELECT cidx,CDECIMAL1,char(CDECIMAL1) from datatypetestm3;
SELECT cidx,CDECIMAL4,char(CDECIMAL4) from datatypetestm3;
SELECT cidx,CDECIMAL4_2,char(CDECIMAL4_2) from datatypetestm3;
SELECT cidx,CINTEGER,char(CINTEGER) from datatypetestm3;
SELECT cidx,CSMALLINT,char(CSMALLINT) from datatypetestm3;
SELECT cidx,CTINYINT,char(CTINYINT) from datatypetestm3;
SELECT cidx,CDOUBLE,char(CDOUBLE) from datatypetestm3;
SELECT cidx,CFLOAT,char(CFLOAT) from datatypetestm3;
SELECT cidx,CCHAR2,char(CCHAR2) from datatypetestm3;
SELECT cidx,CBIGINT,char(CBIGINT) from datatypetestm3;
SELECT cidx,CDECIMAL1,char(CDECIMAL1) from datatypetestm3 where char(CDECIMAL1) <> CDECIMAL1;
SELECT cidx,CDECIMAL4,char(CDECIMAL4) from datatypetestm3 where char(CDECIMAL4) <> CDECIMAL4;
SELECT cidx,CDECIMAL4_2,char(CDECIMAL4_2) from datatypetestm3 where char(CDECIMAL4_2) <> CDECIMAL4_2;
SELECT cidx,CINTEGER,char(CINTEGER) from datatypetestm3 where char(CINTEGER) <> CINTEGER;
SELECT cidx,CSMALLINT,char(CSMALLINT) from datatypetestm3 where char(CSMALLINT) <> CSMALLINT;
SELECT cidx,CTINYINT,char(CTINYINT) from datatypetestm3 where char(CTINYINT) <> CTINYINT;
SELECT cidx,CDOUBLE,char(CDOUBLE) from datatypetestm3 where char(CDOUBLE) <> CDOUBLE;
SELECT cidx,CFLOAT,char(CFLOAT) from datatypetestm3 where char(CFLOAT) <> CFLOAT;
SELECT cidx,CCHAR2,char(CCHAR2) from datatypetestm3 where char(CCHAR2) <> CCHAR2;
