select cidx, CCHAR1, CHAR_LENGTH(CCHAR1) from datatypetestm;
select cidx, CCHAR2, CHAR_LENGTH(CCHAR2) from datatypetestm;
select cidx, CCHAR3, CHAR_LENGTH(CCHAR3) from datatypetestm;
select cidx, CCHAR4, CHAR_LENGTH(CCHAR4) from datatypetestm;
select cidx, CCHAR5, CHAR_LENGTH(CCHAR5) from datatypetestm;
select cidx, CCHAR6, CHAR_LENGTH(CCHAR6) from datatypetestm;
select cidx, CCHAR7, CHAR_LENGTH(CCHAR7) from datatypetestm;
select cidx, CCHAR8, CHAR_LENGTH(CCHAR8) from datatypetestm;
select cidx, CCHAR9, CHAR_LENGTH(CCHAR9) from datatypetestm;
select cidx, CCHAR255, CHAR_LENGTH(CCHAR255) from datatypetestm;
select cidx, CVCHAR1, CHAR_LENGTH(CVCHAR1) from datatypetestm;
select cidx, CVCHAR2, CHAR_LENGTH(CVCHAR2) from datatypetestm;
select cidx, CVCHAR3, CHAR_LENGTH(CVCHAR3) from datatypetestm;
select cidx, CVCHAR4, CHAR_LENGTH(CVCHAR4) from datatypetestm;
select cidx, CVCHAR5, CHAR_LENGTH(CVCHAR5) from datatypetestm;
select cidx, CVCHAR6, CHAR_LENGTH(CVCHAR6) from datatypetestm;
select cidx, CVCHAR7, CHAR_LENGTH(CVCHAR7) from datatypetestm;
select cidx, CVCHAR8, CHAR_LENGTH(CVCHAR8) from datatypetestm;
select cidx, CVCHAR255, CHAR_LENGTH(CVCHAR255) from datatypetestm;
select cidx, CHAR_LENGTH('ALOHA') from datatypetestm;
select cidx, CHAR_LENGTH('MAHALO') from datatypetestm;
select cidx, CHAR_LENGTH('Hawaii') from datatypetestm;
select cidx, CCHAR1 from datatypetestm where CHAR_LENGTH(CCHAR1) <> CCHAR1;
select cidx, CCHAR2 from datatypetestm where CHAR_LENGTH(CCHAR2) <> CCHAR2;
select cidx, CCHAR3 from datatypetestm where CHAR_LENGTH(CCHAR3) <> CCHAR3;
select cidx, CCHAR4 from datatypetestm where CHAR_LENGTH(CCHAR4) <> CCHAR4;
select cidx, CCHAR5 from datatypetestm where CHAR_LENGTH(CCHAR5) <> CCHAR5;
select cidx, CCHAR6 from datatypetestm where CHAR_LENGTH(CCHAR6) <> CCHAR6;
select cidx, CCHAR7 from datatypetestm where CHAR_LENGTH(CCHAR7) <> CCHAR7;
select cidx, CCHAR8 from datatypetestm where CHAR_LENGTH(CCHAR8) <> CCHAR8;
select cidx, CCHAR9 from datatypetestm where CHAR_LENGTH(CCHAR9) <> CCHAR9;
select cidx, CCHAR255 from datatypetestm where CHAR_LENGTH(CCHAR255) <> CCHAR255;
select cidx, CVCHAR1 from datatypetestm where CHAR_LENGTH(CVCHAR1) <> CVCHAR1;
select cidx, CVCHAR2 from datatypetestm where CHAR_LENGTH(CVCHAR2) <> CVCHAR2;
select cidx, CVCHAR3 from datatypetestm where CHAR_LENGTH(CVCHAR3) <> CVCHAR3;
select cidx, CVCHAR4 from datatypetestm where CHAR_LENGTH(CVCHAR4) <> CVCHAR4;
select cidx, CVCHAR5 from datatypetestm where CHAR_LENGTH(CVCHAR5) <> CVCHAR5;
select cidx, CVCHAR6 from datatypetestm where CHAR_LENGTH(CVCHAR6) <> CVCHAR6;
select cidx, CVCHAR7 from datatypetestm where CHAR_LENGTH(CVCHAR7) <> CVCHAR7;
select cidx, CVCHAR8 from datatypetestm where CHAR_LENGTH(CVCHAR8) <> CVCHAR8;
select cidx, CVCHAR255 from datatypetestm where CHAR_LENGTH(CVCHAR255) <> CVCHAR255;
