select cidx, CBIGINT, CONVERT(CBIGINT,SIGNED) from datatypetestm;
select cidx, CBIGINT, CONVERT(CBIGINT,DECIMAL(9)) from datatypetestm;
select cidx, CBIGINT, CONVERT(CBIGINT,DECIMAL(9,2)) from datatypetestm;
select cidx, CDECIMAL1, CONVERT(CDECIMAL1,SIGNED) from datatypetestm;
select cidx, CDECIMAL1, CONVERT(CDECIMAL1,DECIMAL(9)) from datatypetestm;
select cidx, CDECIMAL1, CONVERT(CDECIMAL1,DECIMAL(9,2)) from datatypetestm;
select cidx, CDECIMAL4, CONVERT(CDECIMAL4,SIGNED) from datatypetestm;
select cidx, CDECIMAL4, CONVERT(CDECIMAL4,DECIMAL(9)) from datatypetestm;
select cidx, CDECIMAL4, CONVERT(CDECIMAL4,DECIMAL(9,2)) from datatypetestm;
select cidx, CDECIMAL4_2, CONVERT(CDECIMAL4_2,SIGNED) from datatypetestm;
select cidx, CDECIMAL4_2, CONVERT(CDECIMAL4_2,DECIMAL(9)) from datatypetestm;
select cidx, CDECIMAL4_2, CONVERT(CDECIMAL4_2,DECIMAL(9,2)) from datatypetestm;
select cidx, CDECIMAL5, CONVERT(CDECIMAL5,SIGNED) from datatypetestm;
select cidx, CDECIMAL5, CONVERT(CDECIMAL5,DECIMAL(9)) from datatypetestm;
select cidx, CDECIMAL5, CONVERT(CDECIMAL5,DECIMAL(9,2)) from datatypetestm;
select cidx, CDECIMAL9, CONVERT(CDECIMAL9,SIGNED) from datatypetestm;
select cidx, CDECIMAL9, CONVERT(CDECIMAL9,DECIMAL(9)) from datatypetestm;
select cidx, CDECIMAL9, CONVERT(CDECIMAL9,DECIMAL(9,2)) from datatypetestm;
select cidx, CDECIMAL9_2, CONVERT(CDECIMAL9_2,SIGNED) from datatypetestm;
select cidx, CDECIMAL9_2, CONVERT(CDECIMAL9_2,DECIMAL(9)) from datatypetestm;
select cidx, CDECIMAL9_2, CONVERT(CDECIMAL9_2,DECIMAL(9,2)) from datatypetestm;
select cidx, CDECIMAL10, CONVERT(CDECIMAL10,SIGNED) from datatypetestm;
select cidx, CDECIMAL10, CONVERT(CDECIMAL10,DECIMAL(9)) from datatypetestm;
select cidx, CDECIMAL10, CONVERT(CDECIMAL10,DECIMAL(9,2)) from datatypetestm;
select cidx, CDECIMAL18, CONVERT(CDECIMAL18,SIGNED) from datatypetestm;
select cidx, CDECIMAL18, CONVERT(CDECIMAL18,DECIMAL(9)) from datatypetestm;
select cidx, CDECIMAL18, CONVERT(CDECIMAL18,DECIMAL(9,2)) from datatypetestm;
select cidx, CDECIMAL18_2, CONVERT(CDECIMAL18_2,SIGNED) from datatypetestm;
select cidx, CDECIMAL18_2, CONVERT(CDECIMAL18_2,DECIMAL(9)) from datatypetestm;
select cidx, CDECIMAL18_2, CONVERT(CDECIMAL18_2,DECIMAL(9,2)) from datatypetestm;
select cidx, CINTEGER, CONVERT(CINTEGER,SIGNED) from datatypetestm;
select cidx, CINTEGER, CONVERT(CINTEGER,DECIMAL(9)) from datatypetestm;
select cidx, CINTEGER, CONVERT(CINTEGER,DECIMAL(9,2)) from datatypetestm;
select cidx, CSMALLINT, CONVERT(CSMALLINT,SIGNED) from datatypetestm;
select cidx, CSMALLINT, CONVERT(CSMALLINT,DECIMAL(9)) from datatypetestm;
select cidx, CSMALLINT, CONVERT(CSMALLINT,DECIMAL(9,2)) from datatypetestm;
select cidx, CTINYINT, CONVERT(CTINYINT,SIGNED) from datatypetestm;
select cidx, CTINYINT, CONVERT(CTINYINT,DECIMAL(9)) from datatypetestm;
select cidx, CTINYINT, CONVERT(CTINYINT,DECIMAL(9,2)) from datatypetestm;
select cidx, CBIGINT from datatypetestm where CONVERT(CBIGINT,SIGNED) <> CBIGINT;
select cidx, CBIGINT from datatypetestm where CONVERT(CBIGINT,DECIMAL(9)) <> CBIGINT;
select cidx, CBIGINT from datatypetestm where CONVERT(CBIGINT,DECIMAL(9,2)) <> CBIGINT;
select cidx, CDECIMAL1 from datatypetestm where CONVERT(CDECIMAL1,SIGNED) <> CDECIMAL1;
select cidx, CDECIMAL1 from datatypetestm where CONVERT(CDECIMAL1,DECIMAL(9)) <> CDECIMAL1;
select cidx, CDECIMAL1 from datatypetestm where CONVERT(CDECIMAL1,DECIMAL(9,2)) <> CDECIMAL1;
select cidx, CDECIMAL4 from datatypetestm where CONVERT(CDECIMAL4,SIGNED) <> CDECIMAL4;
select cidx, CDECIMAL4 from datatypetestm where CONVERT(CDECIMAL4,DECIMAL(9)) <> CDECIMAL4;
select cidx, CDECIMAL4 from datatypetestm where CONVERT(CDECIMAL4,DECIMAL(9,2)) <> CDECIMAL4;
select cidx, CDECIMAL4_2 from datatypetestm where CONVERT(CDECIMAL4_2,SIGNED) <> CDECIMAL4_2;
select cidx, CDECIMAL4_2 from datatypetestm where CONVERT(CDECIMAL4_2,DECIMAL(9)) <> CDECIMAL4_2;
select cidx, CDECIMAL4_2 from datatypetestm where CONVERT(CDECIMAL4_2,DECIMAL(9,2)) <> CDECIMAL4_2;
select cidx, CDECIMAL5 from datatypetestm where CONVERT(CDECIMAL5,SIGNED) <> CDECIMAL5;
select cidx, CDECIMAL5 from datatypetestm where CONVERT(CDECIMAL5,DECIMAL(9)) <> CDECIMAL5;
select cidx, CDECIMAL5 from datatypetestm where CONVERT(CDECIMAL5,DECIMAL(9,2)) <> CDECIMAL5;
select cidx, CDECIMAL9 from datatypetestm where CONVERT(CDECIMAL9,SIGNED) <> CDECIMAL9;
select cidx, CDECIMAL9 from datatypetestm where CONVERT(CDECIMAL9,DECIMAL(9)) <> CDECIMAL9;
select cidx, CDECIMAL9 from datatypetestm where CONVERT(CDECIMAL9,DECIMAL(9,2)) <> CDECIMAL9;
select cidx, CDECIMAL9_2 from datatypetestm where CONVERT(CDECIMAL9_2,SIGNED) <> CDECIMAL9_2;
select cidx, CDECIMAL9_2 from datatypetestm where CONVERT(CDECIMAL9_2,DECIMAL(9)) <> CDECIMAL9_2;
select cidx, CDECIMAL9_2 from datatypetestm where CONVERT(CDECIMAL9_2,DECIMAL(9,2)) <> CDECIMAL9_2;
select cidx, CDECIMAL10 from datatypetestm where CONVERT(CDECIMAL10,SIGNED) <> CDECIMAL10;
select cidx, CDECIMAL10 from datatypetestm where CONVERT(CDECIMAL10,DECIMAL(9)) <> CDECIMAL10;
select cidx, CDECIMAL10 from datatypetestm where CONVERT(CDECIMAL10,DECIMAL(9,2)) <> CDECIMAL10;
select cidx, CDECIMAL18 from datatypetestm where CONVERT(CDECIMAL18,SIGNED) <> CDECIMAL18;
select cidx, CDECIMAL18 from datatypetestm where CONVERT(CDECIMAL18,DECIMAL(9)) <> CDECIMAL18;
select cidx, CDECIMAL18 from datatypetestm where CONVERT(CDECIMAL18,DECIMAL(9,2)) <> CDECIMAL18;
select cidx, CDECIMAL18_2 from datatypetestm where CONVERT(CDECIMAL18_2,SIGNED) <> CDECIMAL18_2;
select cidx, CDECIMAL18_2 from datatypetestm where CONVERT(CDECIMAL18_2,DECIMAL(9)) <> CDECIMAL18_2;
select cidx, CDECIMAL18_2 from datatypetestm where CONVERT(CDECIMAL18_2,DECIMAL(9,2)) <> CDECIMAL18_2;
select cidx, CINTEGER from datatypetestm where CONVERT(CINTEGER,SIGNED) <> CINTEGER;
select cidx, CINTEGER from datatypetestm where CONVERT(CINTEGER,DECIMAL(9)) <> CINTEGER;
select cidx, CINTEGER from datatypetestm where CONVERT(CINTEGER,DECIMAL(9,2)) <> CINTEGER;
select cidx, CSMALLINT from datatypetestm where CONVERT(CSMALLINT,SIGNED) <> CSMALLINT;
select cidx, CSMALLINT from datatypetestm where CONVERT(CSMALLINT,DECIMAL(9)) <> CSMALLINT;
select cidx, CSMALLINT from datatypetestm where CONVERT(CSMALLINT,DECIMAL(9,2)) <> CSMALLINT;
select cidx, CTINYINT from datatypetestm where CONVERT(CTINYINT,SIGNED) <> CTINYINT;
select cidx, CTINYINT from datatypetestm where CONVERT(CTINYINT,DECIMAL(9)) <> CTINYINT;
select cidx, CTINYINT from datatypetestm where CONVERT(CTINYINT,DECIMAL(9,2)) <> CTINYINT;
