select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '01:22' YEAR_MONTH) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 0 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 0 MONTH) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -100 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 100 day) from datatypetestm ;
#select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '10 10:10:10:10:10' DAY_MICROSECOND) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '10 10:10:10:10:10' DAY_SECOND) from datatypetestm ;
#select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '10 10:10:10:10' DAY_MICROSECOND) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '10 10:10:10:10' DAY_SECOND) from datatypetestm ;
#select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '10:10:10:10:9' HOUR_MICROSECOND) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '10:10:10:10:9' HOUR_SECOND) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '10:10:10:10:9' month) from datatypetestm ;
#select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '10 10:10:10' DAY_MICROSECOND) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '10 10:10:10' DAY_MINUTE) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '10 10:10:10' DAY_SECOND) from datatypetestm ;
#select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '10:10:10:10' HOUR_MICROSECOND) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '10:10:10:10' HOUR_SECOND) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '10 10:10' DAY_HOUR) from datatypetestm ;
#select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '10 10:10' DAY_MICROSECOND) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '10 10:10' DAY_MINUTE) from datatypetestm ;
#select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '10:10:10' HOUR_MICROSECOND) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '10:10:10' HOUR_MINUTE) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '10:10:10' HOUR_SECOND) from datatypetestm ;
#select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '10:10.10' MINUTE_MICROSECOND) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '10:10.10' MINUTE_SECOND) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '10 10' DAY_HOUR) from datatypetestm ;
#select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '10 10' DAY_MICROSECOND) from datatypetestm ;
#select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '10:10' HOUR_MICROSECOND) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '10 10' HOUR_MINUTE) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '10:10' HOUR_MINUTE) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '10:10' HOUR_SECOND) from datatypetestm ;
#select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '10:10' MINUTE_MICROSECOND) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '10:10' MINUTE_SECOND) from datatypetestm ;
#select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '10:10' SECOND_MICROSECOND) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '10 10' YEAR_MONTH) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -10 -200 year_MONTH) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 10 -200 year_MONTH) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -10 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 10 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '10' DAY_HOUR) from datatypetestm ;
#select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 10 HOUR_MICROSECOND) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '10' HOUR_SECOND) from datatypetestm ;
#select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '10' MINUTE_MICROSECOND) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '10' MINUTE_SECOND) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 10 MINUTE_SECOND) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 10 month) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -10 MONTH) from datatypetestm ;
#select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '10' SECOND_MICROSECOND) from datatypetestm ;
#select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 10 SECOND_MICROSECOND) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 10 year) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '10' YEAR_MONTH) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '111111:22' YEAR_MONTH) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -11111 year) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 11 month) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -11 MONTH) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '11' YEAR_MONTH) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 120 second) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 12 month) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -12 MONTH) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 12 MONTH) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '12' YEAR_MONTH) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 13 month) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -13 MONTH) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '13' YEAR_MONTH) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -14 MONTH) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -15 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -1 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 1 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 1 hour) from datatypetestm ;
#select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -1 microsecond) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -1 MONTH) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 1 MONTH) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 1 quarter) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 1 second) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 1 week) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL --1 year) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -1 year) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 1 year) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL --1 YEAR_MONTH) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -1 YEAR_MONTH) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '1' YEAR_MONTH) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 200 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -200 MONTH) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -200 year_MONTH) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '20' YEAR_MONTH) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '21' YEAR_MONTH) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '22' YEAR_MONTH) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 23 hour) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 23 month) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '23' YEAR_MONTH) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 24888 year) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 24 hour) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 24 month) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 24 year) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '24' YEAR_MONTH) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -29 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -2 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -2 MONTH) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 2 quarter) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -300 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -305 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -306 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -307 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -308 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -309 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -30 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 30 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -310 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -311 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -31 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 31 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -32 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 32 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -330 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -33 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '3 3' year) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '3:3' year) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL '3?3' year) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 34 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 3600 minute) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 3600 second) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 3 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 3 DAY) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 3 hour) from datatypetestm ;
#select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 3 microsecond) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 3 minute) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 3 month) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 3 quarter) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 3 SECOND) from datatypetestm;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 3 SECOND) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 3 week) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 3 year) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -4000 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 41 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 48 hour) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 4 quarter) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 4 week) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 4 year) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 51 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 57 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 58 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 590 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 59 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 59 second) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 5 week) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -60 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 60 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 60 second) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -61 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 61 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 61 minute) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 61 second) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -62 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -63 day) from datatypetestm ;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL -64 day) from datatypetestm ;
select cidx, CDATETIME, DATE_ADD(CDATETIME, INTERVAL 3 DAY) from datatypetestm ;
