select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 3 SECOND) from datatypetestm;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 3 MINUTE) from datatypetestm;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 3 HOUR) from datatypetestm;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 3 DAY) from datatypetestm;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 3 WEEK) from datatypetestm;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 3 MONTH) from datatypetestm;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 3 QUARTER) from datatypetestm;
select cidx, CDATE, DATE_ADD(CDATE, INTERVAL 3 YEAR) from datatypetestm;
select cidx, CDATETIME, DATE_ADD(CDATETIME, INTERVAL 3 SECOND) from datatypetestm;
select cidx, CDATETIME, DATE_ADD(CDATETIME, INTERVAL 3 MINUTE) from datatypetestm;
select cidx, CDATETIME, DATE_ADD(CDATETIME, INTERVAL 3 HOUR) from datatypetestm;
select cidx, CDATETIME, DATE_ADD(CDATETIME, INTERVAL 3 DAY) from datatypetestm;
select cidx, CDATETIME, DATE_ADD(CDATETIME, INTERVAL 3 WEEK) from datatypetestm;
select cidx, CDATETIME, DATE_ADD(CDATETIME, INTERVAL 3 MONTH) from datatypetestm;
select cidx, CDATETIME, DATE_ADD(CDATETIME, INTERVAL 3 QUARTER) from datatypetestm;
select cidx, CDATETIME, DATE_ADD(CDATETIME, INTERVAL 3 YEAR) from datatypetestm;
select cidx, CDATE from datatypetestm where DATE_ADD(CDATE, INTERVAL 3 SECOND) <> CDATE;
select cidx, CDATE from datatypetestm where DATE_ADD(CDATE, INTERVAL 3 MINUTE) <> CDATE;
select cidx, CDATE from datatypetestm where DATE_ADD(CDATE, INTERVAL 3 HOUR) <> CDATE;
select cidx, CDATE from datatypetestm where DATE_ADD(CDATE, INTERVAL 3 DAY) <> CDATE;
select cidx, CDATE from datatypetestm where DATE_ADD(CDATE, INTERVAL 3 WEEK) <> CDATE;
select cidx, CDATE from datatypetestm where DATE_ADD(CDATE, INTERVAL 3 MONTH) <> CDATE;
select cidx, CDATE from datatypetestm where DATE_ADD(CDATE, INTERVAL 3 QUARTER) <> CDATE;
select cidx, CDATE from datatypetestm where DATE_ADD(CDATE, INTERVAL 3 YEAR) <> CDATE;
select cidx, CDATETIME from datatypetestm where DATE_ADD(CDATETIME, INTERVAL 3 SECOND) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where DATE_ADD(CDATETIME, INTERVAL 3 MINUTE) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where DATE_ADD(CDATETIME, INTERVAL 3 HOUR) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where DATE_ADD(CDATETIME, INTERVAL 3 DAY) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where DATE_ADD(CDATETIME, INTERVAL 3 WEEK) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where DATE_ADD(CDATETIME, INTERVAL 3 MONTH) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where DATE_ADD(CDATETIME, INTERVAL 3 QUARTER) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where DATE_ADD(CDATETIME, INTERVAL 3 YEAR) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where DATE_ADD('2007-01-01', INTERVAL 3 SECOND) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where DATE_ADD('2007-01-01', INTERVAL 3 MINUTE) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where DATE_ADD('2007-01-01', INTERVAL 3 HOUR) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where DATE_ADD('2007-01-01', INTERVAL 3 DAY) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where DATE_ADD('2007-01-01', INTERVAL 3 WEEK) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where DATE_ADD('2007-01-01', INTERVAL 3 MONTH) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where DATE_ADD('2007-01-01', INTERVAL 3 QUARTER) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where DATE_ADD('2007-01-01', INTERVAL 3 YEAR) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where DATE_ADD('2007-01-01 01:02:03', INTERVAL 3 SECOND) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where DATE_ADD('2007-01-01 01:02:03', INTERVAL 3 MINUTE) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where DATE_ADD('2007-01-01 01:02:03', INTERVAL 3 HOUR) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where DATE_ADD('2007-01-01 01:02:03', INTERVAL 3 DAY) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where DATE_ADD('2007-01-01 01:02:03', INTERVAL 3 WEEK) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where DATE_ADD('2007-01-01 01:02:03', INTERVAL 3 MONTH) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where DATE_ADD('2007-01-01 01:02:03', INTERVAL 3 QUARTER) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where DATE_ADD('2007-01-01 01:02:03', INTERVAL 3 YEAR) <> CDATETIME;
