select cidx, CBIGINT, DEGREES(CBIGINT) from datatypetestm;
select cidx, CDECIMAL1, DEGREES(CDECIMAL1) from datatypetestm;
select cidx, CDECIMAL4, DEGREES(CDECIMAL4) from datatypetestm;
select cidx, CDECIMAL4_2, DEGREES(CDECIMAL4_2) from datatypetestm;
select cidx, CDECIMAL5, DEGREES(CDECIMAL5) from datatypetestm;
select cidx, CDECIMAL9, DEGREES(CDECIMAL9) from datatypetestm;
select cidx, CDECIMAL9_2, DEGREES(CDECIMAL9_2) from datatypetestm;
select cidx, CDECIMAL10, DEGREES(CDECIMAL10) from datatypetestm;
select cidx, CDECIMAL18, DEGREES(CDECIMAL18) from datatypetestm;
select cidx, CDECIMAL18_2, DEGREES(CDECIMAL18_2) from datatypetestm;
select cidx, CINTEGER, DEGREES(CINTEGER) from datatypetestm;
select cidx, CSMALLINT, DEGREES(CSMALLINT) from datatypetestm;
select cidx, CTINYINT, DEGREES(CTINYINT) from datatypetestm;
select cidx, DEGREES(0) from datatypetestm;
select cidx, DEGREES(60) from datatypetestm;
select cidx, DEGREES(90) from datatypetestm;
select cidx, DEGREES(180) from datatypetestm;
select cidx, DEGREES(360) from datatypetestm;
select cidx, CBIGINT from datatypetestm where DEGREES(CBIGINT) <> 0;
select cidx, CDECIMAL1 from datatypetestm where DEGREES(CDECIMAL1) <> 0;
select cidx, CDECIMAL4 from datatypetestm where DEGREES(CDECIMAL4) <> 0;
select cidx, CDECIMAL4_2 from datatypetestm where DEGREES(CDECIMAL4_2) <> 0;
select cidx, CDECIMAL5 from datatypetestm where DEGREES(CDECIMAL5) <> 0;
select cidx, CDECIMAL9 from datatypetestm where DEGREES(CDECIMAL9) <> 0;
select cidx, CDECIMAL9_2 from datatypetestm where DEGREES(CDECIMAL9_2) <> 0;
select cidx, CDECIMAL10 from datatypetestm where DEGREES(CDECIMAL10) <> 0;
select cidx, CDECIMAL18 from datatypetestm where DEGREES(CDECIMAL18) <> 0;
select cidx, CDECIMAL18_2 from datatypetestm where DEGREES(CDECIMAL18_2) <> 0;
select cidx, CINTEGER from datatypetestm where DEGREES(CINTEGER) <> 0;
select cidx, CSMALLINT from datatypetestm where DEGREES(CSMALLINT) <> 0;
select cidx, CTINYINT from datatypetestm where DEGREES(CTINYINT) <> 0;
