select cidx, CBIGINT, FORMAT(CBIGINT,0) from datatypetestm;
select cidx, CBIGINT, FORMAT(CBIGINT,1) from datatypetestm;
select cidx, CBIGINT, FORMAT(CBIGINT,2) from datatypetestm;
select cidx, CBIGINT, FORMAT(CBIGINT,3) from datatypetestm;
select cidx, CBIGINT, FORMAT(CBIGINT,4) from datatypetestm;
select cidx, CDECIMAL1, FORMAT(CDECIMAL1,0) from datatypetestm;
select cidx, CDECIMAL1, FORMAT(CDECIMAL1,1) from datatypetestm;
select cidx, CDECIMAL1, FORMAT(CDECIMAL1,2) from datatypetestm;
select cidx, CDECIMAL1, FORMAT(CDECIMAL1,3) from datatypetestm;
select cidx, CDECIMAL1, FORMAT(CDECIMAL1,4) from datatypetestm;
select cidx, CDECIMAL4, FORMAT(CDECIMAL4,0) from datatypetestm;
select cidx, CDECIMAL4, FORMAT(CDECIMAL4,1) from datatypetestm;
select cidx, CDECIMAL4, FORMAT(CDECIMAL4,2) from datatypetestm;
select cidx, CDECIMAL4, FORMAT(CDECIMAL4,3) from datatypetestm;
select cidx, CDECIMAL4, FORMAT(CDECIMAL4,4) from datatypetestm;
select cidx, CDECIMAL4_2, FORMAT(CDECIMAL4_2,0) from datatypetestm;
select cidx, CDECIMAL4_2, FORMAT(CDECIMAL4_2,1) from datatypetestm;
select cidx, CDECIMAL4_2, FORMAT(CDECIMAL4_2,2) from datatypetestm;
select cidx, CDECIMAL4_2, FORMAT(CDECIMAL4_2,3) from datatypetestm;
select cidx, CDECIMAL4_2, FORMAT(CDECIMAL4_2,4) from datatypetestm;
select cidx, CDECIMAL5, FORMAT(CDECIMAL5,0) from datatypetestm;
select cidx, CDECIMAL5, FORMAT(CDECIMAL5,1) from datatypetestm;
select cidx, CDECIMAL5, FORMAT(CDECIMAL5,2) from datatypetestm;
select cidx, CDECIMAL5, FORMAT(CDECIMAL5,3) from datatypetestm;
select cidx, CDECIMAL5, FORMAT(CDECIMAL5,4) from datatypetestm;
select cidx, CDECIMAL9, FORMAT(CDECIMAL9,0) from datatypetestm;
select cidx, CDECIMAL9, FORMAT(CDECIMAL9,1) from datatypetestm;
select cidx, CDECIMAL9, FORMAT(CDECIMAL9,2) from datatypetestm;
select cidx, CDECIMAL9, FORMAT(CDECIMAL9,3) from datatypetestm;
select cidx, CDECIMAL9, FORMAT(CDECIMAL9,4) from datatypetestm;
select cidx, CDECIMAL9_2, FORMAT(CDECIMAL9_2,0) from datatypetestm;
select cidx, CDECIMAL9_2, FORMAT(CDECIMAL9_2,1) from datatypetestm;
select cidx, CDECIMAL9_2, FORMAT(CDECIMAL9_2,2) from datatypetestm;
select cidx, CDECIMAL9_2, FORMAT(CDECIMAL9_2,3) from datatypetestm;
select cidx, CDECIMAL9_2, FORMAT(CDECIMAL9_2,4) from datatypetestm;
select cidx, CDECIMAL10, FORMAT(CDECIMAL10,0) from datatypetestm;
select cidx, CDECIMAL10, FORMAT(CDECIMAL10,1) from datatypetestm;
select cidx, CDECIMAL10, FORMAT(CDECIMAL10,2) from datatypetestm;
select cidx, CDECIMAL10, FORMAT(CDECIMAL10,3) from datatypetestm;
select cidx, CDECIMAL10, FORMAT(CDECIMAL10,4) from datatypetestm;
select cidx, CDECIMAL18, FORMAT(CDECIMAL18,0) from datatypetestm;
select cidx, CDECIMAL18, FORMAT(CDECIMAL18,1) from datatypetestm;
select cidx, CDECIMAL18, FORMAT(CDECIMAL18,2) from datatypetestm;
select cidx, CDECIMAL18, FORMAT(CDECIMAL18,3) from datatypetestm;
select cidx, CDECIMAL18, FORMAT(CDECIMAL18,4) from datatypetestm;
select cidx, CDECIMAL18_2, FORMAT(CDECIMAL18_2,0) from datatypetestm;
select cidx, CDECIMAL18_2, FORMAT(CDECIMAL18_2,1) from datatypetestm;
select cidx, CDECIMAL18_2, FORMAT(CDECIMAL18_2,2) from datatypetestm;
select cidx, CDECIMAL18_2, FORMAT(CDECIMAL18_2,3) from datatypetestm;
select cidx, CDECIMAL18_2, FORMAT(CDECIMAL18_2,4) from datatypetestm;
select cidx, CINTEGER, FORMAT(CINTEGER,0) from datatypetestm;
select cidx, CINTEGER, FORMAT(CINTEGER,1) from datatypetestm;
select cidx, CINTEGER, FORMAT(CINTEGER,2) from datatypetestm;
select cidx, CINTEGER, FORMAT(CINTEGER,3) from datatypetestm;
select cidx, CINTEGER, FORMAT(CINTEGER,4) from datatypetestm;
select cidx, CSMALLINT, FORMAT(CSMALLINT,0) from datatypetestm;
select cidx, CSMALLINT, FORMAT(CSMALLINT,1) from datatypetestm;
select cidx, CSMALLINT, FORMAT(CSMALLINT,2) from datatypetestm;
select cidx, CSMALLINT, FORMAT(CSMALLINT,3) from datatypetestm;
select cidx, CSMALLINT, FORMAT(CSMALLINT,4) from datatypetestm;
select cidx, CTINYINT, FORMAT(CTINYINT,0) from datatypetestm;
select cidx, CTINYINT, FORMAT(CTINYINT,1) from datatypetestm;
select cidx, CTINYINT, FORMAT(CTINYINT,2) from datatypetestm;
select cidx, CTINYINT, FORMAT(CTINYINT,3) from datatypetestm;
select cidx, CTINYINT, FORMAT(CTINYINT,4) from datatypetestm;
select cidx, CBIGINT from datatypetestm where FORMAT(CBIGINT,0) <> 0;
select cidx, CBIGINT from datatypetestm where FORMAT(CBIGINT,1) <> 0;
select cidx, CBIGINT from datatypetestm where FORMAT(CBIGINT,2) <> 0;
select cidx, CBIGINT from datatypetestm where FORMAT(CBIGINT,3) <> 0;
select cidx, CBIGINT from datatypetestm where FORMAT(CBIGINT,4) <> 0;
select cidx, CDECIMAL1 from datatypetestm where FORMAT(CDECIMAL1,0) <> 0;
select cidx, CDECIMAL1 from datatypetestm where FORMAT(CDECIMAL1,1) <> 0;
select cidx, CDECIMAL1 from datatypetestm where FORMAT(CDECIMAL1,2) <> 0;
select cidx, CDECIMAL1 from datatypetestm where FORMAT(CDECIMAL1,3) <> 0;
select cidx, CDECIMAL1 from datatypetestm where FORMAT(CDECIMAL1,4) <> 0;
select cidx, CDECIMAL4 from datatypetestm where FORMAT(CDECIMAL4,0) <> 0;
select cidx, CDECIMAL4 from datatypetestm where FORMAT(CDECIMAL4,1) <> 0;
select cidx, CDECIMAL4 from datatypetestm where FORMAT(CDECIMAL4,2) <> 0;
select cidx, CDECIMAL4 from datatypetestm where FORMAT(CDECIMAL4,3) <> 0;
select cidx, CDECIMAL4 from datatypetestm where FORMAT(CDECIMAL4,4) <> 0;
select cidx, CDECIMAL4_2 from datatypetestm where FORMAT(CDECIMAL4_2,0) <> 0;
select cidx, CDECIMAL4_2 from datatypetestm where FORMAT(CDECIMAL4_2,1) <> 0;
select cidx, CDECIMAL4_2 from datatypetestm where FORMAT(CDECIMAL4_2,2) <> 0;
select cidx, CDECIMAL4_2 from datatypetestm where FORMAT(CDECIMAL4_2,3) <> 0;
select cidx, CDECIMAL4_2 from datatypetestm where FORMAT(CDECIMAL4_2,4) <> 0;
select cidx, CDECIMAL5 from datatypetestm where FORMAT(CDECIMAL5,0) <> 0;
select cidx, CDECIMAL5 from datatypetestm where FORMAT(CDECIMAL5,1) <> 0;
select cidx, CDECIMAL5 from datatypetestm where FORMAT(CDECIMAL5,2) <> 0;
select cidx, CDECIMAL5 from datatypetestm where FORMAT(CDECIMAL5,3) <> 0;
select cidx, CDECIMAL5 from datatypetestm where FORMAT(CDECIMAL5,4) <> 0;
select cidx, CDECIMAL9 from datatypetestm where FORMAT(CDECIMAL9,0) <> 0;
select cidx, CDECIMAL9 from datatypetestm where FORMAT(CDECIMAL9,1) <> 0;
select cidx, CDECIMAL9 from datatypetestm where FORMAT(CDECIMAL9,2) <> 0;
select cidx, CDECIMAL9 from datatypetestm where FORMAT(CDECIMAL9,3) <> 0;
select cidx, CDECIMAL9 from datatypetestm where FORMAT(CDECIMAL9,4) <> 0;
select cidx, CDECIMAL9_2 from datatypetestm where FORMAT(CDECIMAL9_2,0) <> 0;
select cidx, CDECIMAL9_2 from datatypetestm where FORMAT(CDECIMAL9_2,1) <> 0;
select cidx, CDECIMAL9_2 from datatypetestm where FORMAT(CDECIMAL9_2,2) <> 0;
select cidx, CDECIMAL9_2 from datatypetestm where FORMAT(CDECIMAL9_2,3) <> 0;
select cidx, CDECIMAL9_2 from datatypetestm where FORMAT(CDECIMAL9_2,4) <> 0;
select cidx, CDECIMAL10 from datatypetestm where FORMAT(CDECIMAL10,0) <> 0;
select cidx, CDECIMAL10 from datatypetestm where FORMAT(CDECIMAL10,1) <> 0;
select cidx, CDECIMAL10 from datatypetestm where FORMAT(CDECIMAL10,2) <> 0;
select cidx, CDECIMAL10 from datatypetestm where FORMAT(CDECIMAL10,3) <> 0;
select cidx, CDECIMAL10 from datatypetestm where FORMAT(CDECIMAL10,4) <> 0;
select cidx, CDECIMAL18 from datatypetestm where FORMAT(CDECIMAL18,0) <> 0;
select cidx, CDECIMAL18 from datatypetestm where FORMAT(CDECIMAL18,1) <> 0;
select cidx, CDECIMAL18 from datatypetestm where FORMAT(CDECIMAL18,2) <> 0;
select cidx, CDECIMAL18 from datatypetestm where FORMAT(CDECIMAL18,3) <> 0;
select cidx, CDECIMAL18 from datatypetestm where FORMAT(CDECIMAL18,4) <> 0;
select cidx, CDECIMAL18_2 from datatypetestm where FORMAT(CDECIMAL18_2,0) <> 0;
select cidx, CDECIMAL18_2 from datatypetestm where FORMAT(CDECIMAL18_2,1) <> 0;
select cidx, CDECIMAL18_2 from datatypetestm where FORMAT(CDECIMAL18_2,2) <> 0;
select cidx, CDECIMAL18_2 from datatypetestm where FORMAT(CDECIMAL18_2,3) <> 0;
select cidx, CDECIMAL18_2 from datatypetestm where FORMAT(CDECIMAL18_2,4) <> 0;
select cidx, CINTEGER from datatypetestm where FORMAT(CINTEGER,0) <> 0;
select cidx, CINTEGER from datatypetestm where FORMAT(CINTEGER,1) <> 0;
select cidx, CINTEGER from datatypetestm where FORMAT(CINTEGER,2) <> 0;
select cidx, CINTEGER from datatypetestm where FORMAT(CINTEGER,3) <> 0;
select cidx, CINTEGER from datatypetestm where FORMAT(CINTEGER,4) <> 0;
select cidx, CSMALLINT from datatypetestm where FORMAT(CSMALLINT,0) <> 0;
select cidx, CSMALLINT from datatypetestm where FORMAT(CSMALLINT,1) <> 0;
select cidx, CSMALLINT from datatypetestm where FORMAT(CSMALLINT,2) <> 0;
select cidx, CSMALLINT from datatypetestm where FORMAT(CSMALLINT,3) <> 0;
select cidx, CSMALLINT from datatypetestm where FORMAT(CSMALLINT,4) <> 0;
select cidx, CTINYINT from datatypetestm where FORMAT(CTINYINT,0) <> 0;
select cidx, CTINYINT from datatypetestm where FORMAT(CTINYINT,1) <> 0;
select cidx, CTINYINT from datatypetestm where FORMAT(CTINYINT,2) <> 0;
select cidx, CTINYINT from datatypetestm where FORMAT(CTINYINT,3) <> 0;
select cidx, CTINYINT from datatypetestm where FORMAT(CTINYINT,4) <> 0;
