select cidx, CBIGINT, IF(CBIGINT>0,1,-1) from datatypetestm;
select cidx, CBIGINT, IF(CBIGINT>0,1,-1) from datatypetestm;
select cidx, CBIGINT, IF(CBIGINT>0,1,-1) from datatypetestm;
select cidx, CDECIMAL1, IF(CDECIMAL1>0,1,-1) from datatypetestm;
select cidx, CDECIMAL1, IF(CDECIMAL1>0,1,-1) from datatypetestm;
select cidx, CDECIMAL1, IF(CDECIMAL1>0,1,-1) from datatypetestm;
select cidx, CDECIMAL4, IF(CDECIMAL4>0,1,-1) from datatypetestm;
select cidx, CDECIMAL4, IF(CDECIMAL4>0,1,-1) from datatypetestm;
select cidx, CDECIMAL4, IF(CDECIMAL4>0,1,-1) from datatypetestm;
select cidx, CDECIMAL4_2, IF(CDECIMAL4_2>0,1,-1) from datatypetestm;
select cidx, CDECIMAL4_2, IF(CDECIMAL4_2>0,1,-1) from datatypetestm;
select cidx, CDECIMAL4_2, IF(CDECIMAL4_2>0,1,-1) from datatypetestm;
select cidx, CDECIMAL5, IF(CDECIMAL5>0,1,-1) from datatypetestm;
select cidx, CDECIMAL5, IF(CDECIMAL5>0,1,-1) from datatypetestm;
select cidx, CDECIMAL5, IF(CDECIMAL5>0,1,-1) from datatypetestm;
select cidx, CDECIMAL9, IF(CDECIMAL9>0,1,-1) from datatypetestm;
select cidx, CDECIMAL9, IF(CDECIMAL9>0,1,-1) from datatypetestm;
select cidx, CDECIMAL9, IF(CDECIMAL9>0,1,-1) from datatypetestm;
select cidx, CDECIMAL9_2, IF(CDECIMAL9_2>0,1,-1) from datatypetestm;
select cidx, CDECIMAL9_2, IF(CDECIMAL9_2>0,1,-1) from datatypetestm;
select cidx, CDECIMAL9_2, IF(CDECIMAL9_2>0,1,-1) from datatypetestm;
select cidx, CDECIMAL10, IF(CDECIMAL10>0,1,-1) from datatypetestm;
select cidx, CDECIMAL10, IF(CDECIMAL10>0,1,-1) from datatypetestm;
select cidx, CDECIMAL10, IF(CDECIMAL10>0,1,-1) from datatypetestm;
select cidx, CDECIMAL18, IF(CDECIMAL18>0,1,-1) from datatypetestm;
select cidx, CDECIMAL18, IF(CDECIMAL18>0,1,-1) from datatypetestm;
select cidx, CDECIMAL18, IF(CDECIMAL18>0,1,-1) from datatypetestm;
select cidx, CDECIMAL18_2, IF(CDECIMAL18_2>0,1,-1) from datatypetestm;
select cidx, CDECIMAL18_2, IF(CDECIMAL18_2>0,1,-1) from datatypetestm;
select cidx, CDECIMAL18_2, IF(CDECIMAL18_2>0,1,-1) from datatypetestm;
select cidx, CINTEGER, IF(CINTEGER>0,1,-1) from datatypetestm;
select cidx, CINTEGER, IF(CINTEGER>0,1,-1) from datatypetestm;
select cidx, CINTEGER, IF(CINTEGER>0,1,-1) from datatypetestm;
select cidx, CSMALLINT, IF(CSMALLINT>0,1,-1) from datatypetestm;
select cidx, CSMALLINT, IF(CSMALLINT>0,1,-1) from datatypetestm;
select cidx, CSMALLINT, IF(CSMALLINT>0,1,-1) from datatypetestm;
select cidx, CTINYINT, IF(CTINYINT>0,1,-1) from datatypetestm;
select cidx, CTINYINT, IF(CTINYINT>0,1,-1) from datatypetestm;
select cidx, CTINYINT, IF(CTINYINT>0,1,-1) from datatypetestm;
select cidx, CBIGINT from datatypetestm where IF(CBIGINT>0,1,-1) <> CBIGINT;
select cidx, CBIGINT from datatypetestm where IF(CBIGINT>0,1,-1) <> CBIGINT;
select cidx, CBIGINT from datatypetestm where IF(CBIGINT>0,1,-1) <> CBIGINT;
select cidx, CDECIMAL1 from datatypetestm where IF(CDECIMAL1>0,1,-1) <> CDECIMAL1;
select cidx, CDECIMAL1 from datatypetestm where IF(CDECIMAL1>0,1,-1) <> CDECIMAL1;
select cidx, CDECIMAL1 from datatypetestm where IF(CDECIMAL1>0,1,-1) <> CDECIMAL1;
select cidx, CDECIMAL4 from datatypetestm where IF(CDECIMAL4>0,1,-1) <> CDECIMAL4;
select cidx, CDECIMAL4 from datatypetestm where IF(CDECIMAL4>0,1,-1) <> CDECIMAL4;
select cidx, CDECIMAL4 from datatypetestm where IF(CDECIMAL4>0,1,-1) <> CDECIMAL4;
select cidx, CDECIMAL4_2 from datatypetestm where IF(CDECIMAL4_2>0,1,-1) <> CDECIMAL4_2;
select cidx, CDECIMAL4_2 from datatypetestm where IF(CDECIMAL4_2>0,1,-1) <> CDECIMAL4_2;
select cidx, CDECIMAL4_2 from datatypetestm where IF(CDECIMAL4_2>0,1,-1) <> CDECIMAL4_2;
select cidx, CDECIMAL5 from datatypetestm where IF(CDECIMAL5>0,1,-1) <> CDECIMAL5;
select cidx, CDECIMAL5 from datatypetestm where IF(CDECIMAL5>0,1,-1) <> CDECIMAL5;
select cidx, CDECIMAL5 from datatypetestm where IF(CDECIMAL5>0,1,-1) <> CDECIMAL5;
select cidx, CDECIMAL9 from datatypetestm where IF(CDECIMAL9>0,1,-1) <> CDECIMAL9;
select cidx, CDECIMAL9 from datatypetestm where IF(CDECIMAL9>0,1,-1) <> CDECIMAL9;
select cidx, CDECIMAL9 from datatypetestm where IF(CDECIMAL9>0,1,-1) <> CDECIMAL9;
select cidx, CDECIMAL9_2 from datatypetestm where IF(CDECIMAL9_2>0,1,-1) <> CDECIMAL9_2;
select cidx, CDECIMAL9_2 from datatypetestm where IF(CDECIMAL9_2>0,1,-1) <> CDECIMAL9_2;
select cidx, CDECIMAL9_2 from datatypetestm where IF(CDECIMAL9_2>0,1,-1) <> CDECIMAL9_2;
select cidx, CDECIMAL10 from datatypetestm where IF(CDECIMAL10>0,1,-1) <> CDECIMAL10;
select cidx, CDECIMAL10 from datatypetestm where IF(CDECIMAL10>0,1,-1) <> CDECIMAL10;
select cidx, CDECIMAL10 from datatypetestm where IF(CDECIMAL10>0,1,-1) <> CDECIMAL10;
select cidx, CDECIMAL18 from datatypetestm where IF(CDECIMAL18>0,1,-1) <> CDECIMAL18;
select cidx, CDECIMAL18 from datatypetestm where IF(CDECIMAL18>0,1,-1) <> CDECIMAL18;
select cidx, CDECIMAL18 from datatypetestm where IF(CDECIMAL18>0,1,-1) <> CDECIMAL18;
select cidx, CDECIMAL18_2 from datatypetestm where IF(CDECIMAL18_2>0,1,-1) <> CDECIMAL18_2;
select cidx, CDECIMAL18_2 from datatypetestm where IF(CDECIMAL18_2>0,1,-1) <> CDECIMAL18_2;
select cidx, CDECIMAL18_2 from datatypetestm where IF(CDECIMAL18_2>0,1,-1) <> CDECIMAL18_2;
select cidx, CINTEGER from datatypetestm where IF(CINTEGER>0,1,-1) <> CINTEGER;
select cidx, CINTEGER from datatypetestm where IF(CINTEGER>0,1,-1) <> CINTEGER;
select cidx, CINTEGER from datatypetestm where IF(CINTEGER>0,1,-1) <> CINTEGER;
select cidx, CSMALLINT from datatypetestm where IF(CSMALLINT>0,1,-1) <> CSMALLINT;
select cidx, CSMALLINT from datatypetestm where IF(CSMALLINT>0,1,-1) <> CSMALLINT;
select cidx, CSMALLINT from datatypetestm where IF(CSMALLINT>0,1,-1) <> CSMALLINT;
select cidx, CTINYINT from datatypetestm where IF(CTINYINT>0,1,-1) <> CTINYINT;
select cidx, CTINYINT from datatypetestm where IF(CTINYINT>0,1,-1) <> CTINYINT;
select cidx, CTINYINT from datatypetestm where IF(CTINYINT>0,1,-1) <> CTINYINT;
