select cidx, CCHAR1, IFNULL(CCHAR1,'Yes') from datatypetestm;
select cidx, CCHAR2, IFNULL(CCHAR2,'Yes') from datatypetestm;
select cidx, CCHAR3, IFNULL(CCHAR3,'Yes') from datatypetestm;
select cidx, CCHAR4, IFNULL(CCHAR4,'Yes') from datatypetestm;
select cidx, CCHAR5, IFNULL(CCHAR5,'Yes') from datatypetestm;
select cidx, CCHAR6, IFNULL(CCHAR6,'Yes') from datatypetestm;
select cidx, CCHAR7, IFNULL(CCHAR7,'Yes') from datatypetestm;
select cidx, CCHAR8, IFNULL(CCHAR8,'Yes') from datatypetestm;
select cidx, CCHAR9, IFNULL(CCHAR9,'Yes') from datatypetestm;
select cidx, CCHAR255, IFNULL(CCHAR255,'Yes') from datatypetestm;
select cidx, CVCHAR1, IFNULL(CVCHAR1,'Yes') from datatypetestm;
select cidx, CVCHAR2, IFNULL(CVCHAR2,'Yes') from datatypetestm;
select cidx, CVCHAR3, IFNULL(CVCHAR3,'Yes') from datatypetestm;
select cidx, CVCHAR4, IFNULL(CVCHAR4,'Yes') from datatypetestm;
select cidx, CVCHAR5, IFNULL(CVCHAR5,'Yes') from datatypetestm;
select cidx, CVCHAR6, IFNULL(CVCHAR6,'Yes') from datatypetestm;
select cidx, CVCHAR7, IFNULL(CVCHAR7,'Yes') from datatypetestm;
select cidx, CVCHAR8, IFNULL(CVCHAR8,'Yes') from datatypetestm;
select cidx, CVCHAR255, IFNULL(CVCHAR255,'Yes') from datatypetestm;
select cidx, IFNULL('aloha','Yes') from datatypetestm;
select cidx, IFNULL('mahalo','Yes') from datatypetestm;
select cidx, IFNULL('','Yes') from datatypetestm;
select cidx, IFNULL(NULL,'Yes') from datatypetestm;
select cidx, CCHAR1 from datatypetestm where IFNULL(CCHAR1,'Yes') <> CCHAR1;
select cidx, CCHAR2 from datatypetestm where IFNULL(CCHAR2,'Yes') <> CCHAR2;
select cidx, CCHAR3 from datatypetestm where IFNULL(CCHAR3,'Yes') <> CCHAR3;
select cidx, CCHAR4 from datatypetestm where IFNULL(CCHAR4,'Yes') <> CCHAR4;
select cidx, CCHAR5 from datatypetestm where IFNULL(CCHAR5,'Yes') <> CCHAR5;
select cidx, CCHAR6 from datatypetestm where IFNULL(CCHAR6,'Yes') <> CCHAR6;
select cidx, CCHAR7 from datatypetestm where IFNULL(CCHAR7,'Yes') <> CCHAR7;
select cidx, CCHAR8 from datatypetestm where IFNULL(CCHAR8,'Yes') <> CCHAR8;
select cidx, CCHAR9 from datatypetestm where IFNULL(CCHAR9,'Yes') <> CCHAR9;
select cidx, CCHAR255 from datatypetestm where IFNULL(CCHAR255,'Yes') <> CCHAR255;
select cidx, CVCHAR1 from datatypetestm where IFNULL(CVCHAR1,'Yes') <> CVCHAR1;
select cidx, CVCHAR2 from datatypetestm where IFNULL(CVCHAR2,'Yes') <> CVCHAR2;
select cidx, CVCHAR3 from datatypetestm where IFNULL(CVCHAR3,'Yes') <> CVCHAR3;
select cidx, CVCHAR4 from datatypetestm where IFNULL(CVCHAR4,'Yes') <> CVCHAR4;
select cidx, CVCHAR5 from datatypetestm where IFNULL(CVCHAR5,'Yes') <> CVCHAR5;
select cidx, CVCHAR6 from datatypetestm where IFNULL(CVCHAR6,'Yes') <> CVCHAR6;
select cidx, CVCHAR7 from datatypetestm where IFNULL(CVCHAR7,'Yes') <> CVCHAR7;
select cidx, CVCHAR8 from datatypetestm where IFNULL(CVCHAR8,'Yes') <> CVCHAR8;
select cidx, CVCHAR255 from datatypetestm where IFNULL(CVCHAR255,'Yes') <> CVCHAR255;
