select cidx, CCHAR1, LEFT(CCHAR1,2) from datatypetestm;
select cidx, CCHAR1, LEFT(CCHAR1,5) from datatypetestm;
select cidx, CCHAR1, LEFT(CCHAR1,7) from datatypetestm;
select cidx, CCHAR1, LEFT(CCHAR1,8) from datatypetestm;
select cidx, CCHAR1, LEFT(CCHAR1,9) from datatypetestm;
select cidx, CCHAR1, LEFT(CCHAR1,25) from datatypetestm;
select cidx, CCHAR2, LEFT(CCHAR2,2) from datatypetestm;
select cidx, CCHAR2, LEFT(CCHAR2,5) from datatypetestm;
select cidx, CCHAR2, LEFT(CCHAR2,7) from datatypetestm;
select cidx, CCHAR2, LEFT(CCHAR2,8) from datatypetestm;
select cidx, CCHAR2, LEFT(CCHAR2,9) from datatypetestm;
select cidx, CCHAR2, LEFT(CCHAR2,25) from datatypetestm;
select cidx, CCHAR3, LEFT(CCHAR3,2) from datatypetestm;
select cidx, CCHAR3, LEFT(CCHAR3,5) from datatypetestm;
select cidx, CCHAR3, LEFT(CCHAR3,7) from datatypetestm;
select cidx, CCHAR3, LEFT(CCHAR3,8) from datatypetestm;
select cidx, CCHAR3, LEFT(CCHAR3,9) from datatypetestm;
select cidx, CCHAR3, LEFT(CCHAR3,25) from datatypetestm;
select cidx, CCHAR4, LEFT(CCHAR4,2) from datatypetestm;
select cidx, CCHAR4, LEFT(CCHAR4,5) from datatypetestm;
select cidx, CCHAR4, LEFT(CCHAR4,7) from datatypetestm;
select cidx, CCHAR4, LEFT(CCHAR4,8) from datatypetestm;
select cidx, CCHAR4, LEFT(CCHAR4,9) from datatypetestm;
select cidx, CCHAR4, LEFT(CCHAR4,25) from datatypetestm;
select cidx, CCHAR5, LEFT(CCHAR5,2) from datatypetestm;
select cidx, CCHAR5, LEFT(CCHAR5,5) from datatypetestm;
select cidx, CCHAR5, LEFT(CCHAR5,7) from datatypetestm;
select cidx, CCHAR5, LEFT(CCHAR5,8) from datatypetestm;
select cidx, CCHAR5, LEFT(CCHAR5,9) from datatypetestm;
select cidx, CCHAR5, LEFT(CCHAR5,25) from datatypetestm;
select cidx, CCHAR6, LEFT(CCHAR6,2) from datatypetestm;
select cidx, CCHAR6, LEFT(CCHAR6,5) from datatypetestm;
select cidx, CCHAR6, LEFT(CCHAR6,7) from datatypetestm;
select cidx, CCHAR6, LEFT(CCHAR6,8) from datatypetestm;
select cidx, CCHAR6, LEFT(CCHAR6,9) from datatypetestm;
select cidx, CCHAR6, LEFT(CCHAR6,25) from datatypetestm;
select cidx, CCHAR7, LEFT(CCHAR7,2) from datatypetestm;
select cidx, CCHAR7, LEFT(CCHAR7,5) from datatypetestm;
select cidx, CCHAR7, LEFT(CCHAR7,7) from datatypetestm;
select cidx, CCHAR7, LEFT(CCHAR7,8) from datatypetestm;
select cidx, CCHAR7, LEFT(CCHAR7,9) from datatypetestm;
select cidx, CCHAR7, LEFT(CCHAR7,25) from datatypetestm;
select cidx, CCHAR8, LEFT(CCHAR8,2) from datatypetestm;
select cidx, CCHAR8, LEFT(CCHAR8,5) from datatypetestm;
select cidx, CCHAR8, LEFT(CCHAR8,7) from datatypetestm;
select cidx, CCHAR8, LEFT(CCHAR8,8) from datatypetestm;
select cidx, CCHAR8, LEFT(CCHAR8,9) from datatypetestm;
select cidx, CCHAR8, LEFT(CCHAR8,25) from datatypetestm;
select cidx, CCHAR9, LEFT(CCHAR9,2) from datatypetestm;
select cidx, CCHAR9, LEFT(CCHAR9,5) from datatypetestm;
select cidx, CCHAR9, LEFT(CCHAR9,7) from datatypetestm;
select cidx, CCHAR9, LEFT(CCHAR9,8) from datatypetestm;
select cidx, CCHAR9, LEFT(CCHAR9,9) from datatypetestm;
select cidx, CCHAR9, LEFT(CCHAR9,25) from datatypetestm;
select cidx, CCHAR255, LEFT(CCHAR255,2) from datatypetestm;
select cidx, CCHAR255, LEFT(CCHAR255,5) from datatypetestm;
select cidx, CCHAR255, LEFT(CCHAR255,7) from datatypetestm;
select cidx, CCHAR255, LEFT(CCHAR255,8) from datatypetestm;
select cidx, CCHAR255, LEFT(CCHAR255,9) from datatypetestm;
select cidx, CCHAR255, LEFT(CCHAR255,25) from datatypetestm;
select cidx, CVCHAR1, LEFT(CVCHAR1,2) from datatypetestm;
select cidx, CVCHAR1, LEFT(CVCHAR1,5) from datatypetestm;
select cidx, CVCHAR1, LEFT(CVCHAR1,7) from datatypetestm;
select cidx, CVCHAR1, LEFT(CVCHAR1,8) from datatypetestm;
select cidx, CVCHAR1, LEFT(CVCHAR1,9) from datatypetestm;
select cidx, CVCHAR1, LEFT(CVCHAR1,25) from datatypetestm;
select cidx, CVCHAR2, LEFT(CVCHAR2,2) from datatypetestm;
select cidx, CVCHAR2, LEFT(CVCHAR2,5) from datatypetestm;
select cidx, CVCHAR2, LEFT(CVCHAR2,7) from datatypetestm;
select cidx, CVCHAR2, LEFT(CVCHAR2,8) from datatypetestm;
select cidx, CVCHAR2, LEFT(CVCHAR2,9) from datatypetestm;
select cidx, CVCHAR2, LEFT(CVCHAR2,25) from datatypetestm;
select cidx, CVCHAR3, LEFT(CVCHAR3,2) from datatypetestm;
select cidx, CVCHAR3, LEFT(CVCHAR3,5) from datatypetestm;
select cidx, CVCHAR3, LEFT(CVCHAR3,7) from datatypetestm;
select cidx, CVCHAR3, LEFT(CVCHAR3,8) from datatypetestm;
select cidx, CVCHAR3, LEFT(CVCHAR3,9) from datatypetestm;
select cidx, CVCHAR3, LEFT(CVCHAR3,25) from datatypetestm;
select cidx, CVCHAR4, LEFT(CVCHAR4,2) from datatypetestm;
select cidx, CVCHAR4, LEFT(CVCHAR4,5) from datatypetestm;
select cidx, CVCHAR4, LEFT(CVCHAR4,7) from datatypetestm;
select cidx, CVCHAR4, LEFT(CVCHAR4,8) from datatypetestm;
select cidx, CVCHAR4, LEFT(CVCHAR4,9) from datatypetestm;
select cidx, CVCHAR4, LEFT(CVCHAR4,25) from datatypetestm;
select cidx, CVCHAR5, LEFT(CVCHAR5,2) from datatypetestm;
select cidx, CVCHAR5, LEFT(CVCHAR5,5) from datatypetestm;
select cidx, CVCHAR5, LEFT(CVCHAR5,7) from datatypetestm;
select cidx, CVCHAR5, LEFT(CVCHAR5,8) from datatypetestm;
select cidx, CVCHAR5, LEFT(CVCHAR5,9) from datatypetestm;
select cidx, CVCHAR5, LEFT(CVCHAR5,25) from datatypetestm;
select cidx, CVCHAR6, LEFT(CVCHAR6,2) from datatypetestm;
select cidx, CVCHAR6, LEFT(CVCHAR6,5) from datatypetestm;
select cidx, CVCHAR6, LEFT(CVCHAR6,7) from datatypetestm;
select cidx, CVCHAR6, LEFT(CVCHAR6,8) from datatypetestm;
select cidx, CVCHAR6, LEFT(CVCHAR6,9) from datatypetestm;
select cidx, CVCHAR6, LEFT(CVCHAR6,25) from datatypetestm;
select cidx, CVCHAR7, LEFT(CVCHAR7,2) from datatypetestm;
select cidx, CVCHAR7, LEFT(CVCHAR7,5) from datatypetestm;
select cidx, CVCHAR7, LEFT(CVCHAR7,7) from datatypetestm;
select cidx, CVCHAR7, LEFT(CVCHAR7,8) from datatypetestm;
select cidx, CVCHAR7, LEFT(CVCHAR7,9) from datatypetestm;
select cidx, CVCHAR7, LEFT(CVCHAR7,25) from datatypetestm;
select cidx, CVCHAR8, LEFT(CVCHAR8,2) from datatypetestm;
select cidx, CVCHAR8, LEFT(CVCHAR8,5) from datatypetestm;
select cidx, CVCHAR8, LEFT(CVCHAR8,7) from datatypetestm;
select cidx, CVCHAR8, LEFT(CVCHAR8,8) from datatypetestm;
select cidx, CVCHAR8, LEFT(CVCHAR8,9) from datatypetestm;
select cidx, CVCHAR8, LEFT(CVCHAR8,25) from datatypetestm;
select cidx, CVCHAR255, LEFT(CVCHAR255,2) from datatypetestm;
select cidx, CVCHAR255, LEFT(CVCHAR255,5) from datatypetestm;
select cidx, CVCHAR255, LEFT(CVCHAR255,7) from datatypetestm;
select cidx, CVCHAR255, LEFT(CVCHAR255,8) from datatypetestm;
select cidx, CVCHAR255, LEFT(CVCHAR255,9) from datatypetestm;
select cidx, CVCHAR255, LEFT(CVCHAR255,25) from datatypetestm;
select cidx, CCHAR1 from datatypetestm where LEFT(CCHAR1,2) <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where LEFT(CCHAR1,5) <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where LEFT(CCHAR1,7) <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where LEFT(CCHAR1,8) <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where LEFT(CCHAR1,9) <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where LEFT(CCHAR1,25) <> CCHAR1;
select cidx, CCHAR2 from datatypetestm where LEFT(CCHAR2,2) <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where LEFT(CCHAR2,5) <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where LEFT(CCHAR2,7) <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where LEFT(CCHAR2,8) <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where LEFT(CCHAR2,9) <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where LEFT(CCHAR2,25) <> CCHAR2;
select cidx, CCHAR3 from datatypetestm where LEFT(CCHAR3,2) <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where LEFT(CCHAR3,5) <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where LEFT(CCHAR3,7) <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where LEFT(CCHAR3,8) <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where LEFT(CCHAR3,9) <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where LEFT(CCHAR3,25) <> CCHAR3;
select cidx, CCHAR4 from datatypetestm where LEFT(CCHAR4,2) <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where LEFT(CCHAR4,5) <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where LEFT(CCHAR4,7) <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where LEFT(CCHAR4,8) <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where LEFT(CCHAR4,9) <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where LEFT(CCHAR4,25) <> CCHAR4;
select cidx, CCHAR5 from datatypetestm where LEFT(CCHAR5,2) <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where LEFT(CCHAR5,5) <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where LEFT(CCHAR5,7) <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where LEFT(CCHAR5,8) <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where LEFT(CCHAR5,9) <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where LEFT(CCHAR5,25) <> CCHAR5;
select cidx, CCHAR6 from datatypetestm where LEFT(CCHAR6,2) <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where LEFT(CCHAR6,5) <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where LEFT(CCHAR6,7) <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where LEFT(CCHAR6,8) <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where LEFT(CCHAR6,9) <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where LEFT(CCHAR6,25) <> CCHAR6;
select cidx, CCHAR7 from datatypetestm where LEFT(CCHAR7,2) <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where LEFT(CCHAR7,5) <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where LEFT(CCHAR7,7) <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where LEFT(CCHAR7,8) <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where LEFT(CCHAR7,9) <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where LEFT(CCHAR7,25) <> CCHAR7;
select cidx, CCHAR8 from datatypetestm where LEFT(CCHAR8,2) <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where LEFT(CCHAR8,5) <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where LEFT(CCHAR8,7) <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where LEFT(CCHAR8,8) <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where LEFT(CCHAR8,9) <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where LEFT(CCHAR8,25) <> CCHAR8;
select cidx, CCHAR9 from datatypetestm where LEFT(CCHAR9,2) <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where LEFT(CCHAR9,5) <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where LEFT(CCHAR9,7) <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where LEFT(CCHAR9,8) <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where LEFT(CCHAR9,9) <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where LEFT(CCHAR9,25) <> CCHAR9;
select cidx, CCHAR255 from datatypetestm where LEFT(CCHAR255,2) <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where LEFT(CCHAR255,5) <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where LEFT(CCHAR255,7) <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where LEFT(CCHAR255,8) <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where LEFT(CCHAR255,9) <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where LEFT(CCHAR255,25) <> CCHAR255;
select cidx, CVCHAR1 from datatypetestm where LEFT(CVCHAR1,2) <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where LEFT(CVCHAR1,5) <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where LEFT(CVCHAR1,7) <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where LEFT(CVCHAR1,8) <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where LEFT(CVCHAR1,9) <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where LEFT(CVCHAR1,25) <> CVCHAR1;
select cidx, CVCHAR2 from datatypetestm where LEFT(CVCHAR2,2) <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where LEFT(CVCHAR2,5) <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where LEFT(CVCHAR2,7) <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where LEFT(CVCHAR2,8) <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where LEFT(CVCHAR2,9) <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where LEFT(CVCHAR2,25) <> CVCHAR2;
select cidx, CVCHAR3 from datatypetestm where LEFT(CVCHAR3,2) <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where LEFT(CVCHAR3,5) <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where LEFT(CVCHAR3,7) <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where LEFT(CVCHAR3,8) <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where LEFT(CVCHAR3,9) <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where LEFT(CVCHAR3,25) <> CVCHAR3;
select cidx, CVCHAR4 from datatypetestm where LEFT(CVCHAR4,2) <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where LEFT(CVCHAR4,5) <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where LEFT(CVCHAR4,7) <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where LEFT(CVCHAR4,8) <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where LEFT(CVCHAR4,9) <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where LEFT(CVCHAR4,25) <> CVCHAR4;
select cidx, CVCHAR5 from datatypetestm where LEFT(CVCHAR5,2) <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where LEFT(CVCHAR5,5) <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where LEFT(CVCHAR5,7) <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where LEFT(CVCHAR5,8) <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where LEFT(CVCHAR5,9) <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where LEFT(CVCHAR5,25) <> CVCHAR5;
select cidx, CVCHAR6 from datatypetestm where LEFT(CVCHAR6,2) <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where LEFT(CVCHAR6,5) <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where LEFT(CVCHAR6,7) <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where LEFT(CVCHAR6,8) <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where LEFT(CVCHAR6,9) <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where LEFT(CVCHAR6,25) <> CVCHAR6;
select cidx, CVCHAR7 from datatypetestm where LEFT(CVCHAR7,2) <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where LEFT(CVCHAR7,5) <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where LEFT(CVCHAR7,7) <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where LEFT(CVCHAR7,8) <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where LEFT(CVCHAR7,9) <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where LEFT(CVCHAR7,25) <> CVCHAR7;
select cidx, CVCHAR8 from datatypetestm where LEFT(CVCHAR8,2) <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where LEFT(CVCHAR8,5) <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where LEFT(CVCHAR8,7) <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where LEFT(CVCHAR8,8) <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where LEFT(CVCHAR8,9) <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where LEFT(CVCHAR8,25) <> CVCHAR8;
select cidx, CVCHAR255 from datatypetestm where LEFT(CVCHAR255,2) <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where LEFT(CVCHAR255,5) <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where LEFT(CVCHAR255,7) <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where LEFT(CVCHAR255,8) <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where LEFT(CVCHAR255,9) <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where LEFT(CVCHAR255,25) <> CVCHAR255;
