select cidx, CBIGINT, LOG(CBIGINT) from datatypetestm;
select cidx, CDECIMAL1, LOG(CDECIMAL1) from datatypetestm;
select cidx, CDECIMAL4, LOG(CDECIMAL4) from datatypetestm;
select cidx, CDECIMAL4_2, LOG(CDECIMAL4_2) from datatypetestm;
select cidx, CDECIMAL5, LOG(CDECIMAL5) from datatypetestm;
select cidx, CDECIMAL9, LOG(CDECIMAL9) from datatypetestm;
select cidx, CDECIMAL9_2, LOG(CDECIMAL9_2) from datatypetestm;
select cidx, CDECIMAL10, LOG(CDECIMAL10) from datatypetestm;
select cidx, CDECIMAL18, LOG(CDECIMAL18) from datatypetestm;
select cidx, CDECIMAL18_2, LOG(CDECIMAL18_2) from datatypetestm;
select cidx, CINTEGER, LOG(CINTEGER) from datatypetestm;
select cidx, CSMALLINT, LOG(CSMALLINT) from datatypetestm;
select cidx, CTINYINT, LOG(CTINYINT) from datatypetestm;
select cidx, LOG(-1) from datatypetestm;
select cidx, LOG(0) from datatypetestm;
select cidx, LOG(2) from datatypetestm;
select cidx, LOG(2,265536) from datatypetestm;
select cidx, LOG(10,100) from datatypetestm;
select cidx, LOG(1,100) from datatypetestm;
select cidx, CBIGINT from datatypetestm where LOG(CBIGINT) <> 0;
select cidx, CDECIMAL1 from datatypetestm where LOG(CDECIMAL1) <> 0;
select cidx, CDECIMAL4 from datatypetestm where LOG(CDECIMAL4) <> 0;
select cidx, CDECIMAL4_2 from datatypetestm where LOG(CDECIMAL4_2) <> 0;
select cidx, CDECIMAL5 from datatypetestm where LOG(CDECIMAL5) <> 0;
select cidx, CDECIMAL9 from datatypetestm where LOG(CDECIMAL9) <> 0;
select cidx, CDECIMAL9_2 from datatypetestm where LOG(CDECIMAL9_2) <> 0;
select cidx, CDECIMAL10 from datatypetestm where LOG(CDECIMAL10) <> 0;
select cidx, CDECIMAL18 from datatypetestm where LOG(CDECIMAL18) <> 0;
select cidx, CDECIMAL18_2 from datatypetestm where LOG(CDECIMAL18_2) <> 0;
select cidx, CINTEGER from datatypetestm where LOG(CINTEGER) <> 0;
select cidx, CSMALLINT from datatypetestm where LOG(CSMALLINT) <> 0;
select cidx, CTINYINT from datatypetestm where LOG(CTINYINT) <> 0;
