select cidx, CCHAR1, LOWER(CCHAR1) from datatypetestm;
select cidx, CCHAR2, LOWER(CCHAR2) from datatypetestm;
select cidx, CCHAR3, LOWER(CCHAR3) from datatypetestm;
select cidx, CCHAR4, LOWER(CCHAR4) from datatypetestm;
select cidx, CCHAR5, LOWER(CCHAR5) from datatypetestm;
select cidx, CCHAR6, LOWER(CCHAR6) from datatypetestm;
select cidx, CCHAR7, LOWER(CCHAR7) from datatypetestm;
select cidx, CCHAR8, LOWER(CCHAR8) from datatypetestm;
select cidx, CCHAR9, LOWER(CCHAR9) from datatypetestm;
select cidx, CCHAR255, LOWER(CCHAR255) from datatypetestm;
select cidx, CVCHAR1, LOWER(CVCHAR1) from datatypetestm;
select cidx, CVCHAR2, LOWER(CVCHAR2) from datatypetestm;
select cidx, CVCHAR3, LOWER(CVCHAR3) from datatypetestm;
select cidx, CVCHAR4, LOWER(CVCHAR4) from datatypetestm;
select cidx, CVCHAR5, LOWER(CVCHAR5) from datatypetestm;
select cidx, CVCHAR6, LOWER(CVCHAR6) from datatypetestm;
select cidx, CVCHAR7, LOWER(CVCHAR7) from datatypetestm;
select cidx, CVCHAR8, LOWER(CVCHAR8) from datatypetestm;
select cidx, CVCHAR255, LOWER(CVCHAR255) from datatypetestm;
select cidx, LOWER('ALOHA') from datatypetestm;
select cidx, LOWER('MAHALO') from datatypetestm;
select cidx, CCHAR1 from datatypetestm where LOWER(CCHAR1) <> CCHAR1;
select cidx, CCHAR2 from datatypetestm where LOWER(CCHAR2) <> CCHAR2;
select cidx, CCHAR3 from datatypetestm where LOWER(CCHAR3) <> CCHAR3;
select cidx, CCHAR4 from datatypetestm where LOWER(CCHAR4) <> CCHAR4;
select cidx, CCHAR5 from datatypetestm where LOWER(CCHAR5) <> CCHAR5;
select cidx, CCHAR6 from datatypetestm where LOWER(CCHAR6) <> CCHAR6;
select cidx, CCHAR7 from datatypetestm where LOWER(CCHAR7) <> CCHAR7;
select cidx, CCHAR8 from datatypetestm where LOWER(CCHAR8) <> CCHAR8;
select cidx, CCHAR9 from datatypetestm where LOWER(CCHAR9) <> CCHAR9;
select cidx, CCHAR255 from datatypetestm where LOWER(CCHAR255) <> CCHAR255;
select cidx, CVCHAR1 from datatypetestm where LOWER(CVCHAR1) <> CVCHAR1;
select cidx, CVCHAR2 from datatypetestm where LOWER(CVCHAR2) <> CVCHAR2;
select cidx, CVCHAR3 from datatypetestm where LOWER(CVCHAR3) <> CVCHAR3;
select cidx, CVCHAR4 from datatypetestm where LOWER(CVCHAR4) <> CVCHAR4;
select cidx, CVCHAR5 from datatypetestm where LOWER(CVCHAR5) <> CVCHAR5;
select cidx, CVCHAR6 from datatypetestm where LOWER(CVCHAR6) <> CVCHAR6;
select cidx, CVCHAR7 from datatypetestm where LOWER(CVCHAR7) <> CVCHAR7;
select cidx, CVCHAR8 from datatypetestm where LOWER(CVCHAR8) <> CVCHAR8;
select cidx, CVCHAR255 from datatypetestm where LOWER(CVCHAR255) <> CVCHAR255;
