select cidx, CBIGINT, MOD(CBIGINT,10) from datatypetestm;
select cidx, CBIGINT, MOD(CBIGINT,2) from datatypetestm;
select cidx, CBIGINT, MOD(CBIGINT,0) from datatypetestm;
select cidx, CBIGINT, MOD(CBIGINT,-2) from datatypetestm;
select cidx, CBIGINT, MOD(CBIGINT,-1) from datatypetestm;
select cidx, CDECIMAL1, MOD(CDECIMAL1,10) from datatypetestm;
select cidx, CDECIMAL1, MOD(CDECIMAL1,2) from datatypetestm;
select cidx, CDECIMAL1, MOD(CDECIMAL1,0) from datatypetestm;
select cidx, CDECIMAL1, MOD(CDECIMAL1,-2) from datatypetestm;
select cidx, CDECIMAL1, MOD(CDECIMAL1,-1) from datatypetestm;
select cidx, CDECIMAL4, MOD(CDECIMAL4,10) from datatypetestm;
select cidx, CDECIMAL4, MOD(CDECIMAL4,2) from datatypetestm;
select cidx, CDECIMAL4, MOD(CDECIMAL4,0) from datatypetestm;
select cidx, CDECIMAL4, MOD(CDECIMAL4,-2) from datatypetestm;
select cidx, CDECIMAL4, MOD(CDECIMAL4,-1) from datatypetestm;
select cidx, CDECIMAL4_2, MOD(CDECIMAL4_2,10) from datatypetestm;
select cidx, CDECIMAL4_2, MOD(CDECIMAL4_2,2) from datatypetestm;
select cidx, CDECIMAL4_2, MOD(CDECIMAL4_2,0) from datatypetestm;
select cidx, CDECIMAL4_2, MOD(CDECIMAL4_2,-2) from datatypetestm;
select cidx, CDECIMAL4_2, MOD(CDECIMAL4_2,-1) from datatypetestm;
select cidx, CDECIMAL5, MOD(CDECIMAL5,10) from datatypetestm;
select cidx, CDECIMAL5, MOD(CDECIMAL5,2) from datatypetestm;
select cidx, CDECIMAL5, MOD(CDECIMAL5,0) from datatypetestm;
select cidx, CDECIMAL5, MOD(CDECIMAL5,-2) from datatypetestm;
select cidx, CDECIMAL5, MOD(CDECIMAL5,-1) from datatypetestm;
select cidx, CDECIMAL9, MOD(CDECIMAL9,10) from datatypetestm;
select cidx, CDECIMAL9, MOD(CDECIMAL9,2) from datatypetestm;
select cidx, CDECIMAL9, MOD(CDECIMAL9,0) from datatypetestm;
select cidx, CDECIMAL9, MOD(CDECIMAL9,-2) from datatypetestm;
select cidx, CDECIMAL9, MOD(CDECIMAL9,-1) from datatypetestm;
select cidx, CDECIMAL9_2, MOD(CDECIMAL9_2,10) from datatypetestm;
select cidx, CDECIMAL9_2, MOD(CDECIMAL9_2,2) from datatypetestm;
select cidx, CDECIMAL9_2, MOD(CDECIMAL9_2,0) from datatypetestm;
select cidx, CDECIMAL9_2, MOD(CDECIMAL9_2,-2) from datatypetestm;
select cidx, CDECIMAL9_2, MOD(CDECIMAL9_2,-1) from datatypetestm;
select cidx, CDECIMAL10, MOD(CDECIMAL10,10) from datatypetestm;
select cidx, CDECIMAL10, MOD(CDECIMAL10,2) from datatypetestm;
select cidx, CDECIMAL10, MOD(CDECIMAL10,0) from datatypetestm;
select cidx, CDECIMAL10, MOD(CDECIMAL10,-2) from datatypetestm;
select cidx, CDECIMAL10, MOD(CDECIMAL10,-1) from datatypetestm;
select cidx, CDECIMAL18, MOD(CDECIMAL18,10) from datatypetestm;
select cidx, CDECIMAL18, MOD(CDECIMAL18,2) from datatypetestm;
select cidx, CDECIMAL18, MOD(CDECIMAL18,0) from datatypetestm;
select cidx, CDECIMAL18, MOD(CDECIMAL18,-2) from datatypetestm;
select cidx, CDECIMAL18, MOD(CDECIMAL18,-1) from datatypetestm;
select cidx, CDECIMAL18_2, MOD(CDECIMAL18_2,10) from datatypetestm;
select cidx, CDECIMAL18_2, MOD(CDECIMAL18_2,2) from datatypetestm;
select cidx, CDECIMAL18_2, MOD(CDECIMAL18_2,0) from datatypetestm;
select cidx, CDECIMAL18_2, MOD(CDECIMAL18_2,-2) from datatypetestm;
select cidx, CDECIMAL18_2, MOD(CDECIMAL18_2,-1) from datatypetestm;
select cidx, CINTEGER, MOD(CINTEGER,10) from datatypetestm;
select cidx, CINTEGER, MOD(CINTEGER,2) from datatypetestm;
select cidx, CINTEGER, MOD(CINTEGER,0) from datatypetestm;
select cidx, CINTEGER, MOD(CINTEGER,-2) from datatypetestm;
select cidx, CINTEGER, MOD(CINTEGER,-1) from datatypetestm;
select cidx, CSMALLINT, MOD(CSMALLINT,10) from datatypetestm;
select cidx, CSMALLINT, MOD(CSMALLINT,2) from datatypetestm;
select cidx, CSMALLINT, MOD(CSMALLINT,0) from datatypetestm;
select cidx, CSMALLINT, MOD(CSMALLINT,-2) from datatypetestm;
select cidx, CSMALLINT, MOD(CSMALLINT,-1) from datatypetestm;
select cidx, CTINYINT, MOD(CTINYINT,10) from datatypetestm;
select cidx, CTINYINT, MOD(CTINYINT,2) from datatypetestm;
select cidx, CTINYINT, MOD(CTINYINT,0) from datatypetestm;
select cidx, CTINYINT, MOD(CTINYINT,-2) from datatypetestm;
select cidx, CTINYINT, MOD(CTINYINT,-1) from datatypetestm;
select cidx, CBIGINT from datatypetestm where MOD(CBIGINT,10) <> CBIGINT;
select cidx, CBIGINT from datatypetestm where MOD(CBIGINT,2) <> CBIGINT;
select cidx, CBIGINT from datatypetestm where MOD(CBIGINT,0) <> CBIGINT;
select cidx, CBIGINT from datatypetestm where MOD(CBIGINT,-2) <> CBIGINT;
select cidx, CBIGINT from datatypetestm where MOD(CBIGINT,-1) <> CBIGINT;
select cidx, CDECIMAL1 from datatypetestm where MOD(CDECIMAL1,10) <> CDECIMAL1;
select cidx, CDECIMAL1 from datatypetestm where MOD(CDECIMAL1,2) <> CDECIMAL1;
select cidx, CDECIMAL1 from datatypetestm where MOD(CDECIMAL1,0) <> CDECIMAL1;
select cidx, CDECIMAL1 from datatypetestm where MOD(CDECIMAL1,-2) <> CDECIMAL1;
select cidx, CDECIMAL1 from datatypetestm where MOD(CDECIMAL1,-1) <> CDECIMAL1;
select cidx, CDECIMAL4 from datatypetestm where MOD(CDECIMAL4,10) <> CDECIMAL4;
select cidx, CDECIMAL4 from datatypetestm where MOD(CDECIMAL4,2) <> CDECIMAL4;
select cidx, CDECIMAL4 from datatypetestm where MOD(CDECIMAL4,0) <> CDECIMAL4;
select cidx, CDECIMAL4 from datatypetestm where MOD(CDECIMAL4,-2) <> CDECIMAL4;
select cidx, CDECIMAL4 from datatypetestm where MOD(CDECIMAL4,-1) <> CDECIMAL4;
select cidx, CDECIMAL4_2 from datatypetestm where MOD(CDECIMAL4_2,10) <> CDECIMAL4_2;
select cidx, CDECIMAL4_2 from datatypetestm where MOD(CDECIMAL4_2,2) <> CDECIMAL4_2;
select cidx, CDECIMAL4_2 from datatypetestm where MOD(CDECIMAL4_2,0) <> CDECIMAL4_2;
select cidx, CDECIMAL4_2 from datatypetestm where MOD(CDECIMAL4_2,-2) <> CDECIMAL4_2;
select cidx, CDECIMAL4_2 from datatypetestm where MOD(CDECIMAL4_2,-1) <> CDECIMAL4_2;
select cidx, CDECIMAL5 from datatypetestm where MOD(CDECIMAL5,10) <> CDECIMAL5;
select cidx, CDECIMAL5 from datatypetestm where MOD(CDECIMAL5,2) <> CDECIMAL5;
select cidx, CDECIMAL5 from datatypetestm where MOD(CDECIMAL5,0) <> CDECIMAL5;
select cidx, CDECIMAL5 from datatypetestm where MOD(CDECIMAL5,-2) <> CDECIMAL5;
select cidx, CDECIMAL5 from datatypetestm where MOD(CDECIMAL5,-1) <> CDECIMAL5;
select cidx, CDECIMAL9 from datatypetestm where MOD(CDECIMAL9,10) <> CDECIMAL9;
select cidx, CDECIMAL9 from datatypetestm where MOD(CDECIMAL9,2) <> CDECIMAL9;
select cidx, CDECIMAL9 from datatypetestm where MOD(CDECIMAL9,0) <> CDECIMAL9;
select cidx, CDECIMAL9 from datatypetestm where MOD(CDECIMAL9,-2) <> CDECIMAL9;
select cidx, CDECIMAL9 from datatypetestm where MOD(CDECIMAL9,-1) <> CDECIMAL9;
select cidx, CDECIMAL9_2 from datatypetestm where MOD(CDECIMAL9_2,10) <> CDECIMAL9_2;
select cidx, CDECIMAL9_2 from datatypetestm where MOD(CDECIMAL9_2,2) <> CDECIMAL9_2;
select cidx, CDECIMAL9_2 from datatypetestm where MOD(CDECIMAL9_2,0) <> CDECIMAL9_2;
select cidx, CDECIMAL9_2 from datatypetestm where MOD(CDECIMAL9_2,-2) <> CDECIMAL9_2;
select cidx, CDECIMAL9_2 from datatypetestm where MOD(CDECIMAL9_2,-1) <> CDECIMAL9_2;
select cidx, CDECIMAL10 from datatypetestm where MOD(CDECIMAL10,10) <> CDECIMAL10;
select cidx, CDECIMAL10 from datatypetestm where MOD(CDECIMAL10,2) <> CDECIMAL10;
select cidx, CDECIMAL10 from datatypetestm where MOD(CDECIMAL10,0) <> CDECIMAL10;
select cidx, CDECIMAL10 from datatypetestm where MOD(CDECIMAL10,-2) <> CDECIMAL10;
select cidx, CDECIMAL10 from datatypetestm where MOD(CDECIMAL10,-1) <> CDECIMAL10;
select cidx, CDECIMAL18 from datatypetestm where MOD(CDECIMAL18,10) <> CDECIMAL18;
select cidx, CDECIMAL18 from datatypetestm where MOD(CDECIMAL18,2) <> CDECIMAL18;
select cidx, CDECIMAL18 from datatypetestm where MOD(CDECIMAL18,0) <> CDECIMAL18;
select cidx, CDECIMAL18 from datatypetestm where MOD(CDECIMAL18,-2) <> CDECIMAL18;
select cidx, CDECIMAL18 from datatypetestm where MOD(CDECIMAL18,-1) <> CDECIMAL18;
select cidx, CDECIMAL18_2 from datatypetestm where MOD(CDECIMAL18_2,10) <> CDECIMAL18_2;
select cidx, CDECIMAL18_2 from datatypetestm where MOD(CDECIMAL18_2,2) <> CDECIMAL18_2;
select cidx, CDECIMAL18_2 from datatypetestm where MOD(CDECIMAL18_2,0) <> CDECIMAL18_2;
select cidx, CDECIMAL18_2 from datatypetestm where MOD(CDECIMAL18_2,-2) <> CDECIMAL18_2;
select cidx, CDECIMAL18_2 from datatypetestm where MOD(CDECIMAL18_2,-1) <> CDECIMAL18_2;
select cidx, CINTEGER from datatypetestm where MOD(CINTEGER,10) <> CINTEGER;
select cidx, CINTEGER from datatypetestm where MOD(CINTEGER,2) <> CINTEGER;
select cidx, CINTEGER from datatypetestm where MOD(CINTEGER,0) <> CINTEGER;
select cidx, CINTEGER from datatypetestm where MOD(CINTEGER,-2) <> CINTEGER;
select cidx, CINTEGER from datatypetestm where MOD(CINTEGER,-1) <> CINTEGER;
select cidx, CSMALLINT from datatypetestm where MOD(CSMALLINT,10) <> CSMALLINT;
select cidx, CSMALLINT from datatypetestm where MOD(CSMALLINT,2) <> CSMALLINT;
select cidx, CSMALLINT from datatypetestm where MOD(CSMALLINT,0) <> CSMALLINT;
select cidx, CSMALLINT from datatypetestm where MOD(CSMALLINT,-2) <> CSMALLINT;
select cidx, CSMALLINT from datatypetestm where MOD(CSMALLINT,-1) <> CSMALLINT;
select cidx, CTINYINT from datatypetestm where MOD(CTINYINT,10) <> CTINYINT;
select cidx, CTINYINT from datatypetestm where MOD(CTINYINT,2) <> CTINYINT;
select cidx, CTINYINT from datatypetestm where MOD(CTINYINT,0) <> CTINYINT;
select cidx, CTINYINT from datatypetestm where MOD(CTINYINT,-2) <> CTINYINT;
select cidx, CTINYINT from datatypetestm where MOD(CTINYINT,-1) <> CTINYINT;
