SELECT cidx,CBIGINT,NULLIF(CBIGINT,CBIGINT) from datatypetestm;
SELECT cidx,CDECIMAL1,NULLIF(CDECIMAL1,CDECIMAL1) from datatypetestm;
SELECT cidx,CDECIMAL4,NULLIF(CDECIMAL4,CDECIMAL4) from datatypetestm;
SELECT cidx,CDECIMAL4_2,NULLIF(CDECIMAL4_2,CDECIMAL4_2) from datatypetestm;
SELECT cidx,CINTEGER,NULLIF(CINTEGER,CINTEGER) from datatypetestm;
SELECT cidx,CSMALLINT,NULLIF(CSMALLINT,CSMALLINT) from datatypetestm;
SELECT cidx,CTINYINT,NULLIF(CTINYINT,CTINYINT) from datatypetestm;
SELECT cidx,CDOUBLE,NULLIF(CDOUBLE,CDOUBLE) from datatypetestm;
SELECT cidx,CFLOAT,NULLIF(CFLOAT,CFLOAT) from datatypetestm;
SELECT cidx,CCHAR2,NULLIF(CCHAR2,CCHAR2) from datatypetestm;
SELECT cidx,CBIGINT,NULLIF(CBIGINT,CBIGINT) from datatypetestm;
SELECT cidx,CDATE,NULLIF(CDATE,CDATE) from datatypetestm;
SELECT cidx,CDATETIME,NULLIF(CDATETIME,CDATETIME) from datatypetestm;
SELECT cidx,CBIGINT,NULLIF(CBIGINT,CDATETIME) from datatypetestm;
SELECT cidx,CDECIMAL1,NULLIF(CDECIMAL1,CDATE) from datatypetestm;
SELECT cidx,CDECIMAL4,NULLIF(CDECIMAL4,CBIGINT) from datatypetestm;
SELECT cidx,CDECIMAL4_2,NULLIF(CDECIMAL4_2,CCHAR2) from datatypetestm;
SELECT cidx,CINTEGER,NULLIF(CINTEGER,CFLOAT) from datatypetestm;
SELECT cidx,CSMALLINT,NULLIF(CSMALLINT,CDOUBLE) from datatypetestm;
SELECT cidx,CTINYINT,NULLIF(CTINYINT,CVCHAR2) from datatypetestm;
SELECT cidx,CDOUBLE,NULLIF(CDOUBLE,CFLOAT) from datatypetestm;
SELECT cidx,CFLOAT,NULLIF(CCHAR2,CDOUBLE) from datatypetestm;
SELECT cidx,CCHAR2,NULLIF(CCHAR2,CBIGINT) from datatypetestm;
SELECT cidx,CBIGINT,NULLIF(CBIGINT,CDECIMAL1) from datatypetestm;
SELECT cidx,CDATE,NULLIF(CDATE,CDECIMAL4_2) from datatypetestm;
SELECT cidx,CDATETIME,NULLIF(CDATETIME,CBIGINT) from datatypetestm;
SELECT cidx,CDATETIME,NULLIF(CBIGINT,1) from datatypetestm;
SELECT cidx,CDATETIME,NULLIF(CCHAR2,'aa') from datatypetestm;
select cidx, CCHAR8, CVCHAR8, NULLIF(CCHAR8,CVCHAR8) from datatypetestm order by cidx;
select cidx, CCHAR255, CVCHAR255, NULLIF(CCHAR255,CVCHAR255) from datatypetestm order by cidx;
select cidx, CCHAR9, CCHAR255, NULLIF(CCHAR9,CCHAR255) from datatypetestm order by cidx;
SELECT cidx,CDECIMAL1 from datatypetestm where NULLIF(CBIGINT,CBIGINT) is null;
SELECT cidx,CDECIMAL4 from datatypetestm where NULLIF(CDECIMAL4_2,CDECIMAL4_2) is not null;
SELECT cidx,CDECIMAL4_2 from datatypetestm where NULLIF(CTINYINT,CTINYINT) is null;
SELECT cidx,CINTEGER from datatypetestm where NULLIF(CTINYINT,CTINYINT) is not null;
SELECT cidx,CSMALLINT from datatypetestm where NULLIF(CTINYINT,CVCHAR2) = 10;
SELECT cidx,CTINYINT from datatypetestm where NULLIF(CTINYINT,CVCHAR2) <> 10;
