select cidx, CCHAR1, NULLIF(CCHAR1,CCHAR4) from datatypetestm order by cidx;
select cidx, CCHAR1, NULLIF(CCHAR1,CCHAR9) from datatypetestm order by cidx;
select cidx, CCHAR1, NULLIF(CCHAR1,CCHAR255) from datatypetestm order by cidx;
select cidx, CCHAR1, NULLIF(CCHAR1,CVCHAR4) from datatypetestm order by cidx;
select cidx, CCHAR1, NULLIF(CCHAR1,CVCHAR8) from datatypetestm order by cidx;
select cidx, CCHAR1, NULLIF(CCHAR1,CINTEGER) from datatypetestm order by cidx;
select cidx, CCHAR1, NULLIF(CCHAR1,CDOUBLE) from datatypetestm order by cidx;
select cidx, CCHAR1, NULLIF(CCHAR1,CDECIMAL9_2) from datatypetestm order by cidx;
select cidx, CCHAR1, NULLIF(CCHAR1,CDATE) from datatypetestm order by cidx;
select cidx, CCHAR1, NULLIF(CCHAR1,NULL) from datatypetestm order by cidx;
select cidx, CCHAR1, NULLIF(CCHAR1,'Hello world') from datatypetestm order by cidx;
select cidx, CCHAR2, NULLIF(CCHAR2,CCHAR4) from datatypetestm order by cidx;
select cidx, CCHAR2, NULLIF(CCHAR2,CCHAR9) from datatypetestm order by cidx;
select cidx, CCHAR2, NULLIF(CCHAR2,CCHAR255) from datatypetestm order by cidx;
select cidx, CCHAR2, NULLIF(CCHAR2,CVCHAR4) from datatypetestm order by cidx;
select cidx, CCHAR2, NULLIF(CCHAR2,CVCHAR8) from datatypetestm order by cidx;
select cidx, CCHAR2, NULLIF(CCHAR2,CINTEGER) from datatypetestm order by cidx;
select cidx, CCHAR2, NULLIF(CCHAR2,CDOUBLE) from datatypetestm order by cidx;
select cidx, CCHAR2, NULLIF(CCHAR2,CDECIMAL9_2) from datatypetestm order by cidx;
select cidx, CCHAR2, NULLIF(CCHAR2,CDATE) from datatypetestm order by cidx;
select cidx, CCHAR2, NULLIF(CCHAR2,NULL) from datatypetestm order by cidx;
select cidx, CCHAR2, NULLIF(CCHAR2,'Hello world') from datatypetestm order by cidx;
select cidx, CCHAR3, NULLIF(CCHAR3,CCHAR4) from datatypetestm order by cidx;
select cidx, CCHAR3, NULLIF(CCHAR3,CCHAR9) from datatypetestm order by cidx;
select cidx, CCHAR3, NULLIF(CCHAR3,CCHAR255) from datatypetestm order by cidx;
select cidx, CCHAR3, NULLIF(CCHAR3,CVCHAR4) from datatypetestm order by cidx;
select cidx, CCHAR3, NULLIF(CCHAR3,CVCHAR8) from datatypetestm order by cidx;
select cidx, CCHAR3, NULLIF(CCHAR3,CINTEGER) from datatypetestm order by cidx;
select cidx, CCHAR3, NULLIF(CCHAR3,CDOUBLE) from datatypetestm order by cidx;
select cidx, CCHAR3, NULLIF(CCHAR3,CDECIMAL9_2) from datatypetestm order by cidx;
select cidx, CCHAR3, NULLIF(CCHAR3,CDATE) from datatypetestm order by cidx;
select cidx, CCHAR3, NULLIF(CCHAR3,NULL) from datatypetestm order by cidx;
select cidx, CCHAR3, NULLIF(CCHAR3,'Hello world') from datatypetestm order by cidx;
select cidx, CCHAR4, NULLIF(CCHAR4,CCHAR4) from datatypetestm order by cidx;
select cidx, CCHAR4, NULLIF(CCHAR4,CCHAR9) from datatypetestm order by cidx;
select cidx, CCHAR4, NULLIF(CCHAR4,CCHAR255) from datatypetestm order by cidx;
select cidx, CCHAR4, NULLIF(CCHAR4,CVCHAR4) from datatypetestm order by cidx;
select cidx, CCHAR4, NULLIF(CCHAR4,CVCHAR8) from datatypetestm order by cidx;
select cidx, CCHAR4, NULLIF(CCHAR4,CINTEGER) from datatypetestm order by cidx;
select cidx, CCHAR4, NULLIF(CCHAR4,CDOUBLE) from datatypetestm order by cidx;
select cidx, CCHAR4, NULLIF(CCHAR4,CDECIMAL9_2) from datatypetestm order by cidx;
select cidx, CCHAR4, NULLIF(CCHAR4,CDATE) from datatypetestm order by cidx;
select cidx, CCHAR4, NULLIF(CCHAR4,NULL) from datatypetestm order by cidx;
select cidx, CCHAR4, NULLIF(CCHAR4,'Hello world') from datatypetestm order by cidx;
select cidx, CCHAR5, NULLIF(CCHAR5,CCHAR4) from datatypetestm order by cidx;
select cidx, CCHAR5, NULLIF(CCHAR5,CCHAR9) from datatypetestm order by cidx;
select cidx, CCHAR5, NULLIF(CCHAR5,CCHAR255) from datatypetestm order by cidx;
select cidx, CCHAR5, NULLIF(CCHAR5,CVCHAR4) from datatypetestm order by cidx;
select cidx, CCHAR5, NULLIF(CCHAR5,CVCHAR8) from datatypetestm order by cidx;
select cidx, CCHAR5, NULLIF(CCHAR5,CINTEGER) from datatypetestm order by cidx;
select cidx, CCHAR5, NULLIF(CCHAR5,CDOUBLE) from datatypetestm order by cidx;
select cidx, CCHAR5, NULLIF(CCHAR5,CDECIMAL9_2) from datatypetestm order by cidx;
select cidx, CCHAR5, NULLIF(CCHAR5,CDATE) from datatypetestm order by cidx;
select cidx, CCHAR5, NULLIF(CCHAR5,NULL) from datatypetestm order by cidx;
select cidx, CCHAR5, NULLIF(CCHAR5,'Hello world') from datatypetestm order by cidx;
select cidx, CCHAR6, NULLIF(CCHAR6,CCHAR4) from datatypetestm order by cidx;
select cidx, CCHAR6, NULLIF(CCHAR6,CCHAR9) from datatypetestm order by cidx;
select cidx, CCHAR6, NULLIF(CCHAR6,CCHAR255) from datatypetestm order by cidx;
select cidx, CCHAR6, NULLIF(CCHAR6,CVCHAR4) from datatypetestm order by cidx;
select cidx, CCHAR6, NULLIF(CCHAR6,CVCHAR8) from datatypetestm order by cidx;
select cidx, CCHAR6, NULLIF(CCHAR6,CINTEGER) from datatypetestm order by cidx;
select cidx, CCHAR6, NULLIF(CCHAR6,CDOUBLE) from datatypetestm order by cidx;
select cidx, CCHAR6, NULLIF(CCHAR6,CDECIMAL9_2) from datatypetestm order by cidx;
select cidx, CCHAR6, NULLIF(CCHAR6,CDATE) from datatypetestm order by cidx;
select cidx, CCHAR6, NULLIF(CCHAR6,NULL) from datatypetestm order by cidx;
select cidx, CCHAR6, NULLIF(CCHAR6,'Hello world') from datatypetestm order by cidx;
select cidx, CCHAR7, NULLIF(CCHAR7,CCHAR4) from datatypetestm order by cidx;
select cidx, CCHAR7, NULLIF(CCHAR7,CCHAR9) from datatypetestm order by cidx;
select cidx, CCHAR7, NULLIF(CCHAR7,CCHAR255) from datatypetestm order by cidx;
select cidx, CCHAR7, NULLIF(CCHAR7,CVCHAR4) from datatypetestm order by cidx;
select cidx, CCHAR7, NULLIF(CCHAR7,CVCHAR8) from datatypetestm order by cidx;
select cidx, CCHAR7, NULLIF(CCHAR7,CINTEGER) from datatypetestm order by cidx;
select cidx, CCHAR7, NULLIF(CCHAR7,CDOUBLE) from datatypetestm order by cidx;
select cidx, CCHAR7, NULLIF(CCHAR7,CDECIMAL9_2) from datatypetestm order by cidx;
select cidx, CCHAR7, NULLIF(CCHAR7,CDATE) from datatypetestm order by cidx;
select cidx, CCHAR7, NULLIF(CCHAR7,NULL) from datatypetestm order by cidx;
select cidx, CCHAR7, NULLIF(CCHAR7,'Hello world') from datatypetestm order by cidx;
select cidx, CCHAR8, NULLIF(CCHAR8,CCHAR4) from datatypetestm order by cidx;
select cidx, CCHAR8, NULLIF(CCHAR8,CCHAR9) from datatypetestm order by cidx;
select cidx, CCHAR8, NULLIF(CCHAR8,CCHAR255) from datatypetestm order by cidx;
select cidx, CCHAR8, NULLIF(CCHAR8,CVCHAR4) from datatypetestm order by cidx;
select cidx, CCHAR8, NULLIF(CCHAR8,CVCHAR8) from datatypetestm order by cidx;
select cidx, CCHAR8, NULLIF(CCHAR8,CINTEGER) from datatypetestm order by cidx;
select cidx, CCHAR8, NULLIF(CCHAR8,CDOUBLE) from datatypetestm order by cidx;
select cidx, CCHAR8, NULLIF(CCHAR8,CDECIMAL9_2) from datatypetestm order by cidx;
select cidx, CCHAR8, NULLIF(CCHAR8,CDATE) from datatypetestm order by cidx;
select cidx, CCHAR8, NULLIF(CCHAR8,NULL) from datatypetestm order by cidx;
select cidx, CCHAR8, NULLIF(CCHAR8,'Hello world') from datatypetestm order by cidx;
select cidx, CCHAR9, NULLIF(CCHAR9,CCHAR4) from datatypetestm order by cidx;
select cidx, CCHAR9, NULLIF(CCHAR9,CCHAR9) from datatypetestm order by cidx;
select cidx, CCHAR9, NULLIF(CCHAR9,CCHAR255) from datatypetestm order by cidx;
select cidx, CCHAR9, NULLIF(CCHAR9,CVCHAR4) from datatypetestm order by cidx;
select cidx, CCHAR9, NULLIF(CCHAR9,CVCHAR8) from datatypetestm order by cidx;
select cidx, CCHAR9, NULLIF(CCHAR9,CINTEGER) from datatypetestm order by cidx;
select cidx, CCHAR9, NULLIF(CCHAR9,CDOUBLE) from datatypetestm order by cidx;
select cidx, CCHAR9, NULLIF(CCHAR9,CDECIMAL9_2) from datatypetestm order by cidx;
select cidx, CCHAR9, NULLIF(CCHAR9,CDATE) from datatypetestm order by cidx;
select cidx, CCHAR9, NULLIF(CCHAR9,NULL) from datatypetestm order by cidx;
select cidx, CCHAR9, NULLIF(CCHAR9,'Hello world') from datatypetestm order by cidx;
select cidx, CCHAR255, NULLIF(CCHAR255,CCHAR4) from datatypetestm order by cidx;
select cidx, CCHAR255, NULLIF(CCHAR255,CCHAR9) from datatypetestm order by cidx;
select cidx, CCHAR255, NULLIF(CCHAR255,CCHAR255) from datatypetestm order by cidx;
select cidx, CCHAR255, NULLIF(CCHAR255,CVCHAR4) from datatypetestm order by cidx;
select cidx, CCHAR255, NULLIF(CCHAR255,CVCHAR8) from datatypetestm order by cidx;
select cidx, CCHAR255, NULLIF(CCHAR255,CINTEGER) from datatypetestm order by cidx;
select cidx, CCHAR255, NULLIF(CCHAR255,CDOUBLE) from datatypetestm order by cidx;
select cidx, CCHAR255, NULLIF(CCHAR255,CDECIMAL9_2) from datatypetestm order by cidx;
select cidx, CCHAR255, NULLIF(CCHAR255,CDATE) from datatypetestm order by cidx;
select cidx, CCHAR255, NULLIF(CCHAR255,NULL) from datatypetestm order by cidx;
select cidx, CCHAR255, NULLIF(CCHAR255,'Hello world') from datatypetestm order by cidx;
select cidx, CVCHAR1, NULLIF(CVCHAR1,CCHAR4) from datatypetestm order by cidx;
select cidx, CVCHAR1, NULLIF(CVCHAR1,CCHAR9) from datatypetestm order by cidx;
select cidx, CVCHAR1, NULLIF(CVCHAR1,CCHAR255) from datatypetestm order by cidx;
select cidx, CVCHAR1, NULLIF(CVCHAR1,CVCHAR4) from datatypetestm order by cidx;
select cidx, CVCHAR1, NULLIF(CVCHAR1,CVCHAR8) from datatypetestm order by cidx;
select cidx, CVCHAR1, NULLIF(CVCHAR1,CINTEGER) from datatypetestm order by cidx;
select cidx, CVCHAR1, NULLIF(CVCHAR1,CDOUBLE) from datatypetestm order by cidx;
select cidx, CVCHAR1, NULLIF(CVCHAR1,CDECIMAL9_2) from datatypetestm order by cidx;
select cidx, CVCHAR1, NULLIF(CVCHAR1,CDATE) from datatypetestm order by cidx;
select cidx, CVCHAR1, NULLIF(CVCHAR1,NULL) from datatypetestm order by cidx;
select cidx, CVCHAR1, NULLIF(CVCHAR1,'Hello world') from datatypetestm order by cidx;
select cidx, CVCHAR2, NULLIF(CVCHAR2,CCHAR4) from datatypetestm order by cidx;
select cidx, CVCHAR2, NULLIF(CVCHAR2,CCHAR9) from datatypetestm order by cidx;
select cidx, CVCHAR2, NULLIF(CVCHAR2,CCHAR255) from datatypetestm order by cidx;
select cidx, CVCHAR2, NULLIF(CVCHAR2,CVCHAR4) from datatypetestm order by cidx;
select cidx, CVCHAR2, NULLIF(CVCHAR2,CVCHAR8) from datatypetestm order by cidx;
select cidx, CVCHAR2, NULLIF(CVCHAR2,CINTEGER) from datatypetestm order by cidx;
select cidx, CVCHAR2, NULLIF(CVCHAR2,CDOUBLE) from datatypetestm order by cidx;
select cidx, CVCHAR2, NULLIF(CVCHAR2,CDECIMAL9_2) from datatypetestm order by cidx;
select cidx, CVCHAR2, NULLIF(CVCHAR2,CDATE) from datatypetestm order by cidx;
select cidx, CVCHAR2, NULLIF(CVCHAR2,NULL) from datatypetestm order by cidx;
select cidx, CVCHAR2, NULLIF(CVCHAR2,'Hello world') from datatypetestm order by cidx;
select cidx, CVCHAR3, NULLIF(CVCHAR3,CCHAR4) from datatypetestm order by cidx;
select cidx, CVCHAR3, NULLIF(CVCHAR3,CCHAR9) from datatypetestm order by cidx;
select cidx, CVCHAR3, NULLIF(CVCHAR3,CCHAR255) from datatypetestm order by cidx;
select cidx, CVCHAR3, NULLIF(CVCHAR3,CVCHAR4) from datatypetestm order by cidx;
select cidx, CVCHAR3, NULLIF(CVCHAR3,CVCHAR8) from datatypetestm order by cidx;
select cidx, CVCHAR3, NULLIF(CVCHAR3,CINTEGER) from datatypetestm order by cidx;
select cidx, CVCHAR3, NULLIF(CVCHAR3,CDOUBLE) from datatypetestm order by cidx;
select cidx, CVCHAR3, NULLIF(CVCHAR3,CDECIMAL9_2) from datatypetestm order by cidx;
select cidx, CVCHAR3, NULLIF(CVCHAR3,CDATE) from datatypetestm order by cidx;
select cidx, CVCHAR3, NULLIF(CVCHAR3,NULL) from datatypetestm order by cidx;
select cidx, CVCHAR3, NULLIF(CVCHAR3,'Hello world') from datatypetestm order by cidx;
select cidx, CVCHAR4, NULLIF(CVCHAR4,CCHAR4) from datatypetestm order by cidx;
select cidx, CVCHAR4, NULLIF(CVCHAR4,CCHAR9) from datatypetestm order by cidx;
select cidx, CVCHAR4, NULLIF(CVCHAR4,CCHAR255) from datatypetestm order by cidx;
select cidx, CVCHAR4, NULLIF(CVCHAR4,CVCHAR4) from datatypetestm order by cidx;
select cidx, CVCHAR4, NULLIF(CVCHAR4,CVCHAR8) from datatypetestm order by cidx;
select cidx, CVCHAR4, NULLIF(CVCHAR4,CINTEGER) from datatypetestm order by cidx;
select cidx, CVCHAR4, NULLIF(CVCHAR4,CDOUBLE) from datatypetestm order by cidx;
select cidx, CVCHAR4, NULLIF(CVCHAR4,CDECIMAL9_2) from datatypetestm order by cidx;
select cidx, CVCHAR4, NULLIF(CVCHAR4,CDATE) from datatypetestm order by cidx;
select cidx, CVCHAR4, NULLIF(CVCHAR4,NULL) from datatypetestm order by cidx;
select cidx, CVCHAR4, NULLIF(CVCHAR4,'Hello world') from datatypetestm order by cidx;
select cidx, CVCHAR5, NULLIF(CVCHAR5,CCHAR4) from datatypetestm order by cidx;
select cidx, CVCHAR5, NULLIF(CVCHAR5,CCHAR9) from datatypetestm order by cidx;
select cidx, CVCHAR5, NULLIF(CVCHAR5,CCHAR255) from datatypetestm order by cidx;
select cidx, CVCHAR5, NULLIF(CVCHAR5,CVCHAR4) from datatypetestm order by cidx;
select cidx, CVCHAR5, NULLIF(CVCHAR5,CVCHAR8) from datatypetestm order by cidx;
select cidx, CVCHAR5, NULLIF(CVCHAR5,CINTEGER) from datatypetestm order by cidx;
select cidx, CVCHAR5, NULLIF(CVCHAR5,CDOUBLE) from datatypetestm order by cidx;
select cidx, CVCHAR5, NULLIF(CVCHAR5,CDECIMAL9_2) from datatypetestm order by cidx;
select cidx, CVCHAR5, NULLIF(CVCHAR5,CDATE) from datatypetestm order by cidx;
select cidx, CVCHAR5, NULLIF(CVCHAR5,NULL) from datatypetestm order by cidx;
select cidx, CVCHAR5, NULLIF(CVCHAR5,'Hello world') from datatypetestm order by cidx;
select cidx, CVCHAR6, NULLIF(CVCHAR6,CCHAR4) from datatypetestm order by cidx;
select cidx, CVCHAR6, NULLIF(CVCHAR6,CCHAR9) from datatypetestm order by cidx;
select cidx, CVCHAR6, NULLIF(CVCHAR6,CCHAR255) from datatypetestm order by cidx;
select cidx, CVCHAR6, NULLIF(CVCHAR6,CVCHAR4) from datatypetestm order by cidx;
select cidx, CVCHAR6, NULLIF(CVCHAR6,CVCHAR8) from datatypetestm order by cidx;
select cidx, CVCHAR6, NULLIF(CVCHAR6,CINTEGER) from datatypetestm order by cidx;
select cidx, CVCHAR6, NULLIF(CVCHAR6,CDOUBLE) from datatypetestm order by cidx;
select cidx, CVCHAR6, NULLIF(CVCHAR6,CDECIMAL9_2) from datatypetestm order by cidx;
select cidx, CVCHAR6, NULLIF(CVCHAR6,CDATE) from datatypetestm order by cidx;
select cidx, CVCHAR6, NULLIF(CVCHAR6,NULL) from datatypetestm order by cidx;
select cidx, CVCHAR6, NULLIF(CVCHAR6,'Hello world') from datatypetestm order by cidx;
select cidx, CVCHAR7, NULLIF(CVCHAR7,CCHAR4) from datatypetestm order by cidx;
select cidx, CVCHAR7, NULLIF(CVCHAR7,CCHAR9) from datatypetestm order by cidx;
select cidx, CVCHAR7, NULLIF(CVCHAR7,CCHAR255) from datatypetestm order by cidx;
select cidx, CVCHAR7, NULLIF(CVCHAR7,CVCHAR4) from datatypetestm order by cidx;
select cidx, CVCHAR7, NULLIF(CVCHAR7,CVCHAR8) from datatypetestm order by cidx;
select cidx, CVCHAR7, NULLIF(CVCHAR7,CINTEGER) from datatypetestm order by cidx;
select cidx, CVCHAR7, NULLIF(CVCHAR7,CDOUBLE) from datatypetestm order by cidx;
select cidx, CVCHAR7, NULLIF(CVCHAR7,CDECIMAL9_2) from datatypetestm order by cidx;
select cidx, CVCHAR7, NULLIF(CVCHAR7,CDATE) from datatypetestm order by cidx;
select cidx, CVCHAR7, NULLIF(CVCHAR7,NULL) from datatypetestm order by cidx;
select cidx, CVCHAR7, NULLIF(CVCHAR7,'Hello world') from datatypetestm order by cidx;
select cidx, CVCHAR8, NULLIF(CVCHAR8,CCHAR4) from datatypetestm order by cidx;
select cidx, CVCHAR8, NULLIF(CVCHAR8,CCHAR9) from datatypetestm order by cidx;
select cidx, CVCHAR8, NULLIF(CVCHAR8,CCHAR255) from datatypetestm order by cidx;
select cidx, CVCHAR8, NULLIF(CVCHAR8,CVCHAR4) from datatypetestm order by cidx;
select cidx, CVCHAR8, NULLIF(CVCHAR8,CVCHAR8) from datatypetestm order by cidx;
select cidx, CVCHAR8, NULLIF(CVCHAR8,CINTEGER) from datatypetestm order by cidx;
select cidx, CVCHAR8, NULLIF(CVCHAR8,CDOUBLE) from datatypetestm order by cidx;
select cidx, CVCHAR8, NULLIF(CVCHAR8,CDECIMAL9_2) from datatypetestm order by cidx;
select cidx, CVCHAR8, NULLIF(CVCHAR8,CDATE) from datatypetestm order by cidx;
select cidx, CVCHAR8, NULLIF(CVCHAR8,NULL) from datatypetestm order by cidx;
select cidx, CVCHAR8, NULLIF(CVCHAR8,'Hello world') from datatypetestm order by cidx;
select cidx, CVCHAR255, NULLIF(CVCHAR255,CCHAR4) from datatypetestm order by cidx;
select cidx, CVCHAR255, NULLIF(CVCHAR255,CCHAR9) from datatypetestm order by cidx;
select cidx, CVCHAR255, NULLIF(CVCHAR255,CCHAR255) from datatypetestm order by cidx;
select cidx, CVCHAR255, NULLIF(CVCHAR255,CVCHAR4) from datatypetestm order by cidx;
select cidx, CVCHAR255, NULLIF(CVCHAR255,CVCHAR8) from datatypetestm order by cidx;
select cidx, CVCHAR255, NULLIF(CVCHAR255,CINTEGER) from datatypetestm order by cidx;
select cidx, CVCHAR255, NULLIF(CVCHAR255,CDOUBLE) from datatypetestm order by cidx;
select cidx, CVCHAR255, NULLIF(CVCHAR255,CDECIMAL9_2) from datatypetestm order by cidx;
select cidx, CVCHAR255, NULLIF(CVCHAR255,CDATE) from datatypetestm order by cidx;
select cidx, CVCHAR255, NULLIF(CVCHAR255,NULL) from datatypetestm order by cidx;
select cidx, CVCHAR255, NULLIF(CVCHAR255,'Hello world') from datatypetestm order by cidx;
select cidx, CCHAR1 from datatypetestm where NULLIF(CCHAR1,CCHAR4) <> CCHAR1 order by cidx;
select cidx, CCHAR1 from datatypetestm where NULLIF(CCHAR1,CCHAR9) <> CCHAR1 order by cidx;
select cidx, CCHAR1 from datatypetestm where NULLIF(CCHAR1,CCHAR255) <> CCHAR1 order by cidx;
select cidx, CCHAR1 from datatypetestm where NULLIF(CCHAR1,CVCHAR4) <> CCHAR1 order by cidx;
select cidx, CCHAR1 from datatypetestm where NULLIF(CCHAR1,CVCHAR8) <> CCHAR1 order by cidx;
select cidx, CCHAR1 from datatypetestm where NULLIF(CCHAR1,CINTEGER) <> CCHAR1 order by cidx;
select cidx, CCHAR1 from datatypetestm where NULLIF(CCHAR1,CDOUBLE) <> CCHAR1 order by cidx;
select cidx, CCHAR1 from datatypetestm where NULLIF(CCHAR1,CDECIMAL9_2) <> CCHAR1 order by cidx;
select cidx, CCHAR1 from datatypetestm where NULLIF(CCHAR1,CDATE) <> CCHAR1 order by cidx;
select cidx, CCHAR1 from datatypetestm where NULLIF(CCHAR1,NULL) <> CCHAR1 order by cidx;
select cidx, CCHAR1 from datatypetestm where NULLIF(CCHAR1,'Hello world') <> CCHAR1 order by cidx;
select cidx, CCHAR2 from datatypetestm where NULLIF(CCHAR2,CCHAR4) <> CCHAR2 order by cidx;
select cidx, CCHAR2 from datatypetestm where NULLIF(CCHAR2,CCHAR9) <> CCHAR2 order by cidx;
select cidx, CCHAR2 from datatypetestm where NULLIF(CCHAR2,CCHAR255) <> CCHAR2 order by cidx;
select cidx, CCHAR2 from datatypetestm where NULLIF(CCHAR2,CVCHAR4) <> CCHAR2 order by cidx;
select cidx, CCHAR2 from datatypetestm where NULLIF(CCHAR2,CVCHAR8) <> CCHAR2 order by cidx;
select cidx, CCHAR2 from datatypetestm where NULLIF(CCHAR2,CINTEGER) <> CCHAR2 order by cidx;
select cidx, CCHAR2 from datatypetestm where NULLIF(CCHAR2,CDOUBLE) <> CCHAR2 order by cidx;
select cidx, CCHAR2 from datatypetestm where NULLIF(CCHAR2,CDECIMAL9_2) <> CCHAR2 order by cidx;
select cidx, CCHAR2 from datatypetestm where NULLIF(CCHAR2,CDATE) <> CCHAR2 order by cidx;
select cidx, CCHAR2 from datatypetestm where NULLIF(CCHAR2,NULL) <> CCHAR2 order by cidx;
select cidx, CCHAR2 from datatypetestm where NULLIF(CCHAR2,'Hello world') <> CCHAR2 order by cidx;
select cidx, CCHAR3 from datatypetestm where NULLIF(CCHAR3,CCHAR4) <> CCHAR3 order by cidx;
select cidx, CCHAR3 from datatypetestm where NULLIF(CCHAR3,CCHAR9) <> CCHAR3 order by cidx;
select cidx, CCHAR3 from datatypetestm where NULLIF(CCHAR3,CCHAR255) <> CCHAR3 order by cidx;
select cidx, CCHAR3 from datatypetestm where NULLIF(CCHAR3,CVCHAR4) <> CCHAR3 order by cidx;
select cidx, CCHAR3 from datatypetestm where NULLIF(CCHAR3,CVCHAR8) <> CCHAR3 order by cidx;
select cidx, CCHAR3 from datatypetestm where NULLIF(CCHAR3,CINTEGER) <> CCHAR3 order by cidx;
select cidx, CCHAR3 from datatypetestm where NULLIF(CCHAR3,CDOUBLE) <> CCHAR3 order by cidx;
select cidx, CCHAR3 from datatypetestm where NULLIF(CCHAR3,CDECIMAL9_2) <> CCHAR3 order by cidx;
select cidx, CCHAR3 from datatypetestm where NULLIF(CCHAR3,CDATE) <> CCHAR3 order by cidx;
select cidx, CCHAR3 from datatypetestm where NULLIF(CCHAR3,NULL) <> CCHAR3 order by cidx;
select cidx, CCHAR3 from datatypetestm where NULLIF(CCHAR3,'Hello world') <> CCHAR3 order by cidx;
select cidx, CCHAR4 from datatypetestm where NULLIF(CCHAR4,CCHAR4) <> CCHAR4 order by cidx;
select cidx, CCHAR4 from datatypetestm where NULLIF(CCHAR4,CCHAR9) <> CCHAR4 order by cidx;
select cidx, CCHAR4 from datatypetestm where NULLIF(CCHAR4,CCHAR255) <> CCHAR4 order by cidx;
select cidx, CCHAR4 from datatypetestm where NULLIF(CCHAR4,CVCHAR4) <> CCHAR4 order by cidx;
select cidx, CCHAR4 from datatypetestm where NULLIF(CCHAR4,CVCHAR8) <> CCHAR4 order by cidx;
select cidx, CCHAR4 from datatypetestm where NULLIF(CCHAR4,CINTEGER) <> CCHAR4 order by cidx;
select cidx, CCHAR4 from datatypetestm where NULLIF(CCHAR4,CDOUBLE) <> CCHAR4 order by cidx;
select cidx, CCHAR4 from datatypetestm where NULLIF(CCHAR4,CDECIMAL9_2) <> CCHAR4 order by cidx;
select cidx, CCHAR4 from datatypetestm where NULLIF(CCHAR4,CDATE) <> CCHAR4 order by cidx;
select cidx, CCHAR4 from datatypetestm where NULLIF(CCHAR4,NULL) <> CCHAR4 order by cidx;
select cidx, CCHAR4 from datatypetestm where NULLIF(CCHAR4,'Hello world') <> CCHAR4 order by cidx;
select cidx, CCHAR5 from datatypetestm where NULLIF(CCHAR5,CCHAR4) <> CCHAR5 order by cidx;
select cidx, CCHAR5 from datatypetestm where NULLIF(CCHAR5,CCHAR9) <> CCHAR5 order by cidx;
select cidx, CCHAR5 from datatypetestm where NULLIF(CCHAR5,CCHAR255) <> CCHAR5 order by cidx;
select cidx, CCHAR5 from datatypetestm where NULLIF(CCHAR5,CVCHAR4) <> CCHAR5 order by cidx;
select cidx, CCHAR5 from datatypetestm where NULLIF(CCHAR5,CVCHAR8) <> CCHAR5 order by cidx;
select cidx, CCHAR5 from datatypetestm where NULLIF(CCHAR5,CINTEGER) <> CCHAR5 order by cidx;
select cidx, CCHAR5 from datatypetestm where NULLIF(CCHAR5,CDOUBLE) <> CCHAR5 order by cidx;
select cidx, CCHAR5 from datatypetestm where NULLIF(CCHAR5,CDECIMAL9_2) <> CCHAR5 order by cidx;
select cidx, CCHAR5 from datatypetestm where NULLIF(CCHAR5,CDATE) <> CCHAR5 order by cidx;
select cidx, CCHAR5 from datatypetestm where NULLIF(CCHAR5,NULL) <> CCHAR5 order by cidx;
select cidx, CCHAR5 from datatypetestm where NULLIF(CCHAR5,'Hello world') <> CCHAR5 order by cidx;
select cidx, CCHAR6 from datatypetestm where NULLIF(CCHAR6,CCHAR4) <> CCHAR6 order by cidx;
select cidx, CCHAR6 from datatypetestm where NULLIF(CCHAR6,CCHAR9) <> CCHAR6 order by cidx;
select cidx, CCHAR6 from datatypetestm where NULLIF(CCHAR6,CCHAR255) <> CCHAR6 order by cidx;
select cidx, CCHAR6 from datatypetestm where NULLIF(CCHAR6,CVCHAR4) <> CCHAR6 order by cidx;
select cidx, CCHAR6 from datatypetestm where NULLIF(CCHAR6,CVCHAR8) <> CCHAR6 order by cidx;
select cidx, CCHAR6 from datatypetestm where NULLIF(CCHAR6,CINTEGER) <> CCHAR6 order by cidx;
select cidx, CCHAR6 from datatypetestm where NULLIF(CCHAR6,CDOUBLE) <> CCHAR6 order by cidx;
select cidx, CCHAR6 from datatypetestm where NULLIF(CCHAR6,CDECIMAL9_2) <> CCHAR6 order by cidx;
select cidx, CCHAR6 from datatypetestm where NULLIF(CCHAR6,CDATE) <> CCHAR6 order by cidx;
select cidx, CCHAR6 from datatypetestm where NULLIF(CCHAR6,NULL) <> CCHAR6 order by cidx;
select cidx, CCHAR6 from datatypetestm where NULLIF(CCHAR6,'Hello world') <> CCHAR6 order by cidx;
select cidx, CCHAR7 from datatypetestm where NULLIF(CCHAR7,CCHAR4) <> CCHAR7 order by cidx;
select cidx, CCHAR7 from datatypetestm where NULLIF(CCHAR7,CCHAR9) <> CCHAR7 order by cidx;
select cidx, CCHAR7 from datatypetestm where NULLIF(CCHAR7,CCHAR255) <> CCHAR7 order by cidx;
select cidx, CCHAR7 from datatypetestm where NULLIF(CCHAR7,CVCHAR4) <> CCHAR7 order by cidx;
select cidx, CCHAR7 from datatypetestm where NULLIF(CCHAR7,CVCHAR8) <> CCHAR7 order by cidx;
select cidx, CCHAR7 from datatypetestm where NULLIF(CCHAR7,CINTEGER) <> CCHAR7 order by cidx;
select cidx, CCHAR7 from datatypetestm where NULLIF(CCHAR7,CDOUBLE) <> CCHAR7 order by cidx;
select cidx, CCHAR7 from datatypetestm where NULLIF(CCHAR7,CDECIMAL9_2) <> CCHAR7 order by cidx;
select cidx, CCHAR7 from datatypetestm where NULLIF(CCHAR7,CDATE) <> CCHAR7 order by cidx;
select cidx, CCHAR7 from datatypetestm where NULLIF(CCHAR7,NULL) <> CCHAR7 order by cidx;
select cidx, CCHAR7 from datatypetestm where NULLIF(CCHAR7,'Hello world') <> CCHAR7 order by cidx;
select cidx, CCHAR8 from datatypetestm where NULLIF(CCHAR8,CCHAR4) <> CCHAR8 order by cidx;
select cidx, CCHAR8 from datatypetestm where NULLIF(CCHAR8,CCHAR9) <> CCHAR8 order by cidx;
select cidx, CCHAR8 from datatypetestm where NULLIF(CCHAR8,CCHAR255) <> CCHAR8 order by cidx;
select cidx, CCHAR8 from datatypetestm where NULLIF(CCHAR8,CVCHAR4) <> CCHAR8 order by cidx;
select cidx, CCHAR8 from datatypetestm where NULLIF(CCHAR8,CVCHAR8) <> CCHAR8 order by cidx;
select cidx, CCHAR8 from datatypetestm where NULLIF(CCHAR8,CINTEGER) <> CCHAR8 order by cidx;
select cidx, CCHAR8 from datatypetestm where NULLIF(CCHAR8,CDOUBLE) <> CCHAR8 order by cidx;
select cidx, CCHAR8 from datatypetestm where NULLIF(CCHAR8,CDECIMAL9_2) <> CCHAR8 order by cidx;
select cidx, CCHAR8 from datatypetestm where NULLIF(CCHAR8,CDATE) <> CCHAR8 order by cidx;
select cidx, CCHAR8 from datatypetestm where NULLIF(CCHAR8,NULL) <> CCHAR8 order by cidx;
select cidx, CCHAR8 from datatypetestm where NULLIF(CCHAR8,'Hello world') <> CCHAR8 order by cidx;
select cidx, CCHAR9 from datatypetestm where NULLIF(CCHAR9,CCHAR4) <> CCHAR9 order by cidx;
select cidx, CCHAR9 from datatypetestm where NULLIF(CCHAR9,CCHAR9) <> CCHAR9 order by cidx;
select cidx, CCHAR9 from datatypetestm where NULLIF(CCHAR9,CCHAR255) <> CCHAR9 order by cidx;
select cidx, CCHAR9 from datatypetestm where NULLIF(CCHAR9,CVCHAR4) <> CCHAR9 order by cidx;
select cidx, CCHAR9 from datatypetestm where NULLIF(CCHAR9,CVCHAR8) <> CCHAR9 order by cidx;
select cidx, CCHAR9 from datatypetestm where NULLIF(CCHAR9,CINTEGER) <> CCHAR9 order by cidx;
select cidx, CCHAR9 from datatypetestm where NULLIF(CCHAR9,CDOUBLE) <> CCHAR9 order by cidx;
select cidx, CCHAR9 from datatypetestm where NULLIF(CCHAR9,CDECIMAL9_2) <> CCHAR9 order by cidx;
select cidx, CCHAR9 from datatypetestm where NULLIF(CCHAR9,CDATE) <> CCHAR9 order by cidx;
select cidx, CCHAR9 from datatypetestm where NULLIF(CCHAR9,NULL) <> CCHAR9 order by cidx;
select cidx, CCHAR9 from datatypetestm where NULLIF(CCHAR9,'Hello world') <> CCHAR9 order by cidx;
select cidx, CCHAR255 from datatypetestm where NULLIF(CCHAR255,CCHAR4) <> CCHAR255 order by cidx;
select cidx, CCHAR255 from datatypetestm where NULLIF(CCHAR255,CCHAR9) <> CCHAR255 order by cidx;
select cidx, CCHAR255 from datatypetestm where NULLIF(CCHAR255,CCHAR255) <> CCHAR255 order by cidx;
select cidx, CCHAR255 from datatypetestm where NULLIF(CCHAR255,CVCHAR4) <> CCHAR255 order by cidx;
select cidx, CCHAR255 from datatypetestm where NULLIF(CCHAR255,CVCHAR8) <> CCHAR255 order by cidx;
select cidx, CCHAR255 from datatypetestm where NULLIF(CCHAR255,CINTEGER) <> CCHAR255 order by cidx;
select cidx, CCHAR255 from datatypetestm where NULLIF(CCHAR255,CDOUBLE) <> CCHAR255 order by cidx;
select cidx, CCHAR255 from datatypetestm where NULLIF(CCHAR255,CDECIMAL9_2) <> CCHAR255 order by cidx;
select cidx, CCHAR255 from datatypetestm where NULLIF(CCHAR255,CDATE) <> CCHAR255 order by cidx;
select cidx, CCHAR255 from datatypetestm where NULLIF(CCHAR255,NULL) <> CCHAR255 order by cidx;
select cidx, CCHAR255 from datatypetestm where NULLIF(CCHAR255,'Hello world') <> CCHAR255 order by cidx;
select cidx, CVCHAR1 from datatypetestm where NULLIF(CVCHAR1,CCHAR4) <> CVCHAR1 order by cidx;
select cidx, CVCHAR1 from datatypetestm where NULLIF(CVCHAR1,CCHAR9) <> CVCHAR1 order by cidx;
select cidx, CVCHAR1 from datatypetestm where NULLIF(CVCHAR1,CCHAR255) <> CVCHAR1 order by cidx;
select cidx, CVCHAR1 from datatypetestm where NULLIF(CVCHAR1,CVCHAR4) <> CVCHAR1 order by cidx;
select cidx, CVCHAR1 from datatypetestm where NULLIF(CVCHAR1,CVCHAR8) <> CVCHAR1 order by cidx;
select cidx, CVCHAR1 from datatypetestm where NULLIF(CVCHAR1,CINTEGER) <> CVCHAR1 order by cidx;
select cidx, CVCHAR1 from datatypetestm where NULLIF(CVCHAR1,CDOUBLE) <> CVCHAR1 order by cidx;
select cidx, CVCHAR1 from datatypetestm where NULLIF(CVCHAR1,CDECIMAL9_2) <> CVCHAR1 order by cidx;
select cidx, CVCHAR1 from datatypetestm where NULLIF(CVCHAR1,CDATE) <> CVCHAR1 order by cidx;
select cidx, CVCHAR1 from datatypetestm where NULLIF(CVCHAR1,NULL) <> CVCHAR1 order by cidx;
select cidx, CVCHAR1 from datatypetestm where NULLIF(CVCHAR1,'Hello world') <> CVCHAR1 order by cidx;
select cidx, CVCHAR2 from datatypetestm where NULLIF(CVCHAR2,CCHAR4) <> CVCHAR2 order by cidx;
select cidx, CVCHAR2 from datatypetestm where NULLIF(CVCHAR2,CCHAR9) <> CVCHAR2 order by cidx;
select cidx, CVCHAR2 from datatypetestm where NULLIF(CVCHAR2,CCHAR255) <> CVCHAR2 order by cidx;
select cidx, CVCHAR2 from datatypetestm where NULLIF(CVCHAR2,CVCHAR4) <> CVCHAR2 order by cidx;
select cidx, CVCHAR2 from datatypetestm where NULLIF(CVCHAR2,CVCHAR8) <> CVCHAR2 order by cidx;
select cidx, CVCHAR2 from datatypetestm where NULLIF(CVCHAR2,CINTEGER) <> CVCHAR2 order by cidx;
select cidx, CVCHAR2 from datatypetestm where NULLIF(CVCHAR2,CDOUBLE) <> CVCHAR2 order by cidx;
select cidx, CVCHAR2 from datatypetestm where NULLIF(CVCHAR2,CDECIMAL9_2) <> CVCHAR2 order by cidx;
select cidx, CVCHAR2 from datatypetestm where NULLIF(CVCHAR2,CDATE) <> CVCHAR2 order by cidx;
select cidx, CVCHAR2 from datatypetestm where NULLIF(CVCHAR2,NULL) <> CVCHAR2 order by cidx;
select cidx, CVCHAR2 from datatypetestm where NULLIF(CVCHAR2,'Hello world') <> CVCHAR2 order by cidx;
select cidx, CVCHAR3 from datatypetestm where NULLIF(CVCHAR3,CCHAR4) <> CVCHAR3 order by cidx;
select cidx, CVCHAR3 from datatypetestm where NULLIF(CVCHAR3,CCHAR9) <> CVCHAR3 order by cidx;
select cidx, CVCHAR3 from datatypetestm where NULLIF(CVCHAR3,CCHAR255) <> CVCHAR3 order by cidx;
select cidx, CVCHAR3 from datatypetestm where NULLIF(CVCHAR3,CVCHAR4) <> CVCHAR3 order by cidx;
select cidx, CVCHAR3 from datatypetestm where NULLIF(CVCHAR3,CVCHAR8) <> CVCHAR3 order by cidx;
select cidx, CVCHAR3 from datatypetestm where NULLIF(CVCHAR3,CINTEGER) <> CVCHAR3 order by cidx;
select cidx, CVCHAR3 from datatypetestm where NULLIF(CVCHAR3,CDOUBLE) <> CVCHAR3 order by cidx;
select cidx, CVCHAR3 from datatypetestm where NULLIF(CVCHAR3,CDECIMAL9_2) <> CVCHAR3 order by cidx;
select cidx, CVCHAR3 from datatypetestm where NULLIF(CVCHAR3,CDATE) <> CVCHAR3 order by cidx;
select cidx, CVCHAR3 from datatypetestm where NULLIF(CVCHAR3,NULL) <> CVCHAR3 order by cidx;
select cidx, CVCHAR3 from datatypetestm where NULLIF(CVCHAR3,'Hello world') <> CVCHAR3 order by cidx;
select cidx, CVCHAR4 from datatypetestm where NULLIF(CVCHAR4,CCHAR4) <> CVCHAR4 order by cidx;
select cidx, CVCHAR4 from datatypetestm where NULLIF(CVCHAR4,CCHAR9) <> CVCHAR4 order by cidx;
select cidx, CVCHAR4 from datatypetestm where NULLIF(CVCHAR4,CCHAR255) <> CVCHAR4 order by cidx;
select cidx, CVCHAR4 from datatypetestm where NULLIF(CVCHAR4,CVCHAR4) <> CVCHAR4 order by cidx;
select cidx, CVCHAR4 from datatypetestm where NULLIF(CVCHAR4,CVCHAR8) <> CVCHAR4 order by cidx;
select cidx, CVCHAR4 from datatypetestm where NULLIF(CVCHAR4,CINTEGER) <> CVCHAR4 order by cidx;
select cidx, CVCHAR4 from datatypetestm where NULLIF(CVCHAR4,CDOUBLE) <> CVCHAR4 order by cidx;
select cidx, CVCHAR4 from datatypetestm where NULLIF(CVCHAR4,CDECIMAL9_2) <> CVCHAR4 order by cidx;
select cidx, CVCHAR4 from datatypetestm where NULLIF(CVCHAR4,CDATE) <> CVCHAR4 order by cidx;
select cidx, CVCHAR4 from datatypetestm where NULLIF(CVCHAR4,NULL) <> CVCHAR4 order by cidx;
select cidx, CVCHAR4 from datatypetestm where NULLIF(CVCHAR4,'Hello world') <> CVCHAR4 order by cidx;
select cidx, CVCHAR5 from datatypetestm where NULLIF(CVCHAR5,CCHAR4) <> CVCHAR5 order by cidx;
select cidx, CVCHAR5 from datatypetestm where NULLIF(CVCHAR5,CCHAR9) <> CVCHAR5 order by cidx;
select cidx, CVCHAR5 from datatypetestm where NULLIF(CVCHAR5,CCHAR255) <> CVCHAR5 order by cidx;
select cidx, CVCHAR5 from datatypetestm where NULLIF(CVCHAR5,CVCHAR4) <> CVCHAR5 order by cidx;
select cidx, CVCHAR5 from datatypetestm where NULLIF(CVCHAR5,CVCHAR8) <> CVCHAR5 order by cidx;
select cidx, CVCHAR5 from datatypetestm where NULLIF(CVCHAR5,CINTEGER) <> CVCHAR5 order by cidx;
select cidx, CVCHAR5 from datatypetestm where NULLIF(CVCHAR5,CDOUBLE) <> CVCHAR5 order by cidx;
select cidx, CVCHAR5 from datatypetestm where NULLIF(CVCHAR5,CDECIMAL9_2) <> CVCHAR5 order by cidx;
select cidx, CVCHAR5 from datatypetestm where NULLIF(CVCHAR5,CDATE) <> CVCHAR5 order by cidx;
select cidx, CVCHAR5 from datatypetestm where NULLIF(CVCHAR5,NULL) <> CVCHAR5 order by cidx;
select cidx, CVCHAR5 from datatypetestm where NULLIF(CVCHAR5,'Hello world') <> CVCHAR5 order by cidx;
select cidx, CVCHAR6 from datatypetestm where NULLIF(CVCHAR6,CCHAR4) <> CVCHAR6 order by cidx;
select cidx, CVCHAR6 from datatypetestm where NULLIF(CVCHAR6,CCHAR9) <> CVCHAR6 order by cidx;
select cidx, CVCHAR6 from datatypetestm where NULLIF(CVCHAR6,CCHAR255) <> CVCHAR6 order by cidx;
select cidx, CVCHAR6 from datatypetestm where NULLIF(CVCHAR6,CVCHAR4) <> CVCHAR6 order by cidx;
select cidx, CVCHAR6 from datatypetestm where NULLIF(CVCHAR6,CVCHAR8) <> CVCHAR6 order by cidx;
select cidx, CVCHAR6 from datatypetestm where NULLIF(CVCHAR6,CINTEGER) <> CVCHAR6 order by cidx;
select cidx, CVCHAR6 from datatypetestm where NULLIF(CVCHAR6,CDOUBLE) <> CVCHAR6 order by cidx;
select cidx, CVCHAR6 from datatypetestm where NULLIF(CVCHAR6,CDECIMAL9_2) <> CVCHAR6 order by cidx;
select cidx, CVCHAR6 from datatypetestm where NULLIF(CVCHAR6,CDATE) <> CVCHAR6 order by cidx;
select cidx, CVCHAR6 from datatypetestm where NULLIF(CVCHAR6,NULL) <> CVCHAR6 order by cidx;
select cidx, CVCHAR6 from datatypetestm where NULLIF(CVCHAR6,'Hello world') <> CVCHAR6 order by cidx;
select cidx, CVCHAR7 from datatypetestm where NULLIF(CVCHAR7,CCHAR4) <> CVCHAR7 order by cidx;
select cidx, CVCHAR7 from datatypetestm where NULLIF(CVCHAR7,CCHAR9) <> CVCHAR7 order by cidx;
select cidx, CVCHAR7 from datatypetestm where NULLIF(CVCHAR7,CCHAR255) <> CVCHAR7 order by cidx;
select cidx, CVCHAR7 from datatypetestm where NULLIF(CVCHAR7,CVCHAR4) <> CVCHAR7 order by cidx;
select cidx, CVCHAR7 from datatypetestm where NULLIF(CVCHAR7,CVCHAR8) <> CVCHAR7 order by cidx;
select cidx, CVCHAR7 from datatypetestm where NULLIF(CVCHAR7,CINTEGER) <> CVCHAR7 order by cidx;
select cidx, CVCHAR7 from datatypetestm where NULLIF(CVCHAR7,CDOUBLE) <> CVCHAR7 order by cidx;
select cidx, CVCHAR7 from datatypetestm where NULLIF(CVCHAR7,CDECIMAL9_2) <> CVCHAR7 order by cidx;
select cidx, CVCHAR7 from datatypetestm where NULLIF(CVCHAR7,CDATE) <> CVCHAR7 order by cidx;
select cidx, CVCHAR7 from datatypetestm where NULLIF(CVCHAR7,NULL) <> CVCHAR7 order by cidx;
select cidx, CVCHAR7 from datatypetestm where NULLIF(CVCHAR7,'Hello world') <> CVCHAR7 order by cidx;
select cidx, CVCHAR8 from datatypetestm where NULLIF(CVCHAR8,CCHAR4) <> CVCHAR8 order by cidx;
select cidx, CVCHAR8 from datatypetestm where NULLIF(CVCHAR8,CCHAR9) <> CVCHAR8 order by cidx;
select cidx, CVCHAR8 from datatypetestm where NULLIF(CVCHAR8,CCHAR255) <> CVCHAR8 order by cidx;
select cidx, CVCHAR8 from datatypetestm where NULLIF(CVCHAR8,CVCHAR4) <> CVCHAR8 order by cidx;
select cidx, CVCHAR8 from datatypetestm where NULLIF(CVCHAR8,CVCHAR8) <> CVCHAR8 order by cidx;
select cidx, CVCHAR8 from datatypetestm where NULLIF(CVCHAR8,CINTEGER) <> CVCHAR8 order by cidx;
select cidx, CVCHAR8 from datatypetestm where NULLIF(CVCHAR8,CDOUBLE) <> CVCHAR8 order by cidx;
select cidx, CVCHAR8 from datatypetestm where NULLIF(CVCHAR8,CDECIMAL9_2) <> CVCHAR8 order by cidx;
select cidx, CVCHAR8 from datatypetestm where NULLIF(CVCHAR8,CDATE) <> CVCHAR8 order by cidx;
select cidx, CVCHAR8 from datatypetestm where NULLIF(CVCHAR8,NULL) <> CVCHAR8 order by cidx;
select cidx, CVCHAR8 from datatypetestm where NULLIF(CVCHAR8,'Hello world') <> CVCHAR8 order by cidx;
select cidx, CVCHAR255 from datatypetestm where NULLIF(CVCHAR255,CCHAR4) <> CVCHAR255 order by cidx;
select cidx, CVCHAR255 from datatypetestm where NULLIF(CVCHAR255,CCHAR9) <> CVCHAR255 order by cidx;
select cidx, CVCHAR255 from datatypetestm where NULLIF(CVCHAR255,CCHAR255) <> CVCHAR255 order by cidx;
select cidx, CVCHAR255 from datatypetestm where NULLIF(CVCHAR255,CVCHAR4) <> CVCHAR255 order by cidx;
select cidx, CVCHAR255 from datatypetestm where NULLIF(CVCHAR255,CVCHAR8) <> CVCHAR255 order by cidx;
select cidx, CVCHAR255 from datatypetestm where NULLIF(CVCHAR255,CINTEGER) <> CVCHAR255 order by cidx;
select cidx, CVCHAR255 from datatypetestm where NULLIF(CVCHAR255,CDOUBLE) <> CVCHAR255 order by cidx;
select cidx, CVCHAR255 from datatypetestm where NULLIF(CVCHAR255,CDECIMAL9_2) <> CVCHAR255 order by cidx;
select cidx, CVCHAR255 from datatypetestm where NULLIF(CVCHAR255,CDATE) <> CVCHAR255 order by cidx;
select cidx, CVCHAR255 from datatypetestm where NULLIF(CVCHAR255,NULL) <> CVCHAR255 order by cidx;
select cidx, CVCHAR255 from datatypetestm where NULLIF(CVCHAR255,'Hello world') <> CVCHAR255 order by cidx;
