select cidx, CBIGINT, NULLIF(CBIGINT,CBIGINT) from datatypetestm order by cidx;
select cidx, CBIGINT, NULLIF(CBIGINT,CINTEGER) from datatypetestm order by cidx;
select cidx, CBIGINT, NULLIF(CBIGINT,CDOUBLE) from datatypetestm order by cidx;
select cidx, CBIGINT, NULLIF(CBIGINT,CDECIMAL9_2) from datatypetestm order by cidx;
select cidx, CBIGINT, NULLIF(CBIGINT,1) from datatypetestm order by cidx;
select cidx, CBIGINT, NULLIF(CBIGINT,3.14) from datatypetestm order by cidx;
select cidx, CBIGINT, NULLIF(CBIGINT,CCHAR4) from datatypetestm order by cidx;
select cidx, CBIGINT, NULLIF(CBIGINT,CDATE) from datatypetestm order by cidx;
select cidx, CBIGINT, NULLIF(CBIGINT,NULL) from datatypetestm order by cidx;
select cidx, CBIGINT, NULLIF(CBIGINT,'HELLO WORLD') from datatypetestm order by cidx;
select cidx, CDECIMAL1, NULLIF(CDECIMAL1,CBIGINT) from datatypetestm order by cidx;
select cidx, CDECIMAL1, NULLIF(CDECIMAL1,CINTEGER) from datatypetestm order by cidx;
select cidx, CDECIMAL1, NULLIF(CDECIMAL1,CDOUBLE) from datatypetestm order by cidx;
select cidx, CDECIMAL1, NULLIF(CDECIMAL1,CDECIMAL9_2) from datatypetestm order by cidx;
select cidx, CDECIMAL1, NULLIF(CDECIMAL1,1) from datatypetestm order by cidx;
select cidx, CDECIMAL1, NULLIF(CDECIMAL1,3.14) from datatypetestm order by cidx;
select cidx, CDECIMAL1, NULLIF(CDECIMAL1,CCHAR4) from datatypetestm order by cidx;
select cidx, CDECIMAL1, NULLIF(CDECIMAL1,CDATE) from datatypetestm order by cidx;
select cidx, CDECIMAL1, NULLIF(CDECIMAL1,NULL) from datatypetestm order by cidx;
select cidx, CDECIMAL1, NULLIF(CDECIMAL1,'HELLO WORLD') from datatypetestm order by cidx;
select cidx, CDECIMAL4, NULLIF(CDECIMAL4,CBIGINT) from datatypetestm order by cidx;
select cidx, CDECIMAL4, NULLIF(CDECIMAL4,CINTEGER) from datatypetestm order by cidx;
select cidx, CDECIMAL4, NULLIF(CDECIMAL4,CDOUBLE) from datatypetestm order by cidx;
select cidx, CDECIMAL4, NULLIF(CDECIMAL4,CDECIMAL9_2) from datatypetestm order by cidx;
select cidx, CDECIMAL4, NULLIF(CDECIMAL4,1) from datatypetestm order by cidx;
select cidx, CDECIMAL4, NULLIF(CDECIMAL4,3.14) from datatypetestm order by cidx;
select cidx, CDECIMAL4, NULLIF(CDECIMAL4,CCHAR4) from datatypetestm order by cidx;
select cidx, CDECIMAL4, NULLIF(CDECIMAL4,CDATE) from datatypetestm order by cidx;
select cidx, CDECIMAL4, NULLIF(CDECIMAL4,NULL) from datatypetestm order by cidx;
select cidx, CDECIMAL4, NULLIF(CDECIMAL4,'HELLO WORLD') from datatypetestm order by cidx;
select cidx, CDECIMAL4_2, NULLIF(CDECIMAL4_2,CBIGINT) from datatypetestm order by cidx;
select cidx, CDECIMAL4_2, NULLIF(CDECIMAL4_2,CINTEGER) from datatypetestm order by cidx;
select cidx, CDECIMAL4_2, NULLIF(CDECIMAL4_2,CDOUBLE) from datatypetestm order by cidx;
select cidx, CDECIMAL4_2, NULLIF(CDECIMAL4_2,CDECIMAL9_2) from datatypetestm order by cidx;
select cidx, CDECIMAL4_2, NULLIF(CDECIMAL4_2,1) from datatypetestm order by cidx;
select cidx, CDECIMAL4_2, NULLIF(CDECIMAL4_2,3.14) from datatypetestm order by cidx;
select cidx, CDECIMAL4_2, NULLIF(CDECIMAL4_2,CCHAR4) from datatypetestm order by cidx;
select cidx, CDECIMAL4_2, NULLIF(CDECIMAL4_2,CDATE) from datatypetestm order by cidx;
select cidx, CDECIMAL4_2, NULLIF(CDECIMAL4_2,NULL) from datatypetestm order by cidx;
select cidx, CDECIMAL4_2, NULLIF(CDECIMAL4_2,'HELLO WORLD') from datatypetestm order by cidx;
select cidx, CDECIMAL5, NULLIF(CDECIMAL5,CBIGINT) from datatypetestm order by cidx;
select cidx, CDECIMAL5, NULLIF(CDECIMAL5,CINTEGER) from datatypetestm order by cidx;
select cidx, CDECIMAL5, NULLIF(CDECIMAL5,CDOUBLE) from datatypetestm order by cidx;
select cidx, CDECIMAL5, NULLIF(CDECIMAL5,CDECIMAL9_2) from datatypetestm order by cidx;
select cidx, CDECIMAL5, NULLIF(CDECIMAL5,1) from datatypetestm order by cidx;
select cidx, CDECIMAL5, NULLIF(CDECIMAL5,3.14) from datatypetestm order by cidx;
select cidx, CDECIMAL5, NULLIF(CDECIMAL5,CCHAR4) from datatypetestm order by cidx;
select cidx, CDECIMAL5, NULLIF(CDECIMAL5,CDATE) from datatypetestm order by cidx;
select cidx, CDECIMAL5, NULLIF(CDECIMAL5,NULL) from datatypetestm order by cidx;
select cidx, CDECIMAL5, NULLIF(CDECIMAL5,'HELLO WORLD') from datatypetestm order by cidx;
select cidx, CDECIMAL9, NULLIF(CDECIMAL9,CBIGINT) from datatypetestm order by cidx;
select cidx, CDECIMAL9, NULLIF(CDECIMAL9,CINTEGER) from datatypetestm order by cidx;
select cidx, CDECIMAL9, NULLIF(CDECIMAL9,CDOUBLE) from datatypetestm order by cidx;
select cidx, CDECIMAL9, NULLIF(CDECIMAL9,CDECIMAL9_2) from datatypetestm order by cidx;
select cidx, CDECIMAL9, NULLIF(CDECIMAL9,1) from datatypetestm order by cidx;
select cidx, CDECIMAL9, NULLIF(CDECIMAL9,3.14) from datatypetestm order by cidx;
select cidx, CDECIMAL9, NULLIF(CDECIMAL9,CCHAR4) from datatypetestm order by cidx;
select cidx, CDECIMAL9, NULLIF(CDECIMAL9,CDATE) from datatypetestm order by cidx;
select cidx, CDECIMAL9, NULLIF(CDECIMAL9,NULL) from datatypetestm order by cidx;
select cidx, CDECIMAL9, NULLIF(CDECIMAL9,'HELLO WORLD') from datatypetestm order by cidx;
select cidx, CDECIMAL9_2, NULLIF(CDECIMAL9_2,CBIGINT) from datatypetestm order by cidx;
select cidx, CDECIMAL9_2, NULLIF(CDECIMAL9_2,CINTEGER) from datatypetestm order by cidx;
select cidx, CDECIMAL9_2, NULLIF(CDECIMAL9_2,CDOUBLE) from datatypetestm order by cidx;
select cidx, CDECIMAL9_2, NULLIF(CDECIMAL9_2,CDECIMAL9_2) from datatypetestm order by cidx;
select cidx, CDECIMAL9_2, NULLIF(CDECIMAL9_2,1) from datatypetestm order by cidx;
select cidx, CDECIMAL9_2, NULLIF(CDECIMAL9_2,3.14) from datatypetestm order by cidx;
select cidx, CDECIMAL9_2, NULLIF(CDECIMAL9_2,CCHAR4) from datatypetestm order by cidx;
select cidx, CDECIMAL9_2, NULLIF(CDECIMAL9_2,CDATE) from datatypetestm order by cidx;
select cidx, CDECIMAL9_2, NULLIF(CDECIMAL9_2,NULL) from datatypetestm order by cidx;
select cidx, CDECIMAL9_2, NULLIF(CDECIMAL9_2,'HELLO WORLD') from datatypetestm order by cidx;
select cidx, CDECIMAL10, NULLIF(CDECIMAL10,CBIGINT) from datatypetestm order by cidx;
select cidx, CDECIMAL10, NULLIF(CDECIMAL10,CINTEGER) from datatypetestm order by cidx;
select cidx, CDECIMAL10, NULLIF(CDECIMAL10,CDOUBLE) from datatypetestm order by cidx;
select cidx, CDECIMAL10, NULLIF(CDECIMAL10,CDECIMAL9_2) from datatypetestm order by cidx;
select cidx, CDECIMAL10, NULLIF(CDECIMAL10,1) from datatypetestm order by cidx;
select cidx, CDECIMAL10, NULLIF(CDECIMAL10,3.14) from datatypetestm order by cidx;
select cidx, CDECIMAL10, NULLIF(CDECIMAL10,CCHAR4) from datatypetestm order by cidx;
select cidx, CDECIMAL10, NULLIF(CDECIMAL10,CDATE) from datatypetestm order by cidx;
select cidx, CDECIMAL10, NULLIF(CDECIMAL10,NULL) from datatypetestm order by cidx;
select cidx, CDECIMAL10, NULLIF(CDECIMAL10,'HELLO WORLD') from datatypetestm order by cidx;
select cidx, CDECIMAL18, NULLIF(CDECIMAL18,CBIGINT) from datatypetestm order by cidx;
select cidx, CDECIMAL18, NULLIF(CDECIMAL18,CINTEGER) from datatypetestm order by cidx;
select cidx, CDECIMAL18, NULLIF(CDECIMAL18,CDOUBLE) from datatypetestm order by cidx;
select cidx, CDECIMAL18, NULLIF(CDECIMAL18,CDECIMAL9_2) from datatypetestm order by cidx;
select cidx, CDECIMAL18, NULLIF(CDECIMAL18,1) from datatypetestm order by cidx;
select cidx, CDECIMAL18, NULLIF(CDECIMAL18,3.14) from datatypetestm order by cidx;
select cidx, CDECIMAL18, NULLIF(CDECIMAL18,CCHAR4) from datatypetestm order by cidx;
select cidx, CDECIMAL18, NULLIF(CDECIMAL18,CDATE) from datatypetestm order by cidx;
select cidx, CDECIMAL18, NULLIF(CDECIMAL18,NULL) from datatypetestm order by cidx;
select cidx, CDECIMAL18, NULLIF(CDECIMAL18,'HELLO WORLD') from datatypetestm order by cidx;
select cidx, CDECIMAL18_2, NULLIF(CDECIMAL18_2,CBIGINT) from datatypetestm order by cidx;
select cidx, CDECIMAL18_2, NULLIF(CDECIMAL18_2,CINTEGER) from datatypetestm order by cidx;
select cidx, CDECIMAL18_2, NULLIF(CDECIMAL18_2,CDOUBLE) from datatypetestm order by cidx;
select cidx, CDECIMAL18_2, NULLIF(CDECIMAL18_2,CDECIMAL9_2) from datatypetestm order by cidx;
select cidx, CDECIMAL18_2, NULLIF(CDECIMAL18_2,1) from datatypetestm order by cidx;
select cidx, CDECIMAL18_2, NULLIF(CDECIMAL18_2,3.14) from datatypetestm order by cidx;
select cidx, CDECIMAL18_2, NULLIF(CDECIMAL18_2,CCHAR4) from datatypetestm order by cidx;
select cidx, CDECIMAL18_2, NULLIF(CDECIMAL18_2,CDATE) from datatypetestm order by cidx;
select cidx, CDECIMAL18_2, NULLIF(CDECIMAL18_2,NULL) from datatypetestm order by cidx;
select cidx, CDECIMAL18_2, NULLIF(CDECIMAL18_2,'HELLO WORLD') from datatypetestm order by cidx;
select cidx, CINTEGER, NULLIF(CINTEGER,CBIGINT) from datatypetestm order by cidx;
select cidx, CINTEGER, NULLIF(CINTEGER,CINTEGER) from datatypetestm order by cidx;
select cidx, CINTEGER, NULLIF(CINTEGER,CDOUBLE) from datatypetestm order by cidx;
select cidx, CINTEGER, NULLIF(CINTEGER,CDECIMAL9_2) from datatypetestm order by cidx;
select cidx, CINTEGER, NULLIF(CINTEGER,1) from datatypetestm order by cidx;
select cidx, CINTEGER, NULLIF(CINTEGER,3.14) from datatypetestm order by cidx;
select cidx, CINTEGER, NULLIF(CINTEGER,CCHAR4) from datatypetestm order by cidx;
select cidx, CINTEGER, NULLIF(CINTEGER,CDATE) from datatypetestm order by cidx;
select cidx, CINTEGER, NULLIF(CINTEGER,NULL) from datatypetestm order by cidx;
select cidx, CINTEGER, NULLIF(CINTEGER,'HELLO WORLD') from datatypetestm order by cidx;
select cidx, CSMALLINT, NULLIF(CSMALLINT,CBIGINT) from datatypetestm order by cidx;
select cidx, CSMALLINT, NULLIF(CSMALLINT,CINTEGER) from datatypetestm order by cidx;
select cidx, CSMALLINT, NULLIF(CSMALLINT,CDOUBLE) from datatypetestm order by cidx;
select cidx, CSMALLINT, NULLIF(CSMALLINT,CDECIMAL9_2) from datatypetestm order by cidx;
select cidx, CSMALLINT, NULLIF(CSMALLINT,1) from datatypetestm order by cidx;
select cidx, CSMALLINT, NULLIF(CSMALLINT,3.14) from datatypetestm order by cidx;
select cidx, CSMALLINT, NULLIF(CSMALLINT,CCHAR4) from datatypetestm order by cidx;
select cidx, CSMALLINT, NULLIF(CSMALLINT,CDATE) from datatypetestm order by cidx;
select cidx, CSMALLINT, NULLIF(CSMALLINT,NULL) from datatypetestm order by cidx;
select cidx, CSMALLINT, NULLIF(CSMALLINT,'HELLO WORLD') from datatypetestm order by cidx;
select cidx, CTINYINT, NULLIF(CTINYINT,CBIGINT) from datatypetestm order by cidx;
select cidx, CTINYINT, NULLIF(CTINYINT,CINTEGER) from datatypetestm order by cidx;
select cidx, CTINYINT, NULLIF(CTINYINT,CDOUBLE) from datatypetestm order by cidx;
select cidx, CTINYINT, NULLIF(CTINYINT,CDECIMAL9_2) from datatypetestm order by cidx;
select cidx, CTINYINT, NULLIF(CTINYINT,1) from datatypetestm order by cidx;
select cidx, CTINYINT, NULLIF(CTINYINT,3.14) from datatypetestm order by cidx;
select cidx, CTINYINT, NULLIF(CTINYINT,CCHAR4) from datatypetestm order by cidx;
select cidx, CTINYINT, NULLIF(CTINYINT,CDATE) from datatypetestm order by cidx;
select cidx, CTINYINT, NULLIF(CTINYINT,NULL) from datatypetestm order by cidx;
select cidx, CTINYINT, NULLIF(CTINYINT,'HELLO WORLD') from datatypetestm order by cidx;
select cidx, CBIGINT from datatypetestm where NULLIF(CBIGINT,CBIGINT) <> CBIGINT order by cidx;
select cidx, CBIGINT from datatypetestm where NULLIF(CBIGINT,CINTEGER) <> CBIGINT order by cidx;
select cidx, CBIGINT from datatypetestm where NULLIF(CBIGINT,CDOUBLE) <> CBIGINT order by cidx;
select cidx, CBIGINT from datatypetestm where NULLIF(CBIGINT,CDECIMAL9_2) <> CBIGINT order by cidx;
select cidx, CBIGINT from datatypetestm where NULLIF(CBIGINT,1) <> CBIGINT order by cidx;
select cidx, CBIGINT from datatypetestm where NULLIF(CBIGINT,3.14) <> CBIGINT order by cidx;
select cidx, CBIGINT from datatypetestm where NULLIF(CBIGINT,CCHAR4) <> CBIGINT order by cidx;
select cidx, CBIGINT from datatypetestm where NULLIF(CBIGINT,CDATE) <> CBIGINT order by cidx;
select cidx, CBIGINT from datatypetestm where NULLIF(CBIGINT,NULL) <> CBIGINT order by cidx;
select cidx, CBIGINT from datatypetestm where NULLIF(CBIGINT,'HELLO WORLD') <> CBIGINT order by cidx;
select cidx, CDECIMAL1 from datatypetestm where NULLIF(CDECIMAL1,CBIGINT) <> CDECIMAL1 order by cidx;
select cidx, CDECIMAL1 from datatypetestm where NULLIF(CDECIMAL1,CINTEGER) <> CDECIMAL1 order by cidx;
select cidx, CDECIMAL1 from datatypetestm where NULLIF(CDECIMAL1,CDOUBLE) <> CDECIMAL1 order by cidx;
select cidx, CDECIMAL1 from datatypetestm where NULLIF(CDECIMAL1,CDECIMAL9_2) <> CDECIMAL1 order by cidx;
select cidx, CDECIMAL1 from datatypetestm where NULLIF(CDECIMAL1,1) <> CDECIMAL1 order by cidx;
select cidx, CDECIMAL1 from datatypetestm where NULLIF(CDECIMAL1,3.14) <> CDECIMAL1 order by cidx;
select cidx, CDECIMAL1 from datatypetestm where NULLIF(CDECIMAL1,CCHAR4) <> CDECIMAL1 order by cidx;
select cidx, CDECIMAL1 from datatypetestm where NULLIF(CDECIMAL1,CDATE) <> CDECIMAL1 order by cidx;
select cidx, CDECIMAL1 from datatypetestm where NULLIF(CDECIMAL1,NULL) <> CDECIMAL1 order by cidx;
select cidx, CDECIMAL1 from datatypetestm where NULLIF(CDECIMAL1,'HELLO WORLD') <> CDECIMAL1 order by cidx;
select cidx, CDECIMAL4 from datatypetestm where NULLIF(CDECIMAL4,CBIGINT) <> CDECIMAL4 order by cidx;
select cidx, CDECIMAL4 from datatypetestm where NULLIF(CDECIMAL4,CINTEGER) <> CDECIMAL4 order by cidx;
select cidx, CDECIMAL4 from datatypetestm where NULLIF(CDECIMAL4,CDOUBLE) <> CDECIMAL4 order by cidx;
select cidx, CDECIMAL4 from datatypetestm where NULLIF(CDECIMAL4,CDECIMAL9_2) <> CDECIMAL4 order by cidx;
select cidx, CDECIMAL4 from datatypetestm where NULLIF(CDECIMAL4,1) <> CDECIMAL4 order by cidx;
select cidx, CDECIMAL4 from datatypetestm where NULLIF(CDECIMAL4,3.14) <> CDECIMAL4 order by cidx;
select cidx, CDECIMAL4 from datatypetestm where NULLIF(CDECIMAL4,CCHAR4) <> CDECIMAL4 order by cidx;
select cidx, CDECIMAL4 from datatypetestm where NULLIF(CDECIMAL4,CDATE) <> CDECIMAL4 order by cidx;
select cidx, CDECIMAL4 from datatypetestm where NULLIF(CDECIMAL4,NULL) <> CDECIMAL4 order by cidx;
select cidx, CDECIMAL4 from datatypetestm where NULLIF(CDECIMAL4,'HELLO WORLD') <> CDECIMAL4 order by cidx;
select cidx, CDECIMAL4_2 from datatypetestm where NULLIF(CDECIMAL4_2,CBIGINT) <> CDECIMAL4_2 order by cidx;
select cidx, CDECIMAL4_2 from datatypetestm where NULLIF(CDECIMAL4_2,CINTEGER) <> CDECIMAL4_2 order by cidx;
select cidx, CDECIMAL4_2 from datatypetestm where NULLIF(CDECIMAL4_2,CDOUBLE) <> CDECIMAL4_2 order by cidx;
select cidx, CDECIMAL4_2 from datatypetestm where NULLIF(CDECIMAL4_2,CDECIMAL9_2) <> CDECIMAL4_2 order by cidx;
select cidx, CDECIMAL4_2 from datatypetestm where NULLIF(CDECIMAL4_2,1) <> CDECIMAL4_2 order by cidx;
select cidx, CDECIMAL4_2 from datatypetestm where NULLIF(CDECIMAL4_2,3.14) <> CDECIMAL4_2 order by cidx;
select cidx, CDECIMAL4_2 from datatypetestm where NULLIF(CDECIMAL4_2,CCHAR4) <> CDECIMAL4_2 order by cidx;
select cidx, CDECIMAL4_2 from datatypetestm where NULLIF(CDECIMAL4_2,CDATE) <> CDECIMAL4_2 order by cidx;
select cidx, CDECIMAL4_2 from datatypetestm where NULLIF(CDECIMAL4_2,NULL) <> CDECIMAL4_2 order by cidx;
select cidx, CDECIMAL4_2 from datatypetestm where NULLIF(CDECIMAL4_2,'HELLO WORLD') <> CDECIMAL4_2 order by cidx;
select cidx, CDECIMAL5 from datatypetestm where NULLIF(CDECIMAL5,CBIGINT) <> CDECIMAL5 order by cidx;
select cidx, CDECIMAL5 from datatypetestm where NULLIF(CDECIMAL5,CINTEGER) <> CDECIMAL5 order by cidx;
select cidx, CDECIMAL5 from datatypetestm where NULLIF(CDECIMAL5,CDOUBLE) <> CDECIMAL5 order by cidx;
select cidx, CDECIMAL5 from datatypetestm where NULLIF(CDECIMAL5,CDECIMAL9_2) <> CDECIMAL5 order by cidx;
select cidx, CDECIMAL5 from datatypetestm where NULLIF(CDECIMAL5,1) <> CDECIMAL5 order by cidx;
select cidx, CDECIMAL5 from datatypetestm where NULLIF(CDECIMAL5,3.14) <> CDECIMAL5 order by cidx;
select cidx, CDECIMAL5 from datatypetestm where NULLIF(CDECIMAL5,CCHAR4) <> CDECIMAL5 order by cidx;
select cidx, CDECIMAL5 from datatypetestm where NULLIF(CDECIMAL5,CDATE) <> CDECIMAL5 order by cidx;
select cidx, CDECIMAL5 from datatypetestm where NULLIF(CDECIMAL5,NULL) <> CDECIMAL5 order by cidx;
select cidx, CDECIMAL5 from datatypetestm where NULLIF(CDECIMAL5,'HELLO WORLD') <> CDECIMAL5 order by cidx;
select cidx, CDECIMAL9 from datatypetestm where NULLIF(CDECIMAL9,CBIGINT) <> CDECIMAL9 order by cidx;
select cidx, CDECIMAL9 from datatypetestm where NULLIF(CDECIMAL9,CINTEGER) <> CDECIMAL9 order by cidx;
select cidx, CDECIMAL9 from datatypetestm where NULLIF(CDECIMAL9,CDOUBLE) <> CDECIMAL9 order by cidx;
select cidx, CDECIMAL9 from datatypetestm where NULLIF(CDECIMAL9,CDECIMAL9_2) <> CDECIMAL9 order by cidx;
select cidx, CDECIMAL9 from datatypetestm where NULLIF(CDECIMAL9,1) <> CDECIMAL9 order by cidx;
select cidx, CDECIMAL9 from datatypetestm where NULLIF(CDECIMAL9,3.14) <> CDECIMAL9 order by cidx;
select cidx, CDECIMAL9 from datatypetestm where NULLIF(CDECIMAL9,CCHAR4) <> CDECIMAL9 order by cidx;
select cidx, CDECIMAL9 from datatypetestm where NULLIF(CDECIMAL9,CDATE) <> CDECIMAL9 order by cidx;
select cidx, CDECIMAL9 from datatypetestm where NULLIF(CDECIMAL9,NULL) <> CDECIMAL9 order by cidx;
select cidx, CDECIMAL9 from datatypetestm where NULLIF(CDECIMAL9,'HELLO WORLD') <> CDECIMAL9 order by cidx;
select cidx, CDECIMAL9_2 from datatypetestm where NULLIF(CDECIMAL9_2,CBIGINT) <> CDECIMAL9_2 order by cidx;
select cidx, CDECIMAL9_2 from datatypetestm where NULLIF(CDECIMAL9_2,CINTEGER) <> CDECIMAL9_2 order by cidx;
select cidx, CDECIMAL9_2 from datatypetestm where NULLIF(CDECIMAL9_2,CDOUBLE) <> CDECIMAL9_2 order by cidx;
select cidx, CDECIMAL9_2 from datatypetestm where NULLIF(CDECIMAL9_2,CDECIMAL9_2) <> CDECIMAL9_2 order by cidx;
select cidx, CDECIMAL9_2 from datatypetestm where NULLIF(CDECIMAL9_2,1) <> CDECIMAL9_2 order by cidx;
select cidx, CDECIMAL9_2 from datatypetestm where NULLIF(CDECIMAL9_2,3.14) <> CDECIMAL9_2 order by cidx;
select cidx, CDECIMAL9_2 from datatypetestm where NULLIF(CDECIMAL9_2,CCHAR4) <> CDECIMAL9_2 order by cidx;
select cidx, CDECIMAL9_2 from datatypetestm where NULLIF(CDECIMAL9_2,CDATE) <> CDECIMAL9_2 order by cidx;
select cidx, CDECIMAL9_2 from datatypetestm where NULLIF(CDECIMAL9_2,NULL) <> CDECIMAL9_2 order by cidx;
select cidx, CDECIMAL9_2 from datatypetestm where NULLIF(CDECIMAL9_2,'HELLO WORLD') <> CDECIMAL9_2 order by cidx;
select cidx, CDECIMAL10 from datatypetestm where NULLIF(CDECIMAL10,CBIGINT) <> CDECIMAL10 order by cidx;
select cidx, CDECIMAL10 from datatypetestm where NULLIF(CDECIMAL10,CINTEGER) <> CDECIMAL10 order by cidx;
select cidx, CDECIMAL10 from datatypetestm where NULLIF(CDECIMAL10,CDOUBLE) <> CDECIMAL10 order by cidx;
select cidx, CDECIMAL10 from datatypetestm where NULLIF(CDECIMAL10,CDECIMAL9_2) <> CDECIMAL10 order by cidx;
select cidx, CDECIMAL10 from datatypetestm where NULLIF(CDECIMAL10,1) <> CDECIMAL10 order by cidx;
select cidx, CDECIMAL10 from datatypetestm where NULLIF(CDECIMAL10,3.14) <> CDECIMAL10 order by cidx;
select cidx, CDECIMAL10 from datatypetestm where NULLIF(CDECIMAL10,CCHAR4) <> CDECIMAL10 order by cidx;
select cidx, CDECIMAL10 from datatypetestm where NULLIF(CDECIMAL10,CDATE) <> CDECIMAL10 order by cidx;
select cidx, CDECIMAL10 from datatypetestm where NULLIF(CDECIMAL10,NULL) <> CDECIMAL10 order by cidx;
select cidx, CDECIMAL10 from datatypetestm where NULLIF(CDECIMAL10,'HELLO WORLD') <> CDECIMAL10 order by cidx;
select cidx, CDECIMAL18 from datatypetestm where NULLIF(CDECIMAL18,CBIGINT) <> CDECIMAL18 order by cidx;
select cidx, CDECIMAL18 from datatypetestm where NULLIF(CDECIMAL18,CINTEGER) <> CDECIMAL18 order by cidx;
select cidx, CDECIMAL18 from datatypetestm where NULLIF(CDECIMAL18,CDOUBLE) <> CDECIMAL18 order by cidx;
select cidx, CDECIMAL18 from datatypetestm where NULLIF(CDECIMAL18,CDECIMAL9_2) <> CDECIMAL18 order by cidx;
select cidx, CDECIMAL18 from datatypetestm where NULLIF(CDECIMAL18,1) <> CDECIMAL18 order by cidx;
select cidx, CDECIMAL18 from datatypetestm where NULLIF(CDECIMAL18,3.14) <> CDECIMAL18 order by cidx;
select cidx, CDECIMAL18 from datatypetestm where NULLIF(CDECIMAL18,CCHAR4) <> CDECIMAL18 order by cidx;
select cidx, CDECIMAL18 from datatypetestm where NULLIF(CDECIMAL18,CDATE) <> CDECIMAL18 order by cidx;
select cidx, CDECIMAL18 from datatypetestm where NULLIF(CDECIMAL18,NULL) <> CDECIMAL18 order by cidx;
select cidx, CDECIMAL18 from datatypetestm where NULLIF(CDECIMAL18,'HELLO WORLD') <> CDECIMAL18 order by cidx;
select cidx, CDECIMAL18_2 from datatypetestm where NULLIF(CDECIMAL18_2,CBIGINT) <> CDECIMAL18_2 order by cidx;
select cidx, CDECIMAL18_2 from datatypetestm where NULLIF(CDECIMAL18_2,CINTEGER) <> CDECIMAL18_2 order by cidx;
select cidx, CDECIMAL18_2 from datatypetestm where NULLIF(CDECIMAL18_2,CDOUBLE) <> CDECIMAL18_2 order by cidx;
select cidx, CDECIMAL18_2 from datatypetestm where NULLIF(CDECIMAL18_2,CDECIMAL9_2) <> CDECIMAL18_2 order by cidx;
select cidx, CDECIMAL18_2 from datatypetestm where NULLIF(CDECIMAL18_2,1) <> CDECIMAL18_2 order by cidx;
select cidx, CDECIMAL18_2 from datatypetestm where NULLIF(CDECIMAL18_2,3.14) <> CDECIMAL18_2 order by cidx;
select cidx, CDECIMAL18_2 from datatypetestm where NULLIF(CDECIMAL18_2,CCHAR4) <> CDECIMAL18_2 order by cidx;
select cidx, CDECIMAL18_2 from datatypetestm where NULLIF(CDECIMAL18_2,CDATE) <> CDECIMAL18_2 order by cidx;
select cidx, CDECIMAL18_2 from datatypetestm where NULLIF(CDECIMAL18_2,NULL) <> CDECIMAL18_2 order by cidx;
select cidx, CDECIMAL18_2 from datatypetestm where NULLIF(CDECIMAL18_2,'HELLO WORLD') <> CDECIMAL18_2 order by cidx;
select cidx, CINTEGER from datatypetestm where NULLIF(CINTEGER,CBIGINT) <> CINTEGER order by cidx;
select cidx, CINTEGER from datatypetestm where NULLIF(CINTEGER,CINTEGER) <> CINTEGER order by cidx;
select cidx, CINTEGER from datatypetestm where NULLIF(CINTEGER,CDOUBLE) <> CINTEGER order by cidx;
select cidx, CINTEGER from datatypetestm where NULLIF(CINTEGER,CDECIMAL9_2) <> CINTEGER order by cidx;
select cidx, CINTEGER from datatypetestm where NULLIF(CINTEGER,1) <> CINTEGER order by cidx;
select cidx, CINTEGER from datatypetestm where NULLIF(CINTEGER,3.14) <> CINTEGER order by cidx;
select cidx, CINTEGER from datatypetestm where NULLIF(CINTEGER,CCHAR4) <> CINTEGER order by cidx;
select cidx, CINTEGER from datatypetestm where NULLIF(CINTEGER,CDATE) <> CINTEGER order by cidx;
select cidx, CINTEGER from datatypetestm where NULLIF(CINTEGER,NULL) <> CINTEGER order by cidx;
select cidx, CINTEGER from datatypetestm where NULLIF(CINTEGER,'HELLO WORLD') <> CINTEGER order by cidx;
select cidx, CSMALLINT from datatypetestm where NULLIF(CSMALLINT,CBIGINT) <> CSMALLINT order by cidx;
select cidx, CSMALLINT from datatypetestm where NULLIF(CSMALLINT,CINTEGER) <> CSMALLINT order by cidx;
select cidx, CSMALLINT from datatypetestm where NULLIF(CSMALLINT,CDOUBLE) <> CSMALLINT order by cidx;
select cidx, CSMALLINT from datatypetestm where NULLIF(CSMALLINT,CDECIMAL9_2) <> CSMALLINT order by cidx;
select cidx, CSMALLINT from datatypetestm where NULLIF(CSMALLINT,1) <> CSMALLINT order by cidx;
select cidx, CSMALLINT from datatypetestm where NULLIF(CSMALLINT,3.14) <> CSMALLINT order by cidx;
select cidx, CSMALLINT from datatypetestm where NULLIF(CSMALLINT,CCHAR4) <> CSMALLINT order by cidx;
select cidx, CSMALLINT from datatypetestm where NULLIF(CSMALLINT,CDATE) <> CSMALLINT order by cidx;
select cidx, CSMALLINT from datatypetestm where NULLIF(CSMALLINT,NULL) <> CSMALLINT order by cidx;
select cidx, CSMALLINT from datatypetestm where NULLIF(CSMALLINT,'HELLO WORLD') <> CSMALLINT order by cidx;
select cidx, CTINYINT from datatypetestm where NULLIF(CTINYINT,CBIGINT) <> CTINYINT order by cidx;
select cidx, CTINYINT from datatypetestm where NULLIF(CTINYINT,CINTEGER) <> CTINYINT order by cidx;
select cidx, CTINYINT from datatypetestm where NULLIF(CTINYINT,CDOUBLE) <> CTINYINT order by cidx;
select cidx, CTINYINT from datatypetestm where NULLIF(CTINYINT,CDECIMAL9_2) <> CTINYINT order by cidx;
select cidx, CTINYINT from datatypetestm where NULLIF(CTINYINT,1) <> CTINYINT order by cidx;
select cidx, CTINYINT from datatypetestm where NULLIF(CTINYINT,3.14) <> CTINYINT order by cidx;
select cidx, CTINYINT from datatypetestm where NULLIF(CTINYINT,CCHAR4) <> CTINYINT order by cidx;
select cidx, CTINYINT from datatypetestm where NULLIF(CTINYINT,CDATE) <> CTINYINT order by cidx;
select cidx, CTINYINT from datatypetestm where NULLIF(CTINYINT,NULL) <> CTINYINT order by cidx;
select cidx, CTINYINT from datatypetestm where NULLIF(CTINYINT,'HELLO WORLD') <> CTINYINT order by cidx;
