select cidx, CCHAR1, POSITION('aaa' IN CCHAR1) from datatypetestm;
select cidx, CCHAR1, POSITION('zzz' IN CCHAR1) from datatypetestm;
select cidx, CCHAR1, POSITION('aaaaaaaaa' IN CCHAR1) from datatypetestm;
select cidx, CCHAR1, POSITION('zzzzzzzzz' IN CCHAR1) from datatypetestm;
select cidx, CCHAR2, POSITION('aaa' IN CCHAR2) from datatypetestm;
select cidx, CCHAR2, POSITION('zzz' IN CCHAR2) from datatypetestm;
select cidx, CCHAR2, POSITION('aaaaaaaaa' IN CCHAR2) from datatypetestm;
select cidx, CCHAR2, POSITION('zzzzzzzzz' IN CCHAR2) from datatypetestm;
select cidx, CCHAR3, POSITION('aaa' IN CCHAR3) from datatypetestm;
select cidx, CCHAR3, POSITION('zzz' IN CCHAR3) from datatypetestm;
select cidx, CCHAR3, POSITION('aaaaaaaaa' IN CCHAR3) from datatypetestm;
select cidx, CCHAR3, POSITION('zzzzzzzzz' IN CCHAR3) from datatypetestm;
select cidx, CCHAR4, POSITION('aaa' IN CCHAR4) from datatypetestm;
select cidx, CCHAR4, POSITION('zzz' IN CCHAR4) from datatypetestm;
select cidx, CCHAR4, POSITION('aaaaaaaaa' IN CCHAR4) from datatypetestm;
select cidx, CCHAR4, POSITION('zzzzzzzzz' IN CCHAR4) from datatypetestm;
select cidx, CCHAR5, POSITION('aaa' IN CCHAR5) from datatypetestm;
select cidx, CCHAR5, POSITION('zzz' IN CCHAR5) from datatypetestm;
select cidx, CCHAR5, POSITION('aaaaaaaaa' IN CCHAR5) from datatypetestm;
select cidx, CCHAR5, POSITION('zzzzzzzzz' IN CCHAR5) from datatypetestm;
select cidx, CCHAR6, POSITION('aaa' IN CCHAR6) from datatypetestm;
select cidx, CCHAR6, POSITION('zzz' IN CCHAR6) from datatypetestm;
select cidx, CCHAR6, POSITION('aaaaaaaaa' IN CCHAR6) from datatypetestm;
select cidx, CCHAR6, POSITION('zzzzzzzzz' IN CCHAR6) from datatypetestm;
select cidx, CCHAR7, POSITION('aaa' IN CCHAR7) from datatypetestm;
select cidx, CCHAR7, POSITION('zzz' IN CCHAR7) from datatypetestm;
select cidx, CCHAR7, POSITION('aaaaaaaaa' IN CCHAR7) from datatypetestm;
select cidx, CCHAR7, POSITION('zzzzzzzzz' IN CCHAR7) from datatypetestm;
select cidx, CCHAR8, POSITION('aaa' IN CCHAR8) from datatypetestm;
select cidx, CCHAR8, POSITION('zzz' IN CCHAR8) from datatypetestm;
select cidx, CCHAR8, POSITION('aaaaaaaaa' IN CCHAR8) from datatypetestm;
select cidx, CCHAR8, POSITION('zzzzzzzzz' IN CCHAR8) from datatypetestm;
select cidx, CCHAR9, POSITION('aaa' IN CCHAR9) from datatypetestm;
select cidx, CCHAR9, POSITION('zzz' IN CCHAR9) from datatypetestm;
select cidx, CCHAR9, POSITION('aaaaaaaaa' IN CCHAR9) from datatypetestm;
select cidx, CCHAR9, POSITION('zzzzzzzzz' IN CCHAR9) from datatypetestm;
select cidx, CCHAR255, POSITION('aaa' IN CCHAR255) from datatypetestm;
select cidx, CCHAR255, POSITION('zzz' IN CCHAR255) from datatypetestm;
select cidx, CCHAR255, POSITION('aaaaaaaaa' IN CCHAR255) from datatypetestm;
select cidx, CCHAR255, POSITION('zzzzzzzzz' IN CCHAR255) from datatypetestm;
select cidx, CVCHAR1, POSITION('aaa' IN CVCHAR1) from datatypetestm;
select cidx, CVCHAR1, POSITION('zzz' IN CVCHAR1) from datatypetestm;
select cidx, CVCHAR1, POSITION('aaaaaaaaa' IN CVCHAR1) from datatypetestm;
select cidx, CVCHAR1, POSITION('zzzzzzzzz' IN CVCHAR1) from datatypetestm;
select cidx, CVCHAR2, POSITION('aaa' IN CVCHAR2) from datatypetestm;
select cidx, CVCHAR2, POSITION('zzz' IN CVCHAR2) from datatypetestm;
select cidx, CVCHAR2, POSITION('aaaaaaaaa' IN CVCHAR2) from datatypetestm;
select cidx, CVCHAR2, POSITION('zzzzzzzzz' IN CVCHAR2) from datatypetestm;
select cidx, CVCHAR3, POSITION('aaa' IN CVCHAR3) from datatypetestm;
select cidx, CVCHAR3, POSITION('zzz' IN CVCHAR3) from datatypetestm;
select cidx, CVCHAR3, POSITION('aaaaaaaaa' IN CVCHAR3) from datatypetestm;
select cidx, CVCHAR3, POSITION('zzzzzzzzz' IN CVCHAR3) from datatypetestm;
select cidx, CVCHAR4, POSITION('aaa' IN CVCHAR4) from datatypetestm;
select cidx, CVCHAR4, POSITION('zzz' IN CVCHAR4) from datatypetestm;
select cidx, CVCHAR4, POSITION('aaaaaaaaa' IN CVCHAR4) from datatypetestm;
select cidx, CVCHAR4, POSITION('zzzzzzzzz' IN CVCHAR4) from datatypetestm;
select cidx, CVCHAR5, POSITION('aaa' IN CVCHAR5) from datatypetestm;
select cidx, CVCHAR5, POSITION('zzz' IN CVCHAR5) from datatypetestm;
select cidx, CVCHAR5, POSITION('aaaaaaaaa' IN CVCHAR5) from datatypetestm;
select cidx, CVCHAR5, POSITION('zzzzzzzzz' IN CVCHAR5) from datatypetestm;
select cidx, CVCHAR6, POSITION('aaa' IN CVCHAR6) from datatypetestm;
select cidx, CVCHAR6, POSITION('zzz' IN CVCHAR6) from datatypetestm;
select cidx, CVCHAR6, POSITION('aaaaaaaaa' IN CVCHAR6) from datatypetestm;
select cidx, CVCHAR6, POSITION('zzzzzzzzz' IN CVCHAR6) from datatypetestm;
select cidx, CVCHAR7, POSITION('aaa' IN CVCHAR7) from datatypetestm;
select cidx, CVCHAR7, POSITION('zzz' IN CVCHAR7) from datatypetestm;
select cidx, CVCHAR7, POSITION('aaaaaaaaa' IN CVCHAR7) from datatypetestm;
select cidx, CVCHAR7, POSITION('zzzzzzzzz' IN CVCHAR7) from datatypetestm;
select cidx, CVCHAR8, POSITION('aaa' IN CVCHAR8) from datatypetestm;
select cidx, CVCHAR8, POSITION('zzz' IN CVCHAR8) from datatypetestm;
select cidx, CVCHAR8, POSITION('aaaaaaaaa' IN CVCHAR8) from datatypetestm;
select cidx, CVCHAR8, POSITION('zzzzzzzzz' IN CVCHAR8) from datatypetestm;
select cidx, CVCHAR255, POSITION('aaa' IN CVCHAR255) from datatypetestm;
select cidx, CVCHAR255, POSITION('zzz' IN CVCHAR255) from datatypetestm;
select cidx, CVCHAR255, POSITION('aaaaaaaaa' IN CVCHAR255) from datatypetestm;
select cidx, CVCHAR255, POSITION('zzzzzzzzz' IN CVCHAR255) from datatypetestm;
select cidx, CCHAR1 from datatypetestm where POSITION('aaa' IN CCHAR1) <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where POSITION('zzz' IN CCHAR1) <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where POSITION('aaaaaaaaa' IN CCHAR1) <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where POSITION('zzzzzzzzz' IN CCHAR1) <> CCHAR1;
select cidx, CCHAR2 from datatypetestm where POSITION('aaa' IN CCHAR2) <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where POSITION('zzz' IN CCHAR2) <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where POSITION('aaaaaaaaa' IN CCHAR2) <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where POSITION('zzzzzzzzz' IN CCHAR2) <> CCHAR2;
select cidx, CCHAR3 from datatypetestm where POSITION('aaa' IN CCHAR3) <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where POSITION('zzz' IN CCHAR3) <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where POSITION('aaaaaaaaa' IN CCHAR3) <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where POSITION('zzzzzzzzz' IN CCHAR3) <> CCHAR3;
select cidx, CCHAR4 from datatypetestm where POSITION('aaa' IN CCHAR4) <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where POSITION('zzz' IN CCHAR4) <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where POSITION('aaaaaaaaa' IN CCHAR4) <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where POSITION('zzzzzzzzz' IN CCHAR4) <> CCHAR4;
select cidx, CCHAR5 from datatypetestm where POSITION('aaa' IN CCHAR5) <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where POSITION('zzz' IN CCHAR5) <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where POSITION('aaaaaaaaa' IN CCHAR5) <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where POSITION('zzzzzzzzz' IN CCHAR5) <> CCHAR5;
select cidx, CCHAR6 from datatypetestm where POSITION('aaa' IN CCHAR6) <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where POSITION('zzz' IN CCHAR6) <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where POSITION('aaaaaaaaa' IN CCHAR6) <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where POSITION('zzzzzzzzz' IN CCHAR6) <> CCHAR6;
select cidx, CCHAR7 from datatypetestm where POSITION('aaa' IN CCHAR7) <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where POSITION('zzz' IN CCHAR7) <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where POSITION('aaaaaaaaa' IN CCHAR7) <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where POSITION('zzzzzzzzz' IN CCHAR7) <> CCHAR7;
select cidx, CCHAR8 from datatypetestm where POSITION('aaa' IN CCHAR8) <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where POSITION('zzz' IN CCHAR8) <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where POSITION('aaaaaaaaa' IN CCHAR8) <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where POSITION('zzzzzzzzz' IN CCHAR8) <> CCHAR8;
select cidx, CCHAR9 from datatypetestm where POSITION('aaa' IN CCHAR9) <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where POSITION('zzz' IN CCHAR9) <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where POSITION('aaaaaaaaa' IN CCHAR9) <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where POSITION('zzzzzzzzz' IN CCHAR9) <> CCHAR9;
select cidx, CCHAR255 from datatypetestm where POSITION('aaa' IN CCHAR255) <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where POSITION('zzz' IN CCHAR255) <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where POSITION('aaaaaaaaa' IN CCHAR255) <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where POSITION('zzzzzzzzz' IN CCHAR255) <> CCHAR255;
select cidx, CVCHAR1 from datatypetestm where POSITION('aaa' IN CVCHAR1) <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where POSITION('zzz' IN CVCHAR1) <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where POSITION('aaaaaaaaa' IN CVCHAR1) <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where POSITION('zzzzzzzzz' IN CVCHAR1) <> CVCHAR1;
select cidx, CVCHAR2 from datatypetestm where POSITION('aaa' IN CVCHAR2) <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where POSITION('zzz' IN CVCHAR2) <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where POSITION('aaaaaaaaa' IN CVCHAR2) <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where POSITION('zzzzzzzzz' IN CVCHAR2) <> CVCHAR2;
select cidx, CVCHAR3 from datatypetestm where POSITION('aaa' IN CVCHAR3) <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where POSITION('zzz' IN CVCHAR3) <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where POSITION('aaaaaaaaa' IN CVCHAR3) <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where POSITION('zzzzzzzzz' IN CVCHAR3) <> CVCHAR3;
select cidx, CVCHAR4 from datatypetestm where POSITION('aaa' IN CVCHAR4) <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where POSITION('zzz' IN CVCHAR4) <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where POSITION('aaaaaaaaa' IN CVCHAR4) <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where POSITION('zzzzzzzzz' IN CVCHAR4) <> CVCHAR4;
select cidx, CVCHAR5 from datatypetestm where POSITION('aaa' IN CVCHAR5) <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where POSITION('zzz' IN CVCHAR5) <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where POSITION('aaaaaaaaa' IN CVCHAR5) <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where POSITION('zzzzzzzzz' IN CVCHAR5) <> CVCHAR5;
select cidx, CVCHAR6 from datatypetestm where POSITION('aaa' IN CVCHAR6) <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where POSITION('zzz' IN CVCHAR6) <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where POSITION('aaaaaaaaa' IN CVCHAR6) <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where POSITION('zzzzzzzzz' IN CVCHAR6) <> CVCHAR6;
select cidx, CVCHAR7 from datatypetestm where POSITION('aaa' IN CVCHAR7) <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where POSITION('zzz' IN CVCHAR7) <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where POSITION('aaaaaaaaa' IN CVCHAR7) <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where POSITION('zzzzzzzzz' IN CVCHAR7) <> CVCHAR7;
select cidx, CVCHAR8 from datatypetestm where POSITION('aaa' IN CVCHAR8) <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where POSITION('zzz' IN CVCHAR8) <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where POSITION('aaaaaaaaa' IN CVCHAR8) <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where POSITION('zzzzzzzzz' IN CVCHAR8) <> CVCHAR8;
select cidx, CVCHAR255 from datatypetestm where POSITION('aaa' IN CVCHAR255) <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where POSITION('zzz' IN CVCHAR255) <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where POSITION('aaaaaaaaa' IN CVCHAR255) <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where POSITION('zzzzzzzzz' IN CVCHAR255) <> CVCHAR255;
