select cidx, CCHAR1, CCHAR1 REGEXP 'ssss$' from datatypetestm;
select cidx, CCHAR1, CCHAR1 REGEXP 'ggg$' from datatypetestm;
select cidx, CCHAR1, CCHAR1 REGEXP 'hhh$' from datatypetestm;
select cidx, CCHAR1, CCHAR1 REGEXP '(ttttttt)+' from datatypetestm;
select cidx, CCHAR1, CCHAR1 REGEXP '(ssssssss)+' from datatypetestm;
select cidx, CCHAR1, CCHAR1 REGEXP 'z$' from datatypetestm;
select cidx, CCHAR1, CCHAR1 REGEXP 'w*' from datatypetestm;
select cidx, CCHAR1, CCHAR1 REGEXP 'ww+w' from datatypetestm;
select cidx, CCHAR1, CCHAR1 REGEXP 'dd?d' from datatypetestm;
select cidx, CCHAR2, CCHAR2 REGEXP 'ssss$' from datatypetestm;
select cidx, CCHAR2, CCHAR2 REGEXP 'ggg$' from datatypetestm;
select cidx, CCHAR2, CCHAR2 REGEXP 'hhh$' from datatypetestm;
select cidx, CCHAR2, CCHAR2 REGEXP '(ttttttt)+' from datatypetestm;
select cidx, CCHAR2, CCHAR2 REGEXP '(ssssssss)+' from datatypetestm;
select cidx, CCHAR2, CCHAR2 REGEXP 'z$' from datatypetestm;
select cidx, CCHAR2, CCHAR2 REGEXP 'w*' from datatypetestm;
select cidx, CCHAR2, CCHAR2 REGEXP 'ww+w' from datatypetestm;
select cidx, CCHAR2, CCHAR2 REGEXP 'dd?d' from datatypetestm;
select cidx, CCHAR3, CCHAR3 REGEXP 'ssss$' from datatypetestm;
select cidx, CCHAR3, CCHAR3 REGEXP 'ggg$' from datatypetestm;
select cidx, CCHAR3, CCHAR3 REGEXP 'hhh$' from datatypetestm;
select cidx, CCHAR3, CCHAR3 REGEXP '(ttttttt)+' from datatypetestm;
select cidx, CCHAR3, CCHAR3 REGEXP '(ssssssss)+' from datatypetestm;
select cidx, CCHAR3, CCHAR3 REGEXP 'z$' from datatypetestm;
select cidx, CCHAR3, CCHAR3 REGEXP 'w*' from datatypetestm;
select cidx, CCHAR3, CCHAR3 REGEXP 'ww+w' from datatypetestm;
select cidx, CCHAR3, CCHAR3 REGEXP 'dd?d' from datatypetestm;
select cidx, CCHAR4, CCHAR4 REGEXP 'ssss$' from datatypetestm;
select cidx, CCHAR4, CCHAR4 REGEXP 'ggg$' from datatypetestm;
select cidx, CCHAR4, CCHAR4 REGEXP 'hhh$' from datatypetestm;
select cidx, CCHAR4, CCHAR4 REGEXP '(ttttttt)+' from datatypetestm;
select cidx, CCHAR4, CCHAR4 REGEXP '(ssssssss)+' from datatypetestm;
select cidx, CCHAR4, CCHAR4 REGEXP 'z$' from datatypetestm;
select cidx, CCHAR4, CCHAR4 REGEXP 'w*' from datatypetestm;
select cidx, CCHAR4, CCHAR4 REGEXP 'ww+w' from datatypetestm;
select cidx, CCHAR4, CCHAR4 REGEXP 'dd?d' from datatypetestm;
select cidx, CCHAR5, CCHAR5 REGEXP 'ssss$' from datatypetestm;
select cidx, CCHAR5, CCHAR5 REGEXP 'ggg$' from datatypetestm;
select cidx, CCHAR5, CCHAR5 REGEXP 'hhh$' from datatypetestm;
select cidx, CCHAR5, CCHAR5 REGEXP '(ttttttt)+' from datatypetestm;
select cidx, CCHAR5, CCHAR5 REGEXP '(ssssssss)+' from datatypetestm;
select cidx, CCHAR5, CCHAR5 REGEXP 'z$' from datatypetestm;
select cidx, CCHAR5, CCHAR5 REGEXP 'w*' from datatypetestm;
select cidx, CCHAR5, CCHAR5 REGEXP 'ww+w' from datatypetestm;
select cidx, CCHAR5, CCHAR5 REGEXP 'dd?d' from datatypetestm;
select cidx, CCHAR6, CCHAR6 REGEXP 'ssss$' from datatypetestm;
select cidx, CCHAR6, CCHAR6 REGEXP 'ggg$' from datatypetestm;
select cidx, CCHAR6, CCHAR6 REGEXP 'hhh$' from datatypetestm;
select cidx, CCHAR6, CCHAR6 REGEXP '(ttttttt)+' from datatypetestm;
select cidx, CCHAR6, CCHAR6 REGEXP '(ssssssss)+' from datatypetestm;
select cidx, CCHAR6, CCHAR6 REGEXP 'z$' from datatypetestm;
select cidx, CCHAR6, CCHAR6 REGEXP 'w*' from datatypetestm;
select cidx, CCHAR6, CCHAR6 REGEXP 'ww+w' from datatypetestm;
select cidx, CCHAR6, CCHAR6 REGEXP 'dd?d' from datatypetestm;
select cidx, CCHAR7, CCHAR7 REGEXP 'ssss$' from datatypetestm;
select cidx, CCHAR7, CCHAR7 REGEXP 'ggg$' from datatypetestm;
select cidx, CCHAR7, CCHAR7 REGEXP 'hhh$' from datatypetestm;
select cidx, CCHAR7, CCHAR7 REGEXP '(ttttttt)+' from datatypetestm;
select cidx, CCHAR7, CCHAR7 REGEXP '(ssssssss)+' from datatypetestm;
select cidx, CCHAR7, CCHAR7 REGEXP 'z$' from datatypetestm;
select cidx, CCHAR7, CCHAR7 REGEXP 'w*' from datatypetestm;
select cidx, CCHAR7, CCHAR7 REGEXP 'ww+w' from datatypetestm;
select cidx, CCHAR7, CCHAR7 REGEXP 'dd?d' from datatypetestm;
select cidx, CCHAR8, CCHAR8 REGEXP 'ssss$' from datatypetestm;
select cidx, CCHAR8, CCHAR8 REGEXP 'ggg$' from datatypetestm;
select cidx, CCHAR8, CCHAR8 REGEXP 'hhh$' from datatypetestm;
select cidx, CCHAR8, CCHAR8 REGEXP '(ttttttt)+' from datatypetestm;
select cidx, CCHAR8, CCHAR8 REGEXP '(ssssssss)+' from datatypetestm;
select cidx, CCHAR8, CCHAR8 REGEXP 'z$' from datatypetestm;
select cidx, CCHAR8, CCHAR8 REGEXP 'w*' from datatypetestm;
select cidx, CCHAR8, CCHAR8 REGEXP 'ww+w' from datatypetestm;
select cidx, CCHAR8, CCHAR8 REGEXP 'dd?d' from datatypetestm;
select cidx, CCHAR9, CCHAR9 REGEXP 'ssss$' from datatypetestm;
select cidx, CCHAR9, CCHAR9 REGEXP 'ggg$' from datatypetestm;
select cidx, CCHAR9, CCHAR9 REGEXP 'hhh$' from datatypetestm;
select cidx, CCHAR9, CCHAR9 REGEXP '(ttttttt)+' from datatypetestm;
select cidx, CCHAR9, CCHAR9 REGEXP '(ssssssss)+' from datatypetestm;
select cidx, CCHAR9, CCHAR9 REGEXP 'z$' from datatypetestm;
select cidx, CCHAR9, CCHAR9 REGEXP 'w*' from datatypetestm;
select cidx, CCHAR9, CCHAR9 REGEXP 'ww+w' from datatypetestm;
select cidx, CCHAR9, CCHAR9 REGEXP 'dd?d' from datatypetestm;
select cidx, CCHAR255, CCHAR255 REGEXP 'ssss$' from datatypetestm;
select cidx, CCHAR255, CCHAR255 REGEXP 'ggg$' from datatypetestm;
select cidx, CCHAR255, CCHAR255 REGEXP 'hhh$' from datatypetestm;
select cidx, CCHAR255, CCHAR255 REGEXP '(ttttttt)+' from datatypetestm;
select cidx, CCHAR255, CCHAR255 REGEXP '(ssssssss)+' from datatypetestm;
select cidx, CCHAR255, CCHAR255 REGEXP 'z$' from datatypetestm;
select cidx, CCHAR255, CCHAR255 REGEXP 'w*' from datatypetestm;
select cidx, CCHAR255, CCHAR255 REGEXP 'ww+w' from datatypetestm;
select cidx, CCHAR255, CCHAR255 REGEXP 'dd?d' from datatypetestm;
select cidx, CVCHAR1, CVCHAR1 REGEXP 'ssss$' from datatypetestm;
select cidx, CVCHAR1, CVCHAR1 REGEXP 'ggg$' from datatypetestm;
select cidx, CVCHAR1, CVCHAR1 REGEXP 'hhh$' from datatypetestm;
select cidx, CVCHAR1, CVCHAR1 REGEXP '(ttttttt)+' from datatypetestm;
select cidx, CVCHAR1, CVCHAR1 REGEXP '(ssssssss)+' from datatypetestm;
select cidx, CVCHAR1, CVCHAR1 REGEXP 'z$' from datatypetestm;
select cidx, CVCHAR1, CVCHAR1 REGEXP 'w*' from datatypetestm;
select cidx, CVCHAR1, CVCHAR1 REGEXP 'ww+w' from datatypetestm;
select cidx, CVCHAR1, CVCHAR1 REGEXP 'dd?d' from datatypetestm;
select cidx, CVCHAR2, CVCHAR2 REGEXP 'ssss$' from datatypetestm;
select cidx, CVCHAR2, CVCHAR2 REGEXP 'ggg$' from datatypetestm;
select cidx, CVCHAR2, CVCHAR2 REGEXP 'hhh$' from datatypetestm;
select cidx, CVCHAR2, CVCHAR2 REGEXP '(ttttttt)+' from datatypetestm;
select cidx, CVCHAR2, CVCHAR2 REGEXP '(ssssssss)+' from datatypetestm;
select cidx, CVCHAR2, CVCHAR2 REGEXP 'z$' from datatypetestm;
select cidx, CVCHAR2, CVCHAR2 REGEXP 'w*' from datatypetestm;
select cidx, CVCHAR2, CVCHAR2 REGEXP 'ww+w' from datatypetestm;
select cidx, CVCHAR2, CVCHAR2 REGEXP 'dd?d' from datatypetestm;
select cidx, CVCHAR3, CVCHAR3 REGEXP 'ssss$' from datatypetestm;
select cidx, CVCHAR3, CVCHAR3 REGEXP 'ggg$' from datatypetestm;
select cidx, CVCHAR3, CVCHAR3 REGEXP 'hhh$' from datatypetestm;
select cidx, CVCHAR3, CVCHAR3 REGEXP '(ttttttt)+' from datatypetestm;
select cidx, CVCHAR3, CVCHAR3 REGEXP '(ssssssss)+' from datatypetestm;
select cidx, CVCHAR3, CVCHAR3 REGEXP 'z$' from datatypetestm;
select cidx, CVCHAR3, CVCHAR3 REGEXP 'w*' from datatypetestm;
select cidx, CVCHAR3, CVCHAR3 REGEXP 'ww+w' from datatypetestm;
select cidx, CVCHAR3, CVCHAR3 REGEXP 'dd?d' from datatypetestm;
select cidx, CVCHAR4, CVCHAR4 REGEXP 'ssss$' from datatypetestm;
select cidx, CVCHAR4, CVCHAR4 REGEXP 'ggg$' from datatypetestm;
select cidx, CVCHAR4, CVCHAR4 REGEXP 'hhh$' from datatypetestm;
select cidx, CVCHAR4, CVCHAR4 REGEXP '(ttttttt)+' from datatypetestm;
select cidx, CVCHAR4, CVCHAR4 REGEXP '(ssssssss)+' from datatypetestm;
select cidx, CVCHAR4, CVCHAR4 REGEXP 'z$' from datatypetestm;
select cidx, CVCHAR4, CVCHAR4 REGEXP 'w*' from datatypetestm;
select cidx, CVCHAR4, CVCHAR4 REGEXP 'ww+w' from datatypetestm;
select cidx, CVCHAR4, CVCHAR4 REGEXP 'dd?d' from datatypetestm;
select cidx, CVCHAR5, CVCHAR5 REGEXP 'ssss$' from datatypetestm;
select cidx, CVCHAR5, CVCHAR5 REGEXP 'ggg$' from datatypetestm;
select cidx, CVCHAR5, CVCHAR5 REGEXP 'hhh$' from datatypetestm;
select cidx, CVCHAR5, CVCHAR5 REGEXP '(ttttttt)+' from datatypetestm;
select cidx, CVCHAR5, CVCHAR5 REGEXP '(ssssssss)+' from datatypetestm;
select cidx, CVCHAR5, CVCHAR5 REGEXP 'z$' from datatypetestm;
select cidx, CVCHAR5, CVCHAR5 REGEXP 'w*' from datatypetestm;
select cidx, CVCHAR5, CVCHAR5 REGEXP 'ww+w' from datatypetestm;
select cidx, CVCHAR5, CVCHAR5 REGEXP 'dd?d' from datatypetestm;
select cidx, CVCHAR6, CVCHAR6 REGEXP 'ssss$' from datatypetestm;
select cidx, CVCHAR6, CVCHAR6 REGEXP 'ggg$' from datatypetestm;
select cidx, CVCHAR6, CVCHAR6 REGEXP 'hhh$' from datatypetestm;
select cidx, CVCHAR6, CVCHAR6 REGEXP '(ttttttt)+' from datatypetestm;
select cidx, CVCHAR6, CVCHAR6 REGEXP '(ssssssss)+' from datatypetestm;
select cidx, CVCHAR6, CVCHAR6 REGEXP 'z$' from datatypetestm;
select cidx, CVCHAR6, CVCHAR6 REGEXP 'w*' from datatypetestm;
select cidx, CVCHAR6, CVCHAR6 REGEXP 'ww+w' from datatypetestm;
select cidx, CVCHAR6, CVCHAR6 REGEXP 'dd?d' from datatypetestm;
select cidx, CVCHAR7, CVCHAR7 REGEXP 'ssss$' from datatypetestm;
select cidx, CVCHAR7, CVCHAR7 REGEXP 'ggg$' from datatypetestm;
select cidx, CVCHAR7, CVCHAR7 REGEXP 'hhh$' from datatypetestm;
select cidx, CVCHAR7, CVCHAR7 REGEXP '(ttttttt)+' from datatypetestm;
select cidx, CVCHAR7, CVCHAR7 REGEXP '(ssssssss)+' from datatypetestm;
select cidx, CVCHAR7, CVCHAR7 REGEXP 'z$' from datatypetestm;
select cidx, CVCHAR7, CVCHAR7 REGEXP 'w*' from datatypetestm;
select cidx, CVCHAR7, CVCHAR7 REGEXP 'ww+w' from datatypetestm;
select cidx, CVCHAR7, CVCHAR7 REGEXP 'dd?d' from datatypetestm;
select cidx, CVCHAR8, CVCHAR8 REGEXP 'ssss$' from datatypetestm;
select cidx, CVCHAR8, CVCHAR8 REGEXP 'ggg$' from datatypetestm;
select cidx, CVCHAR8, CVCHAR8 REGEXP 'hhh$' from datatypetestm;
select cidx, CVCHAR8, CVCHAR8 REGEXP '(ttttttt)+' from datatypetestm;
select cidx, CVCHAR8, CVCHAR8 REGEXP '(ssssssss)+' from datatypetestm;
select cidx, CVCHAR8, CVCHAR8 REGEXP 'z$' from datatypetestm;
select cidx, CVCHAR8, CVCHAR8 REGEXP 'w*' from datatypetestm;
select cidx, CVCHAR8, CVCHAR8 REGEXP 'ww+w' from datatypetestm;
select cidx, CVCHAR8, CVCHAR8 REGEXP 'dd?d' from datatypetestm;
select cidx, CVCHAR255, CVCHAR255 REGEXP 'ssss$' from datatypetestm;
select cidx, CVCHAR255, CVCHAR255 REGEXP 'ggg$' from datatypetestm;
select cidx, CVCHAR255, CVCHAR255 REGEXP 'hhh$' from datatypetestm;
select cidx, CVCHAR255, CVCHAR255 REGEXP '(ttttttt)+' from datatypetestm;
select cidx, CVCHAR255, CVCHAR255 REGEXP '(ssssssss)+' from datatypetestm;
select cidx, CVCHAR255, CVCHAR255 REGEXP 'z$' from datatypetestm;
select cidx, CVCHAR255, CVCHAR255 REGEXP 'w*' from datatypetestm;
select cidx, CVCHAR255, CVCHAR255 REGEXP 'ww+w' from datatypetestm;
select cidx, CVCHAR255, CVCHAR255 REGEXP 'dd?d' from datatypetestm;
select cidx, CCHAR1 from datatypetestm where CCHAR1 REGEXP 'ssss$' <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where CCHAR1 REGEXP 'ggg$' <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where CCHAR1 REGEXP 'hhh$' <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where CCHAR1 REGEXP '(ttttttt)+' <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where CCHAR1 REGEXP '(ssssssss)+' <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where CCHAR1 REGEXP 'z$' <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where CCHAR1 REGEXP 'w*' <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where CCHAR1 REGEXP 'ww+w' <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where CCHAR1 REGEXP 'dd?d' <> CCHAR1;
select cidx, CCHAR2 from datatypetestm where CCHAR2 REGEXP 'ssss$' <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where CCHAR2 REGEXP 'ggg$' <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where CCHAR2 REGEXP 'hhh$' <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where CCHAR2 REGEXP '(ttttttt)+' <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where CCHAR2 REGEXP '(ssssssss)+' <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where CCHAR2 REGEXP 'z$' <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where CCHAR2 REGEXP 'w*' <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where CCHAR2 REGEXP 'ww+w' <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where CCHAR2 REGEXP 'dd?d' <> CCHAR2;
select cidx, CCHAR3 from datatypetestm where CCHAR3 REGEXP 'ssss$' <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where CCHAR3 REGEXP 'ggg$' <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where CCHAR3 REGEXP 'hhh$' <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where CCHAR3 REGEXP '(ttttttt)+' <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where CCHAR3 REGEXP '(ssssssss)+' <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where CCHAR3 REGEXP 'z$' <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where CCHAR3 REGEXP 'w*' <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where CCHAR3 REGEXP 'ww+w' <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where CCHAR3 REGEXP 'dd?d' <> CCHAR3;
select cidx, CCHAR4 from datatypetestm where CCHAR4 REGEXP 'ssss$' <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where CCHAR4 REGEXP 'ggg$' <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where CCHAR4 REGEXP 'hhh$' <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where CCHAR4 REGEXP '(ttttttt)+' <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where CCHAR4 REGEXP '(ssssssss)+' <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where CCHAR4 REGEXP 'z$' <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where CCHAR4 REGEXP 'w*' <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where CCHAR4 REGEXP 'ww+w' <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where CCHAR4 REGEXP 'dd?d' <> CCHAR4;
select cidx, CCHAR5 from datatypetestm where CCHAR5 REGEXP 'ssss$' <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where CCHAR5 REGEXP 'ggg$' <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where CCHAR5 REGEXP 'hhh$' <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where CCHAR5 REGEXP '(ttttttt)+' <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where CCHAR5 REGEXP '(ssssssss)+' <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where CCHAR5 REGEXP 'z$' <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where CCHAR5 REGEXP 'w*' <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where CCHAR5 REGEXP 'ww+w' <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where CCHAR5 REGEXP 'dd?d' <> CCHAR5;
select cidx, CCHAR6 from datatypetestm where CCHAR6 REGEXP 'ssss$' <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where CCHAR6 REGEXP 'ggg$' <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where CCHAR6 REGEXP 'hhh$' <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where CCHAR6 REGEXP '(ttttttt)+' <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where CCHAR6 REGEXP '(ssssssss)+' <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where CCHAR6 REGEXP 'z$' <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where CCHAR6 REGEXP 'w*' <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where CCHAR6 REGEXP 'ww+w' <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where CCHAR6 REGEXP 'dd?d' <> CCHAR6;
select cidx, CCHAR7 from datatypetestm where CCHAR7 REGEXP 'ssss$' <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where CCHAR7 REGEXP 'ggg$' <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where CCHAR7 REGEXP 'hhh$' <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where CCHAR7 REGEXP '(ttttttt)+' <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where CCHAR7 REGEXP '(ssssssss)+' <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where CCHAR7 REGEXP 'z$' <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where CCHAR7 REGEXP 'w*' <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where CCHAR7 REGEXP 'ww+w' <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where CCHAR7 REGEXP 'dd?d' <> CCHAR7;
select cidx, CCHAR8 from datatypetestm where CCHAR8 REGEXP 'ssss$' <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where CCHAR8 REGEXP 'ggg$' <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where CCHAR8 REGEXP 'hhh$' <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where CCHAR8 REGEXP '(ttttttt)+' <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where CCHAR8 REGEXP '(ssssssss)+' <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where CCHAR8 REGEXP 'z$' <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where CCHAR8 REGEXP 'w*' <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where CCHAR8 REGEXP 'ww+w' <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where CCHAR8 REGEXP 'dd?d' <> CCHAR8;
select cidx, CCHAR9 from datatypetestm where CCHAR9 REGEXP 'ssss$' <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where CCHAR9 REGEXP 'ggg$' <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where CCHAR9 REGEXP 'hhh$' <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where CCHAR9 REGEXP '(ttttttt)+' <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where CCHAR9 REGEXP '(ssssssss)+' <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where CCHAR9 REGEXP 'z$' <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where CCHAR9 REGEXP 'w*' <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where CCHAR9 REGEXP 'ww+w' <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where CCHAR9 REGEXP 'dd?d' <> CCHAR9;
select cidx, CCHAR255 from datatypetestm where CCHAR255 REGEXP 'ssss$' <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where CCHAR255 REGEXP 'ggg$' <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where CCHAR255 REGEXP 'hhh$' <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where CCHAR255 REGEXP '(ttttttt)+' <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where CCHAR255 REGEXP '(ssssssss)+' <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where CCHAR255 REGEXP 'z$' <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where CCHAR255 REGEXP 'w*' <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where CCHAR255 REGEXP 'ww+w' <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where CCHAR255 REGEXP 'dd?d' <> CCHAR255;
select cidx, CVCHAR1 from datatypetestm where CVCHAR1 REGEXP 'ssss$' <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where CVCHAR1 REGEXP 'ggg$' <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where CVCHAR1 REGEXP 'hhh$' <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where CVCHAR1 REGEXP '(ttttttt)+' <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where CVCHAR1 REGEXP '(ssssssss)+' <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where CVCHAR1 REGEXP 'z$' <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where CVCHAR1 REGEXP 'w*' <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where CVCHAR1 REGEXP 'ww+w' <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where CVCHAR1 REGEXP 'dd?d' <> CVCHAR1;
select cidx, CVCHAR2 from datatypetestm where CVCHAR2 REGEXP 'ssss$' <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where CVCHAR2 REGEXP 'ggg$' <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where CVCHAR2 REGEXP 'hhh$' <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where CVCHAR2 REGEXP '(ttttttt)+' <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where CVCHAR2 REGEXP '(ssssssss)+' <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where CVCHAR2 REGEXP 'z$' <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where CVCHAR2 REGEXP 'w*' <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where CVCHAR2 REGEXP 'ww+w' <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where CVCHAR2 REGEXP 'dd?d' <> CVCHAR2;
select cidx, CVCHAR3 from datatypetestm where CVCHAR3 REGEXP 'ssss$' <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where CVCHAR3 REGEXP 'ggg$' <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where CVCHAR3 REGEXP 'hhh$' <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where CVCHAR3 REGEXP '(ttttttt)+' <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where CVCHAR3 REGEXP '(ssssssss)+' <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where CVCHAR3 REGEXP 'z$' <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where CVCHAR3 REGEXP 'w*' <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where CVCHAR3 REGEXP 'ww+w' <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where CVCHAR3 REGEXP 'dd?d' <> CVCHAR3;
select cidx, CVCHAR4 from datatypetestm where CVCHAR4 REGEXP 'ssss$' <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where CVCHAR4 REGEXP 'ggg$' <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where CVCHAR4 REGEXP 'hhh$' <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where CVCHAR4 REGEXP '(ttttttt)+' <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where CVCHAR4 REGEXP '(ssssssss)+' <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where CVCHAR4 REGEXP 'z$' <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where CVCHAR4 REGEXP 'w*' <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where CVCHAR4 REGEXP 'ww+w' <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where CVCHAR4 REGEXP 'dd?d' <> CVCHAR4;
select cidx, CVCHAR5 from datatypetestm where CVCHAR5 REGEXP 'ssss$' <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where CVCHAR5 REGEXP 'ggg$' <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where CVCHAR5 REGEXP 'hhh$' <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where CVCHAR5 REGEXP '(ttttttt)+' <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where CVCHAR5 REGEXP '(ssssssss)+' <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where CVCHAR5 REGEXP 'z$' <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where CVCHAR5 REGEXP 'w*' <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where CVCHAR5 REGEXP 'ww+w' <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where CVCHAR5 REGEXP 'dd?d' <> CVCHAR5;
select cidx, CVCHAR6 from datatypetestm where CVCHAR6 REGEXP 'ssss$' <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where CVCHAR6 REGEXP 'ggg$' <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where CVCHAR6 REGEXP 'hhh$' <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where CVCHAR6 REGEXP '(ttttttt)+' <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where CVCHAR6 REGEXP '(ssssssss)+' <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where CVCHAR6 REGEXP 'z$' <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where CVCHAR6 REGEXP 'w*' <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where CVCHAR6 REGEXP 'ww+w' <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where CVCHAR6 REGEXP 'dd?d' <> CVCHAR6;
select cidx, CVCHAR7 from datatypetestm where CVCHAR7 REGEXP 'ssss$' <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where CVCHAR7 REGEXP 'ggg$' <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where CVCHAR7 REGEXP 'hhh$' <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where CVCHAR7 REGEXP '(ttttttt)+' <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where CVCHAR7 REGEXP '(ssssssss)+' <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where CVCHAR7 REGEXP 'z$' <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where CVCHAR7 REGEXP 'w*' <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where CVCHAR7 REGEXP 'ww+w' <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where CVCHAR7 REGEXP 'dd?d' <> CVCHAR7;
select cidx, CVCHAR8 from datatypetestm where CVCHAR8 REGEXP 'ssss$' <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where CVCHAR8 REGEXP 'ggg$' <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where CVCHAR8 REGEXP 'hhh$' <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where CVCHAR8 REGEXP '(ttttttt)+' <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where CVCHAR8 REGEXP '(ssssssss)+' <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where CVCHAR8 REGEXP 'z$' <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where CVCHAR8 REGEXP 'w*' <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where CVCHAR8 REGEXP 'ww+w' <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where CVCHAR8 REGEXP 'dd?d' <> CVCHAR8;
select cidx, CVCHAR255 from datatypetestm where CVCHAR255 REGEXP 'ssss$' <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where CVCHAR255 REGEXP 'ggg$' <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where CVCHAR255 REGEXP 'hhh$' <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where CVCHAR255 REGEXP '(ttttttt)+' <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where CVCHAR255 REGEXP '(ssssssss)+' <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where CVCHAR255 REGEXP 'z$' <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where CVCHAR255 REGEXP 'w*' <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where CVCHAR255 REGEXP 'ww+w' <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where CVCHAR255 REGEXP 'dd?d' <> CVCHAR255;
