select cidx, CBIGINT, ROUND(CBIGINT) from datatypetestm;
select cidx, CBIGINT, ROUND(CBIGINT,1) from datatypetestm;
select cidx, CBIGINT, ROUND(CBIGINT,2) from datatypetestm;
select cidx, CBIGINT, ROUND(CBIGINT,0) from datatypetestm;
select cidx, CBIGINT, ROUND(CBIGINT,-2) from datatypetestm;
select cidx, CBIGINT, ROUND(CBIGINT,-1) from datatypetestm;
select cidx, CDECIMAL1, ROUND(CDECIMAL1) from datatypetestm;
select cidx, CDECIMAL1, ROUND(CDECIMAL1,1) from datatypetestm;
select cidx, CDECIMAL1, ROUND(CDECIMAL1,2) from datatypetestm;
select cidx, CDECIMAL1, ROUND(CDECIMAL1,0) from datatypetestm;
select cidx, CDECIMAL1, ROUND(CDECIMAL1,-2) from datatypetestm;
-- Bug 2618.  Commented out query below.
-- select cidx, CDECIMAL1, ROUND(CDECIMAL1,-1) from datatypetestm;
select cidx, CDECIMAL4, ROUND(CDECIMAL4) from datatypetestm;
select cidx, CDECIMAL4, ROUND(CDECIMAL4,1) from datatypetestm;
select cidx, CDECIMAL4, ROUND(CDECIMAL4,2) from datatypetestm;
select cidx, CDECIMAL4, ROUND(CDECIMAL4,0) from datatypetestm;
select cidx, CDECIMAL4, ROUND(CDECIMAL4,-2) from datatypetestm;
select cidx, CDECIMAL4, ROUND(CDECIMAL4,-1) from datatypetestm;
select cidx, CDECIMAL4_2, ROUND(CDECIMAL4_2) from datatypetestm;
select cidx, CDECIMAL4_2, ROUND(CDECIMAL4_2,1) from datatypetestm;
select cidx, CDECIMAL4_2, ROUND(CDECIMAL4_2,2) from datatypetestm;
select cidx, CDECIMAL4_2, ROUND(CDECIMAL4_2,0) from datatypetestm;
select cidx, CDECIMAL4_2, ROUND(CDECIMAL4_2,-2) from datatypetestm;
select cidx, CDECIMAL4_2, ROUND(CDECIMAL4_2,-1) from datatypetestm;
select cidx, CDECIMAL5, ROUND(CDECIMAL5) from datatypetestm;
select cidx, CDECIMAL5, ROUND(CDECIMAL5,1) from datatypetestm;
select cidx, CDECIMAL5, ROUND(CDECIMAL5,2) from datatypetestm;
select cidx, CDECIMAL5, ROUND(CDECIMAL5,0) from datatypetestm;
select cidx, CDECIMAL5, ROUND(CDECIMAL5,-2) from datatypetestm;
select cidx, CDECIMAL5, ROUND(CDECIMAL5,-1) from datatypetestm;
select cidx, CDECIMAL9, ROUND(CDECIMAL9) from datatypetestm;
select cidx, CDECIMAL9, ROUND(CDECIMAL9,1) from datatypetestm;
select cidx, CDECIMAL9, ROUND(CDECIMAL9,2) from datatypetestm;
select cidx, CDECIMAL9, ROUND(CDECIMAL9,0) from datatypetestm;
select cidx, CDECIMAL9, ROUND(CDECIMAL9,-2) from datatypetestm;
select cidx, CDECIMAL9, ROUND(CDECIMAL9,-1) from datatypetestm;
select cidx, CDECIMAL9_2, ROUND(CDECIMAL9_2) from datatypetestm;
select cidx, CDECIMAL9_2, ROUND(CDECIMAL9_2,1) from datatypetestm;
select cidx, CDECIMAL9_2, ROUND(CDECIMAL9_2,2) from datatypetestm;
select cidx, CDECIMAL9_2, ROUND(CDECIMAL9_2,0) from datatypetestm;
select cidx, CDECIMAL9_2, ROUND(CDECIMAL9_2,-2) from datatypetestm;
select cidx, CDECIMAL9_2, ROUND(CDECIMAL9_2,-1) from datatypetestm;
select cidx, CDECIMAL10, ROUND(CDECIMAL10) from datatypetestm;
select cidx, CDECIMAL10, ROUND(CDECIMAL10,1) from datatypetestm;
select cidx, CDECIMAL10, ROUND(CDECIMAL10,2) from datatypetestm;
select cidx, CDECIMAL10, ROUND(CDECIMAL10,0) from datatypetestm;
select cidx, CDECIMAL10, ROUND(CDECIMAL10,-2) from datatypetestm;
select cidx, CDECIMAL10, ROUND(CDECIMAL10,-1) from datatypetestm;
select cidx, CDECIMAL18, ROUND(CDECIMAL18) from datatypetestm;
select cidx, CDECIMAL18, ROUND(CDECIMAL18,1) from datatypetestm;
select cidx, CDECIMAL18, ROUND(CDECIMAL18,2) from datatypetestm;
select cidx, CDECIMAL18, ROUND(CDECIMAL18,0) from datatypetestm;
select cidx, CDECIMAL18, ROUND(CDECIMAL18,-2) from datatypetestm;
select cidx, CDECIMAL18, ROUND(CDECIMAL18,-1) from datatypetestm;
select cidx, CDECIMAL18_2, ROUND(CDECIMAL18_2) from datatypetestm;
select cidx, CDECIMAL18_2, ROUND(CDECIMAL18_2,1) from datatypetestm;
select cidx, CDECIMAL18_2, ROUND(CDECIMAL18_2,2) from datatypetestm;
select cidx, CDECIMAL18_2, ROUND(CDECIMAL18_2,0) from datatypetestm;
select cidx, CDECIMAL18_2, ROUND(CDECIMAL18_2,-2) from datatypetestm;
select cidx, CDECIMAL18_2, ROUND(CDECIMAL18_2,-1) from datatypetestm;
select cidx, CINTEGER, ROUND(CINTEGER) from datatypetestm;
select cidx, CINTEGER, ROUND(CINTEGER,1) from datatypetestm;
select cidx, CINTEGER, ROUND(CINTEGER,2) from datatypetestm;
select cidx, CINTEGER, ROUND(CINTEGER,0) from datatypetestm;
select cidx, CINTEGER, ROUND(CINTEGER,-2) from datatypetestm;
select cidx, CINTEGER, ROUND(CINTEGER,-1) from datatypetestm;
select cidx, CSMALLINT, ROUND(CSMALLINT) from datatypetestm;
select cidx, CSMALLINT, ROUND(CSMALLINT,1) from datatypetestm;
select cidx, CSMALLINT, ROUND(CSMALLINT,2) from datatypetestm;
select cidx, CSMALLINT, ROUND(CSMALLINT,0) from datatypetestm;
select cidx, CSMALLINT, ROUND(CSMALLINT,-2) from datatypetestm;
select cidx, CSMALLINT, ROUND(CSMALLINT,-1) from datatypetestm;
select cidx, CTINYINT, ROUND(CTINYINT) from datatypetestm;
select cidx, CTINYINT, ROUND(CTINYINT,1) from datatypetestm;
select cidx, CTINYINT, ROUND(CTINYINT,2) from datatypetestm;
select cidx, CTINYINT, ROUND(CTINYINT,0) from datatypetestm;
select cidx, CTINYINT, ROUND(CTINYINT,-2) from datatypetestm;
select cidx, CTINYINT, ROUND(CTINYINT,-1) from datatypetestm;
select cidx, CBIGINT from datatypetestm order by ROUND(CBIGINT), cidx;
select cidx, CBIGINT from datatypetestm order by ROUND(CBIGINT,1), cidx;
select cidx, CBIGINT from datatypetestm order by ROUND(CBIGINT,2), cidx;
select cidx, CBIGINT from datatypetestm order by ROUND(CBIGINT,0), cidx;
select cidx, CBIGINT from datatypetestm order by ROUND(CBIGINT,-2), cidx;
select cidx, CBIGINT from datatypetestm order by ROUND(CBIGINT,-1), cidx;
select cidx, CDECIMAL1 from datatypetestm order by ROUND(CDECIMAL1), cidx;
select cidx, CDECIMAL1 from datatypetestm order by ROUND(CDECIMAL1,1), cidx;
select cidx, CDECIMAL1 from datatypetestm order by ROUND(CDECIMAL1,2), cidx;
select cidx, CDECIMAL1 from datatypetestm order by ROUND(CDECIMAL1,0), cidx;
select cidx, CDECIMAL1 from datatypetestm order by ROUND(CDECIMAL1,-2), cidx;
select cidx, CDECIMAL1 from datatypetestm order by ROUND(CDECIMAL1,-1), cidx;
select cidx, CDECIMAL4 from datatypetestm order by ROUND(CDECIMAL4), cidx;
select cidx, CDECIMAL4 from datatypetestm order by ROUND(CDECIMAL4,1), cidx;
select cidx, CDECIMAL4 from datatypetestm order by ROUND(CDECIMAL4,2), cidx;
select cidx, CDECIMAL4 from datatypetestm order by ROUND(CDECIMAL4,0), cidx;
select cidx, CDECIMAL4 from datatypetestm order by ROUND(CDECIMAL4,-2), cidx;
select cidx, CDECIMAL4 from datatypetestm order by ROUND(CDECIMAL4,-1), cidx;
select cidx, CDECIMAL4_2 from datatypetestm order by ROUND(CDECIMAL4_2), cidx;
select cidx, CDECIMAL4_2 from datatypetestm order by ROUND(CDECIMAL4_2,1), cidx;
select cidx, CDECIMAL4_2 from datatypetestm order by ROUND(CDECIMAL4_2,2), cidx;
select cidx, CDECIMAL4_2 from datatypetestm order by ROUND(CDECIMAL4_2,0), cidx;
select cidx, CDECIMAL4_2 from datatypetestm order by ROUND(CDECIMAL4_2,-2), cidx;
select cidx, CDECIMAL4_2 from datatypetestm order by ROUND(CDECIMAL4_2,-1), cidx;
select cidx, CDECIMAL5 from datatypetestm order by ROUND(CDECIMAL5), cidx;
select cidx, CDECIMAL5 from datatypetestm order by ROUND(CDECIMAL5,1), cidx;
select cidx, CDECIMAL5 from datatypetestm order by ROUND(CDECIMAL5,2), cidx;
select cidx, CDECIMAL5 from datatypetestm order by ROUND(CDECIMAL5,0), cidx;
select cidx, CDECIMAL5 from datatypetestm order by ROUND(CDECIMAL5,-2), cidx;
select cidx, CDECIMAL5 from datatypetestm order by ROUND(CDECIMAL5,-1), cidx;
select cidx, CDECIMAL9 from datatypetestm order by ROUND(CDECIMAL9), cidx;
select cidx, CDECIMAL9 from datatypetestm order by ROUND(CDECIMAL9,1), cidx;
select cidx, CDECIMAL9 from datatypetestm order by ROUND(CDECIMAL9,2), cidx;
select cidx, CDECIMAL9 from datatypetestm order by ROUND(CDECIMAL9,0), cidx;
select cidx, CDECIMAL9 from datatypetestm order by ROUND(CDECIMAL9,-2), cidx;
select cidx, CDECIMAL9 from datatypetestm order by ROUND(CDECIMAL9,-1), cidx;
select cidx, CDECIMAL9_2 from datatypetestm order by ROUND(CDECIMAL9_2), cidx;
select cidx, CDECIMAL9_2 from datatypetestm order by ROUND(CDECIMAL9_2,1), cidx;
select cidx, CDECIMAL9_2 from datatypetestm order by ROUND(CDECIMAL9_2,2), cidx;
select cidx, CDECIMAL9_2 from datatypetestm order by ROUND(CDECIMAL9_2,0), cidx;
select cidx, CDECIMAL9_2 from datatypetestm order by ROUND(CDECIMAL9_2,-2), cidx;
select cidx, CDECIMAL9_2 from datatypetestm order by ROUND(CDECIMAL9_2,-1), cidx;
select cidx, CDECIMAL10 from datatypetestm order by ROUND(CDECIMAL10), cidx;
select cidx, CDECIMAL10 from datatypetestm order by ROUND(CDECIMAL10,1), cidx;
select cidx, CDECIMAL10 from datatypetestm order by ROUND(CDECIMAL10,2), cidx;
select cidx, CDECIMAL10 from datatypetestm order by ROUND(CDECIMAL10,0), cidx;
select cidx, CDECIMAL10 from datatypetestm order by ROUND(CDECIMAL10,-2), cidx;
select cidx, CDECIMAL10 from datatypetestm order by ROUND(CDECIMAL10,-1), cidx;
select cidx, CDECIMAL18 from datatypetestm order by ROUND(CDECIMAL18), cidx;
select cidx, CDECIMAL18 from datatypetestm order by ROUND(CDECIMAL18,1), cidx;
select cidx, CDECIMAL18 from datatypetestm order by ROUND(CDECIMAL18,2), cidx;
select cidx, CDECIMAL18 from datatypetestm order by ROUND(CDECIMAL18,0), cidx;
select cidx, CDECIMAL18 from datatypetestm order by ROUND(CDECIMAL18,-2), cidx;
select cidx, CDECIMAL18 from datatypetestm order by ROUND(CDECIMAL18,-1), cidx;
select cidx, CDECIMAL18_2 from datatypetestm order by ROUND(CDECIMAL18_2), cidx;
select cidx, CDECIMAL18_2 from datatypetestm order by ROUND(CDECIMAL18_2,1), cidx;
select cidx, CDECIMAL18_2 from datatypetestm order by ROUND(CDECIMAL18_2,2), cidx;
select cidx, CDECIMAL18_2 from datatypetestm order by ROUND(CDECIMAL18_2,0), cidx;
select cidx, CDECIMAL18_2 from datatypetestm order by ROUND(CDECIMAL18_2,-2), cidx;
select cidx, CDECIMAL18_2 from datatypetestm order by ROUND(CDECIMAL18_2,-1), cidx;
select cidx, CINTEGER from datatypetestm order by ROUND(CINTEGER), cidx;
select cidx, CINTEGER from datatypetestm order by ROUND(CINTEGER,1), cidx;
select cidx, CINTEGER from datatypetestm order by ROUND(CINTEGER,2), cidx;
select cidx, CINTEGER from datatypetestm order by ROUND(CINTEGER,0), cidx;
select cidx, CINTEGER from datatypetestm order by ROUND(CINTEGER,-2), cidx;
select cidx, CINTEGER from datatypetestm order by ROUND(CINTEGER,-1), cidx;
select cidx, CSMALLINT from datatypetestm order by ROUND(CSMALLINT), cidx;
select cidx, CSMALLINT from datatypetestm order by ROUND(CSMALLINT,1), cidx;
select cidx, CSMALLINT from datatypetestm order by ROUND(CSMALLINT,2), cidx;
select cidx, CSMALLINT from datatypetestm order by ROUND(CSMALLINT,0), cidx;
select cidx, CSMALLINT from datatypetestm order by ROUND(CSMALLINT,-2), cidx;
select cidx, CSMALLINT from datatypetestm order by ROUND(CSMALLINT,-1), cidx;
select cidx, CTINYINT from datatypetestm order by ROUND(CTINYINT), cidx;
select cidx, CTINYINT from datatypetestm order by ROUND(CTINYINT,1), cidx;
select cidx, CTINYINT from datatypetestm order by ROUND(CTINYINT,2), cidx;
select cidx, CTINYINT from datatypetestm order by ROUND(CTINYINT,0), cidx;
select cidx, CTINYINT from datatypetestm order by ROUND(CTINYINT,-2), cidx;
select cidx, CTINYINT from datatypetestm order by ROUND(CTINYINT,-1), cidx;
