select cidx, CBIGINT, ROUND(CBIGINT) from datatypetestm;
select cidx, CBIGINT, ROUND(CBIGINT,1) from datatypetestm;
select cidx, CBIGINT, ROUND(CBIGINT,2) from datatypetestm;
select cidx, CBIGINT, ROUND(CBIGINT,0) from datatypetestm;
select cidx, CBIGINT, ROUND(CBIGINT,-2) from datatypetestm;
select cidx, CBIGINT, ROUND(CBIGINT,-1) from datatypetestm;
select cidx, CDECIMAL1, ROUND(CDECIMAL1) from datatypetestm;
select cidx, CDECIMAL1, ROUND(CDECIMAL1,1) from datatypetestm;
select cidx, CDECIMAL1, ROUND(CDECIMAL1,2) from datatypetestm;
select cidx, CDECIMAL1, ROUND(CDECIMAL1,0) from datatypetestm;
select cidx, CDECIMAL1, ROUND(CDECIMAL1,-2) from datatypetestm;
-- Bug 2618.  Commented out query below.
-- select cidx, CDECIMAL1, ROUND(CDECIMAL1,-1) from datatypetestm;
select cidx, CDECIMAL4, ROUND(CDECIMAL4) from datatypetestm;
select cidx, CDECIMAL4, ROUND(CDECIMAL4,1) from datatypetestm;
select cidx, CDECIMAL4, ROUND(CDECIMAL4,2) from datatypetestm;
select cidx, CDECIMAL4, ROUND(CDECIMAL4,0) from datatypetestm;
select cidx, CDECIMAL4, ROUND(CDECIMAL4,-2) from datatypetestm;
select cidx, CDECIMAL4, ROUND(CDECIMAL4,-1) from datatypetestm;
select cidx, CDECIMAL4_2, ROUND(CDECIMAL4_2) from datatypetestm;
select cidx, CDECIMAL4_2, ROUND(CDECIMAL4_2,1) from datatypetestm;
select cidx, CDECIMAL4_2, ROUND(CDECIMAL4_2,2) from datatypetestm;
select cidx, CDECIMAL4_2, ROUND(CDECIMAL4_2,0) from datatypetestm;
select cidx, CDECIMAL4_2, ROUND(CDECIMAL4_2,-2) from datatypetestm;
select cidx, CDECIMAL4_2, ROUND(CDECIMAL4_2,-1) from datatypetestm;
select cidx, CDECIMAL5, ROUND(CDECIMAL5) from datatypetestm;
select cidx, CDECIMAL5, ROUND(CDECIMAL5,1) from datatypetestm;
select cidx, CDECIMAL5, ROUND(CDECIMAL5,2) from datatypetestm;
select cidx, CDECIMAL5, ROUND(CDECIMAL5,0) from datatypetestm;
select cidx, CDECIMAL5, ROUND(CDECIMAL5,-2) from datatypetestm;
select cidx, CDECIMAL5, ROUND(CDECIMAL5,-1) from datatypetestm;
select cidx, CDECIMAL9, ROUND(CDECIMAL9) from datatypetestm;
select cidx, CDECIMAL9, ROUND(CDECIMAL9,1) from datatypetestm;
select cidx, CDECIMAL9, ROUND(CDECIMAL9,2) from datatypetestm;
select cidx, CDECIMAL9, ROUND(CDECIMAL9,0) from datatypetestm;
select cidx, CDECIMAL9, ROUND(CDECIMAL9,-2) from datatypetestm;
select cidx, CDECIMAL9, ROUND(CDECIMAL9,-1) from datatypetestm;
select cidx, CDECIMAL9_2, ROUND(CDECIMAL9_2) from datatypetestm;
select cidx, CDECIMAL9_2, ROUND(CDECIMAL9_2,1) from datatypetestm;
select cidx, CDECIMAL9_2, ROUND(CDECIMAL9_2,2) from datatypetestm;
select cidx, CDECIMAL9_2, ROUND(CDECIMAL9_2,0) from datatypetestm;
select cidx, CDECIMAL9_2, ROUND(CDECIMAL9_2,-2) from datatypetestm;
select cidx, CDECIMAL9_2, ROUND(CDECIMAL9_2,-1) from datatypetestm;
select cidx, CDECIMAL10, ROUND(CDECIMAL10) from datatypetestm;
select cidx, CDECIMAL10, ROUND(CDECIMAL10,1) from datatypetestm;
select cidx, CDECIMAL10, ROUND(CDECIMAL10,2) from datatypetestm;
select cidx, CDECIMAL10, ROUND(CDECIMAL10,0) from datatypetestm;
select cidx, CDECIMAL10, ROUND(CDECIMAL10,-2) from datatypetestm;
select cidx, CDECIMAL10, ROUND(CDECIMAL10,-1) from datatypetestm;
select cidx, CDECIMAL18, ROUND(CDECIMAL18) from datatypetestm;
select cidx, CDECIMAL18, ROUND(CDECIMAL18,1) from datatypetestm;
select cidx, CDECIMAL18, ROUND(CDECIMAL18,2) from datatypetestm;
select cidx, CDECIMAL18, ROUND(CDECIMAL18,0) from datatypetestm;
select cidx, CDECIMAL18, ROUND(CDECIMAL18,-2) from datatypetestm;
select cidx, CDECIMAL18, ROUND(CDECIMAL18,-1) from datatypetestm;
select cidx, CDECIMAL18_2, ROUND(CDECIMAL18_2) from datatypetestm;
select cidx, CDECIMAL18_2, ROUND(CDECIMAL18_2,1) from datatypetestm;
select cidx, CDECIMAL18_2, ROUND(CDECIMAL18_2,2) from datatypetestm;
select cidx, CDECIMAL18_2, ROUND(CDECIMAL18_2,0) from datatypetestm;
select cidx, CDECIMAL18_2, ROUND(CDECIMAL18_2,-2) from datatypetestm;
select cidx, CDECIMAL18_2, ROUND(CDECIMAL18_2,-1) from datatypetestm;
select cidx, CINTEGER, ROUND(CINTEGER) from datatypetestm;
select cidx, CINTEGER, ROUND(CINTEGER,1) from datatypetestm;
select cidx, CINTEGER, ROUND(CINTEGER,2) from datatypetestm;
select cidx, CINTEGER, ROUND(CINTEGER,0) from datatypetestm;
select cidx, CINTEGER, ROUND(CINTEGER,-2) from datatypetestm;
select cidx, CINTEGER, ROUND(CINTEGER,-1) from datatypetestm;
select cidx, CSMALLINT, ROUND(CSMALLINT) from datatypetestm;
select cidx, CSMALLINT, ROUND(CSMALLINT,1) from datatypetestm;
select cidx, CSMALLINT, ROUND(CSMALLINT,2) from datatypetestm;
select cidx, CSMALLINT, ROUND(CSMALLINT,0) from datatypetestm;
select cidx, CSMALLINT, ROUND(CSMALLINT,-2) from datatypetestm;
select cidx, CSMALLINT, ROUND(CSMALLINT,-1) from datatypetestm;
select cidx, CTINYINT, ROUND(CTINYINT) from datatypetestm;
select cidx, CTINYINT, ROUND(CTINYINT,1) from datatypetestm;
select cidx, CTINYINT, ROUND(CTINYINT,2) from datatypetestm;
select cidx, CTINYINT, ROUND(CTINYINT,0) from datatypetestm;
select cidx, CTINYINT, ROUND(CTINYINT,-2) from datatypetestm;
select cidx, CTINYINT, ROUND(CTINYINT,-1) from datatypetestm;
select cidx, CBIGINT from datatypetestm where ROUND(CBIGINT) <> CBIGINT;
select cidx, CBIGINT from datatypetestm where ROUND(CBIGINT,1) <> CBIGINT;
select cidx, CBIGINT from datatypetestm where ROUND(CBIGINT,2) <> CBIGINT;
select cidx, CBIGINT from datatypetestm where ROUND(CBIGINT,0) <> CBIGINT;
select cidx, CBIGINT from datatypetestm where ROUND(CBIGINT,-2) <> CBIGINT;
select cidx, CBIGINT from datatypetestm where ROUND(CBIGINT,-1) <> CBIGINT;
select cidx, CDECIMAL1 from datatypetestm where ROUND(CDECIMAL1) <> CDECIMAL1;
select cidx, CDECIMAL1 from datatypetestm where ROUND(CDECIMAL1,1) <> CDECIMAL1;
select cidx, CDECIMAL1 from datatypetestm where ROUND(CDECIMAL1,2) <> CDECIMAL1;
select cidx, CDECIMAL1 from datatypetestm where ROUND(CDECIMAL1,0) <> CDECIMAL1;
select cidx, CDECIMAL1 from datatypetestm where ROUND(CDECIMAL1,-2) <> CDECIMAL1;
select cidx, CDECIMAL1 from datatypetestm where ROUND(CDECIMAL1,-1) <> CDECIMAL1;
select cidx, CDECIMAL4 from datatypetestm where ROUND(CDECIMAL4) <> CDECIMAL4;
select cidx, CDECIMAL4 from datatypetestm where ROUND(CDECIMAL4,1) <> CDECIMAL4;
select cidx, CDECIMAL4 from datatypetestm where ROUND(CDECIMAL4,2) <> CDECIMAL4;
select cidx, CDECIMAL4 from datatypetestm where ROUND(CDECIMAL4,0) <> CDECIMAL4;
select cidx, CDECIMAL4 from datatypetestm where ROUND(CDECIMAL4,-2) <> CDECIMAL4;
select cidx, CDECIMAL4 from datatypetestm where ROUND(CDECIMAL4,-1) <> CDECIMAL4;
select cidx, CDECIMAL4_2 from datatypetestm where ROUND(CDECIMAL4_2) <> CDECIMAL4_2;
select cidx, CDECIMAL4_2 from datatypetestm where ROUND(CDECIMAL4_2,1) <> CDECIMAL4_2;
select cidx, CDECIMAL4_2 from datatypetestm where ROUND(CDECIMAL4_2,2) <> CDECIMAL4_2;
select cidx, CDECIMAL4_2 from datatypetestm where ROUND(CDECIMAL4_2,0) <> CDECIMAL4_2;
select cidx, CDECIMAL4_2 from datatypetestm where ROUND(CDECIMAL4_2,-2) <> CDECIMAL4_2;
select cidx, CDECIMAL4_2 from datatypetestm where ROUND(CDECIMAL4_2,-1) <> CDECIMAL4_2;
select cidx, CDECIMAL5 from datatypetestm where ROUND(CDECIMAL5) <> CDECIMAL5;
select cidx, CDECIMAL5 from datatypetestm where ROUND(CDECIMAL5,1) <> CDECIMAL5;
select cidx, CDECIMAL5 from datatypetestm where ROUND(CDECIMAL5,2) <> CDECIMAL5;
select cidx, CDECIMAL5 from datatypetestm where ROUND(CDECIMAL5,0) <> CDECIMAL5;
select cidx, CDECIMAL5 from datatypetestm where ROUND(CDECIMAL5,-2) <> CDECIMAL5;
select cidx, CDECIMAL5 from datatypetestm where ROUND(CDECIMAL5,-1) <> CDECIMAL5;
select cidx, CDECIMAL9 from datatypetestm where ROUND(CDECIMAL9) <> CDECIMAL9;
select cidx, CDECIMAL9 from datatypetestm where ROUND(CDECIMAL9,1) <> CDECIMAL9;
select cidx, CDECIMAL9 from datatypetestm where ROUND(CDECIMAL9,2) <> CDECIMAL9;
select cidx, CDECIMAL9 from datatypetestm where ROUND(CDECIMAL9,0) <> CDECIMAL9;
select cidx, CDECIMAL9 from datatypetestm where ROUND(CDECIMAL9,-2) <> CDECIMAL9;
select cidx, CDECIMAL9 from datatypetestm where ROUND(CDECIMAL9,-1) <> CDECIMAL9;
select cidx, CDECIMAL9_2 from datatypetestm where ROUND(CDECIMAL9_2) <> CDECIMAL9_2;
select cidx, CDECIMAL9_2 from datatypetestm where ROUND(CDECIMAL9_2,1) <> CDECIMAL9_2;
select cidx, CDECIMAL9_2 from datatypetestm where ROUND(CDECIMAL9_2,2) <> CDECIMAL9_2;
select cidx, CDECIMAL9_2 from datatypetestm where ROUND(CDECIMAL9_2,0) <> CDECIMAL9_2;
select cidx, CDECIMAL9_2 from datatypetestm where ROUND(CDECIMAL9_2,-2) <> CDECIMAL9_2;
select cidx, CDECIMAL9_2 from datatypetestm where ROUND(CDECIMAL9_2,-1) <> CDECIMAL9_2;
select cidx, CDECIMAL10 from datatypetestm where ROUND(CDECIMAL10) <> CDECIMAL10;
select cidx, CDECIMAL10 from datatypetestm where ROUND(CDECIMAL10,1) <> CDECIMAL10;
select cidx, CDECIMAL10 from datatypetestm where ROUND(CDECIMAL10,2) <> CDECIMAL10;
select cidx, CDECIMAL10 from datatypetestm where ROUND(CDECIMAL10,0) <> CDECIMAL10;
select cidx, CDECIMAL10 from datatypetestm where ROUND(CDECIMAL10,-2) <> CDECIMAL10;
select cidx, CDECIMAL10 from datatypetestm where ROUND(CDECIMAL10,-1) <> CDECIMAL10;
select cidx, CDECIMAL18 from datatypetestm where ROUND(CDECIMAL18) <> CDECIMAL18;
select cidx, CDECIMAL18 from datatypetestm where ROUND(CDECIMAL18,1) <> CDECIMAL18;
select cidx, CDECIMAL18 from datatypetestm where ROUND(CDECIMAL18,2) <> CDECIMAL18;
select cidx, CDECIMAL18 from datatypetestm where ROUND(CDECIMAL18,0) <> CDECIMAL18;
select cidx, CDECIMAL18 from datatypetestm where ROUND(CDECIMAL18,-2) <> CDECIMAL18;
select cidx, CDECIMAL18 from datatypetestm where ROUND(CDECIMAL18,-1) <> CDECIMAL18;
select cidx, CDECIMAL18_2 from datatypetestm where ROUND(CDECIMAL18_2) <> CDECIMAL18_2;
select cidx, CDECIMAL18_2 from datatypetestm where ROUND(CDECIMAL18_2,1) <> CDECIMAL18_2;
select cidx, CDECIMAL18_2 from datatypetestm where ROUND(CDECIMAL18_2,2) <> CDECIMAL18_2;
select cidx, CDECIMAL18_2 from datatypetestm where ROUND(CDECIMAL18_2,0) <> CDECIMAL18_2;
select cidx, CDECIMAL18_2 from datatypetestm where ROUND(CDECIMAL18_2,-2) <> CDECIMAL18_2;
select cidx, CDECIMAL18_2 from datatypetestm where ROUND(CDECIMAL18_2,-1) <> CDECIMAL18_2;
select cidx, CINTEGER from datatypetestm where ROUND(CINTEGER) <> CINTEGER;
select cidx, CINTEGER from datatypetestm where ROUND(CINTEGER,1) <> CINTEGER;
select cidx, CINTEGER from datatypetestm where ROUND(CINTEGER,2) <> CINTEGER;
select cidx, CINTEGER from datatypetestm where ROUND(CINTEGER,0) <> CINTEGER;
select cidx, CINTEGER from datatypetestm where ROUND(CINTEGER,-2) <> CINTEGER;
select cidx, CINTEGER from datatypetestm where ROUND(CINTEGER,-1) <> CINTEGER;
select cidx, CSMALLINT from datatypetestm where ROUND(CSMALLINT) <> CSMALLINT;
select cidx, CSMALLINT from datatypetestm where ROUND(CSMALLINT,1) <> CSMALLINT;
select cidx, CSMALLINT from datatypetestm where ROUND(CSMALLINT,2) <> CSMALLINT;
select cidx, CSMALLINT from datatypetestm where ROUND(CSMALLINT,0) <> CSMALLINT;
select cidx, CSMALLINT from datatypetestm where ROUND(CSMALLINT,-2) <> CSMALLINT;
select cidx, CSMALLINT from datatypetestm where ROUND(CSMALLINT,-1) <> CSMALLINT;
select cidx, CTINYINT from datatypetestm where ROUND(CTINYINT) <> CTINYINT;
select cidx, CTINYINT from datatypetestm where ROUND(CTINYINT,1) <> CTINYINT;
select cidx, CTINYINT from datatypetestm where ROUND(CTINYINT,2) <> CTINYINT;
select cidx, CTINYINT from datatypetestm where ROUND(CTINYINT,0) <> CTINYINT;
select cidx, CTINYINT from datatypetestm where ROUND(CTINYINT,-2) <> CTINYINT;
select cidx, CTINYINT from datatypetestm where ROUND(CTINYINT,-1) <> CTINYINT;
select cidx, CDATE, round(CDATE) from datatypetestm;
select cidx, CDATETIME, round(CDATETIME) from datatypetestm;
select cidx, CDATE, round(CDATE,4) from datatypetestm;
select cidx, CDATETIME, round(CDATETIME,4) from datatypetestm;
select cidx, CDATE, round(CDATE,-3) from datatypetestm;
select cidx, CDATETIME, round(CDATETIME,-3) from datatypetestm;
select cidx, CDATE, round(CDATE,0) from datatypetestm;
select cidx, CDATETIME, round(CDATETIME,0) from datatypetestm;
select cidx, CDATE, round(CDATE,10) from datatypetestm;
select cidx, CDATETIME, round(CDATETIME,10) from datatypetestm;
select * from datatypetestm where round(CDATETIME) < 20091232;
select * from datatypetestm where round(CDATE) < 20091232;
