select cidx, CCHAR1, RTRIM(CCHAR1) from datatypetestm;
select cidx, CCHAR2, RTRIM(CCHAR2) from datatypetestm;
select cidx, CCHAR3, RTRIM(CCHAR3) from datatypetestm;
select cidx, CCHAR4, RTRIM(CCHAR4) from datatypetestm;
select cidx, CCHAR5, RTRIM(CCHAR5) from datatypetestm;
select cidx, CCHAR6, RTRIM(CCHAR6) from datatypetestm;
select cidx, CCHAR7, RTRIM(CCHAR7) from datatypetestm;
select cidx, CCHAR8, RTRIM(CCHAR8) from datatypetestm;
select cidx, CCHAR9, RTRIM(CCHAR9) from datatypetestm;
select cidx, CCHAR255, RTRIM(CCHAR255) from datatypetestm;
select cidx, CVCHAR1, RTRIM(CVCHAR1) from datatypetestm;
select cidx, CVCHAR2, RTRIM(CVCHAR2) from datatypetestm;
select cidx, CVCHAR3, RTRIM(CVCHAR3) from datatypetestm;
select cidx, CVCHAR4, RTRIM(CVCHAR4) from datatypetestm;
select cidx, CVCHAR5, RTRIM(CVCHAR5) from datatypetestm;
select cidx, CVCHAR6, RTRIM(CVCHAR6) from datatypetestm;
select cidx, CVCHAR7, RTRIM(CVCHAR7) from datatypetestm;
select cidx, CVCHAR8, RTRIM(CVCHAR8) from datatypetestm;
select cidx, CVCHAR255, RTRIM(CVCHAR255) from datatypetestm;
select cidx, RTRIM('Hello ') from datatypetestm;
select cidx, RTRIM(' world') from datatypetestm;
select cidx, RTRIM(' Howzit ') from datatypetestm;
select cidx, CCHAR1 from datatypetestm where RTRIM(CCHAR1) <> CCHAR1;
select cidx, CCHAR2 from datatypetestm where RTRIM(CCHAR2) <> CCHAR2;
select cidx, CCHAR3 from datatypetestm where RTRIM(CCHAR3) <> CCHAR3;
select cidx, CCHAR4 from datatypetestm where RTRIM(CCHAR4) <> CCHAR4;
select cidx, CCHAR5 from datatypetestm where RTRIM(CCHAR5) <> CCHAR5;
select cidx, CCHAR6 from datatypetestm where RTRIM(CCHAR6) <> CCHAR6;
select cidx, CCHAR7 from datatypetestm where RTRIM(CCHAR7) <> CCHAR7;
select cidx, CCHAR8 from datatypetestm where RTRIM(CCHAR8) <> CCHAR8;
select cidx, CCHAR9 from datatypetestm where RTRIM(CCHAR9) <> CCHAR9;
select cidx, CCHAR255 from datatypetestm where RTRIM(CCHAR255) <> CCHAR255;
select cidx, CVCHAR1 from datatypetestm where RTRIM(CVCHAR1) <> CVCHAR1;
select cidx, CVCHAR2 from datatypetestm where RTRIM(CVCHAR2) <> CVCHAR2;
select cidx, CVCHAR3 from datatypetestm where RTRIM(CVCHAR3) <> CVCHAR3;
select cidx, CVCHAR4 from datatypetestm where RTRIM(CVCHAR4) <> CVCHAR4;
select cidx, CVCHAR5 from datatypetestm where RTRIM(CVCHAR5) <> CVCHAR5;
select cidx, CVCHAR6 from datatypetestm where RTRIM(CVCHAR6) <> CVCHAR6;
select cidx, CVCHAR7 from datatypetestm where RTRIM(CVCHAR7) <> CVCHAR7;
select cidx, CVCHAR8 from datatypetestm where RTRIM(CVCHAR8) <> CVCHAR8;
select cidx, CVCHAR255 from datatypetestm where RTRIM(CVCHAR255) <> CVCHAR255;
