select CIDX        , sha(CIDX         ) from datatypetestm;
select CBIGINT     , sha(CBIGINT      ) from datatypetestm;
select CDECIMAL1   , sha(CDECIMAL1    ) from datatypetestm;
select CDECIMAL4   , sha(CDECIMAL4    ) from datatypetestm;
select CDECIMAL4_2 , sha(CDECIMAL4_2  ) from datatypetestm;
select CDECIMAL5   , sha(CDECIMAL5    ) from datatypetestm;
select CDECIMAL9   , sha(CDECIMAL9    ) from datatypetestm;
select CDECIMAL9_2 , sha(CDECIMAL9_2  ) from datatypetestm;
select CDECIMAL10  , sha(CDECIMAL10   ) from datatypetestm;
select CDECIMAL18  , sha(CDECIMAL18   ) from datatypetestm;
select CDECIMAL18_2, sha(CDECIMAL18_2 ) from datatypetestm;
select CINTEGER    , sha(CINTEGER     ) from datatypetestm;
select CSMALLINT   , sha(CSMALLINT    ) from datatypetestm;
select CTINYINT    , sha(CTINYINT     ) from datatypetestm;
select CDATETIME   , sha(CDATETIME    ) from datatypetestm;
select CCHAR1      , sha(CCHAR1       ) from datatypetestm;
select CCHAR2      , sha(CCHAR2       ) from datatypetestm;
select CCHAR3      , sha(CCHAR3       ) from datatypetestm;
select CCHAR4      , sha(CCHAR4       ) from datatypetestm;
select CCHAR5      , sha(CCHAR5       ) from datatypetestm;
select CCHAR6      , sha(CCHAR6       ) from datatypetestm;
select CCHAR7      , sha(CCHAR7       ) from datatypetestm;
select CCHAR8      , sha(CCHAR8       ) from datatypetestm;
select CCHAR9      , sha(CCHAR9       ) from datatypetestm;
select CCHAR255    , sha(CCHAR255     ) from datatypetestm;
select CVCHAR1     , sha(CVCHAR1      ) from datatypetestm;
select CVCHAR2     , sha(CVCHAR2      ) from datatypetestm;
select CVCHAR3     , sha(CVCHAR3      ) from datatypetestm;
select CVCHAR4     , sha(CVCHAR4      ) from datatypetestm;
select CVCHAR5     , sha(CVCHAR5      ) from datatypetestm;
select CVCHAR6     , sha(CVCHAR6      ) from datatypetestm;
select CVCHAR7     , sha(CVCHAR7      ) from datatypetestm;
select CVCHAR8     , sha(CVCHAR8      ) from datatypetestm;
select CVCHAR255   , sha(CVCHAR255    ) from datatypetestm;
select * from region where sha1(r_name) = sha('ASIA');
select sha(r_name), count(*) from region group by 1 order by 1;
select * from region where substr(sha(r_comment), 1, 8) > sha('a');

