select cidx, CBIGINT, ACOS(CBIGINT) from datatypetestm;
select cidx, CDECIMAL1, ACOS(CDECIMAL1) from datatypetestm;
select cidx, CDECIMAL4, ACOS(CDECIMAL4) from datatypetestm;
select cidx, CDECIMAL4_2, ACOS(CDECIMAL4_2) from datatypetestm;
select cidx, CDECIMAL5, ACOS(CDECIMAL5) from datatypetestm;
select cidx, CDECIMAL9, ACOS(CDECIMAL9) from datatypetestm;
select cidx, CDECIMAL9_2, ACOS(CDECIMAL9_2) from datatypetestm;
select cidx, CDECIMAL10, ACOS(CDECIMAL10) from datatypetestm;
select cidx, CDECIMAL18, ACOS(CDECIMAL18) from datatypetestm;
select cidx, CDECIMAL18_2, ACOS(CDECIMAL18_2) from datatypetestm;
select cidx, CINTEGER, ACOS(CINTEGER) from datatypetestm;
select cidx, CSMALLINT, ACOS(CSMALLINT) from datatypetestm;
select cidx, CTINYINT, ACOS(CTINYINT) from datatypetestm;
select cidx, ACOS(0) from datatypetestm;
select cidx, ACOS(60) from datatypetestm;
select cidx, ACOS(90) from datatypetestm;
select cidx, ACOS(180) from datatypetestm;
select cidx, ACOS(360) from datatypetestm;
select cidx, CBIGINT from datatypetestm where ACOS(CBIGINT) <> 0;
select cidx, CDECIMAL1 from datatypetestm where ACOS(CDECIMAL1) <> 0;
select cidx, CDECIMAL4 from datatypetestm where ACOS(CDECIMAL4) <> 0;
select cidx, CDECIMAL4_2 from datatypetestm where ACOS(CDECIMAL4_2) <> 0;
select cidx, CDECIMAL5 from datatypetestm where ACOS(CDECIMAL5) <> 0;
select cidx, CDECIMAL9 from datatypetestm where ACOS(CDECIMAL9) <> 0;
select cidx, CDECIMAL9_2 from datatypetestm where ACOS(CDECIMAL9_2) <> 0;
select cidx, CDECIMAL10 from datatypetestm where ACOS(CDECIMAL10) <> 0;
select cidx, CDECIMAL18 from datatypetestm where ACOS(CDECIMAL18) <> 0;
select cidx, CDECIMAL18_2 from datatypetestm where ACOS(CDECIMAL18_2) <> 0;
select cidx, CINTEGER from datatypetestm where ACOS(CINTEGER) <> 0;
select cidx, CSMALLINT from datatypetestm where ACOS(CSMALLINT) <> 0;
select cidx, CTINYINT from datatypetestm where ACOS(CTINYINT) <> 0;
