select cidx, CBIGINT, SQRT(CBIGINT) from datatypetestm;
select cidx, CDECIMAL1, SQRT(CDECIMAL1) from datatypetestm;
select cidx, CDECIMAL4, SQRT(CDECIMAL4) from datatypetestm;
select cidx, CDECIMAL4_2, SQRT(CDECIMAL4_2) from datatypetestm;
select cidx, CDECIMAL5, SQRT(CDECIMAL5) from datatypetestm;
select cidx, CDECIMAL9, SQRT(CDECIMAL9) from datatypetestm;
select cidx, CDECIMAL9_2, SQRT(CDECIMAL9_2) from datatypetestm;
select cidx, CDECIMAL10, SQRT(CDECIMAL10) from datatypetestm;
select cidx, CDECIMAL18, SQRT(CDECIMAL18) from datatypetestm;
select cidx, CDECIMAL18_2, SQRT(CDECIMAL18_2) from datatypetestm;
select cidx, CINTEGER, SQRT(CINTEGER) from datatypetestm;
select cidx, CSMALLINT, SQRT(CSMALLINT) from datatypetestm;
select cidx, CTINYINT, SQRT(CTINYINT) from datatypetestm;
select cidx, SQRT(122) from datatypetestm;
select cidx, SQRT(324) from datatypetestm;
select cidx, SQRT(33) from datatypetestm;
select cidx, SQRT(54) from datatypetestm;
select cidx, SQRT(9) from datatypetestm;
select cidx, SQRT(81) from datatypetestm;
select cidx, SQRT(1) from datatypetestm;
select cidx, SQRT(4) from datatypetestm;
select cidx, SQRT(11.2) from datatypetestm;
select cidx, SQRT(39.457) from datatypetestm;
select cidx, SQRT(672.12) from datatypetestm;
select cidx, CBIGINT from datatypetestm where SQRT(CBIGINT) <> 0;;
select cidx, CDECIMAL1 from datatypetestm where SQRT(CDECIMAL1) <> 0;;
select cidx, CDECIMAL4 from datatypetestm where SQRT(CDECIMAL4) <> 0;;
select cidx, CDECIMAL4_2 from datatypetestm where SQRT(CDECIMAL4_2) <> 0;;
select cidx, CDECIMAL5 from datatypetestm where SQRT(CDECIMAL5) <> 0;;
select cidx, CDECIMAL9 from datatypetestm where SQRT(CDECIMAL9) <> 0;;
select cidx, CDECIMAL9_2 from datatypetestm where SQRT(CDECIMAL9_2) <> 0;;
select cidx, CDECIMAL10 from datatypetestm where SQRT(CDECIMAL10) <> 0;;
select cidx, CDECIMAL18 from datatypetestm where SQRT(CDECIMAL18) <> 0;;
select cidx, CDECIMAL18_2 from datatypetestm where SQRT(CDECIMAL18_2) <> 0;;
select cidx, CINTEGER from datatypetestm where SQRT(CINTEGER) <> 0;;
select cidx, CSMALLINT from datatypetestm where SQRT(CSMALLINT) <> 0;;
select cidx, CTINYINT from datatypetestm where SQRT(CTINYINT) <> 0;;
