select cidx, CDATE, STR_TO_DATE(DATE_FORMAT(CDATE,GET_FORMAT(DATE,'USA')), GET_FORMAT(DATE,'USA')) from datatypetestm order by cidx;
select cidx, CDATE, STR_TO_DATE(DATE_FORMAT(CDATE,GET_FORMAT(DATE,'JIS')), GET_FORMAT(DATE,'JIS')) from datatypetestm order by cidx;
select cidx, CDATE, STR_TO_DATE(DATE_FORMAT(CDATE,GET_FORMAT(DATE,'ISO')), GET_FORMAT(DATE,'ISO')) from datatypetestm order by cidx;
select cidx, CDATE, STR_TO_DATE(DATE_FORMAT(CDATE,GET_FORMAT(DATE,'EUR')), GET_FORMAT(DATE,'EUR')) from datatypetestm order by cidx;
select cidx, CDATE, STR_TO_DATE(DATE_FORMAT(CDATE,GET_FORMAT(DATE,'INTERNAL')), GET_FORMAT(DATE,'INTERNAL')) from datatypetestm order by cidx;
select cidx, CDATE, STR_TO_DATE(DATE_FORMAT(CDATE,GET_FORMAT(DATETIME,'USA')), GET_FORMAT(DATETIME,'USA')) from datatypetestm order by cidx;
select cidx, CDATE, STR_TO_DATE(DATE_FORMAT(CDATE,GET_FORMAT(DATETIME,'JIS')), GET_FORMAT(DATETIME,'JIS')) from datatypetestm order by cidx;
select cidx, CDATE, STR_TO_DATE(DATE_FORMAT(CDATE,GET_FORMAT(DATETIME,'ISO')), GET_FORMAT(DATETIME,'ISO')) from datatypetestm order by cidx;
select cidx, CDATE, STR_TO_DATE(DATE_FORMAT(CDATE,GET_FORMAT(DATETIME,'EUR')), GET_FORMAT(DATETIME,'EUR')) from datatypetestm order by cidx;
select cidx, CDATE, STR_TO_DATE(DATE_FORMAT(CDATE,GET_FORMAT(DATETIME,'INTERNAL')), GET_FORMAT(DATETIME,'INTERNAL')) from datatypetestm order by cidx;
select cidx, CDATE, STR_TO_DATE(DATE_FORMAT(CDATE,GET_FORMAT(TIME,'USA')), GET_FORMAT(TIME,'USA')) from datatypetestm order by cidx;
select cidx, CDATE, STR_TO_DATE(DATE_FORMAT(CDATE,GET_FORMAT(TIME,'JIS')), GET_FORMAT(TIME,'JIS')) from datatypetestm order by cidx;
select cidx, CDATE, STR_TO_DATE(DATE_FORMAT(CDATE,GET_FORMAT(TIME,'ISO')), GET_FORMAT(TIME,'ISO')) from datatypetestm order by cidx;
select cidx, CDATE, STR_TO_DATE(DATE_FORMAT(CDATE,GET_FORMAT(TIME,'EUR')), GET_FORMAT(TIME,'EUR')) from datatypetestm order by cidx;
select cidx, CDATE, STR_TO_DATE(DATE_FORMAT(CDATE,GET_FORMAT(TIME,'INTERNAL')), GET_FORMAT(TIME,'INTERNAL')) from datatypetestm order by cidx;
select cidx, CDATETIME, STR_TO_DATE(DATE_FORMAT(CDATETIME,GET_FORMAT(DATE,'USA')), GET_FORMAT(DATE,'USA')) from datatypetestm order by cidx;
select cidx, CDATETIME, STR_TO_DATE(DATE_FORMAT(CDATETIME,GET_FORMAT(DATE,'JIS')), GET_FORMAT(DATE,'JIS')) from datatypetestm order by cidx;
select cidx, CDATETIME, STR_TO_DATE(DATE_FORMAT(CDATETIME,GET_FORMAT(DATE,'ISO')), GET_FORMAT(DATE,'ISO')) from datatypetestm order by cidx;
select cidx, CDATETIME, STR_TO_DATE(DATE_FORMAT(CDATETIME,GET_FORMAT(DATE,'EUR')), GET_FORMAT(DATE,'EUR')) from datatypetestm order by cidx;
select cidx, CDATETIME, STR_TO_DATE(DATE_FORMAT(CDATETIME,GET_FORMAT(DATE,'INTERNAL')), GET_FORMAT(DATE,'INTERNAL')) from datatypetestm order by cidx;
select cidx, CDATETIME, STR_TO_DATE(DATE_FORMAT(CDATETIME,GET_FORMAT(DATETIME,'USA')), GET_FORMAT(DATETIME,'USA')) from datatypetestm order by cidx;
select cidx, CDATETIME, STR_TO_DATE(DATE_FORMAT(CDATETIME,GET_FORMAT(DATETIME,'JIS')), GET_FORMAT(DATETIME,'JIS')) from datatypetestm order by cidx;
select cidx, CDATETIME, STR_TO_DATE(DATE_FORMAT(CDATETIME,GET_FORMAT(DATETIME,'ISO')), GET_FORMAT(DATETIME,'ISO')) from datatypetestm order by cidx;
select cidx, CDATETIME, STR_TO_DATE(DATE_FORMAT(CDATETIME,GET_FORMAT(DATETIME,'EUR')), GET_FORMAT(DATETIME,'EUR')) from datatypetestm order by cidx;
select cidx, CDATETIME, STR_TO_DATE(DATE_FORMAT(CDATETIME,GET_FORMAT(DATETIME,'INTERNAL')), GET_FORMAT(DATETIME,'INTERNAL')) from datatypetestm order by cidx;
select cidx, CDATETIME, STR_TO_DATE(DATE_FORMAT(CDATETIME,GET_FORMAT(TIME,'USA')), GET_FORMAT(TIME,'USA')) from datatypetestm order by cidx;
select cidx, CDATETIME, STR_TO_DATE(DATE_FORMAT(CDATETIME,GET_FORMAT(TIME,'JIS')), GET_FORMAT(TIME,'JIS')) from datatypetestm order by cidx;
select cidx, CDATETIME, STR_TO_DATE(DATE_FORMAT(CDATETIME,GET_FORMAT(TIME,'ISO')), GET_FORMAT(TIME,'ISO')) from datatypetestm order by cidx;
select cidx, CDATETIME, STR_TO_DATE(DATE_FORMAT(CDATETIME,GET_FORMAT(TIME,'EUR')), GET_FORMAT(TIME,'EUR')) from datatypetestm order by cidx;
select cidx, CDATETIME, STR_TO_DATE(DATE_FORMAT(CDATETIME,GET_FORMAT(TIME,'INTERNAL')), GET_FORMAT(TIME,'INTERNAL')) from datatypetestm order by cidx;
select cidx, CDATE from datatypetestm where STR_TO_DATE(DATE_FORMAT(CDATE,GET_FORMAT(DATE,'USA')), GET_FORMAT(DATE,'USA')) <> CDATE order by cidx;
select cidx, CDATE from datatypetestm where STR_TO_DATE(DATE_FORMAT(CDATE,GET_FORMAT(DATE,'JIS')), GET_FORMAT(DATE,'JIS')) <> CDATE order by cidx;
select cidx, CDATE from datatypetestm where STR_TO_DATE(DATE_FORMAT(CDATE,GET_FORMAT(DATE,'ISO')), GET_FORMAT(DATE,'ISO')) <> CDATE order by cidx;
select cidx, CDATE from datatypetestm where STR_TO_DATE(DATE_FORMAT(CDATE,GET_FORMAT(DATE,'EUR')), GET_FORMAT(DATE,'EUR')) <> CDATE order by cidx;
select cidx, CDATE from datatypetestm where STR_TO_DATE(DATE_FORMAT(CDATE,GET_FORMAT(DATE,'INTERNAL')), GET_FORMAT(DATE,'INTERNAL')) <> CDATE order by cidx;
select cidx, CDATE from datatypetestm where STR_TO_DATE(DATE_FORMAT(CDATE,GET_FORMAT(DATETIME,'USA')), GET_FORMAT(DATETIME,'USA')) <> CDATE order by cidx;
select cidx, CDATE from datatypetestm where STR_TO_DATE(DATE_FORMAT(CDATE,GET_FORMAT(DATETIME,'JIS')), GET_FORMAT(DATETIME,'JIS')) <> CDATE order by cidx;
select cidx, CDATE from datatypetestm where STR_TO_DATE(DATE_FORMAT(CDATE,GET_FORMAT(DATETIME,'ISO')), GET_FORMAT(DATETIME,'ISO')) <> CDATE order by cidx;
select cidx, CDATE from datatypetestm where STR_TO_DATE(DATE_FORMAT(CDATE,GET_FORMAT(DATETIME,'EUR')), GET_FORMAT(DATETIME,'EUR')) <> CDATE order by cidx;
select cidx, CDATE from datatypetestm where STR_TO_DATE(DATE_FORMAT(CDATE,GET_FORMAT(DATETIME,'INTERNAL')), GET_FORMAT(DATETIME,'INTERNAL')) <> CDATE order by cidx;
select cidx, CDATE from datatypetestm where STR_TO_DATE(DATE_FORMAT(CDATE,GET_FORMAT(TIME,'USA')), GET_FORMAT(TIME,'USA')) <> CDATE order by cidx;
select cidx, CDATE from datatypetestm where STR_TO_DATE(DATE_FORMAT(CDATE,GET_FORMAT(TIME,'JIS')), GET_FORMAT(TIME,'JIS')) <> CDATE order by cidx;
select cidx, CDATE from datatypetestm where STR_TO_DATE(DATE_FORMAT(CDATE,GET_FORMAT(TIME,'ISO')), GET_FORMAT(TIME,'ISO')) <> CDATE order by cidx;
select cidx, CDATE from datatypetestm where STR_TO_DATE(DATE_FORMAT(CDATE,GET_FORMAT(TIME,'EUR')), GET_FORMAT(TIME,'EUR')) <> CDATE order by cidx;
select cidx, CDATE from datatypetestm where STR_TO_DATE(DATE_FORMAT(CDATE,GET_FORMAT(TIME,'INTERNAL')), GET_FORMAT(TIME,'INTERNAL')) <> CDATE order by cidx;
select cidx, CDATETIME from datatypetestm where STR_TO_DATE(DATE_FORMAT(CDATETIME,GET_FORMAT(DATE,'USA')), GET_FORMAT(DATE,'USA')) <> CDATETIME order by cidx;
select cidx, CDATETIME from datatypetestm where STR_TO_DATE(DATE_FORMAT(CDATETIME,GET_FORMAT(DATE,'JIS')), GET_FORMAT(DATE,'JIS')) <> CDATETIME order by cidx;
select cidx, CDATETIME from datatypetestm where STR_TO_DATE(DATE_FORMAT(CDATETIME,GET_FORMAT(DATE,'ISO')), GET_FORMAT(DATE,'ISO')) <> CDATETIME order by cidx;
select cidx, CDATETIME from datatypetestm where STR_TO_DATE(DATE_FORMAT(CDATETIME,GET_FORMAT(DATE,'EUR')), GET_FORMAT(DATE,'EUR')) <> CDATETIME order by cidx;
select cidx, CDATETIME from datatypetestm where STR_TO_DATE(DATE_FORMAT(CDATETIME,GET_FORMAT(DATE,'INTERNAL')), GET_FORMAT(DATE,'INTERNAL')) <> CDATETIME order by cidx;
select cidx, CDATETIME from datatypetestm where STR_TO_DATE(DATE_FORMAT(CDATETIME,GET_FORMAT(DATETIME,'USA')), GET_FORMAT(DATETIME,'USA')) <> CDATETIME order by cidx;
select cidx, CDATETIME from datatypetestm where STR_TO_DATE(DATE_FORMAT(CDATETIME,GET_FORMAT(DATETIME,'JIS')), GET_FORMAT(DATETIME,'JIS')) <> CDATETIME order by cidx;
select cidx, CDATETIME from datatypetestm where STR_TO_DATE(DATE_FORMAT(CDATETIME,GET_FORMAT(DATETIME,'ISO')), GET_FORMAT(DATETIME,'ISO')) <> CDATETIME order by cidx;
select cidx, CDATETIME from datatypetestm where STR_TO_DATE(DATE_FORMAT(CDATETIME,GET_FORMAT(DATETIME,'EUR')), GET_FORMAT(DATETIME,'EUR')) <> CDATETIME order by cidx;
select cidx, CDATETIME from datatypetestm where STR_TO_DATE(DATE_FORMAT(CDATETIME,GET_FORMAT(DATETIME,'INTERNAL')), GET_FORMAT(DATETIME,'INTERNAL')) <> CDATETIME order by cidx;
select cidx, CDATETIME from datatypetestm where STR_TO_DATE(DATE_FORMAT(CDATETIME,GET_FORMAT(TIME,'USA')), GET_FORMAT(TIME,'USA')) <> CDATETIME order by cidx;
select cidx, CDATETIME from datatypetestm where STR_TO_DATE(DATE_FORMAT(CDATETIME,GET_FORMAT(TIME,'JIS')), GET_FORMAT(TIME,'JIS')) <> CDATETIME order by cidx;
select cidx, CDATETIME from datatypetestm where STR_TO_DATE(DATE_FORMAT(CDATETIME,GET_FORMAT(TIME,'ISO')), GET_FORMAT(TIME,'ISO')) <> CDATETIME order by cidx;
select cidx, CDATETIME from datatypetestm where STR_TO_DATE(DATE_FORMAT(CDATETIME,GET_FORMAT(TIME,'EUR')), GET_FORMAT(TIME,'EUR')) <> CDATETIME order by cidx;
select cidx, CDATETIME from datatypetestm where STR_TO_DATE(DATE_FORMAT(CDATETIME,GET_FORMAT(TIME,'INTERNAL')), GET_FORMAT(TIME,'INTERNAL')) <> CDATETIME order by cidx;
