select cidx, CCHAR3, SUBSTRING_INDEX(CCHAR3,'z',-5) from datatypetestm order by cidx;
select substring_index(r_comment,'.',-5) from region;
select substring_index(r_comment,'.',-4) from region;
select substring_index(r_comment,'.',-3) from region;
select substring_index(r_comment,'.',-2) from region;
select substring_index(r_comment,'.',-1) from region;
select substring_index(r_comment,'.',0) from region;
select substring_index(r_comment,'.',1) from region;
select substring_index(r_comment,'.',2) from region;
select substring_index(r_comment,'.',3) from region;
select substring_index(r_comment,'.',4) from region;
select substring_index(r_comment,'.',5) from region;
select cidx, CCHAR3, SUBSTRING_INDEX(CCHAR3,'z',5) from datatypetestm;
select cidx, CCHAR3, SUBSTRING_INDEX(CCHAR3,'z',4) from datatypetestm;
select cidx, CCHAR3, SUBSTRING_INDEX(CCHAR3,'z',3) from datatypetestm;
select cidx, CCHAR3, SUBSTRING_INDEX(CCHAR3,'z',2) from datatypetestm;
select cidx, CCHAR3, SUBSTRING_INDEX(CCHAR3,'z',1) from datatypetestm;
select cidx, CCHAR3, SUBSTRING_INDEX(CCHAR3,'z',0) from datatypetestm;
select cidx, CCHAR3, SUBSTRING_INDEX(CCHAR3,'z',-1) from datatypetestm;
select cidx, CCHAR3, SUBSTRING_INDEX(CCHAR3,'z',-2) from datatypetestm;
select cidx, CCHAR3, SUBSTRING_INDEX(CCHAR3,'z',-3) from datatypetestm;
select cidx, CCHAR3, SUBSTRING_INDEX(CCHAR3,'z',-5) from datatypetestm;
select r_comment from region where substring_index(r_comment,'.',1) = "ges";
SELECT SUBSTRING_INDEX('www.mysql.com', '.', 2);
SELECT SUBSTRING_INDEX('www.mysql.com', '.', -2);

