select cidx, CCHAR1, TRIM(CCHAR1) from datatypetestm;
select cidx, CCHAR2, TRIM(CCHAR2) from datatypetestm;
select cidx, CCHAR3, TRIM(CCHAR3) from datatypetestm;
select cidx, CCHAR4, TRIM(CCHAR4) from datatypetestm;
select cidx, CCHAR5, TRIM(CCHAR5) from datatypetestm;
select cidx, CCHAR6, TRIM(CCHAR6) from datatypetestm;
select cidx, CCHAR7, TRIM(CCHAR7) from datatypetestm;
select cidx, CCHAR8, TRIM(CCHAR8) from datatypetestm;
select cidx, CCHAR9, TRIM(CCHAR9) from datatypetestm;
select cidx, CCHAR255, TRIM(CCHAR255) from datatypetestm;
select cidx, CVCHAR1, TRIM(CVCHAR1) from datatypetestm;
select cidx, CVCHAR2, TRIM(CVCHAR2) from datatypetestm;
select cidx, CVCHAR3, TRIM(CVCHAR3) from datatypetestm;
select cidx, CVCHAR4, TRIM(CVCHAR4) from datatypetestm;
select cidx, CVCHAR5, TRIM(CVCHAR5) from datatypetestm;
select cidx, CVCHAR6, TRIM(CVCHAR6) from datatypetestm;
select cidx, CVCHAR7, TRIM(CVCHAR7) from datatypetestm;
select cidx, CVCHAR8, TRIM(CVCHAR8) from datatypetestm;
select cidx, CVCHAR255, TRIM(CVCHAR255) from datatypetestm;
select cidx, TRIM('Hello ') from datatypetestm;
select cidx, TRIM(' world') from datatypetestm;
select cidx, TRIM(' Howzit ') from datatypetestm;
select cidx, CCHAR1 from datatypetestm where TRIM(CCHAR1) <> CCHAR1;
select cidx, CCHAR2 from datatypetestm where TRIM(CCHAR2) <> CCHAR2;
select cidx, CCHAR3 from datatypetestm where TRIM(CCHAR3) <> CCHAR3;
select cidx, CCHAR4 from datatypetestm where TRIM(CCHAR4) <> CCHAR4;
select cidx, CCHAR5 from datatypetestm where TRIM(CCHAR5) <> CCHAR5;
select cidx, CCHAR6 from datatypetestm where TRIM(CCHAR6) <> CCHAR6;
select cidx, CCHAR7 from datatypetestm where TRIM(CCHAR7) <> CCHAR7;
select cidx, CCHAR8 from datatypetestm where TRIM(CCHAR8) <> CCHAR8;
select cidx, CCHAR9 from datatypetestm where TRIM(CCHAR9) <> CCHAR9;
select cidx, CCHAR255 from datatypetestm where TRIM(CCHAR255) <> CCHAR255;
select cidx, CVCHAR1 from datatypetestm where TRIM(CVCHAR1) <> CVCHAR1;
select cidx, CVCHAR2 from datatypetestm where TRIM(CVCHAR2) <> CVCHAR2;
select cidx, CVCHAR3 from datatypetestm where TRIM(CVCHAR3) <> CVCHAR3;
select cidx, CVCHAR4 from datatypetestm where TRIM(CVCHAR4) <> CVCHAR4;
select cidx, CVCHAR5 from datatypetestm where TRIM(CVCHAR5) <> CVCHAR5;
select cidx, CVCHAR6 from datatypetestm where TRIM(CVCHAR6) <> CVCHAR6;
select cidx, CVCHAR7 from datatypetestm where TRIM(CVCHAR7) <> CVCHAR7;
select cidx, CVCHAR8 from datatypetestm where TRIM(CVCHAR8) <> CVCHAR8;
select cidx, CVCHAR255 from datatypetestm where TRIM(CVCHAR255) <> CVCHAR255;
