select cidx, CDATE, YEARWEEK(CDATE,0) from datatypetestm;
select cidx, CDATE, YEARWEEK(CDATE,1) from datatypetestm;
select cidx, CDATE, YEARWEEK(CDATE,2) from datatypetestm;
select cidx, CDATE, YEARWEEK(CDATE,3) from datatypetestm;
select cidx, CDATE, YEARWEEK(CDATE,4) from datatypetestm;
select cidx, CDATE, YEARWEEK(CDATE,5) from datatypetestm;
select cidx, CDATE, YEARWEEK(CDATE,6) from datatypetestm;
select cidx, CDATE, YEARWEEK(CDATE,7) from datatypetestm;
select cidx, CDATETIME, YEARWEEK(CDATETIME,0) from datatypetestm;
select cidx, CDATETIME, YEARWEEK(CDATETIME,1) from datatypetestm;
select cidx, CDATETIME, YEARWEEK(CDATETIME,2) from datatypetestm;
select cidx, CDATETIME, YEARWEEK(CDATETIME,3) from datatypetestm;
select cidx, CDATETIME, YEARWEEK(CDATETIME,4) from datatypetestm;
select cidx, CDATETIME, YEARWEEK(CDATETIME,5) from datatypetestm;
select cidx, CDATETIME, YEARWEEK(CDATETIME,6) from datatypetestm;
select cidx, CDATETIME, YEARWEEK(CDATETIME,7) from datatypetestm;
select cidx, CDATE from datatypetestm where YEARWEEK(CDATE,0) <> CDATE;
select cidx, CDATE from datatypetestm where YEARWEEK(CDATE,1) <> CDATE;
select cidx, CDATE from datatypetestm where YEARWEEK(CDATE,2) <> CDATE;
select cidx, CDATE from datatypetestm where YEARWEEK(CDATE,3) <> CDATE;
select cidx, CDATE from datatypetestm where YEARWEEK(CDATE,4) <> CDATE;
select cidx, CDATE from datatypetestm where YEARWEEK(CDATE,5) <> CDATE;
select cidx, CDATE from datatypetestm where YEARWEEK(CDATE,6) <> CDATE;
select cidx, CDATE from datatypetestm where YEARWEEK(CDATE,7) <> CDATE;
select cidx, CDATETIME from datatypetestm where YEARWEEK(CDATETIME,0) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where YEARWEEK(CDATETIME,1) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where YEARWEEK(CDATETIME,2) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where YEARWEEK(CDATETIME,3) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where YEARWEEK(CDATETIME,4) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where YEARWEEK(CDATETIME,5) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where YEARWEEK(CDATETIME,6) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where YEARWEEK(CDATETIME,7) <> CDATETIME;
