select cidx, CCHAR1, INSTR(CCHAR1,'aaa') from datatypetestm;
select cidx, CCHAR1, INSTR(CCHAR1,'zz') from datatypetestm;
select cidx, CCHAR1, INSTR(CCHAR1,'aaaaaaaaaaaa') from datatypetestm;
select cidx, CCHAR1, INSTR(CCHAR1,'zzzzzzzzzzzzzz') from datatypetestm;
select cidx, CCHAR2, INSTR(CCHAR2,'aaa') from datatypetestm;
select cidx, CCHAR2, INSTR(CCHAR2,'zz') from datatypetestm;
select cidx, CCHAR2, INSTR(CCHAR2,'aaaaaaaaaaaa') from datatypetestm;
select cidx, CCHAR2, INSTR(CCHAR2,'zzzzzzzzzzzzzz') from datatypetestm;
select cidx, CCHAR3, INSTR(CCHAR3,'aaa') from datatypetestm;
select cidx, CCHAR3, INSTR(CCHAR3,'zz') from datatypetestm;
select cidx, CCHAR3, INSTR(CCHAR3,'aaaaaaaaaaaa') from datatypetestm;
select cidx, CCHAR3, INSTR(CCHAR3,'zzzzzzzzzzzzzz') from datatypetestm;
select cidx, CCHAR4, INSTR(CCHAR4,'aaa') from datatypetestm;
select cidx, CCHAR4, INSTR(CCHAR4,'zz') from datatypetestm;
select cidx, CCHAR4, INSTR(CCHAR4,'aaaaaaaaaaaa') from datatypetestm;
select cidx, CCHAR4, INSTR(CCHAR4,'zzzzzzzzzzzzzz') from datatypetestm;
select cidx, CCHAR5, INSTR(CCHAR5,'aaa') from datatypetestm;
select cidx, CCHAR5, INSTR(CCHAR5,'zz') from datatypetestm;
select cidx, CCHAR5, INSTR(CCHAR5,'aaaaaaaaaaaa') from datatypetestm;
select cidx, CCHAR5, INSTR(CCHAR5,'zzzzzzzzzzzzzz') from datatypetestm;
select cidx, CCHAR6, INSTR(CCHAR6,'aaa') from datatypetestm;
select cidx, CCHAR6, INSTR(CCHAR6,'zz') from datatypetestm;
select cidx, CCHAR6, INSTR(CCHAR6,'aaaaaaaaaaaa') from datatypetestm;
select cidx, CCHAR6, INSTR(CCHAR6,'zzzzzzzzzzzzzz') from datatypetestm;
select cidx, CCHAR7, INSTR(CCHAR7,'aaa') from datatypetestm;
select cidx, CCHAR7, INSTR(CCHAR7,'zz') from datatypetestm;
select cidx, CCHAR7, INSTR(CCHAR7,'aaaaaaaaaaaa') from datatypetestm;
select cidx, CCHAR7, INSTR(CCHAR7,'zzzzzzzzzzzzzz') from datatypetestm;
select cidx, CCHAR8, INSTR(CCHAR8,'aaa') from datatypetestm;
select cidx, CCHAR8, INSTR(CCHAR8,'zz') from datatypetestm;
select cidx, CCHAR8, INSTR(CCHAR8,'aaaaaaaaaaaa') from datatypetestm;
select cidx, CCHAR8, INSTR(CCHAR8,'zzzzzzzzzzzzzz') from datatypetestm;
select cidx, CCHAR9, INSTR(CCHAR9,'aaa') from datatypetestm;
select cidx, CCHAR9, INSTR(CCHAR9,'zz') from datatypetestm;
select cidx, CCHAR9, INSTR(CCHAR9,'aaaaaaaaaaaa') from datatypetestm;
select cidx, CCHAR9, INSTR(CCHAR9,'zzzzzzzzzzzzzz') from datatypetestm;
select cidx, CCHAR255, INSTR(CCHAR255,'aaa') from datatypetestm;
select cidx, CCHAR255, INSTR(CCHAR255,'zz') from datatypetestm;
select cidx, CCHAR255, INSTR(CCHAR255,'aaaaaaaaaaaa') from datatypetestm;
select cidx, CCHAR255, INSTR(CCHAR255,'zzzzzzzzzzzzzz') from datatypetestm;
select cidx, CVCHAR1, INSTR(CVCHAR1,'aaa') from datatypetestm;
select cidx, CVCHAR1, INSTR(CVCHAR1,'zz') from datatypetestm;
select cidx, CVCHAR1, INSTR(CVCHAR1,'aaaaaaaaaaaa') from datatypetestm;
select cidx, CVCHAR1, INSTR(CVCHAR1,'zzzzzzzzzzzzzz') from datatypetestm;
select cidx, CVCHAR2, INSTR(CVCHAR2,'aaa') from datatypetestm;
select cidx, CVCHAR2, INSTR(CVCHAR2,'zz') from datatypetestm;
select cidx, CVCHAR2, INSTR(CVCHAR2,'aaaaaaaaaaaa') from datatypetestm;
select cidx, CVCHAR2, INSTR(CVCHAR2,'zzzzzzzzzzzzzz') from datatypetestm;
select cidx, CVCHAR3, INSTR(CVCHAR3,'aaa') from datatypetestm;
select cidx, CVCHAR3, INSTR(CVCHAR3,'zz') from datatypetestm;
select cidx, CVCHAR3, INSTR(CVCHAR3,'aaaaaaaaaaaa') from datatypetestm;
select cidx, CVCHAR3, INSTR(CVCHAR3,'zzzzzzzzzzzzzz') from datatypetestm;
select cidx, CVCHAR4, INSTR(CVCHAR4,'aaa') from datatypetestm;
select cidx, CVCHAR4, INSTR(CVCHAR4,'zz') from datatypetestm;
select cidx, CVCHAR4, INSTR(CVCHAR4,'aaaaaaaaaaaa') from datatypetestm;
select cidx, CVCHAR4, INSTR(CVCHAR4,'zzzzzzzzzzzzzz') from datatypetestm;
select cidx, CVCHAR5, INSTR(CVCHAR5,'aaa') from datatypetestm;
select cidx, CVCHAR5, INSTR(CVCHAR5,'zz') from datatypetestm;
select cidx, CVCHAR5, INSTR(CVCHAR5,'aaaaaaaaaaaa') from datatypetestm;
select cidx, CVCHAR5, INSTR(CVCHAR5,'zzzzzzzzzzzzzz') from datatypetestm;
select cidx, CVCHAR6, INSTR(CVCHAR6,'aaa') from datatypetestm;
select cidx, CVCHAR6, INSTR(CVCHAR6,'zz') from datatypetestm;
select cidx, CVCHAR6, INSTR(CVCHAR6,'aaaaaaaaaaaa') from datatypetestm;
select cidx, CVCHAR6, INSTR(CVCHAR6,'zzzzzzzzzzzzzz') from datatypetestm;
select cidx, CVCHAR7, INSTR(CVCHAR7,'aaa') from datatypetestm;
select cidx, CVCHAR7, INSTR(CVCHAR7,'zz') from datatypetestm;
select cidx, CVCHAR7, INSTR(CVCHAR7,'aaaaaaaaaaaa') from datatypetestm;
select cidx, CVCHAR7, INSTR(CVCHAR7,'zzzzzzzzzzzzzz') from datatypetestm;
select cidx, CVCHAR8, INSTR(CVCHAR8,'aaa') from datatypetestm;
select cidx, CVCHAR8, INSTR(CVCHAR8,'zz') from datatypetestm;
select cidx, CVCHAR8, INSTR(CVCHAR8,'aaaaaaaaaaaa') from datatypetestm;
select cidx, CVCHAR8, INSTR(CVCHAR8,'zzzzzzzzzzzzzz') from datatypetestm;
select cidx, CVCHAR255, INSTR(CVCHAR255,'aaa') from datatypetestm;
select cidx, CVCHAR255, INSTR(CVCHAR255,'zz') from datatypetestm;
select cidx, CVCHAR255, INSTR(CVCHAR255,'aaaaaaaaaaaa') from datatypetestm;
select cidx, CVCHAR255, INSTR(CVCHAR255,'zzzzzzzzzzzzzz') from datatypetestm;
select cidx, CCHAR1 from datatypetestm where INSTR(CCHAR1,'aaa') <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where INSTR(CCHAR1,'zz') <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where INSTR(CCHAR1,'aaaaaaaaaaaa') <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where INSTR(CCHAR1,'zzzzzzzzzzzzzz') <> CCHAR1;
select cidx, CCHAR2 from datatypetestm where INSTR(CCHAR2,'aaa') <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where INSTR(CCHAR2,'zz') <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where INSTR(CCHAR2,'aaaaaaaaaaaa') <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where INSTR(CCHAR2,'zzzzzzzzzzzzzz') <> CCHAR2;
select cidx, CCHAR3 from datatypetestm where INSTR(CCHAR3,'aaa') <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where INSTR(CCHAR3,'zz') <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where INSTR(CCHAR3,'aaaaaaaaaaaa') <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where INSTR(CCHAR3,'zzzzzzzzzzzzzz') <> CCHAR3;
select cidx, CCHAR4 from datatypetestm where INSTR(CCHAR4,'aaa') <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where INSTR(CCHAR4,'zz') <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where INSTR(CCHAR4,'aaaaaaaaaaaa') <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where INSTR(CCHAR4,'zzzzzzzzzzzzzz') <> CCHAR4;
select cidx, CCHAR5 from datatypetestm where INSTR(CCHAR5,'aaa') <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where INSTR(CCHAR5,'zz') <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where INSTR(CCHAR5,'aaaaaaaaaaaa') <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where INSTR(CCHAR5,'zzzzzzzzzzzzzz') <> CCHAR5;
select cidx, CCHAR6 from datatypetestm where INSTR(CCHAR6,'aaa') <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where INSTR(CCHAR6,'zz') <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where INSTR(CCHAR6,'aaaaaaaaaaaa') <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where INSTR(CCHAR6,'zzzzzzzzzzzzzz') <> CCHAR6;
select cidx, CCHAR7 from datatypetestm where INSTR(CCHAR7,'aaa') <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where INSTR(CCHAR7,'zz') <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where INSTR(CCHAR7,'aaaaaaaaaaaa') <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where INSTR(CCHAR7,'zzzzzzzzzzzzzz') <> CCHAR7;
select cidx, CCHAR8 from datatypetestm where INSTR(CCHAR8,'aaa') <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where INSTR(CCHAR8,'zz') <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where INSTR(CCHAR8,'aaaaaaaaaaaa') <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where INSTR(CCHAR8,'zzzzzzzzzzzzzz') <> CCHAR8;
select cidx, CCHAR9 from datatypetestm where INSTR(CCHAR9,'aaa') <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where INSTR(CCHAR9,'zz') <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where INSTR(CCHAR9,'aaaaaaaaaaaa') <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where INSTR(CCHAR9,'zzzzzzzzzzzzzz') <> CCHAR9;
select cidx, CCHAR255 from datatypetestm where INSTR(CCHAR255,'aaa') <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where INSTR(CCHAR255,'zz') <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where INSTR(CCHAR255,'aaaaaaaaaaaa') <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where INSTR(CCHAR255,'zzzzzzzzzzzzzz') <> CCHAR255;
select cidx, CVCHAR1 from datatypetestm where INSTR(CVCHAR1,'aaa') <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where INSTR(CVCHAR1,'zz') <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where INSTR(CVCHAR1,'aaaaaaaaaaaa') <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where INSTR(CVCHAR1,'zzzzzzzzzzzzzz') <> CVCHAR1;
select cidx, CVCHAR2 from datatypetestm where INSTR(CVCHAR2,'aaa') <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where INSTR(CVCHAR2,'zz') <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where INSTR(CVCHAR2,'aaaaaaaaaaaa') <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where INSTR(CVCHAR2,'zzzzzzzzzzzzzz') <> CVCHAR2;
select cidx, CVCHAR3 from datatypetestm where INSTR(CVCHAR3,'aaa') <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where INSTR(CVCHAR3,'zz') <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where INSTR(CVCHAR3,'aaaaaaaaaaaa') <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where INSTR(CVCHAR3,'zzzzzzzzzzzzzz') <> CVCHAR3;
select cidx, CVCHAR4 from datatypetestm where INSTR(CVCHAR4,'aaa') <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where INSTR(CVCHAR4,'zz') <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where INSTR(CVCHAR4,'aaaaaaaaaaaa') <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where INSTR(CVCHAR4,'zzzzzzzzzzzzzz') <> CVCHAR4;
select cidx, CVCHAR5 from datatypetestm where INSTR(CVCHAR5,'aaa') <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where INSTR(CVCHAR5,'zz') <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where INSTR(CVCHAR5,'aaaaaaaaaaaa') <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where INSTR(CVCHAR5,'zzzzzzzzzzzzzz') <> CVCHAR5;
select cidx, CVCHAR6 from datatypetestm where INSTR(CVCHAR6,'aaa') <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where INSTR(CVCHAR6,'zz') <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where INSTR(CVCHAR6,'aaaaaaaaaaaa') <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where INSTR(CVCHAR6,'zzzzzzzzzzzzzz') <> CVCHAR6;
select cidx, CVCHAR7 from datatypetestm where INSTR(CVCHAR7,'aaa') <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where INSTR(CVCHAR7,'zz') <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where INSTR(CVCHAR7,'aaaaaaaaaaaa') <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where INSTR(CVCHAR7,'zzzzzzzzzzzzzz') <> CVCHAR7;
select cidx, CVCHAR8 from datatypetestm where INSTR(CVCHAR8,'aaa') <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where INSTR(CVCHAR8,'zz') <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where INSTR(CVCHAR8,'aaaaaaaaaaaa') <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where INSTR(CVCHAR8,'zzzzzzzzzzzzzz') <> CVCHAR8;
select cidx, CVCHAR255 from datatypetestm where INSTR(CVCHAR255,'aaa') <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where INSTR(CVCHAR255,'zz') <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where INSTR(CVCHAR255,'aaaaaaaaaaaa') <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where INSTR(CVCHAR255,'zzzzzzzzzzzzzz') <> CVCHAR255;
