select cidx, CBIGINT, POW(CBIGINT,-3) from datatypetestm;
select cidx, CBIGINT, POW(CBIGINT,0) from datatypetestm;
select cidx, CBIGINT, POW(CBIGINT,3) from datatypetestm;
select cidx, CBIGINT, POW(CBIGINT,-2.37) from datatypetestm;
select cidx, CBIGINT, POW(CBIGINT,-0.02) from datatypetestm;
select cidx, CBIGINT, POW(CBIGINT,2.43) from datatypetestm;
select cidx, CBIGINT, POW(CBIGINT,1) from datatypetestm;
select cidx, CBIGINT, POW(CBIGINT,-1) from datatypetestm;
select cidx, CDECIMAL1, POW(CDECIMAL1,-3) from datatypetestm;
select cidx, CDECIMAL1, POW(CDECIMAL1,0) from datatypetestm;
select cidx, CDECIMAL1, POW(CDECIMAL1,3) from datatypetestm;
select cidx, CDECIMAL1, POW(CDECIMAL1,-2.37) from datatypetestm;
select cidx, CDECIMAL1, POW(CDECIMAL1,-0.02) from datatypetestm;
select cidx, CDECIMAL1, POW(CDECIMAL1,2.43) from datatypetestm;
select cidx, CDECIMAL1, POW(CDECIMAL1,1) from datatypetestm;
select cidx, CDECIMAL1, POW(CDECIMAL1,-1) from datatypetestm;
select cidx, CDECIMAL4, POW(CDECIMAL4,-3) from datatypetestm;
select cidx, CDECIMAL4, POW(CDECIMAL4,0) from datatypetestm;
select cidx, CDECIMAL4, POW(CDECIMAL4,3) from datatypetestm;
select cidx, CDECIMAL4, POW(CDECIMAL4,-2.37) from datatypetestm;
select cidx, CDECIMAL4, POW(CDECIMAL4,-0.02) from datatypetestm;
select cidx, CDECIMAL4, POW(CDECIMAL4,2.43) from datatypetestm;
select cidx, CDECIMAL4, POW(CDECIMAL4,1) from datatypetestm;
select cidx, CDECIMAL4, POW(CDECIMAL4,-1) from datatypetestm;
select cidx, CDECIMAL4_2, POW(CDECIMAL4_2,-3) from datatypetestm;
select cidx, CDECIMAL4_2, POW(CDECIMAL4_2,0) from datatypetestm;
select cidx, CDECIMAL4_2, POW(CDECIMAL4_2,3) from datatypetestm;
select cidx, CDECIMAL4_2, POW(CDECIMAL4_2,-2.37) from datatypetestm;
select cidx, CDECIMAL4_2, POW(CDECIMAL4_2,-0.02) from datatypetestm;
select cidx, CDECIMAL4_2, POW(CDECIMAL4_2,2.43) from datatypetestm;
select cidx, CDECIMAL4_2, POW(CDECIMAL4_2,1) from datatypetestm;
select cidx, CDECIMAL4_2, POW(CDECIMAL4_2,-1) from datatypetestm;
select cidx, CDECIMAL5, POW(CDECIMAL5,-3) from datatypetestm;
select cidx, CDECIMAL5, POW(CDECIMAL5,0) from datatypetestm;
select cidx, CDECIMAL5, POW(CDECIMAL5,3) from datatypetestm;
select cidx, CDECIMAL5, POW(CDECIMAL5,-2.37) from datatypetestm;
select cidx, CDECIMAL5, POW(CDECIMAL5,-0.02) from datatypetestm;
select cidx, CDECIMAL5, POW(CDECIMAL5,2.43) from datatypetestm;
select cidx, CDECIMAL5, POW(CDECIMAL5,1) from datatypetestm;
select cidx, CDECIMAL5, POW(CDECIMAL5,-1) from datatypetestm;
select cidx, CDECIMAL9, POW(CDECIMAL9,-3) from datatypetestm;
select cidx, CDECIMAL9, POW(CDECIMAL9,0) from datatypetestm;
select cidx, CDECIMAL9, POW(CDECIMAL9,3) from datatypetestm;
select cidx, CDECIMAL9, POW(CDECIMAL9,-2.37) from datatypetestm;
select cidx, CDECIMAL9, POW(CDECIMAL9,-0.02) from datatypetestm;
select cidx, CDECIMAL9, POW(CDECIMAL9,2.43) from datatypetestm;
select cidx, CDECIMAL9, POW(CDECIMAL9,1) from datatypetestm;
select cidx, CDECIMAL9, POW(CDECIMAL9,-1) from datatypetestm;
select cidx, CDECIMAL9_2, POW(CDECIMAL9_2,-3) from datatypetestm;
select cidx, CDECIMAL9_2, POW(CDECIMAL9_2,0) from datatypetestm;
select cidx, CDECIMAL9_2, POW(CDECIMAL9_2,3) from datatypetestm;
select cidx, CDECIMAL9_2, POW(CDECIMAL9_2,-2.37) from datatypetestm;
select cidx, CDECIMAL9_2, POW(CDECIMAL9_2,-0.02) from datatypetestm;
select cidx, CDECIMAL9_2, POW(CDECIMAL9_2,2.43) from datatypetestm;
select cidx, CDECIMAL9_2, POW(CDECIMAL9_2,1) from datatypetestm;
select cidx, CDECIMAL9_2, POW(CDECIMAL9_2,-1) from datatypetestm;
select cidx, CDECIMAL10, POW(CDECIMAL10,-3) from datatypetestm;
select cidx, CDECIMAL10, POW(CDECIMAL10,0) from datatypetestm;
select cidx, CDECIMAL10, POW(CDECIMAL10,3) from datatypetestm;
select cidx, CDECIMAL10, POW(CDECIMAL10,-2.37) from datatypetestm;
select cidx, CDECIMAL10, POW(CDECIMAL10,-0.02) from datatypetestm;
select cidx, CDECIMAL10, POW(CDECIMAL10,2.43) from datatypetestm;
select cidx, CDECIMAL10, POW(CDECIMAL10,1) from datatypetestm;
select cidx, CDECIMAL10, POW(CDECIMAL10,-1) from datatypetestm;
select cidx, CDECIMAL18, POW(CDECIMAL18,-3) from datatypetestm;
select cidx, CDECIMAL18, POW(CDECIMAL18,0) from datatypetestm;
select cidx, CDECIMAL18, POW(CDECIMAL18,3) from datatypetestm;
select cidx, CDECIMAL18, POW(CDECIMAL18,-2.37) from datatypetestm;
select cidx, CDECIMAL18, POW(CDECIMAL18,-0.02) from datatypetestm;
select cidx, CDECIMAL18, POW(CDECIMAL18,2.43) from datatypetestm;
select cidx, CDECIMAL18, POW(CDECIMAL18,1) from datatypetestm;
select cidx, CDECIMAL18, POW(CDECIMAL18,-1) from datatypetestm;
select cidx, CDECIMAL18_2, POW(CDECIMAL18_2,-3) from datatypetestm;
select cidx, CDECIMAL18_2, POW(CDECIMAL18_2,0) from datatypetestm;
select cidx, CDECIMAL18_2, POW(CDECIMAL18_2,3) from datatypetestm;
select cidx, CDECIMAL18_2, POW(CDECIMAL18_2,-2.37) from datatypetestm;
select cidx, CDECIMAL18_2, POW(CDECIMAL18_2,-0.02) from datatypetestm;
select cidx, CDECIMAL18_2, POW(CDECIMAL18_2,2.43) from datatypetestm;
select cidx, CDECIMAL18_2, POW(CDECIMAL18_2,1) from datatypetestm;
select cidx, CDECIMAL18_2, POW(CDECIMAL18_2,-1) from datatypetestm;
select cidx, CINTEGER, POW(CINTEGER,-3) from datatypetestm;
select cidx, CINTEGER, POW(CINTEGER,0) from datatypetestm;
select cidx, CINTEGER, POW(CINTEGER,3) from datatypetestm;
select cidx, CINTEGER, POW(CINTEGER,-2.37) from datatypetestm;
select cidx, CINTEGER, POW(CINTEGER,-0.02) from datatypetestm;
select cidx, CINTEGER, POW(CINTEGER,2.43) from datatypetestm;
select cidx, CINTEGER, POW(CINTEGER,1) from datatypetestm;
select cidx, CINTEGER, POW(CINTEGER,-1) from datatypetestm;
select cidx, CSMALLINT, POW(CSMALLINT,-3) from datatypetestm;
select cidx, CSMALLINT, POW(CSMALLINT,0) from datatypetestm;
select cidx, CSMALLINT, POW(CSMALLINT,3) from datatypetestm;
select cidx, CSMALLINT, POW(CSMALLINT,-2.37) from datatypetestm;
select cidx, CSMALLINT, POW(CSMALLINT,-0.02) from datatypetestm;
select cidx, CSMALLINT, POW(CSMALLINT,2.43) from datatypetestm;
select cidx, CSMALLINT, POW(CSMALLINT,1) from datatypetestm;
select cidx, CSMALLINT, POW(CSMALLINT,-1) from datatypetestm;
select cidx, CTINYINT, POW(CTINYINT,-3) from datatypetestm;
select cidx, CTINYINT, POW(CTINYINT,0) from datatypetestm;
select cidx, CTINYINT, POW(CTINYINT,3) from datatypetestm;
select cidx, CTINYINT, POW(CTINYINT,-2.37) from datatypetestm;
select cidx, CTINYINT, POW(CTINYINT,-0.02) from datatypetestm;
select cidx, CTINYINT, POW(CTINYINT,2.43) from datatypetestm;
select cidx, CTINYINT, POW(CTINYINT,1) from datatypetestm;
select cidx, CTINYINT, POW(CTINYINT,-1) from datatypetestm;
select cidx, CBIGINT from datatypetestm where POW(CBIGINT,-3) <> CBIGINT;
select cidx, CBIGINT from datatypetestm where POW(CBIGINT,0) <> CBIGINT;
select cidx, CBIGINT from datatypetestm where POW(CBIGINT,3) <> CBIGINT;
select cidx, CBIGINT from datatypetestm where POW(CBIGINT,-2.37) <> CBIGINT;
select cidx, CBIGINT from datatypetestm where POW(CBIGINT,-0.02) <> CBIGINT;
select cidx, CBIGINT from datatypetestm where POW(CBIGINT,2.43) <> CBIGINT;
select cidx, CBIGINT from datatypetestm where POW(CBIGINT,1) <> CBIGINT;
select cidx, CBIGINT from datatypetestm where POW(CBIGINT,-1) <> CBIGINT;
select cidx, CDECIMAL1 from datatypetestm where POW(CDECIMAL1,-3) <> CDECIMAL1;
select cidx, CDECIMAL1 from datatypetestm where POW(CDECIMAL1,0) <> CDECIMAL1;
select cidx, CDECIMAL1 from datatypetestm where POW(CDECIMAL1,3) <> CDECIMAL1;
select cidx, CDECIMAL1 from datatypetestm where POW(CDECIMAL1,-2.37) <> CDECIMAL1;
select cidx, CDECIMAL1 from datatypetestm where POW(CDECIMAL1,-0.02) <> CDECIMAL1;
select cidx, CDECIMAL1 from datatypetestm where POW(CDECIMAL1,2.43) <> CDECIMAL1;
select cidx, CDECIMAL1 from datatypetestm where POW(CDECIMAL1,1) <> CDECIMAL1;
select cidx, CDECIMAL1 from datatypetestm where POW(CDECIMAL1,-1) <> CDECIMAL1;
select cidx, CDECIMAL4 from datatypetestm where POW(CDECIMAL4,-3) <> CDECIMAL4;
select cidx, CDECIMAL4 from datatypetestm where POW(CDECIMAL4,0) <> CDECIMAL4;
select cidx, CDECIMAL4 from datatypetestm where POW(CDECIMAL4,3) <> CDECIMAL4;
select cidx, CDECIMAL4 from datatypetestm where POW(CDECIMAL4,-2.37) <> CDECIMAL4;
select cidx, CDECIMAL4 from datatypetestm where POW(CDECIMAL4,-0.02) <> CDECIMAL4;
select cidx, CDECIMAL4 from datatypetestm where POW(CDECIMAL4,2.43) <> CDECIMAL4;
select cidx, CDECIMAL4 from datatypetestm where POW(CDECIMAL4,1) <> CDECIMAL4;
select cidx, CDECIMAL4 from datatypetestm where POW(CDECIMAL4,-1) <> CDECIMAL4;
select cidx, CDECIMAL4_2 from datatypetestm where POW(CDECIMAL4_2,-3) <> CDECIMAL4_2;
select cidx, CDECIMAL4_2 from datatypetestm where POW(CDECIMAL4_2,0) <> CDECIMAL4_2;
select cidx, CDECIMAL4_2 from datatypetestm where POW(CDECIMAL4_2,3) <> CDECIMAL4_2;
select cidx, CDECIMAL4_2 from datatypetestm where POW(CDECIMAL4_2,-2.37) <> CDECIMAL4_2;
select cidx, CDECIMAL4_2 from datatypetestm where POW(CDECIMAL4_2,-0.02) <> CDECIMAL4_2;
select cidx, CDECIMAL4_2 from datatypetestm where POW(CDECIMAL4_2,2.43) <> CDECIMAL4_2;
select cidx, CDECIMAL4_2 from datatypetestm where POW(CDECIMAL4_2,1) <> CDECIMAL4_2;
select cidx, CDECIMAL4_2 from datatypetestm where POW(CDECIMAL4_2,-1) <> CDECIMAL4_2;
select cidx, CDECIMAL5 from datatypetestm where POW(CDECIMAL5,-3) <> CDECIMAL5;
select cidx, CDECIMAL5 from datatypetestm where POW(CDECIMAL5,0) <> CDECIMAL5;
select cidx, CDECIMAL5 from datatypetestm where POW(CDECIMAL5,3) <> CDECIMAL5;
select cidx, CDECIMAL5 from datatypetestm where POW(CDECIMAL5,-2.37) <> CDECIMAL5;
select cidx, CDECIMAL5 from datatypetestm where POW(CDECIMAL5,-0.02) <> CDECIMAL5;
select cidx, CDECIMAL5 from datatypetestm where POW(CDECIMAL5,2.43) <> CDECIMAL5;
select cidx, CDECIMAL5 from datatypetestm where POW(CDECIMAL5,1) <> CDECIMAL5;
select cidx, CDECIMAL5 from datatypetestm where POW(CDECIMAL5,-1) <> CDECIMAL5;
select cidx, CDECIMAL9 from datatypetestm where POW(CDECIMAL9,-3) <> CDECIMAL9;
select cidx, CDECIMAL9 from datatypetestm where POW(CDECIMAL9,0) <> CDECIMAL9;
select cidx, CDECIMAL9 from datatypetestm where POW(CDECIMAL9,3) <> CDECIMAL9;
select cidx, CDECIMAL9 from datatypetestm where POW(CDECIMAL9,-2.37) <> CDECIMAL9;
select cidx, CDECIMAL9 from datatypetestm where POW(CDECIMAL9,-0.02) <> CDECIMAL9;
select cidx, CDECIMAL9 from datatypetestm where POW(CDECIMAL9,2.43) <> CDECIMAL9;
select cidx, CDECIMAL9 from datatypetestm where POW(CDECIMAL9,1) <> CDECIMAL9;
select cidx, CDECIMAL9 from datatypetestm where POW(CDECIMAL9,-1) <> CDECIMAL9;
select cidx, CDECIMAL9_2 from datatypetestm where POW(CDECIMAL9_2,-3) <> CDECIMAL9_2;
select cidx, CDECIMAL9_2 from datatypetestm where POW(CDECIMAL9_2,0) <> CDECIMAL9_2;
select cidx, CDECIMAL9_2 from datatypetestm where POW(CDECIMAL9_2,3) <> CDECIMAL9_2;
select cidx, CDECIMAL9_2 from datatypetestm where POW(CDECIMAL9_2,-2.37) <> CDECIMAL9_2;
select cidx, CDECIMAL9_2 from datatypetestm where POW(CDECIMAL9_2,-0.02) <> CDECIMAL9_2;
select cidx, CDECIMAL9_2 from datatypetestm where POW(CDECIMAL9_2,2.43) <> CDECIMAL9_2;
select cidx, CDECIMAL9_2 from datatypetestm where POW(CDECIMAL9_2,1) <> CDECIMAL9_2;
select cidx, CDECIMAL9_2 from datatypetestm where POW(CDECIMAL9_2,-1) <> CDECIMAL9_2;
select cidx, CDECIMAL10 from datatypetestm where POW(CDECIMAL10,-3) <> CDECIMAL10;
select cidx, CDECIMAL10 from datatypetestm where POW(CDECIMAL10,0) <> CDECIMAL10;
select cidx, CDECIMAL10 from datatypetestm where POW(CDECIMAL10,3) <> CDECIMAL10;
select cidx, CDECIMAL10 from datatypetestm where POW(CDECIMAL10,-2.37) <> CDECIMAL10;
select cidx, CDECIMAL10 from datatypetestm where POW(CDECIMAL10,-0.02) <> CDECIMAL10;
select cidx, CDECIMAL10 from datatypetestm where POW(CDECIMAL10,2.43) <> CDECIMAL10;
select cidx, CDECIMAL10 from datatypetestm where POW(CDECIMAL10,1) <> CDECIMAL10;
select cidx, CDECIMAL10 from datatypetestm where POW(CDECIMAL10,-1) <> CDECIMAL10;
select cidx, CDECIMAL18 from datatypetestm where POW(CDECIMAL18,-3) <> CDECIMAL18;
select cidx, CDECIMAL18 from datatypetestm where POW(CDECIMAL18,0) <> CDECIMAL18;
select cidx, CDECIMAL18 from datatypetestm where POW(CDECIMAL18,3) <> CDECIMAL18;
select cidx, CDECIMAL18 from datatypetestm where POW(CDECIMAL18,-2.37) <> CDECIMAL18;
select cidx, CDECIMAL18 from datatypetestm where POW(CDECIMAL18,-0.02) <> CDECIMAL18;
select cidx, CDECIMAL18 from datatypetestm where POW(CDECIMAL18,2.43) <> CDECIMAL18;
select cidx, CDECIMAL18 from datatypetestm where POW(CDECIMAL18,1) <> CDECIMAL18;
select cidx, CDECIMAL18 from datatypetestm where POW(CDECIMAL18,-1) <> CDECIMAL18;
select cidx, CDECIMAL18_2 from datatypetestm where POW(CDECIMAL18_2,-3) <> CDECIMAL18_2;
select cidx, CDECIMAL18_2 from datatypetestm where POW(CDECIMAL18_2,0) <> CDECIMAL18_2;
select cidx, CDECIMAL18_2 from datatypetestm where POW(CDECIMAL18_2,3) <> CDECIMAL18_2;
select cidx, CDECIMAL18_2 from datatypetestm where POW(CDECIMAL18_2,-2.37) <> CDECIMAL18_2;
select cidx, CDECIMAL18_2 from datatypetestm where POW(CDECIMAL18_2,-0.02) <> CDECIMAL18_2;
select cidx, CDECIMAL18_2 from datatypetestm where POW(CDECIMAL18_2,2.43) <> CDECIMAL18_2;
select cidx, CDECIMAL18_2 from datatypetestm where POW(CDECIMAL18_2,1) <> CDECIMAL18_2;
select cidx, CDECIMAL18_2 from datatypetestm where POW(CDECIMAL18_2,-1) <> CDECIMAL18_2;
select cidx, CINTEGER from datatypetestm where POW(CINTEGER,-3) <> CINTEGER;
select cidx, CINTEGER from datatypetestm where POW(CINTEGER,0) <> CINTEGER;
select cidx, CINTEGER from datatypetestm where POW(CINTEGER,3) <> CINTEGER;
select cidx, CINTEGER from datatypetestm where POW(CINTEGER,-2.37) <> CINTEGER;
select cidx, CINTEGER from datatypetestm where POW(CINTEGER,-0.02) <> CINTEGER;
select cidx, CINTEGER from datatypetestm where POW(CINTEGER,2.43) <> CINTEGER;
select cidx, CINTEGER from datatypetestm where POW(CINTEGER,1) <> CINTEGER;
select cidx, CINTEGER from datatypetestm where POW(CINTEGER,-1) <> CINTEGER;
select cidx, CSMALLINT from datatypetestm where POW(CSMALLINT,-3) <> CSMALLINT;
select cidx, CSMALLINT from datatypetestm where POW(CSMALLINT,0) <> CSMALLINT;
select cidx, CSMALLINT from datatypetestm where POW(CSMALLINT,3) <> CSMALLINT;
select cidx, CSMALLINT from datatypetestm where POW(CSMALLINT,-2.37) <> CSMALLINT;
select cidx, CSMALLINT from datatypetestm where POW(CSMALLINT,-0.02) <> CSMALLINT;
select cidx, CSMALLINT from datatypetestm where POW(CSMALLINT,2.43) <> CSMALLINT;
select cidx, CSMALLINT from datatypetestm where POW(CSMALLINT,1) <> CSMALLINT;
select cidx, CSMALLINT from datatypetestm where POW(CSMALLINT,-1) <> CSMALLINT;
select cidx, CTINYINT from datatypetestm where POW(CTINYINT,-3) <> CTINYINT;
select cidx, CTINYINT from datatypetestm where POW(CTINYINT,0) <> CTINYINT;
select cidx, CTINYINT from datatypetestm where POW(CTINYINT,3) <> CTINYINT;
select cidx, CTINYINT from datatypetestm where POW(CTINYINT,-2.37) <> CTINYINT;
select cidx, CTINYINT from datatypetestm where POW(CTINYINT,-0.02) <> CTINYINT;
select cidx, CTINYINT from datatypetestm where POW(CTINYINT,2.43) <> CTINYINT;
select cidx, CTINYINT from datatypetestm where POW(CTINYINT,1) <> CTINYINT;
select cidx, CTINYINT from datatypetestm where POW(CTINYINT,-1) <> CTINYINT;
