select cidx, CBIGINT, SIGN(CBIGINT) from datatypetestm;
select cidx, CDECIMAL1, SIGN(CDECIMAL1) from datatypetestm;
select cidx, CDECIMAL4, SIGN(CDECIMAL4) from datatypetestm;
select cidx, CDECIMAL4_2, SIGN(CDECIMAL4_2) from datatypetestm;
select cidx, CDECIMAL5, SIGN(CDECIMAL5) from datatypetestm;
select cidx, CDECIMAL9, SIGN(CDECIMAL9) from datatypetestm;
select cidx, CDECIMAL9_2, SIGN(CDECIMAL9_2) from datatypetestm;
select cidx, CDECIMAL10, SIGN(CDECIMAL10) from datatypetestm;
select cidx, CDECIMAL18, SIGN(CDECIMAL18) from datatypetestm;
select cidx, CDECIMAL18_2, SIGN(CDECIMAL18_2) from datatypetestm;
select cidx, CINTEGER, SIGN(CINTEGER) from datatypetestm;
select cidx, CSMALLINT, SIGN(CSMALLINT) from datatypetestm;
select cidx, CTINYINT, SIGN(CTINYINT) from datatypetestm;
select cidx, SIGN(-1000) from datatypetestm;
select cidx, SIGN(-1) from datatypetestm;
select cidx, SIGN(0) from datatypetestm;
select cidx, SIGN(1) from datatypetestm;
select cidx, SIGN(1000) from datatypetestm;
select cidx, CBIGINT from datatypetestm order by SIGN(CBIGINT), cidx;
select cidx, CDECIMAL1 from datatypetestm order by SIGN(CDECIMAL1), cidx;
select cidx, CDECIMAL4 from datatypetestm order by SIGN(CDECIMAL4), cidx;
select cidx, CDECIMAL4_2 from datatypetestm order by SIGN(CDECIMAL4_2), cidx;
select cidx, CDECIMAL5 from datatypetestm order by SIGN(CDECIMAL5), cidx;
select cidx, CDECIMAL9 from datatypetestm order by SIGN(CDECIMAL9), cidx;
select cidx, CDECIMAL9_2 from datatypetestm order by SIGN(CDECIMAL9_2), cidx;
select cidx, CDECIMAL10 from datatypetestm order by SIGN(CDECIMAL10), cidx;
select cidx, CDECIMAL18 from datatypetestm order by SIGN(CDECIMAL18), cidx;
select cidx, CDECIMAL18_2 from datatypetestm order by SIGN(CDECIMAL18_2), cidx;
select cidx, CINTEGER from datatypetestm order by SIGN(CINTEGER), cidx;
select cidx, CSMALLINT from datatypetestm order by SIGN(CSMALLINT), cidx;
select cidx, CTINYINT from datatypetestm order by SIGN(CTINYINT), cidx;
