select SUM(CBIGINT) from datatypetestm;
select SUM(CDECIMAL1) from datatypetestm;
select SUM(CDECIMAL4) from datatypetestm;
select SUM(CDECIMAL4_2) from datatypetestm;
select SUM(CDECIMAL5) from datatypetestm;
select SUM(CDECIMAL9) from datatypetestm;
select SUM(CDECIMAL9_2) from datatypetestm;
select SUM(CDECIMAL10) from datatypetestm;
select SUM(CDECIMAL18) from datatypetestm;
select SUM(CDECIMAL18_2) from datatypetestm;
select SUM(CINTEGER) from datatypetestm;
select SUM(CSMALLINT) from datatypetestm;
select SUM(CTINYINT) from datatypetestm;
select cidx, CBIGINT, SUM(CBIGINT) from datatypetestm group by cidx, CBIGINT order by 1;
select cidx, CDECIMAL1, SUM(CDECIMAL1) from datatypetestm group by cidx, CDECIMAL1 order by 1;
select cidx, CDECIMAL4, SUM(CDECIMAL4) from datatypetestm group by cidx, CDECIMAL4 order by 1;
select cidx, CDECIMAL4_2, SUM(CDECIMAL4_2) from datatypetestm group by cidx, CDECIMAL4_2 order by 1;
select cidx, CDECIMAL5, SUM(CDECIMAL5) from datatypetestm group by cidx, CDECIMAL5 order by 1;
select cidx, CDECIMAL9, SUM(CDECIMAL9) from datatypetestm group by cidx, CDECIMAL9 order by 1;
select cidx, CDECIMAL9_2, SUM(CDECIMAL9_2) from datatypetestm group by cidx, CDECIMAL9_2 order by 1;
select cidx, CDECIMAL10, SUM(CDECIMAL10) from datatypetestm group by cidx, CDECIMAL10 order by 1;
select cidx, CDECIMAL18, SUM(CDECIMAL18) from datatypetestm group by cidx, CDECIMAL18 order by 1;
select cidx, CDECIMAL18_2, SUM(CDECIMAL18_2) from datatypetestm group by cidx, CDECIMAL18_2 order by 1;
select cidx, CINTEGER, SUM(CINTEGER) from datatypetestm group by cidx, CINTEGER order by 1;
select cidx, CSMALLINT, SUM(CSMALLINT) from datatypetestm group by cidx, CSMALLINT order by 1;
select cidx, CTINYINT, SUM(CTINYINT) from datatypetestm group by cidx, CTINYINT order by 1;
