select cidx, CDATE, WEEK(CDATE,0) from datatypetestm;
select cidx, CDATE, WEEK(CDATE,1) from datatypetestm;
select cidx, CDATE, WEEK(CDATE,2) from datatypetestm;
select cidx, CDATE, WEEK(CDATE,3) from datatypetestm;
select cidx, CDATE, WEEK(CDATE,4) from datatypetestm;
select cidx, CDATE, WEEK(CDATE,5) from datatypetestm;
select cidx, CDATE, WEEK(CDATE,6) from datatypetestm;
select cidx, CDATE, WEEK(CDATE,7) from datatypetestm;
select cidx, CDATETIME, WEEK(CDATETIME,0) from datatypetestm;
select cidx, CDATETIME, WEEK(CDATETIME,1) from datatypetestm;
select cidx, CDATETIME, WEEK(CDATETIME,2) from datatypetestm;
select cidx, CDATETIME, WEEK(CDATETIME,3) from datatypetestm;
select cidx, CDATETIME, WEEK(CDATETIME,4) from datatypetestm;
select cidx, CDATETIME, WEEK(CDATETIME,5) from datatypetestm;
select cidx, CDATETIME, WEEK(CDATETIME,6) from datatypetestm;
select cidx, CDATETIME, WEEK(CDATETIME,7) from datatypetestm;
select cidx, CDATE from datatypetestm order by WEEK(CDATE,0), cidx;
select cidx, CDATE from datatypetestm order by WEEK(CDATE,1), cidx;
select cidx, CDATE from datatypetestm order by WEEK(CDATE,2), cidx;
select cidx, CDATE from datatypetestm order by WEEK(CDATE,3), cidx;
select cidx, CDATE from datatypetestm order by WEEK(CDATE,4), cidx;
select cidx, CDATE from datatypetestm order by WEEK(CDATE,5), cidx;
select cidx, CDATE from datatypetestm order by WEEK(CDATE,6), cidx;
select cidx, CDATE from datatypetestm order by WEEK(CDATE,7), cidx;
select cidx, CDATETIME from datatypetestm order by WEEK(CDATETIME,0), cidx;
select cidx, CDATETIME from datatypetestm order by WEEK(CDATETIME,1), cidx;
select cidx, CDATETIME from datatypetestm order by WEEK(CDATETIME,2), cidx;
select cidx, CDATETIME from datatypetestm order by WEEK(CDATETIME,3), cidx;
select cidx, CDATETIME from datatypetestm order by WEEK(CDATETIME,4), cidx;
select cidx, CDATETIME from datatypetestm order by WEEK(CDATETIME,5), cidx;
select cidx, CDATETIME from datatypetestm order by WEEK(CDATETIME,6), cidx;
select cidx, CDATETIME from datatypetestm order by WEEK(CDATETIME,7), cidx;
