select cidx, CDATE, YEARWEEK(CDATE,0) from datatypetestm;
select cidx, CDATE, YEARWEEK(CDATE,1) from datatypetestm;
select cidx, CDATE, YEARWEEK(CDATE,2) from datatypetestm;
select cidx, CDATE, YEARWEEK(CDATE,3) from datatypetestm;
select cidx, CDATE, YEARWEEK(CDATE,4) from datatypetestm;
select cidx, CDATE, YEARWEEK(CDATE,5) from datatypetestm;
select cidx, CDATE, YEARWEEK(CDATE,6) from datatypetestm;
select cidx, CDATE, YEARWEEK(CDATE,7) from datatypetestm;
select cidx, CDATETIME, YEARWEEK(CDATETIME,0) from datatypetestm;
select cidx, CDATETIME, YEARWEEK(CDATETIME,1) from datatypetestm;
select cidx, CDATETIME, YEARWEEK(CDATETIME,2) from datatypetestm;
select cidx, CDATETIME, YEARWEEK(CDATETIME,3) from datatypetestm;
select cidx, CDATETIME, YEARWEEK(CDATETIME,4) from datatypetestm;
select cidx, CDATETIME, YEARWEEK(CDATETIME,5) from datatypetestm;
select cidx, CDATETIME, YEARWEEK(CDATETIME,6) from datatypetestm;
select cidx, CDATETIME, YEARWEEK(CDATETIME,7) from datatypetestm;
select cidx, CDATE from datatypetestm order by YEARWEEK(CDATE,0), cidx;
select cidx, CDATE from datatypetestm order by YEARWEEK(CDATE,1), cidx;
select cidx, CDATE from datatypetestm order by YEARWEEK(CDATE,2), cidx;
select cidx, CDATE from datatypetestm order by YEARWEEK(CDATE,3), cidx;
select cidx, CDATE from datatypetestm order by YEARWEEK(CDATE,4), cidx;
select cidx, CDATE from datatypetestm order by YEARWEEK(CDATE,5), cidx;
select cidx, CDATE from datatypetestm order by YEARWEEK(CDATE,6), cidx;
select cidx, CDATE from datatypetestm order by YEARWEEK(CDATE,7), cidx;
select cidx, CDATETIME from datatypetestm order by YEARWEEK(CDATETIME,0), cidx;
select cidx, CDATETIME from datatypetestm order by YEARWEEK(CDATETIME,1), cidx;
select cidx, CDATETIME from datatypetestm order by YEARWEEK(CDATETIME,2), cidx;
select cidx, CDATETIME from datatypetestm order by YEARWEEK(CDATETIME,3), cidx;
select cidx, CDATETIME from datatypetestm order by YEARWEEK(CDATETIME,4), cidx;
select cidx, CDATETIME from datatypetestm order by YEARWEEK(CDATETIME,5), cidx;
select cidx, CDATETIME from datatypetestm order by YEARWEEK(CDATETIME,6), cidx;
select cidx, CDATETIME from datatypetestm order by YEARWEEK(CDATETIME,7), cidx;
