-- Commented out selects that throw the overflow error.  That is expected for iteration 17.

-- SELECT AVG(CBIGINT) FROM DataTypeTestm;
SELECT AVG(CDECIMAL1) FROM DataTypeTestm;
SELECT AVG(CDECIMAL4) FROM DataTypeTestm;
SELECT AVG(CDECIMAL4_2) FROM DataTypeTestm;
SELECT AVG(CDECIMAL5) FROM DataTypeTestm;
SELECT AVG(CDECIMAL9) FROM DataTypeTestm;
SELECT AVG(CDECIMAL9_2) FROM DataTypeTestm;
SELECT AVG(CDECIMAL10) FROM DataTypeTestm;
-- SELECT AVG(CDECIMAL18) FROM DataTypeTestm;
-- SELECT AVG(CDECIMAL18_2) FROM DataTypeTestm;
SELECT AVG(CINTEGER) FROM DataTypeTestm;
SELECT AVG(CSMALLINT) FROM DataTypeTestm;
SELECT AVG(CTINYINT) FROM DataTypeTestm;

