select cidx, CBIGINT, ASIN(CBIGINT) from datatypetestm;
select cidx, CDECIMAL1, ASIN(CDECIMAL1) from datatypetestm;
select cidx, CDECIMAL4, ASIN(CDECIMAL4) from datatypetestm;
select cidx, CDECIMAL4_2, ASIN(CDECIMAL4_2) from datatypetestm;
select cidx, CDECIMAL5, ASIN(CDECIMAL5) from datatypetestm;
select cidx, CDECIMAL9, ASIN(CDECIMAL9) from datatypetestm;
select cidx, CDECIMAL9_2, ASIN(CDECIMAL9_2) from datatypetestm;
select cidx, CDECIMAL10, ASIN(CDECIMAL10) from datatypetestm;
select cidx, CDECIMAL18, ASIN(CDECIMAL18) from datatypetestm;
select cidx, CDECIMAL18_2, ASIN(CDECIMAL18_2) from datatypetestm;
select cidx, CINTEGER, ASIN(CINTEGER) from datatypetestm;
select cidx, CSMALLINT, ASIN(CSMALLINT) from datatypetestm;
select cidx, CTINYINT, ASIN(CTINYINT) from datatypetestm;
select cidx, ASIN(0) from datatypetestm;
select cidx, ASIN(60) from datatypetestm;
select cidx, ASIN(90) from datatypetestm;
select cidx, ASIN(180) from datatypetestm;
select cidx, ASIN(360) from datatypetestm;
select cidx, CBIGINT from datatypetestm where ASIN(CBIGINT) <> 0;
select cidx, CDECIMAL1 from datatypetestm where ASIN(CDECIMAL1) <> 0;
select cidx, CDECIMAL4 from datatypetestm where ASIN(CDECIMAL4) <> 0;
select cidx, CDECIMAL4_2 from datatypetestm where ASIN(CDECIMAL4_2) <> 0;
select cidx, CDECIMAL5 from datatypetestm where ASIN(CDECIMAL5) <> 0;
select cidx, CDECIMAL9 from datatypetestm where ASIN(CDECIMAL9) <> 0;
select cidx, CDECIMAL9_2 from datatypetestm where ASIN(CDECIMAL9_2) <> 0;
select cidx, CDECIMAL10 from datatypetestm where ASIN(CDECIMAL10) <> 0;
select cidx, CDECIMAL18 from datatypetestm where ASIN(CDECIMAL18) <> 0;
select cidx, CDECIMAL18_2 from datatypetestm where ASIN(CDECIMAL18_2) <> 0;
select cidx, CINTEGER from datatypetestm where ASIN(CINTEGER) <> 0;
select cidx, CSMALLINT from datatypetestm where ASIN(CSMALLINT) <> 0;
select cidx, CTINYINT from datatypetestm where ASIN(CTINYINT) <> 0;
