select cidx, CBIGINT, ATAN(CBIGINT) from datatypetestm;
select cidx, CDECIMAL1, ATAN(CDECIMAL1) from datatypetestm;
select cidx, CDECIMAL4, ATAN(CDECIMAL4) from datatypetestm;
select cidx, CDECIMAL4_2, ATAN(CDECIMAL4_2) from datatypetestm;
select cidx, CDECIMAL5, ATAN(CDECIMAL5) from datatypetestm;
select cidx, CDECIMAL9, ATAN(CDECIMAL9) from datatypetestm;
select cidx, CDECIMAL9_2, ATAN(CDECIMAL9_2) from datatypetestm;
select cidx, CDECIMAL10, ATAN(CDECIMAL10) from datatypetestm;
select cidx, CDECIMAL18, ATAN(CDECIMAL18) from datatypetestm;
select cidx, CDECIMAL18_2, ATAN(CDECIMAL18_2) from datatypetestm;
select cidx, CINTEGER, ATAN(CINTEGER) from datatypetestm;
select cidx, CSMALLINT, ATAN(CSMALLINT) from datatypetestm;
select cidx, CTINYINT, ATAN(CTINYINT) from datatypetestm;
select cidx, ATAN(0) from datatypetestm;
select cidx, ATAN(60) from datatypetestm;
select cidx, ATAN(90) from datatypetestm;
select cidx, ATAN(180) from datatypetestm;
select cidx, ATAN(360) from datatypetestm;
select cidx, CBIGINT from datatypetestm where ATAN(CBIGINT) <> 0;
select cidx, CDECIMAL1 from datatypetestm where ATAN(CDECIMAL1) <> 0;
select cidx, CDECIMAL4 from datatypetestm where ATAN(CDECIMAL4) <> 0;
select cidx, CDECIMAL4_2 from datatypetestm where ATAN(CDECIMAL4_2) <> 0;
select cidx, CDECIMAL5 from datatypetestm where ATAN(CDECIMAL5) <> 0;
select cidx, CDECIMAL9 from datatypetestm where ATAN(CDECIMAL9) <> 0;
select cidx, CDECIMAL9_2 from datatypetestm where ATAN(CDECIMAL9_2) <> 0;
select cidx, CDECIMAL10 from datatypetestm where ATAN(CDECIMAL10) <> 0;
select cidx, CDECIMAL18 from datatypetestm where ATAN(CDECIMAL18) <> 0;
select cidx, CDECIMAL18_2 from datatypetestm where ATAN(CDECIMAL18_2) <> 0;
select cidx, CINTEGER from datatypetestm where ATAN(CINTEGER) <> 0;
select cidx, CSMALLINT from datatypetestm where ATAN(CSMALLINT) <> 0;
select cidx, CTINYINT from datatypetestm where ATAN(CTINYINT) <> 0;
