SELECT cidx,CDECIMAL18_2 & CDECIMAL18_2 from datatypetestm where cidx > 5;                
SELECT cidx,CDECIMAL18_2 & CDECIMAL4_2 from datatypetestm where cidx > 5;                
SELECT cidx,CDECIMAL18_2 & CDATE from datatypetestm where cidx > 5;                
SELECT cidx,CDECIMAL18_2 & CBIGINT from datatypetestm where cidx > 5;                
SELECT cidx,CDECIMAL18_2 & CDECIMAL1 from datatypetestm where cidx > 5;                
SELECT cidx,CDECIMAL18_2 & CINTEGER from datatypetestm where cidx > 5;                
SELECT cidx,CDECIMAL18_2 & CSMALLINT from datatypetestm where cidx > 5;                
SELECT cidx,CDECIMAL18_2 & CTINYINT from datatypetestm where cidx > 5;                
SELECT cidx,CDECIMAL18_2 & CCHAR1 from datatypetestm where cidx > 5;                
SELECT cidx,CDECIMAL18_2 & CVCHAR8 from datatypetestm where cidx > 5;                
#
SELECT cidx,CDATE & CDECIMAL18_2 from datatypetestm where cidx > 5;
SELECT cidx,CDATE & CDECIMAL4_2 from datatypetestm where cidx > 5;
SELECT cidx,CDATE & CDATE from datatypetestm where cidx > 5;
SELECT cidx,CDATE & CBIGINT from datatypetestm where cidx > 5;
SELECT cidx,CDATE & CDECIMAL1 from datatypetestm where cidx > 5;
SELECT cidx,CDATE & CINTEGER from datatypetestm where cidx > 5;
SELECT cidx,CDATE & CSMALLINT from datatypetestm where cidx > 5;
SELECT cidx,CDATE & CTINYINT from datatypetestm where cidx > 5;
SELECT cidx,CDATE & CCHAR1 from datatypetestm where cidx > 5;
SELECT cidx,CDATE & CVCHAR8 from datatypetestm where cidx > 5;
#
SELECT cidx,CBIGINT & CDECIMAL18_2 from datatypetestm where cidx > 5;
SELECT cidx,CBIGINT & CDECIMAL4_2 from datatypetestm where cidx > 5;
SELECT cidx,CBIGINT & CDATE from datatypetestm where cidx > 5;
SELECT cidx,CBIGINT & CBIGINT from datatypetestm where cidx > 5;
SELECT cidx,CBIGINT & CDECIMAL1 from datatypetestm where cidx > 5;
SELECT cidx,CBIGINT & CINTEGER from datatypetestm where cidx > 5;
SELECT cidx,CBIGINT & CSMALLINT from datatypetestm where cidx > 5;
SELECT cidx,CBIGINT & CTINYINT from datatypetestm where cidx > 5;
SELECT cidx,CBIGINT & CCHAR1 from datatypetestm where cidx > 5;
SELECT cidx,CBIGINT & CVCHAR8 from datatypetestm where cidx > 5;
#
SELECT cidx,CDECIMAL1 & CDECIMAL18_2 from datatypetestm where cidx > 5;
SELECT cidx,CDECIMAL1 & CDECIMAL4_2 from datatypetestm where cidx > 5;
SELECT cidx,CDECIMAL1 & CDATE from datatypetestm where cidx > 5;
SELECT cidx,CDECIMAL1 & CBIGINT from datatypetestm where cidx > 5;
SELECT cidx,CDECIMAL1 & CDECIMAL1 from datatypetestm where cidx > 5;
SELECT cidx,CDECIMAL1 & CINTEGER from datatypetestm where cidx > 5;
SELECT cidx,CDECIMAL1 & CSMALLINT from datatypetestm where cidx > 5;
SELECT cidx,CDECIMAL1 & CTINYINT from datatypetestm where cidx > 5;
SELECT cidx,CDECIMAL1 & CCHAR1 from datatypetestm where cidx > 5;
SELECT cidx,CDECIMAL1 & CVCHAR8 from datatypetestm where cidx > 5;
#
SELECT cidx,CINTEGER & CDECIMAL18_2 from datatypetestm where cidx > 5;
SELECT cidx,CINTEGER & CDECIMAL4_2 from datatypetestm where cidx > 5;
SELECT cidx,CINTEGER & CDATE from datatypetestm where cidx > 5;
SELECT cidx,CINTEGER & CBIGINT from datatypetestm where cidx > 5;
SELECT cidx,CINTEGER & CDECIMAL1 from datatypetestm where cidx > 5;
SELECT cidx,CINTEGER & CINTEGER from datatypetestm where cidx > 5;
SELECT cidx,CINTEGER & CSMALLINT from datatypetestm where cidx > 5;
SELECT cidx,CINTEGER & CTINYINT from datatypetestm where cidx > 5;
SELECT cidx,CINTEGER & CCHAR1 from datatypetestm where cidx > 5;
SELECT cidx,CINTEGER & CVCHAR8 from datatypetestm where cidx > 5;
#
SELECT cidx,CSMALLINT & CDECIMAL18_2 from datatypetestm where cidx > 5;
SELECT cidx,CSMALLINT & CDECIMAL4_2 from datatypetestm where cidx > 5;
SELECT cidx,CSMALLINT & CDATE from datatypetestm where cidx > 5;
SELECT cidx,CSMALLINT & CBIGINT from datatypetestm where cidx > 5;
SELECT cidx,CSMALLINT & CDECIMAL1 from datatypetestm where cidx > 5;
SELECT cidx,CSMALLINT & CINTEGER from datatypetestm where cidx > 5;
SELECT cidx,CSMALLINT & CSMALLINT from datatypetestm where cidx > 5;
SELECT cidx,CSMALLINT & CTINYINT from datatypetestm where cidx > 5;
SELECT cidx,CSMALLINT & CCHAR1 from datatypetestm where cidx > 5;
SELECT cidx,CSMALLINT & CVCHAR8 from datatypetestm where cidx > 5;
#
SELECT cidx,CTINYINT & CDECIMAL18_2 from datatypetestm where cidx > 5;
SELECT cidx,CTINYINT & CDECIMAL4_2 from datatypetestm where cidx > 5;
SELECT cidx,CTINYINT & CDATE from datatypetestm where cidx > 5;
SELECT cidx,CTINYINT & CBIGINT from datatypetestm where cidx > 5;
SELECT cidx,CTINYINT & CDECIMAL1 from datatypetestm where cidx > 5;
SELECT cidx,CTINYINT & CINTEGER from datatypetestm where cidx > 5;
SELECT cidx,CTINYINT & CSMALLINT from datatypetestm where cidx > 5;
SELECT cidx,CTINYINT & CTINYINT from datatypetestm where cidx > 5;
SELECT cidx,CTINYINT & CCHAR1 from datatypetestm where cidx > 5;
SELECT cidx,CTINYINT & CVCHAR8 from datatypetestm where cidx > 5;
#
SELECT cidx,CCHAR1 & CDECIMAL18_2 from datatypetestm where cidx > 5;
SELECT cidx,CCHAR1 & CDECIMAL4_2 from datatypetestm where cidx > 5;
SELECT cidx,CCHAR1 & CDATE from datatypetestm where cidx > 5;
SELECT cidx,CCHAR1 & CBIGINT from datatypetestm where cidx > 5;
SELECT cidx,CCHAR1 & CDECIMAL1 from datatypetestm where cidx > 5;
SELECT cidx,CCHAR1 & CINTEGER from datatypetestm where cidx > 5;
SELECT cidx,CCHAR1 & CSMALLINT from datatypetestm where cidx > 5;
SELECT cidx,CCHAR1 & CTINYINT from datatypetestm where cidx > 5;
SELECT cidx,CCHAR1 & CCHAR1 from datatypetestm where cidx > 5;
SELECT cidx,CCHAR1 & CVCHAR8 from datatypetestm where cidx > 5;
#
SELECT cidx,CFLOAT & CDECIMAL18_2 from datatypetestm where cidx > 5;
SELECT cidx,CFLOAT & CDECIMAL4_2 from datatypetestm where cidx > 5;
SELECT cidx,CFLOAT & CDATE from datatypetestm where cidx > 5;
#SELECT cidx,CFLOAT & CBIGINT from datatypetestm where cidx > 5;
SELECT cidx,CFLOAT & CDECIMAL1 from datatypetestm where cidx > 5;
SELECT cidx,CFLOAT & CINTEGER from datatypetestm where cidx > 5;
SELECT cidx,CFLOAT & CSMALLINT from datatypetestm where cidx > 5;
SELECT cidx,CFLOAT & CTINYINT from datatypetestm where cidx > 5;
SELECT cidx,CFLOAT & CCHAR1 from datatypetestm where cidx > 5;
SELECT cidx,CFLOAT & CVCHAR8 from datatypetestm where cidx > 5;
#
#SELECT cidx,CDOUBLE & CDECIMAL18_2 from datatypetestm where cidx > 5;
#SELECT cidx,CDOUBLE & CDECIMAL4_2 from datatypetestm where cidx > 5;
#SELECT cidx,CDOUBLE & CDATE from datatypetestm where cidx > 5;
#SELECT cidx,CDOUBLE & CBIGINT from datatypetestm where cidx > 5;
#SELECT cidx,CDOUBLE & CDECIMAL1 from datatypetestm where cidx > 5;
#SELECT cidx,CDOUBLE & CINTEGER from datatypetestm where cidx > 5;
#SELECT cidx,CDOUBLE & CSMALLINT from datatypetestm where cidx > 5;
#SELECT cidx,CDOUBLE & CTINYINT from datatypetestm where cidx > 5;
SELECT cidx,CDOUBLE & CCHAR1 from datatypetestm where cidx > 5;
SELECT cidx,CDOUBLE & CVCHAR8 from datatypetestm where cidx > 5;
#
SELECT cidx,CDECIMAL18_2 from datatypetestm where CDECIMAL18_2 & CDECIMAL18_2 = CDECIMAL18_2 AND cidx > 5;
SELECT cidx,CDECIMAL4_2 from datatypetestm where CDECIMAL4_2 & CDECIMAL18_2 <> CDECIMAL18_2 AND cidx > 5;
SELECT cidx,CDATE from datatypetestm where CDECIMAL4_2 & CDATE <> CDECIMAL4_2 AND cidx > 5;
SELECT cidx,CBIGINT from datatypetestm where CDECIMAL1 & CBIGINT <> CBIGINT AND cidx > 5;
#SELECT cidx,CDECIMAL1 from datatypetestm where CDECIMAL1 & CDOUBLE <> CDECIMAL1 AND cidx > 5;
SELECT cidx,CINTEGER from datatypetestm where CINTEGER & CFLOAT <> CINTEGER AND cidx > 5;
SELECT cidx,CSMALLINT from datatypetestm where CSMALLINT & CTINYINT <> CSMALLINT AND cidx > 5;
SELECT cidx,CTINYINT from datatypetestm where CSMALLINT & CDATE <> CSMALLINT AND cidx > 5;
