select cidx, CBIGINT, CEILING(CBIGINT) from datatypetestm;
select cidx, CDECIMAL1, CEILING(CDECIMAL1) from datatypetestm;
select cidx, CDECIMAL4, CEILING(CDECIMAL4) from datatypetestm;
select cidx, CDECIMAL4_2, CEILING(CDECIMAL4_2) from datatypetestm;
select cidx, CDECIMAL5, CEILING(CDECIMAL5) from datatypetestm;
select cidx, CDECIMAL9, CEILING(CDECIMAL9) from datatypetestm;
select cidx, CDECIMAL9_2, CEILING(CDECIMAL9_2) from datatypetestm;
select cidx, CDECIMAL10, CEILING(CDECIMAL10) from datatypetestm;
select cidx, CDECIMAL18, CEILING(CDECIMAL18) from datatypetestm;
select cidx, CDECIMAL18_2, CEILING(CDECIMAL18_2) from datatypetestm;
select cidx, CINTEGER, CEILING(CINTEGER) from datatypetestm;
select cidx, CSMALLINT, CEILING(CSMALLINT) from datatypetestm;
select cidx, CTINYINT, CEILING(CTINYINT) from datatypetestm;
select cidx, CEILING(1.23) from datatypetestm;
select cidx, CEILING(-1.23) from datatypetestm;
select cidx, CEILING(0) from datatypetestm;
select cidx, CBIGINT from datatypetestm where CEILING(CBIGINT) <> CBIGINT;
select cidx, CDECIMAL1 from datatypetestm where CEILING(CDECIMAL1) <> CDECIMAL1;
select cidx, CDECIMAL4 from datatypetestm where CEILING(CDECIMAL4) <> CDECIMAL4;
select cidx, CDECIMAL4_2 from datatypetestm where CEILING(CDECIMAL4_2) <> CDECIMAL4_2;
select cidx, CDECIMAL5 from datatypetestm where CEILING(CDECIMAL5) <> CDECIMAL5;
select cidx, CDECIMAL9 from datatypetestm where CEILING(CDECIMAL9) <> CDECIMAL9;
select cidx, CDECIMAL9_2 from datatypetestm where CEILING(CDECIMAL9_2) <> CDECIMAL9_2;
select cidx, CDECIMAL10 from datatypetestm where CEILING(CDECIMAL10) <> CDECIMAL10;
select cidx, CDECIMAL18 from datatypetestm where CEILING(CDECIMAL18) <> CDECIMAL18;
select cidx, CDECIMAL18_2 from datatypetestm where CEILING(CDECIMAL18_2) <> CDECIMAL18_2;
select cidx, CINTEGER from datatypetestm where CEILING(CINTEGER) <> CINTEGER;
select cidx, CSMALLINT from datatypetestm where CEILING(CSMALLINT) <> CSMALLINT;
select cidx, CTINYINT from datatypetestm where CEILING(CTINYINT) <> CTINYINT;
