select cidx, CBIGINT, FLOOR(CBIGINT) from datatypetestm;
select cidx, CDECIMAL1, FLOOR(CDECIMAL1) from datatypetestm;
select cidx, CDECIMAL4, FLOOR(CDECIMAL4) from datatypetestm;
select cidx, CDECIMAL4_2, FLOOR(CDECIMAL4_2) from datatypetestm;
select cidx, CDECIMAL5, FLOOR(CDECIMAL5) from datatypetestm;
select cidx, CDECIMAL9, FLOOR(CDECIMAL9) from datatypetestm;
select cidx, CDECIMAL9_2, FLOOR(CDECIMAL9_2) from datatypetestm;
select cidx, CDECIMAL10, FLOOR(CDECIMAL10) from datatypetestm;
select cidx, CDECIMAL18, FLOOR(CDECIMAL18) from datatypetestm;
select cidx, CDECIMAL18_2, FLOOR(CDECIMAL18_2) from datatypetestm;
select cidx, CINTEGER, FLOOR(CINTEGER) from datatypetestm;
select cidx, CSMALLINT, FLOOR(CSMALLINT) from datatypetestm;
select cidx, CTINYINT, FLOOR(CTINYINT) from datatypetestm;
select cidx, FLOOR(1.23) from datatypetestm;
select cidx, FLOOR(-1.23) from datatypetestm;
select cidx, FLOOR(0) from datatypetestm;
select cidx, CBIGINT from datatypetestm where FLOOR(CBIGINT) <> CBIGINT;
select cidx, CDECIMAL1 from datatypetestm where FLOOR(CDECIMAL1) <> CDECIMAL1;
select cidx, CDECIMAL4 from datatypetestm where FLOOR(CDECIMAL4) <> CDECIMAL4;
select cidx, CDECIMAL4_2 from datatypetestm where FLOOR(CDECIMAL4_2) <> CDECIMAL4_2;
select cidx, CDECIMAL5 from datatypetestm where FLOOR(CDECIMAL5) <> CDECIMAL5;
select cidx, CDECIMAL9 from datatypetestm where FLOOR(CDECIMAL9) <> CDECIMAL9;
select cidx, CDECIMAL9_2 from datatypetestm where FLOOR(CDECIMAL9_2) <> CDECIMAL9_2;
select cidx, CDECIMAL10 from datatypetestm where FLOOR(CDECIMAL10) <> CDECIMAL10;
select cidx, CDECIMAL18 from datatypetestm where FLOOR(CDECIMAL18) <> CDECIMAL18;
select cidx, CDECIMAL18_2 from datatypetestm where FLOOR(CDECIMAL18_2) <> CDECIMAL18_2;
select cidx, CINTEGER from datatypetestm where FLOOR(CINTEGER) <> CINTEGER;
select cidx, CSMALLINT from datatypetestm where FLOOR(CSMALLINT) <> CSMALLINT;
select cidx, CTINYINT from datatypetestm where FLOOR(CTINYINT) <> CTINYINT;
select cidx, CBIGINT from datatypetestm where FLOOR(CBIGINT) is null;
select cidx, CBIGINT from datatypetestm where isnull(FLOOR(CBIGINT));
#select cidx, CDATE, FLOOR(CDATE) from datatypetestm;
#select cidx, CDATETIME, FLOOR(CDATETIME) from datatypetestm;
#select * from datatypetestm where ceil(CDATETIME) < 20091232;
#select * from datatypetestm where ceil(CDATE) < 20091232;
