select cidx, CBIGINT, FORMAT(CBIGINT,0) from datatypetestm;
select cidx, CDECIMAL1, FORMAT(CDECIMAL1,2) from datatypetestm;
select cidx, CDECIMAL4, FORMAT(CDECIMAL4,-1) from datatypetestm;
select cidx, CDECIMAL4_2, FORMAT(CDECIMAL4_2,1) from datatypetestm;
select cidx, CDECIMAL5, FORMAT(CDECIMAL5,4) from datatypetestm;
select cidx, CDECIMAL9, FORMAT(CDECIMAL9,5) from datatypetestm;
select cidx, CDECIMAL9_2, FORMAT(CDECIMAL9_2,2) from datatypetestm;
select cidx, CDECIMAL10, FORMAT(CDECIMAL10,10) from datatypetestm;
select cidx, CDECIMAL18, FORMAT(CDECIMAL18,1) from datatypetestm;
select cidx, CDECIMAL18_2, FORMAT(CDECIMAL18_2,4) from datatypetestm;
select cidx, CINTEGER, FORMAT(CINTEGER,5) from datatypetestm;
select cidx, CSMALLINT, FORMAT(CSMALLINT,0) from datatypetestm;
select cidx, CTINYINT, FORMAT(CTINYINT,-4) from datatypetestm;
select cidx, CBIGINT from datatypetestm where FORMAT(CBIGINT,1) <> CBIGINT;
select cidx, CDECIMAL1 from datatypetestm where FORMAT(CDECIMAL1,2) <> CDECIMAL1;
select cidx, CDECIMAL4 from datatypetestm where FORMAT(CDECIMAL4,3) <> CDECIMAL4;
select cidx, CDECIMAL4_2 from datatypetestm where FORMAT(CDECIMAL4_2,4) <> CDECIMAL4_2;
select cidx, CDECIMAL5 from datatypetestm where FORMAT(CDECIMAL5,0) <> CDECIMAL5;
select cidx, CDECIMAL9 from datatypetestm where FORMAT(CDECIMAL9,-1) <> CDECIMAL9;
select cidx, CDECIMAL9_2 from datatypetestm where FORMAT(CDECIMAL9_2,1) <> CDECIMAL9_2;
select cidx, CDECIMAL10 from datatypetestm where FORMAT(CDECIMAL10,5) <> CDECIMAL10;
select cidx, CDECIMAL18 from datatypetestm where FORMAT(CDECIMAL18,3) <> CDECIMAL18;
select cidx, CDECIMAL18_2 from datatypetestm where FORMAT(CDECIMAL18_2,4) <> CDECIMAL18_2;
select cidx, CINTEGER from datatypetestm where FORMAT(CINTEGER,10) <> CINTEGER;
select cidx, CSMALLINT from datatypetestm where FORMAT(CSMALLINT,0) <> CSMALLINT;
select cidx, CTINYINT from datatypetestm where FORMAT(CTINYINT,-1) <> CTINYINT;
