select cidx, CBIGINT, IFNULL(CBIGINT,0) from datatypetestm;
select cidx, CDECIMAL1, IFNULL(CDECIMAL1,0) from datatypetestm;
select cidx, CDECIMAL4, IFNULL(CDECIMAL4,0) from datatypetestm;
select cidx, CDECIMAL4_2, IFNULL(CDECIMAL4_2,0) from datatypetestm;
select cidx, CDECIMAL5, IFNULL(CDECIMAL5,0) from datatypetestm;
select cidx, CDECIMAL9, IFNULL(CDECIMAL9,0) from datatypetestm;
select cidx, CDECIMAL9_2, IFNULL(CDECIMAL9_2,0) from datatypetestm;
select cidx, CDECIMAL10, IFNULL(CDECIMAL10,0) from datatypetestm;
select cidx, CDECIMAL18, IFNULL(CDECIMAL18,0) from datatypetestm;
select cidx, CDECIMAL18_2, IFNULL(CDECIMAL18_2,0) from datatypetestm;
select cidx, CINTEGER, IFNULL(CINTEGER,0) from datatypetestm;
select cidx, CSMALLINT, IFNULL(CSMALLINT,0) from datatypetestm;
select cidx, CTINYINT, IFNULL(CTINYINT,0) from datatypetestm;
select cidx, IFNULL(-1,0) from datatypetestm;
select cidx, IFNULL(0,0) from datatypetestm;
select cidx, IFNULL(1,0) from datatypetestm;
select cidx, IFNULL(NULL,0) from datatypetestm;
select cidx, CBIGINT from datatypetestm where IFNULL(CBIGINT,0) <> CBIGINT;
select cidx, CDECIMAL1 from datatypetestm where IFNULL(CDECIMAL1,0) <> CDECIMAL1;
select cidx, CDECIMAL4 from datatypetestm where IFNULL(CDECIMAL4,0) <> CDECIMAL4;
select cidx, CDECIMAL4_2 from datatypetestm where IFNULL(CDECIMAL4_2,0) <> CDECIMAL4_2;
select cidx, CDECIMAL5 from datatypetestm where IFNULL(CDECIMAL5,0) <> CDECIMAL5;
select cidx, CDECIMAL9 from datatypetestm where IFNULL(CDECIMAL9,0) <> CDECIMAL9;
select cidx, CDECIMAL9_2 from datatypetestm where IFNULL(CDECIMAL9_2,0) <> CDECIMAL9_2;
select cidx, CDECIMAL10 from datatypetestm where IFNULL(CDECIMAL10,0) <> CDECIMAL10;
select cidx, CDECIMAL18 from datatypetestm where IFNULL(CDECIMAL18,0) <> CDECIMAL18;
select cidx, CDECIMAL18_2 from datatypetestm where IFNULL(CDECIMAL18_2,0) <> CDECIMAL18_2;
select cidx, CINTEGER from datatypetestm where IFNULL(CINTEGER,0) <> CINTEGER;
select cidx, CSMALLINT from datatypetestm where IFNULL(CSMALLINT,0) <> CSMALLINT;
select cidx, CTINYINT from datatypetestm where IFNULL(CTINYINT,0) <> CTINYINT;
