select cidx, CCHAR1, INSERT(CCHAR1,-1,4,'a') from datatypetestm;
select cidx, CCHAR1, INSERT(CCHAR1,2,-1,'a') from datatypetestm;
select cidx, CCHAR1, INSERT(CCHAR1,NULL,4,'a') from datatypetestm;
select cidx, CCHAR1, INSERT(CCHAR1,2,4,'a') from datatypetestm;
select cidx, CCHAR1, INSERT(CCHAR1,2,4,'zz') from datatypetestm;
select cidx, CCHAR2, INSERT(CCHAR2,2,4,'a') from datatypetestm;
select cidx, CCHAR2, INSERT(CCHAR2,2,4,'zz') from datatypetestm;
select cidx, CCHAR3, INSERT(CCHAR3,2,4,'a') from datatypetestm;
select cidx, CCHAR3, INSERT(CCHAR3,2,4,'zz') from datatypetestm;
select cidx, CCHAR4, INSERT(CCHAR4,2,4,'a') from datatypetestm;
select cidx, CCHAR4, INSERT(CCHAR4,2,4,'zz') from datatypetestm;
select cidx, CCHAR5, INSERT(CCHAR5,2,4,'a') from datatypetestm;
select cidx, CCHAR5, INSERT(CCHAR5,2,4,'zz') from datatypetestm;
select cidx, CCHAR6, INSERT(CCHAR6,2,4,'a') from datatypetestm;
select cidx, CCHAR6, INSERT(CCHAR6,2,4,'zz') from datatypetestm;
select cidx, CCHAR7, INSERT(CCHAR7,2,4,'a') from datatypetestm;
select cidx, CCHAR7, INSERT(CCHAR7,2,4,'zz') from datatypetestm;
select cidx, CCHAR8, INSERT(CCHAR8,2,4,'a') from datatypetestm;
select cidx, CCHAR8, INSERT(CCHAR8,2,4,'zz') from datatypetestm;
select cidx, CCHAR9, INSERT(CCHAR9,2,4,'a') from datatypetestm;
select cidx, CCHAR9, INSERT(CCHAR9,2,4,'zz') from datatypetestm;
select cidx, CCHAR255, INSERT(CCHAR255,2,4,'a') from datatypetestm;
select cidx, CCHAR255, INSERT(CCHAR255,2,4,'zz') from datatypetestm;
select cidx, CVCHAR1, INSERT(CVCHAR1,2,4,'a') from datatypetestm;
select cidx, CVCHAR1, INSERT(CVCHAR1,2,4,'zz') from datatypetestm;
select cidx, CVCHAR2, INSERT(CVCHAR2,2,4,'a') from datatypetestm;
select cidx, CVCHAR2, INSERT(CVCHAR2,2,4,'zz') from datatypetestm;
select cidx, CVCHAR3, INSERT(CVCHAR3,2,4,'a') from datatypetestm;
select cidx, CVCHAR3, INSERT(CVCHAR3,2,4,'zz') from datatypetestm;
select cidx, CVCHAR4, INSERT(CVCHAR4,2,4,'a') from datatypetestm;
select cidx, CVCHAR4, INSERT(CVCHAR4,2,4,'zz') from datatypetestm;
select cidx, CVCHAR5, INSERT(CVCHAR5,2,4,'a') from datatypetestm;
select cidx, CVCHAR5, INSERT(CVCHAR5,2,4,'zz') from datatypetestm;
select cidx, CVCHAR6, INSERT(CVCHAR6,2,4,'a') from datatypetestm;
select cidx, CVCHAR6, INSERT(CVCHAR6,2,4,'zz') from datatypetestm;
select cidx, CVCHAR7, INSERT(CVCHAR7,2,4,'a') from datatypetestm;
select cidx, CVCHAR7, INSERT(CVCHAR7,2,4,'zz') from datatypetestm;
select cidx, CVCHAR8, INSERT(CVCHAR8,2,4,'a') from datatypetestm;
select cidx, CVCHAR8, INSERT(CVCHAR8,2,4,'zz') from datatypetestm;
select cidx, CVCHAR255, INSERT(CVCHAR255,2,4,'a') from datatypetestm;
select cidx, CVCHAR255, INSERT(CVCHAR255,2,4,'zz') from datatypetestm;
select cidx, CCHAR1 from datatypetestm where INSERT(CCHAR1,2,4,'a') <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where INSERT(CCHAR1,2,4,'zz') <> CCHAR1;
select cidx, CCHAR2 from datatypetestm where INSERT(CCHAR2,2,4,'a') <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where INSERT(CCHAR2,2,4,'zz') <> CCHAR2;
select cidx, CCHAR3 from datatypetestm where INSERT(CCHAR3,2,4,'a') <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where INSERT(CCHAR3,2,4,'zz') <> CCHAR3;
select cidx, CCHAR4 from datatypetestm where INSERT(CCHAR4,2,4,'a') <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where INSERT(CCHAR4,2,4,'zz') <> CCHAR4;
select cidx, CCHAR5 from datatypetestm where INSERT(CCHAR5,2,4,'a') <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where INSERT(CCHAR5,2,4,'zz') <> CCHAR5;
select cidx, CCHAR6 from datatypetestm where INSERT(CCHAR6,2,4,'a') <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where INSERT(CCHAR6,2,4,'zz') <> CCHAR6;
select cidx, CCHAR7 from datatypetestm where INSERT(CCHAR7,2,4,'a') <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where INSERT(CCHAR7,2,4,'zz') <> CCHAR7;
select cidx, CCHAR8 from datatypetestm where INSERT(CCHAR8,2,4,'a') <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where INSERT(CCHAR8,2,4,'zz') <> CCHAR8;
select cidx, CCHAR9 from datatypetestm where INSERT(CCHAR9,2,4,'a') <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where INSERT(CCHAR9,2,4,'zz') <> CCHAR9;
select cidx, CCHAR255 from datatypetestm where INSERT(CCHAR255,2,4,'a') <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where INSERT(CCHAR255,2,4,'zz') <> CCHAR255;
select cidx, CVCHAR1 from datatypetestm where INSERT(CVCHAR1,2,4,'a') <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where INSERT(CVCHAR1,2,4,'zz') <> CVCHAR1;
select cidx, CVCHAR2 from datatypetestm where INSERT(CVCHAR2,2,4,'a') <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where INSERT(CVCHAR2,2,4,'zz') <> CVCHAR2;
select cidx, CVCHAR3 from datatypetestm where INSERT(CVCHAR3,2,4,'a') <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where INSERT(CVCHAR3,2,4,'zz') <> CVCHAR3;
select cidx, CVCHAR4 from datatypetestm where INSERT(CVCHAR4,2,4,'a') <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where INSERT(CVCHAR4,2,4,'zz') <> CVCHAR4;
select cidx, CVCHAR5 from datatypetestm where INSERT(CVCHAR5,2,4,'a') <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where INSERT(CVCHAR5,2,4,'zz') <> CVCHAR5;
select cidx, CVCHAR6 from datatypetestm where INSERT(CVCHAR6,2,4,'a') <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where INSERT(CVCHAR6,2,4,'zz') <> CVCHAR6;
select cidx, CVCHAR7 from datatypetestm where INSERT(CVCHAR7,2,4,'a') <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where INSERT(CVCHAR7,2,4,'zz') <> CVCHAR7;
select cidx, CVCHAR8 from datatypetestm where INSERT(CVCHAR8,2,4,'a') <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where INSERT(CVCHAR8,2,4,'zz') <> CVCHAR8;
select cidx, CVCHAR255 from datatypetestm where INSERT(CVCHAR255,2,4,'a') <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where INSERT(CVCHAR255,2,4,'zz') <> CVCHAR255;
