select cidx, CCHAR1, LCASE(CCHAR1) from datatypetestm;
select cidx, CCHAR2, LCASE(CCHAR2) from datatypetestm;
select cidx, CCHAR3, LCASE(CCHAR3) from datatypetestm;
select cidx, CCHAR4, LCASE(CCHAR4) from datatypetestm;
select cidx, CCHAR5, LCASE(CCHAR5) from datatypetestm;
select cidx, CCHAR6, LCASE(CCHAR6) from datatypetestm;
select cidx, CCHAR7, LCASE(CCHAR7) from datatypetestm;
select cidx, CCHAR8, LCASE(CCHAR8) from datatypetestm;
select cidx, CCHAR9, LCASE(CCHAR9) from datatypetestm;
select cidx, CCHAR255, LCASE(CCHAR255) from datatypetestm;
select cidx, CVCHAR1, LCASE(CVCHAR1) from datatypetestm;
select cidx, CVCHAR2, LCASE(CVCHAR2) from datatypetestm;
select cidx, CVCHAR3, LCASE(CVCHAR3) from datatypetestm;
select cidx, CVCHAR4, LCASE(CVCHAR4) from datatypetestm;
select cidx, CVCHAR5, LCASE(CVCHAR5) from datatypetestm;
select cidx, CVCHAR6, LCASE(CVCHAR6) from datatypetestm;
select cidx, CVCHAR7, LCASE(CVCHAR7) from datatypetestm;
select cidx, CVCHAR8, LCASE(CVCHAR8) from datatypetestm;
select cidx, CVCHAR255, LCASE(CVCHAR255) from datatypetestm;
select cidx, LCASE('ALOHA') from datatypetestm;
select cidx, LCASE('MAHALO') from datatypetestm;
select cidx, LCASE('Hawaii') from datatypetestm;
select cidx, CCHAR1 from datatypetestm where LCASE(CCHAR1) <> CCHAR1;
select cidx, CCHAR2 from datatypetestm where LCASE(CCHAR2) <> CCHAR2;
select cidx, CCHAR3 from datatypetestm where LCASE(CCHAR3) <> CCHAR3;
select cidx, CCHAR4 from datatypetestm where LCASE(CCHAR4) <> CCHAR4;
select cidx, CCHAR5 from datatypetestm where LCASE(CCHAR5) <> CCHAR5;
select cidx, CCHAR6 from datatypetestm where LCASE(CCHAR6) <> CCHAR6;
select cidx, CCHAR7 from datatypetestm where LCASE(CCHAR7) <> CCHAR7;
select cidx, CCHAR8 from datatypetestm where LCASE(CCHAR8) <> CCHAR8;
select cidx, CCHAR9 from datatypetestm where LCASE(CCHAR9) <> CCHAR9;
select cidx, CCHAR255 from datatypetestm where LCASE(CCHAR255) <> CCHAR255;
select cidx, CVCHAR1 from datatypetestm where LCASE(CVCHAR1) <> CVCHAR1;
select cidx, CVCHAR2 from datatypetestm where LCASE(CVCHAR2) <> CVCHAR2;
select cidx, CVCHAR3 from datatypetestm where LCASE(CVCHAR3) <> CVCHAR3;
select cidx, CVCHAR4 from datatypetestm where LCASE(CVCHAR4) <> CVCHAR4;
select cidx, CVCHAR5 from datatypetestm where LCASE(CVCHAR5) <> CVCHAR5;
select cidx, CVCHAR6 from datatypetestm where LCASE(CVCHAR6) <> CVCHAR6;
select cidx, CVCHAR7 from datatypetestm where LCASE(CVCHAR7) <> CVCHAR7;
select cidx, CVCHAR8 from datatypetestm where LCASE(CVCHAR8) <> CVCHAR8;
select cidx, CVCHAR255 from datatypetestm where LCASE(CVCHAR255) <> CVCHAR255;
