select cidx, CCHAR1, LENGTH(CCHAR1) from datatypetestm;
select cidx, CCHAR2, LENGTH(CCHAR2) from datatypetestm;
select cidx, CCHAR3, LENGTH(CCHAR3) from datatypetestm;
select cidx, CCHAR4, LENGTH(CCHAR4) from datatypetestm;
select cidx, CCHAR5, LENGTH(CCHAR5) from datatypetestm;
select cidx, CCHAR6, LENGTH(CCHAR6) from datatypetestm;
select cidx, CCHAR7, LENGTH(CCHAR7) from datatypetestm;
select cidx, CCHAR8, LENGTH(CCHAR8) from datatypetestm;
select cidx, CCHAR9, LENGTH(CCHAR9) from datatypetestm;
select cidx, CCHAR255, LENGTH(CCHAR255) from datatypetestm;
select cidx, CVCHAR1, LENGTH(CVCHAR1) from datatypetestm;
select cidx, CVCHAR2, LENGTH(CVCHAR2) from datatypetestm;
select cidx, CVCHAR3, LENGTH(CVCHAR3) from datatypetestm;
select cidx, CVCHAR4, LENGTH(CVCHAR4) from datatypetestm;
select cidx, CVCHAR5, LENGTH(CVCHAR5) from datatypetestm;
select cidx, CVCHAR6, LENGTH(CVCHAR6) from datatypetestm;
select cidx, CVCHAR7, LENGTH(CVCHAR7) from datatypetestm;
select cidx, CVCHAR8, LENGTH(CVCHAR8) from datatypetestm;
select cidx, CVCHAR255, LENGTH(CVCHAR255) from datatypetestm;
select cidx, LENGTH('ALOHA') from datatypetestm;
select cidx, LENGTH('HAWAII') from datatypetestm;
select cidx, LENGTH('MELEKALIKIMAKA') from datatypetestm;
select cidx, CCHAR1 from datatypetestm where LENGTH(CCHAR1) <> CCHAR1;
select cidx, CCHAR2 from datatypetestm where LENGTH(CCHAR2) <> CCHAR2;
select cidx, CCHAR3 from datatypetestm where LENGTH(CCHAR3) <> CCHAR3;
select cidx, CCHAR4 from datatypetestm where LENGTH(CCHAR4) <> CCHAR4;
select cidx, CCHAR5 from datatypetestm where LENGTH(CCHAR5) <> CCHAR5;
select cidx, CCHAR6 from datatypetestm where LENGTH(CCHAR6) <> CCHAR6;
select cidx, CCHAR7 from datatypetestm where LENGTH(CCHAR7) <> CCHAR7;
select cidx, CCHAR8 from datatypetestm where LENGTH(CCHAR8) <> CCHAR8;
select cidx, CCHAR9 from datatypetestm where LENGTH(CCHAR9) <> CCHAR9;
select cidx, CCHAR255 from datatypetestm where LENGTH(CCHAR255) <> CCHAR255;
select cidx, CVCHAR1 from datatypetestm where LENGTH(CVCHAR1) <> CVCHAR1;
select cidx, CVCHAR2 from datatypetestm where LENGTH(CVCHAR2) <> CVCHAR2;
select cidx, CVCHAR3 from datatypetestm where LENGTH(CVCHAR3) <> CVCHAR3;
select cidx, CVCHAR4 from datatypetestm where LENGTH(CVCHAR4) <> CVCHAR4;
select cidx, CVCHAR5 from datatypetestm where LENGTH(CVCHAR5) <> CVCHAR5;
select cidx, CVCHAR6 from datatypetestm where LENGTH(CVCHAR6) <> CVCHAR6;
select cidx, CVCHAR7 from datatypetestm where LENGTH(CVCHAR7) <> CVCHAR7;
select cidx, CVCHAR8 from datatypetestm where LENGTH(CVCHAR8) <> CVCHAR8;
select cidx, CVCHAR255 from datatypetestm where LENGTH(CVCHAR255) <> CVCHAR255;
