select cidx, CBIGINT, LOG10(CBIGINT) from datatypetestm;
select cidx, CDECIMAL1, LOG10(CDECIMAL1) from datatypetestm;
select cidx, CDECIMAL4, LOG10(CDECIMAL4) from datatypetestm;
select cidx, CDECIMAL4_2, LOG10(CDECIMAL4_2) from datatypetestm;
select cidx, CDECIMAL5, LOG10(CDECIMAL5) from datatypetestm;
select cidx, CDECIMAL9, LOG10(CDECIMAL9) from datatypetestm;
select cidx, CDECIMAL9_2, LOG10(CDECIMAL9_2) from datatypetestm;
select cidx, CDECIMAL10, LOG10(CDECIMAL10) from datatypetestm;
select cidx, CDECIMAL18, LOG10(CDECIMAL18) from datatypetestm;
select cidx, CDECIMAL18_2, LOG10(CDECIMAL18_2) from datatypetestm;
select cidx, CINTEGER, LOG10(CINTEGER) from datatypetestm;
select cidx, CSMALLINT, LOG10(CSMALLINT) from datatypetestm;
select cidx, CTINYINT, LOG10(CTINYINT) from datatypetestm;
select cidx, LOG10(-1) from datatypetestm;
select cidx, LOG10(0) from datatypetestm;
select cidx, LOG10(2) from datatypetestm;
select cidx, LOG10(265536) from datatypetestm;
select cidx, LOG10(100) from datatypetestm;
select cidx, LOG10(-100) from datatypetestm;
select cidx, CBIGINT from datatypetestm where LOG10(CBIGINT) <> 0;
select cidx, CDECIMAL1 from datatypetestm where LOG10(CDECIMAL1) <> 0;
select cidx, CDECIMAL4 from datatypetestm where LOG10(CDECIMAL4) <> 0;
select cidx, CDECIMAL4_2 from datatypetestm where LOG10(CDECIMAL4_2) <> 0;
select cidx, CDECIMAL5 from datatypetestm where LOG10(CDECIMAL5) <> 0;
select cidx, CDECIMAL9 from datatypetestm where LOG10(CDECIMAL9) <> 0;
select cidx, CDECIMAL9_2 from datatypetestm where LOG10(CDECIMAL9_2) <> 0;
select cidx, CDECIMAL10 from datatypetestm where LOG10(CDECIMAL10) <> 0;
select cidx, CDECIMAL18 from datatypetestm where LOG10(CDECIMAL18) <> 0;
select cidx, CDECIMAL18_2 from datatypetestm where LOG10(CDECIMAL18_2) <> 0;
select cidx, CINTEGER from datatypetestm where LOG10(CINTEGER) <> 0;
select cidx, CSMALLINT from datatypetestm where LOG10(CSMALLINT) <> 0;
select cidx, CTINYINT from datatypetestm where LOG10(CTINYINT) <> 0;;
