select cidx, CDECIMAL1, LOG2(CDECIMAL1) from datatypetestm;
select cidx, CDECIMAL4, LOG2(CDECIMAL4) from datatypetestm;
select cidx, CDECIMAL4_2, LOG2(CDECIMAL4_2) from datatypetestm;
select cidx, CDECIMAL5, LOG2(CDECIMAL5) from datatypetestm;
select cidx, CDECIMAL9, LOG2(CDECIMAL9) from datatypetestm;
select cidx, CDECIMAL9_2, LOG2(CDECIMAL9_2) from datatypetestm;
select cidx, CDECIMAL10, LOG2(CDECIMAL10) from datatypetestm;
select cidx, CDECIMAL18, LOG2(CDECIMAL18) from datatypetestm;
select cidx, CDECIMAL18_2, LOG2(CDECIMAL18_2) from datatypetestm;
select cidx, CINTEGER, LOG2(CINTEGER) from datatypetestm;
select cidx, CSMALLINT, LOG2(CSMALLINT) from datatypetestm;
select cidx, CTINYINT, LOG2(CTINYINT) from datatypetestm;
select cidx, LOG2(-1) from datatypetestm;
select cidx, LOG2(0) from datatypetestm;
select cidx, LOG2(2) from datatypetestm;
select cidx, LOG2(265536) from datatypetestm;
select cidx, LOG2(100) from datatypetestm;
select cidx, LOG2(-100) from datatypetestm;
select cidx, CBIGINT from datatypetestm where LOG2(CBIGINT) <> 0;
select cidx, CDECIMAL1 from datatypetestm where LOG2(CDECIMAL1) <> 0;
select cidx, CDECIMAL4 from datatypetestm where LOG2(CDECIMAL4) <> 0;
select cidx, CDECIMAL4_2 from datatypetestm where LOG2(CDECIMAL4_2) <> 0;
select cidx, CDECIMAL5 from datatypetestm where LOG2(CDECIMAL5) <> 0;
select cidx, CDECIMAL9 from datatypetestm where LOG2(CDECIMAL9) <> 0;
select cidx, CDECIMAL9_2 from datatypetestm where LOG2(CDECIMAL9_2) <> 0;
select cidx, CDECIMAL10 from datatypetestm where LOG2(CDECIMAL10) <> 0;
select cidx, CDECIMAL18 from datatypetestm where LOG2(CDECIMAL18) <> 0;
select cidx, CDECIMAL18_2 from datatypetestm where LOG2(CDECIMAL18_2) <> 0;
select cidx, CINTEGER from datatypetestm where LOG2(CINTEGER) <> 0;
select cidx, CSMALLINT from datatypetestm where LOG2(CSMALLINT) <> 0;
select cidx, CTINYINT from datatypetestm where LOG2(CTINYINT) <> 0;
