select cidx, CCHAR1, LPAD(CCHAR1,5,'**') from datatypetestm;
select cidx, CCHAR1, LPAD(CCHAR1,5,'********') from datatypetestm;
select cidx, CCHAR1, LPAD(CCHAR1,15,'**') from datatypetestm;
select cidx, CCHAR1, LPAD(CCHAR1,15,'********') from datatypetestm;
select cidx, CCHAR2, LPAD(CCHAR2,5,'**') from datatypetestm;
select cidx, CCHAR2, LPAD(CCHAR2,5,'********') from datatypetestm;
select cidx, CCHAR2, LPAD(CCHAR2,15,'**') from datatypetestm;
select cidx, CCHAR2, LPAD(CCHAR2,15,'********') from datatypetestm;
select cidx, CCHAR3, LPAD(CCHAR3,5,'**') from datatypetestm;
select cidx, CCHAR3, LPAD(CCHAR3,5,'********') from datatypetestm;
select cidx, CCHAR3, LPAD(CCHAR3,15,'**') from datatypetestm;
select cidx, CCHAR3, LPAD(CCHAR3,15,'********') from datatypetestm;
select cidx, CCHAR4, LPAD(CCHAR4,5,'**') from datatypetestm;
select cidx, CCHAR4, LPAD(CCHAR4,5,'********') from datatypetestm;
select cidx, CCHAR4, LPAD(CCHAR4,15,'**') from datatypetestm;
select cidx, CCHAR4, LPAD(CCHAR4,15,'********') from datatypetestm;
select cidx, CCHAR5, LPAD(CCHAR5,5,'**') from datatypetestm;
select cidx, CCHAR5, LPAD(CCHAR5,5,'********') from datatypetestm;
select cidx, CCHAR5, LPAD(CCHAR5,15,'**') from datatypetestm;
select cidx, CCHAR5, LPAD(CCHAR5,15,'********') from datatypetestm;
select cidx, CCHAR6, LPAD(CCHAR6,5,'**') from datatypetestm;
select cidx, CCHAR6, LPAD(CCHAR6,5,'********') from datatypetestm;
select cidx, CCHAR6, LPAD(CCHAR6,15,'**') from datatypetestm;
select cidx, CCHAR6, LPAD(CCHAR6,15,'********') from datatypetestm;
select cidx, CCHAR7, LPAD(CCHAR7,5,'**') from datatypetestm;
select cidx, CCHAR7, LPAD(CCHAR7,5,'********') from datatypetestm;
select cidx, CCHAR7, LPAD(CCHAR7,15,'**') from datatypetestm;
select cidx, CCHAR7, LPAD(CCHAR7,15,'********') from datatypetestm;
select cidx, CCHAR8, LPAD(CCHAR8,5,'**') from datatypetestm;
select cidx, CCHAR8, LPAD(CCHAR8,5,'********') from datatypetestm;
select cidx, CCHAR8, LPAD(CCHAR8,15,'**') from datatypetestm;
select cidx, CCHAR8, LPAD(CCHAR8,15,'********') from datatypetestm;
select cidx, CCHAR9, LPAD(CCHAR9,5,'**') from datatypetestm;
select cidx, CCHAR9, LPAD(CCHAR9,5,'********') from datatypetestm;
select cidx, CCHAR9, LPAD(CCHAR9,15,'**') from datatypetestm;
select cidx, CCHAR9, LPAD(CCHAR9,15,'********') from datatypetestm;
select cidx, CCHAR255, LPAD(CCHAR255,5,'**') from datatypetestm;
select cidx, CCHAR255, LPAD(CCHAR255,5,'********') from datatypetestm;
select cidx, CCHAR255, LPAD(CCHAR255,15,'**') from datatypetestm;
select cidx, CCHAR255, LPAD(CCHAR255,15,'********') from datatypetestm;
select cidx, CVCHAR1, LPAD(CVCHAR1,5,'**') from datatypetestm;
select cidx, CVCHAR1, LPAD(CVCHAR1,5,'********') from datatypetestm;
select cidx, CVCHAR1, LPAD(CVCHAR1,15,'**') from datatypetestm;
select cidx, CVCHAR1, LPAD(CVCHAR1,15,'********') from datatypetestm;
select cidx, CVCHAR2, LPAD(CVCHAR2,5,'**') from datatypetestm;
select cidx, CVCHAR2, LPAD(CVCHAR2,5,'********') from datatypetestm;
select cidx, CVCHAR2, LPAD(CVCHAR2,15,'**') from datatypetestm;
select cidx, CVCHAR2, LPAD(CVCHAR2,15,'********') from datatypetestm;
select cidx, CVCHAR3, LPAD(CVCHAR3,5,'**') from datatypetestm;
select cidx, CVCHAR3, LPAD(CVCHAR3,5,'********') from datatypetestm;
select cidx, CVCHAR3, LPAD(CVCHAR3,15,'**') from datatypetestm;
select cidx, CVCHAR3, LPAD(CVCHAR3,15,'********') from datatypetestm;
select cidx, CVCHAR4, LPAD(CVCHAR4,5,'**') from datatypetestm;
select cidx, CVCHAR4, LPAD(CVCHAR4,5,'********') from datatypetestm;
select cidx, CVCHAR4, LPAD(CVCHAR4,15,'**') from datatypetestm;
select cidx, CVCHAR4, LPAD(CVCHAR4,15,'********') from datatypetestm;
select cidx, CVCHAR5, LPAD(CVCHAR5,5,'**') from datatypetestm;
select cidx, CVCHAR5, LPAD(CVCHAR5,5,'********') from datatypetestm;
select cidx, CVCHAR5, LPAD(CVCHAR5,15,'**') from datatypetestm;
select cidx, CVCHAR5, LPAD(CVCHAR5,15,'********') from datatypetestm;
select cidx, CVCHAR6, LPAD(CVCHAR6,5,'**') from datatypetestm;
select cidx, CVCHAR6, LPAD(CVCHAR6,5,'********') from datatypetestm;
select cidx, CVCHAR6, LPAD(CVCHAR6,15,'**') from datatypetestm;
select cidx, CVCHAR6, LPAD(CVCHAR6,15,'********') from datatypetestm;
select cidx, CVCHAR7, LPAD(CVCHAR7,5,'**') from datatypetestm;
select cidx, CVCHAR7, LPAD(CVCHAR7,5,'********') from datatypetestm;
select cidx, CVCHAR7, LPAD(CVCHAR7,15,'**') from datatypetestm;
select cidx, CVCHAR7, LPAD(CVCHAR7,15,'********') from datatypetestm;
select cidx, CVCHAR8, LPAD(CVCHAR8,5,'**') from datatypetestm;
select cidx, CVCHAR8, LPAD(CVCHAR8,5,'********') from datatypetestm;
select cidx, CVCHAR8, LPAD(CVCHAR8,15,'**') from datatypetestm;
select cidx, CVCHAR8, LPAD(CVCHAR8,15,'********') from datatypetestm;
select cidx, CVCHAR255, LPAD(CVCHAR255,5,'**') from datatypetestm;
select cidx, CVCHAR255, LPAD(CVCHAR255,5,'********') from datatypetestm;
select cidx, CVCHAR255, LPAD(CVCHAR255,15,'**') from datatypetestm;
select cidx, CVCHAR255, LPAD(CVCHAR255,15,'********') from datatypetestm;
select cidx, CCHAR1 from datatypetestm where LPAD(CCHAR1,5,'**') <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where LPAD(CCHAR1,5,'********') <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where LPAD(CCHAR1,15,'**') <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where LPAD(CCHAR1,15,'********') <> CCHAR1;
select cidx, CCHAR2 from datatypetestm where LPAD(CCHAR2,5,'**') <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where LPAD(CCHAR2,5,'********') <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where LPAD(CCHAR2,15,'**') <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where LPAD(CCHAR2,15,'********') <> CCHAR2;
select cidx, CCHAR3 from datatypetestm where LPAD(CCHAR3,5,'**') <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where LPAD(CCHAR3,5,'********') <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where LPAD(CCHAR3,15,'**') <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where LPAD(CCHAR3,15,'********') <> CCHAR3;
select cidx, CCHAR4 from datatypetestm where LPAD(CCHAR4,5,'**') <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where LPAD(CCHAR4,5,'********') <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where LPAD(CCHAR4,15,'**') <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where LPAD(CCHAR4,15,'********') <> CCHAR4;
select cidx, CCHAR5 from datatypetestm where LPAD(CCHAR5,5,'**') <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where LPAD(CCHAR5,5,'********') <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where LPAD(CCHAR5,15,'**') <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where LPAD(CCHAR5,15,'********') <> CCHAR5;
select cidx, CCHAR6 from datatypetestm where LPAD(CCHAR6,5,'**') <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where LPAD(CCHAR6,5,'********') <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where LPAD(CCHAR6,15,'**') <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where LPAD(CCHAR6,15,'********') <> CCHAR6;
select cidx, CCHAR7 from datatypetestm where LPAD(CCHAR7,5,'**') <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where LPAD(CCHAR7,5,'********') <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where LPAD(CCHAR7,15,'**') <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where LPAD(CCHAR7,15,'********') <> CCHAR7;
select cidx, CCHAR8 from datatypetestm where LPAD(CCHAR8,5,'**') <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where LPAD(CCHAR8,5,'********') <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where LPAD(CCHAR8,15,'**') <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where LPAD(CCHAR8,15,'********') <> CCHAR8;
select cidx, CCHAR9 from datatypetestm where LPAD(CCHAR9,5,'**') <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where LPAD(CCHAR9,5,'********') <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where LPAD(CCHAR9,15,'**') <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where LPAD(CCHAR9,15,'********') <> CCHAR9;
select cidx, CCHAR255 from datatypetestm where LPAD(CCHAR255,5,'**') <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where LPAD(CCHAR255,5,'********') <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where LPAD(CCHAR255,15,'**') <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where LPAD(CCHAR255,15,'********') <> CCHAR255;
select cidx, CVCHAR1 from datatypetestm where LPAD(CVCHAR1,5,'**') <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where LPAD(CVCHAR1,5,'********') <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where LPAD(CVCHAR1,15,'**') <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where LPAD(CVCHAR1,15,'********') <> CVCHAR1;
select cidx, CVCHAR2 from datatypetestm where LPAD(CVCHAR2,5,'**') <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where LPAD(CVCHAR2,5,'********') <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where LPAD(CVCHAR2,15,'**') <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where LPAD(CVCHAR2,15,'********') <> CVCHAR2;
select cidx, CVCHAR3 from datatypetestm where LPAD(CVCHAR3,5,'**') <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where LPAD(CVCHAR3,5,'********') <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where LPAD(CVCHAR3,15,'**') <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where LPAD(CVCHAR3,15,'********') <> CVCHAR3;
select cidx, CVCHAR4 from datatypetestm where LPAD(CVCHAR4,5,'**') <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where LPAD(CVCHAR4,5,'********') <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where LPAD(CVCHAR4,15,'**') <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where LPAD(CVCHAR4,15,'********') <> CVCHAR4;
select cidx, CVCHAR5 from datatypetestm where LPAD(CVCHAR5,5,'**') <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where LPAD(CVCHAR5,5,'********') <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where LPAD(CVCHAR5,15,'**') <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where LPAD(CVCHAR5,15,'********') <> CVCHAR5;
select cidx, CVCHAR6 from datatypetestm where LPAD(CVCHAR6,5,'**') <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where LPAD(CVCHAR6,5,'********') <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where LPAD(CVCHAR6,15,'**') <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where LPAD(CVCHAR6,15,'********') <> CVCHAR6;
select cidx, CVCHAR7 from datatypetestm where LPAD(CVCHAR7,5,'**') <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where LPAD(CVCHAR7,5,'********') <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where LPAD(CVCHAR7,15,'**') <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where LPAD(CVCHAR7,15,'********') <> CVCHAR7;
select cidx, CVCHAR8 from datatypetestm where LPAD(CVCHAR8,5,'**') <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where LPAD(CVCHAR8,5,'********') <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where LPAD(CVCHAR8,15,'**') <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where LPAD(CVCHAR8,15,'********') <> CVCHAR8;
select cidx, CVCHAR255 from datatypetestm where LPAD(CVCHAR255,5,'**') <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where LPAD(CVCHAR255,5,'********') <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where LPAD(CVCHAR255,15,'**') <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where LPAD(CVCHAR255,15,'********') <> CVCHAR255;
