select cidx, CCHAR1, LTRIM(CCHAR1) from datatypetestm;
select cidx, CCHAR2, LTRIM(CCHAR2) from datatypetestm;
select cidx, CCHAR3, LTRIM(CCHAR3) from datatypetestm;
select cidx, CCHAR4, LTRIM(CCHAR4) from datatypetestm;
select cidx, CCHAR5, LTRIM(CCHAR5) from datatypetestm;
select cidx, CCHAR6, LTRIM(CCHAR6) from datatypetestm;
select cidx, CCHAR7, LTRIM(CCHAR7) from datatypetestm;
select cidx, CCHAR8, LTRIM(CCHAR8) from datatypetestm;
select cidx, CCHAR9, LTRIM(CCHAR9) from datatypetestm;
select cidx, CCHAR255, LTRIM(CCHAR255) from datatypetestm;
select cidx, CVCHAR1, LTRIM(CVCHAR1) from datatypetestm;
select cidx, CVCHAR2, LTRIM(CVCHAR2) from datatypetestm;
select cidx, CVCHAR3, LTRIM(CVCHAR3) from datatypetestm;
select cidx, CVCHAR4, LTRIM(CVCHAR4) from datatypetestm;
select cidx, CVCHAR5, LTRIM(CVCHAR5) from datatypetestm;
select cidx, CVCHAR6, LTRIM(CVCHAR6) from datatypetestm;
select cidx, CVCHAR7, LTRIM(CVCHAR7) from datatypetestm;
select cidx, CVCHAR8, LTRIM(CVCHAR8) from datatypetestm;
select cidx, CVCHAR255, LTRIM(CVCHAR255) from datatypetestm;
select cidx, LTRIM('Hello ') from datatypetestm;
select cidx, LTRIM(' world') from datatypetestm;
select cidx, LTRIM(' Howzit ') from datatypetestm;
select cidx, CCHAR1 from datatypetestm where LTRIM(CCHAR1) <> CCHAR1;
select cidx, CCHAR2 from datatypetestm where LTRIM(CCHAR2) <> CCHAR2;
select cidx, CCHAR3 from datatypetestm where LTRIM(CCHAR3) <> CCHAR3;
select cidx, CCHAR4 from datatypetestm where LTRIM(CCHAR4) <> CCHAR4;
select cidx, CCHAR5 from datatypetestm where LTRIM(CCHAR5) <> CCHAR5;
select cidx, CCHAR6 from datatypetestm where LTRIM(CCHAR6) <> CCHAR6;
select cidx, CCHAR7 from datatypetestm where LTRIM(CCHAR7) <> CCHAR7;
select cidx, CCHAR8 from datatypetestm where LTRIM(CCHAR8) <> CCHAR8;
select cidx, CCHAR9 from datatypetestm where LTRIM(CCHAR9) <> CCHAR9;
select cidx, CCHAR255 from datatypetestm where LTRIM(CCHAR255) <> CCHAR255;
select cidx, CVCHAR1 from datatypetestm where LTRIM(CVCHAR1) <> CVCHAR1;
select cidx, CVCHAR2 from datatypetestm where LTRIM(CVCHAR2) <> CVCHAR2;
select cidx, CVCHAR3 from datatypetestm where LTRIM(CVCHAR3) <> CVCHAR3;
select cidx, CVCHAR4 from datatypetestm where LTRIM(CVCHAR4) <> CVCHAR4;
select cidx, CVCHAR5 from datatypetestm where LTRIM(CVCHAR5) <> CVCHAR5;
select cidx, CVCHAR6 from datatypetestm where LTRIM(CVCHAR6) <> CVCHAR6;
select cidx, CVCHAR7 from datatypetestm where LTRIM(CVCHAR7) <> CVCHAR7;
select cidx, CVCHAR8 from datatypetestm where LTRIM(CVCHAR8) <> CVCHAR8;
select cidx, CVCHAR255 from datatypetestm where LTRIM(CVCHAR255) <> CVCHAR255;
