select cidx, CBIGINT, RADIANS(CBIGINT) from datatypetestm;
select cidx, CDECIMAL1, RADIANS(CDECIMAL1) from datatypetestm;
select cidx, CDECIMAL4, RADIANS(CDECIMAL4) from datatypetestm;
select cidx, CDECIMAL4_2, RADIANS(CDECIMAL4_2) from datatypetestm;
select cidx, CDECIMAL5, RADIANS(CDECIMAL5) from datatypetestm;
select cidx, CDECIMAL9, RADIANS(CDECIMAL9) from datatypetestm;
select cidx, CDECIMAL9_2, RADIANS(CDECIMAL9_2) from datatypetestm;
select cidx, CDECIMAL10, RADIANS(CDECIMAL10) from datatypetestm;
select cidx, CDECIMAL18, RADIANS(CDECIMAL18) from datatypetestm;
select cidx, CDECIMAL18_2, RADIANS(CDECIMAL18_2) from datatypetestm;
select cidx, CINTEGER, RADIANS(CINTEGER) from datatypetestm;
select cidx, CSMALLINT, RADIANS(CSMALLINT) from datatypetestm;
select cidx, CTINYINT, RADIANS(CTINYINT) from datatypetestm;
select cidx, RADIANS(0) from datatypetestm;
select cidx, RADIANS(60) from datatypetestm;
select cidx, RADIANS(90) from datatypetestm;
select cidx, RADIANS(180) from datatypetestm;
select cidx, RADIANS(360) from datatypetestm;
select cidx, CBIGINT from datatypetestm where RADIANS(CBIGINT) <> 0;
select cidx, CDECIMAL1 from datatypetestm where RADIANS(CDECIMAL1) <> 0;
select cidx, CDECIMAL4 from datatypetestm where RADIANS(CDECIMAL4) <> 0;
select cidx, CDECIMAL4_2 from datatypetestm where RADIANS(CDECIMAL4_2) <> 0;
select cidx, CDECIMAL5 from datatypetestm where RADIANS(CDECIMAL5) <> 0;
select cidx, CDECIMAL9 from datatypetestm where RADIANS(CDECIMAL9) <> 0;
select cidx, CDECIMAL9_2 from datatypetestm where RADIANS(CDECIMAL9_2) <> 0;
select cidx, CDECIMAL10 from datatypetestm where RADIANS(CDECIMAL10) <> 0;
select cidx, CDECIMAL18 from datatypetestm where RADIANS(CDECIMAL18) <> 0;
select cidx, CDECIMAL18_2 from datatypetestm where RADIANS(CDECIMAL18_2) <> 0;
select cidx, CINTEGER from datatypetestm where RADIANS(CINTEGER) <> 0;
select cidx, CSMALLINT from datatypetestm where RADIANS(CSMALLINT) <> 0;
select cidx, CTINYINT from datatypetestm where RADIANS(CTINYINT) <> 0;
