select cidx, CBIGINT, CBIGINT REGEXP '99$' from datatypetestm;
select cidx, CBIGINT, CBIGINT REGEXP '\.99$' from datatypetestm;
select cidx, CBIGINT, CBIGINT REGEXP '03$' from datatypetestm;
select cidx, CBIGINT, CBIGINT REGEXP '\.+' from datatypetestm;
select cidx, CBIGINT, CBIGINT REGEXP '(-7)*' from datatypetestm;
select cidx, CBIGINT, CBIGINT REGEXP '0?' from datatypetestm;
select cidx, CBIGINT, CBIGINT REGEXP '-26' from datatypetestm;
select cidx, CDECIMAL1, CDECIMAL1 REGEXP '99$' from datatypetestm;
select cidx, CDECIMAL1, CDECIMAL1 REGEXP '\.99$' from datatypetestm;
select cidx, CDECIMAL1, CDECIMAL1 REGEXP '03$' from datatypetestm;
select cidx, CDECIMAL1, CDECIMAL1 REGEXP '\.+' from datatypetestm;
select cidx, CDECIMAL1, CDECIMAL1 REGEXP '(-7)*' from datatypetestm;
select cidx, CDECIMAL1, CDECIMAL1 REGEXP '0?' from datatypetestm;
select cidx, CDECIMAL1, CDECIMAL1 REGEXP '-26' from datatypetestm;
select cidx, CDECIMAL4, CDECIMAL4 REGEXP '99$' from datatypetestm;
select cidx, CDECIMAL4, CDECIMAL4 REGEXP '\.99$' from datatypetestm;
select cidx, CDECIMAL4, CDECIMAL4 REGEXP '03$' from datatypetestm;
select cidx, CDECIMAL4, CDECIMAL4 REGEXP '\.+' from datatypetestm;
select cidx, CDECIMAL4, CDECIMAL4 REGEXP '(-7)*' from datatypetestm;
select cidx, CDECIMAL4, CDECIMAL4 REGEXP '0?' from datatypetestm;
select cidx, CDECIMAL4, CDECIMAL4 REGEXP '-26' from datatypetestm;
select cidx, CDECIMAL4_2, CDECIMAL4_2 REGEXP '99$' from datatypetestm;
select cidx, CDECIMAL4_2, CDECIMAL4_2 REGEXP '\.99$' from datatypetestm;
select cidx, CDECIMAL4_2, CDECIMAL4_2 REGEXP '03$' from datatypetestm;
select cidx, CDECIMAL4_2, CDECIMAL4_2 REGEXP '\.+' from datatypetestm;
select cidx, CDECIMAL4_2, CDECIMAL4_2 REGEXP '(-7)*' from datatypetestm;
select cidx, CDECIMAL4_2, CDECIMAL4_2 REGEXP '0?' from datatypetestm;
select cidx, CDECIMAL4_2, CDECIMAL4_2 REGEXP '-26' from datatypetestm;
select cidx, CDECIMAL5, CDECIMAL5 REGEXP '99$' from datatypetestm;
select cidx, CDECIMAL5, CDECIMAL5 REGEXP '\.99$' from datatypetestm;
select cidx, CDECIMAL5, CDECIMAL5 REGEXP '03$' from datatypetestm;
select cidx, CDECIMAL5, CDECIMAL5 REGEXP '\.+' from datatypetestm;
select cidx, CDECIMAL5, CDECIMAL5 REGEXP '(-7)*' from datatypetestm;
select cidx, CDECIMAL5, CDECIMAL5 REGEXP '0?' from datatypetestm;
select cidx, CDECIMAL5, CDECIMAL5 REGEXP '-26' from datatypetestm;
select cidx, CDECIMAL9, CDECIMAL9 REGEXP '99$' from datatypetestm;
select cidx, CDECIMAL9, CDECIMAL9 REGEXP '\.99$' from datatypetestm;
select cidx, CDECIMAL9, CDECIMAL9 REGEXP '03$' from datatypetestm;
select cidx, CDECIMAL9, CDECIMAL9 REGEXP '\.+' from datatypetestm;
select cidx, CDECIMAL9, CDECIMAL9 REGEXP '(-7)*' from datatypetestm;
select cidx, CDECIMAL9, CDECIMAL9 REGEXP '0?' from datatypetestm;
select cidx, CDECIMAL9, CDECIMAL9 REGEXP '-26' from datatypetestm;
select cidx, CDECIMAL9_2, CDECIMAL9_2 REGEXP '99$' from datatypetestm;
select cidx, CDECIMAL9_2, CDECIMAL9_2 REGEXP '\.99$' from datatypetestm;
select cidx, CDECIMAL9_2, CDECIMAL9_2 REGEXP '03$' from datatypetestm;
select cidx, CDECIMAL9_2, CDECIMAL9_2 REGEXP '\.+' from datatypetestm;
select cidx, CDECIMAL9_2, CDECIMAL9_2 REGEXP '(-7)*' from datatypetestm;
select cidx, CDECIMAL9_2, CDECIMAL9_2 REGEXP '0?' from datatypetestm;
select cidx, CDECIMAL9_2, CDECIMAL9_2 REGEXP '-26' from datatypetestm;
select cidx, CDECIMAL10, CDECIMAL10 REGEXP '99$' from datatypetestm;
select cidx, CDECIMAL10, CDECIMAL10 REGEXP '\.99$' from datatypetestm;
select cidx, CDECIMAL10, CDECIMAL10 REGEXP '03$' from datatypetestm;
select cidx, CDECIMAL10, CDECIMAL10 REGEXP '\.+' from datatypetestm;
select cidx, CDECIMAL10, CDECIMAL10 REGEXP '(-7)*' from datatypetestm;
select cidx, CDECIMAL10, CDECIMAL10 REGEXP '0?' from datatypetestm;
select cidx, CDECIMAL10, CDECIMAL10 REGEXP '-26' from datatypetestm;
select cidx, CDECIMAL18, CDECIMAL18 REGEXP '99$' from datatypetestm;
select cidx, CDECIMAL18, CDECIMAL18 REGEXP '\.99$' from datatypetestm;
select cidx, CDECIMAL18, CDECIMAL18 REGEXP '03$' from datatypetestm;
select cidx, CDECIMAL18, CDECIMAL18 REGEXP '\.+' from datatypetestm;
select cidx, CDECIMAL18, CDECIMAL18 REGEXP '(-7)*' from datatypetestm;
select cidx, CDECIMAL18, CDECIMAL18 REGEXP '0?' from datatypetestm;
select cidx, CDECIMAL18, CDECIMAL18 REGEXP '-26' from datatypetestm;
select cidx, CDECIMAL18_2, CDECIMAL18_2 REGEXP '99$' from datatypetestm;
select cidx, CDECIMAL18_2, CDECIMAL18_2 REGEXP '\.99$' from datatypetestm;
select cidx, CDECIMAL18_2, CDECIMAL18_2 REGEXP '03$' from datatypetestm;
select cidx, CDECIMAL18_2, CDECIMAL18_2 REGEXP '\.+' from datatypetestm;
select cidx, CDECIMAL18_2, CDECIMAL18_2 REGEXP '(-7)*' from datatypetestm;
select cidx, CDECIMAL18_2, CDECIMAL18_2 REGEXP '0?' from datatypetestm;
select cidx, CDECIMAL18_2, CDECIMAL18_2 REGEXP '-26' from datatypetestm;
select cidx, CINTEGER, CINTEGER REGEXP '99$' from datatypetestm;
select cidx, CINTEGER, CINTEGER REGEXP '\.99$' from datatypetestm;
select cidx, CINTEGER, CINTEGER REGEXP '03$' from datatypetestm;
select cidx, CINTEGER, CINTEGER REGEXP '\.+' from datatypetestm;
select cidx, CINTEGER, CINTEGER REGEXP '(-7)*' from datatypetestm;
select cidx, CINTEGER, CINTEGER REGEXP '0?' from datatypetestm;
select cidx, CINTEGER, CINTEGER REGEXP '-26' from datatypetestm;
select cidx, CSMALLINT, CSMALLINT REGEXP '99$' from datatypetestm;
select cidx, CSMALLINT, CSMALLINT REGEXP '\.99$' from datatypetestm;
select cidx, CSMALLINT, CSMALLINT REGEXP '03$' from datatypetestm;
select cidx, CSMALLINT, CSMALLINT REGEXP '\.+' from datatypetestm;
select cidx, CSMALLINT, CSMALLINT REGEXP '(-7)*' from datatypetestm;
select cidx, CSMALLINT, CSMALLINT REGEXP '0?' from datatypetestm;
select cidx, CSMALLINT, CSMALLINT REGEXP '-26' from datatypetestm;
select cidx, CTINYINT, CTINYINT REGEXP '99$' from datatypetestm;
select cidx, CTINYINT, CTINYINT REGEXP '\.99$' from datatypetestm;
select cidx, CTINYINT, CTINYINT REGEXP '03$' from datatypetestm;
select cidx, CTINYINT, CTINYINT REGEXP '\.+' from datatypetestm;
select cidx, CTINYINT, CTINYINT REGEXP '(-7)*' from datatypetestm;
select cidx, CTINYINT, CTINYINT REGEXP '0?' from datatypetestm;
select cidx, CTINYINT, CTINYINT REGEXP '-26' from datatypetestm;
select cidx, CBIGINT from datatypetestm where CBIGINT REGEXP '99$' <> CBIGINT;
select cidx, CBIGINT from datatypetestm where CBIGINT REGEXP '\.99$' <> CBIGINT;
select cidx, CBIGINT from datatypetestm where CBIGINT REGEXP '03$' <> CBIGINT;
select cidx, CBIGINT from datatypetestm where CBIGINT REGEXP '\.+' <> CBIGINT;
select cidx, CBIGINT from datatypetestm where CBIGINT REGEXP '(-7)*' <> CBIGINT;
select cidx, CBIGINT from datatypetestm where CBIGINT REGEXP '0?' <> CBIGINT;
select cidx, CBIGINT from datatypetestm where CBIGINT REGEXP '-26' <> CBIGINT;
select cidx, CDECIMAL1 from datatypetestm where CDECIMAL1 REGEXP '99$' <> CDECIMAL1;
select cidx, CDECIMAL1 from datatypetestm where CDECIMAL1 REGEXP '\.99$' <> CDECIMAL1;
select cidx, CDECIMAL1 from datatypetestm where CDECIMAL1 REGEXP '03$' <> CDECIMAL1;
select cidx, CDECIMAL1 from datatypetestm where CDECIMAL1 REGEXP '\.+' <> CDECIMAL1;
select cidx, CDECIMAL1 from datatypetestm where CDECIMAL1 REGEXP '(-7)*' <> CDECIMAL1;
select cidx, CDECIMAL1 from datatypetestm where CDECIMAL1 REGEXP '0?' <> CDECIMAL1;
select cidx, CDECIMAL1 from datatypetestm where CDECIMAL1 REGEXP '-26' <> CDECIMAL1;
select cidx, CDECIMAL4 from datatypetestm where CDECIMAL4 REGEXP '99$' <> CDECIMAL4;
select cidx, CDECIMAL4 from datatypetestm where CDECIMAL4 REGEXP '\.99$' <> CDECIMAL4;
select cidx, CDECIMAL4 from datatypetestm where CDECIMAL4 REGEXP '03$' <> CDECIMAL4;
select cidx, CDECIMAL4 from datatypetestm where CDECIMAL4 REGEXP '\.+' <> CDECIMAL4;
select cidx, CDECIMAL4 from datatypetestm where CDECIMAL4 REGEXP '(-7)*' <> CDECIMAL4;
select cidx, CDECIMAL4 from datatypetestm where CDECIMAL4 REGEXP '0?' <> CDECIMAL4;
select cidx, CDECIMAL4 from datatypetestm where CDECIMAL4 REGEXP '-26' <> CDECIMAL4;
select cidx, CDECIMAL4_2 from datatypetestm where CDECIMAL4_2 REGEXP '99$' <> CDECIMAL4_2;
select cidx, CDECIMAL4_2 from datatypetestm where CDECIMAL4_2 REGEXP '\.99$' <> CDECIMAL4_2;
select cidx, CDECIMAL4_2 from datatypetestm where CDECIMAL4_2 REGEXP '03$' <> CDECIMAL4_2;
select cidx, CDECIMAL4_2 from datatypetestm where CDECIMAL4_2 REGEXP '\.+' <> CDECIMAL4_2;
select cidx, CDECIMAL4_2 from datatypetestm where CDECIMAL4_2 REGEXP '(-7)*' <> CDECIMAL4_2;
select cidx, CDECIMAL4_2 from datatypetestm where CDECIMAL4_2 REGEXP '0?' <> CDECIMAL4_2;
select cidx, CDECIMAL4_2 from datatypetestm where CDECIMAL4_2 REGEXP '-26' <> CDECIMAL4_2;
select cidx, CDECIMAL5 from datatypetestm where CDECIMAL5 REGEXP '99$' <> CDECIMAL5;
select cidx, CDECIMAL5 from datatypetestm where CDECIMAL5 REGEXP '\.99$' <> CDECIMAL5;
select cidx, CDECIMAL5 from datatypetestm where CDECIMAL5 REGEXP '03$' <> CDECIMAL5;
select cidx, CDECIMAL5 from datatypetestm where CDECIMAL5 REGEXP '\.+' <> CDECIMAL5;
select cidx, CDECIMAL5 from datatypetestm where CDECIMAL5 REGEXP '(-7)*' <> CDECIMAL5;
select cidx, CDECIMAL5 from datatypetestm where CDECIMAL5 REGEXP '0?' <> CDECIMAL5;
select cidx, CDECIMAL5 from datatypetestm where CDECIMAL5 REGEXP '-26' <> CDECIMAL5;
select cidx, CDECIMAL9 from datatypetestm where CDECIMAL9 REGEXP '99$' <> CDECIMAL9;
select cidx, CDECIMAL9 from datatypetestm where CDECIMAL9 REGEXP '\.99$' <> CDECIMAL9;
select cidx, CDECIMAL9 from datatypetestm where CDECIMAL9 REGEXP '03$' <> CDECIMAL9;
select cidx, CDECIMAL9 from datatypetestm where CDECIMAL9 REGEXP '\.+' <> CDECIMAL9;
select cidx, CDECIMAL9 from datatypetestm where CDECIMAL9 REGEXP '(-7)*' <> CDECIMAL9;
select cidx, CDECIMAL9 from datatypetestm where CDECIMAL9 REGEXP '0?' <> CDECIMAL9;
select cidx, CDECIMAL9 from datatypetestm where CDECIMAL9 REGEXP '-26' <> CDECIMAL9;
select cidx, CDECIMAL9_2 from datatypetestm where CDECIMAL9_2 REGEXP '99$' <> CDECIMAL9_2;
select cidx, CDECIMAL9_2 from datatypetestm where CDECIMAL9_2 REGEXP '\.99$' <> CDECIMAL9_2;
select cidx, CDECIMAL9_2 from datatypetestm where CDECIMAL9_2 REGEXP '03$' <> CDECIMAL9_2;
select cidx, CDECIMAL9_2 from datatypetestm where CDECIMAL9_2 REGEXP '\.+' <> CDECIMAL9_2;
select cidx, CDECIMAL9_2 from datatypetestm where CDECIMAL9_2 REGEXP '(-7)*' <> CDECIMAL9_2;
select cidx, CDECIMAL9_2 from datatypetestm where CDECIMAL9_2 REGEXP '0?' <> CDECIMAL9_2;
select cidx, CDECIMAL9_2 from datatypetestm where CDECIMAL9_2 REGEXP '-26' <> CDECIMAL9_2;
select cidx, CDECIMAL10 from datatypetestm where CDECIMAL10 REGEXP '99$' <> CDECIMAL10;
select cidx, CDECIMAL10 from datatypetestm where CDECIMAL10 REGEXP '\.99$' <> CDECIMAL10;
select cidx, CDECIMAL10 from datatypetestm where CDECIMAL10 REGEXP '03$' <> CDECIMAL10;
select cidx, CDECIMAL10 from datatypetestm where CDECIMAL10 REGEXP '\.+' <> CDECIMAL10;
select cidx, CDECIMAL10 from datatypetestm where CDECIMAL10 REGEXP '(-7)*' <> CDECIMAL10;
select cidx, CDECIMAL10 from datatypetestm where CDECIMAL10 REGEXP '0?' <> CDECIMAL10;
select cidx, CDECIMAL10 from datatypetestm where CDECIMAL10 REGEXP '-26' <> CDECIMAL10;
select cidx, CDECIMAL18 from datatypetestm where CDECIMAL18 REGEXP '99$' <> CDECIMAL18;
select cidx, CDECIMAL18 from datatypetestm where CDECIMAL18 REGEXP '\.99$' <> CDECIMAL18;
select cidx, CDECIMAL18 from datatypetestm where CDECIMAL18 REGEXP '03$' <> CDECIMAL18;
select cidx, CDECIMAL18 from datatypetestm where CDECIMAL18 REGEXP '\.+' <> CDECIMAL18;
select cidx, CDECIMAL18 from datatypetestm where CDECIMAL18 REGEXP '(-7)*' <> CDECIMAL18;
select cidx, CDECIMAL18 from datatypetestm where CDECIMAL18 REGEXP '0?' <> CDECIMAL18;
select cidx, CDECIMAL18 from datatypetestm where CDECIMAL18 REGEXP '-26' <> CDECIMAL18;
select cidx, CDECIMAL18_2 from datatypetestm where CDECIMAL18_2 REGEXP '99$' <> CDECIMAL18_2;
select cidx, CDECIMAL18_2 from datatypetestm where CDECIMAL18_2 REGEXP '\.99$' <> CDECIMAL18_2;
select cidx, CDECIMAL18_2 from datatypetestm where CDECIMAL18_2 REGEXP '03$' <> CDECIMAL18_2;
select cidx, CDECIMAL18_2 from datatypetestm where CDECIMAL18_2 REGEXP '\.+' <> CDECIMAL18_2;
select cidx, CDECIMAL18_2 from datatypetestm where CDECIMAL18_2 REGEXP '(-7)*' <> CDECIMAL18_2;
select cidx, CDECIMAL18_2 from datatypetestm where CDECIMAL18_2 REGEXP '0?' <> CDECIMAL18_2;
select cidx, CDECIMAL18_2 from datatypetestm where CDECIMAL18_2 REGEXP '-26' <> CDECIMAL18_2;
select cidx, CINTEGER from datatypetestm where CINTEGER REGEXP '99$' <> CINTEGER;
select cidx, CINTEGER from datatypetestm where CINTEGER REGEXP '\.99$' <> CINTEGER;
select cidx, CINTEGER from datatypetestm where CINTEGER REGEXP '03$' <> CINTEGER;
select cidx, CINTEGER from datatypetestm where CINTEGER REGEXP '\.+' <> CINTEGER;
select cidx, CINTEGER from datatypetestm where CINTEGER REGEXP '(-7)*' <> CINTEGER;
select cidx, CINTEGER from datatypetestm where CINTEGER REGEXP '0?' <> CINTEGER;
select cidx, CINTEGER from datatypetestm where CINTEGER REGEXP '-26' <> CINTEGER;
select cidx, CSMALLINT from datatypetestm where CSMALLINT REGEXP '99$' <> CSMALLINT;
select cidx, CSMALLINT from datatypetestm where CSMALLINT REGEXP '\.99$' <> CSMALLINT;
select cidx, CSMALLINT from datatypetestm where CSMALLINT REGEXP '03$' <> CSMALLINT;
select cidx, CSMALLINT from datatypetestm where CSMALLINT REGEXP '\.+' <> CSMALLINT;
select cidx, CSMALLINT from datatypetestm where CSMALLINT REGEXP '(-7)*' <> CSMALLINT;
select cidx, CSMALLINT from datatypetestm where CSMALLINT REGEXP '0?' <> CSMALLINT;
select cidx, CSMALLINT from datatypetestm where CSMALLINT REGEXP '-26' <> CSMALLINT;
select cidx, CTINYINT from datatypetestm where CTINYINT REGEXP '99$' <> CTINYINT;
select cidx, CTINYINT from datatypetestm where CTINYINT REGEXP '\.99$' <> CTINYINT;
select cidx, CTINYINT from datatypetestm where CTINYINT REGEXP '03$' <> CTINYINT;
select cidx, CTINYINT from datatypetestm where CTINYINT REGEXP '\.+' <> CTINYINT;
select cidx, CTINYINT from datatypetestm where CTINYINT REGEXP '(-7)*' <> CTINYINT;
select cidx, CTINYINT from datatypetestm where CTINYINT REGEXP '0?' <> CTINYINT;
select cidx, CTINYINT from datatypetestm where CTINYINT REGEXP '-26' <> CTINYINT;
