select cidx, CCHAR1, REPEAT(CCHAR1,1) from datatypetestm;
select cidx, CCHAR1, REPEAT(CCHAR1,0) from datatypetestm;
select cidx, CCHAR1, REPEAT(CCHAR1,1) from datatypetestm;
select cidx, CCHAR1, REPEAT(CCHAR1,100) from datatypetestm;
select cidx, CCHAR7, REPEAT(CCHAR7,2) from datatypetestm;
select cidx, CCHAR8, REPEAT(CCHAR8,7) from datatypetestm;
select cidx, CCHAR9, REPEAT(CCHAR9,4) from datatypetestm;
select cidx, CCHAR9, REPEAT(CCHAR9,10) from datatypetestm;
select cidx, CCHAR255, REPEAT(CCHAR255,2) from datatypetestm;
select cidx, CVCHAR1, REPEAT(CVCHAR1,6) from datatypetestm;
select cidx, CVCHAR6, REPEAT(CVCHAR6,9) from datatypetestm;
select cidx, CVCHAR255, REPEAT(CVCHAR255,6) from datatypetestm;
select cidx, CVCHAR255, REPEAT(CVCHAR255,1) from datatypetestm;
select cidx, CCHAR1 from datatypetestm where REPEAT(CCHAR1,1) <> "a";
select cidx, CCHAR5 from datatypetestm where REPEAT(CCHAR5,2) <> "a";
select cidx, CCHAR9 from datatypetestm where REPEAT(CCHAR9,3) <> "a";
select cidx, CCHAR9 from datatypetestm where REPEAT(CCHAR9,1) <> "a";
select cidx, CCHAR9 from datatypetestm where REPEAT(CCHAR9,5) <> "a";
select cidx, CCHAR255 from datatypetestm where REPEAT(CCHAR255,1) <> "a";
select cidx, CBIGINT, REPEAT(CBIGINT,-5) from datatypetestm order by cidx;
select repeat(cchar8, cidx) from datatypetestm order by 1;
