select cidx, CCHAR1, REPLACE(CCHAR1,'a','II') from datatypetestm;
select cidx, CCHAR1, REPLACE(CCHAR1,'zz','JJ') from datatypetestm;
select cidx, CCHAR2, REPLACE(CCHAR2,'a','II') from datatypetestm;
select cidx, CCHAR2, REPLACE(CCHAR2,'zz','JJ') from datatypetestm;
select cidx, CCHAR3, REPLACE(CCHAR3,'a','II') from datatypetestm;
select cidx, CCHAR3, REPLACE(CCHAR3,'zz','JJ') from datatypetestm;
select cidx, CCHAR4, REPLACE(CCHAR4,'a','II') from datatypetestm;
select cidx, CCHAR4, REPLACE(CCHAR4,'zz','JJ') from datatypetestm;
select cidx, CCHAR5, REPLACE(CCHAR5,'a','II') from datatypetestm;
select cidx, CCHAR5, REPLACE(CCHAR5,'zz','JJ') from datatypetestm;
select cidx, CCHAR6, REPLACE(CCHAR6,'a','II') from datatypetestm;
select cidx, CCHAR6, REPLACE(CCHAR6,'zz','JJ') from datatypetestm;
select cidx, CCHAR7, REPLACE(CCHAR7,'a','II') from datatypetestm;
select cidx, CCHAR7, REPLACE(CCHAR7,'zz','JJ') from datatypetestm;
select cidx, CCHAR8, REPLACE(CCHAR8,'a','II') from datatypetestm;
select cidx, CCHAR8, REPLACE(CCHAR8,'zz','JJ') from datatypetestm;
select cidx, CCHAR9, REPLACE(CCHAR9,'a','II') from datatypetestm;
select cidx, CCHAR9, REPLACE(CCHAR9,'zz','JJ') from datatypetestm;
select cidx, CCHAR255, REPLACE(CCHAR255,'a','II') from datatypetestm;
select cidx, CCHAR255, REPLACE(CCHAR255,'zz','JJ') from datatypetestm;
select cidx, CVCHAR1, REPLACE(CVCHAR1,'a','II') from datatypetestm;
select cidx, CVCHAR1, REPLACE(CVCHAR1,'zz','JJ') from datatypetestm;
select cidx, CVCHAR2, REPLACE(CVCHAR2,'a','II') from datatypetestm;
select cidx, CVCHAR2, REPLACE(CVCHAR2,'zz','JJ') from datatypetestm;
select cidx, CVCHAR3, REPLACE(CVCHAR3,'a','II') from datatypetestm;
select cidx, CVCHAR3, REPLACE(CVCHAR3,'zz','JJ') from datatypetestm;
select cidx, CVCHAR4, REPLACE(CVCHAR4,'a','II') from datatypetestm;
select cidx, CVCHAR4, REPLACE(CVCHAR4,'zz','JJ') from datatypetestm;
select cidx, CVCHAR5, REPLACE(CVCHAR5,'a','II') from datatypetestm;
select cidx, CVCHAR5, REPLACE(CVCHAR5,'zz','JJ') from datatypetestm;
select cidx, CVCHAR6, REPLACE(CVCHAR6,'a','II') from datatypetestm;
select cidx, CVCHAR6, REPLACE(CVCHAR6,'zz','JJ') from datatypetestm;
select cidx, CVCHAR7, REPLACE(CVCHAR7,'a','II') from datatypetestm;
select cidx, CVCHAR7, REPLACE(CVCHAR7,'zz','JJ') from datatypetestm;
select cidx, CVCHAR8, REPLACE(CVCHAR8,'a','II') from datatypetestm;
select cidx, CVCHAR8, REPLACE(CVCHAR8,'zz','JJ') from datatypetestm;
select cidx, CVCHAR255, REPLACE(CVCHAR255,'a','II') from datatypetestm;
select cidx, CVCHAR255, REPLACE(CVCHAR255,'zz','JJ') from datatypetestm;
select cidx, CCHAR1 from datatypetestm where REPLACE(CCHAR1,'a','II') <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where REPLACE(CCHAR1,'zz','JJ') <> CCHAR1;
select cidx, CCHAR2 from datatypetestm where REPLACE(CCHAR2,'a','II') <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where REPLACE(CCHAR2,'zz','JJ') <> CCHAR2;
select cidx, CCHAR3 from datatypetestm where REPLACE(CCHAR3,'a','II') <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where REPLACE(CCHAR3,'zz','JJ') <> CCHAR3;
select cidx, CCHAR4 from datatypetestm where REPLACE(CCHAR4,'a','II') <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where REPLACE(CCHAR4,'zz','JJ') <> CCHAR4;
select cidx, CCHAR5 from datatypetestm where REPLACE(CCHAR5,'a','II') <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where REPLACE(CCHAR5,'zz','JJ') <> CCHAR5;
select cidx, CCHAR6 from datatypetestm where REPLACE(CCHAR6,'a','II') <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where REPLACE(CCHAR6,'zz','JJ') <> CCHAR6;
select cidx, CCHAR7 from datatypetestm where REPLACE(CCHAR7,'a','II') <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where REPLACE(CCHAR7,'zz','JJ') <> CCHAR7;
select cidx, CCHAR8 from datatypetestm where REPLACE(CCHAR8,'a','II') <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where REPLACE(CCHAR8,'zz','JJ') <> CCHAR8;
select cidx, CCHAR9 from datatypetestm where REPLACE(CCHAR9,'a','II') <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where REPLACE(CCHAR9,'zz','JJ') <> CCHAR9;
select cidx, CCHAR255 from datatypetestm where REPLACE(CCHAR255,'a','II') <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where REPLACE(CCHAR255,'zz','JJ') <> CCHAR255;
select cidx, CVCHAR1 from datatypetestm where REPLACE(CVCHAR1,'a','II') <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where REPLACE(CVCHAR1,'zz','JJ') <> CVCHAR1;
select cidx, CVCHAR2 from datatypetestm where REPLACE(CVCHAR2,'a','II') <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where REPLACE(CVCHAR2,'zz','JJ') <> CVCHAR2;
select cidx, CVCHAR3 from datatypetestm where REPLACE(CVCHAR3,'a','II') <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where REPLACE(CVCHAR3,'zz','JJ') <> CVCHAR3;
select cidx, CVCHAR4 from datatypetestm where REPLACE(CVCHAR4,'a','II') <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where REPLACE(CVCHAR4,'zz','JJ') <> CVCHAR4;
select cidx, CVCHAR5 from datatypetestm where REPLACE(CVCHAR5,'a','II') <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where REPLACE(CVCHAR5,'zz','JJ') <> CVCHAR5;
select cidx, CVCHAR6 from datatypetestm where REPLACE(CVCHAR6,'a','II') <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where REPLACE(CVCHAR6,'zz','JJ') <> CVCHAR6;
select cidx, CVCHAR7 from datatypetestm where REPLACE(CVCHAR7,'a','II') <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where REPLACE(CVCHAR7,'zz','JJ') <> CVCHAR7;
select cidx, CVCHAR8 from datatypetestm where REPLACE(CVCHAR8,'a','II') <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where REPLACE(CVCHAR8,'zz','JJ') <> CVCHAR8;
select cidx, CVCHAR255 from datatypetestm where REPLACE(CVCHAR255,'a','II') <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where REPLACE(CVCHAR255,'zz','JJ') <> CVCHAR255;
