select n_name, REVERSE(n_name) from nation;
select n_comment, REVERSE(n_comment) from nation;
select cidx, CCHAR1, REVERSE(CCHAR1) from datatypetestm;
select cidx, CCHAR7, REVERSE(CCHAR7) from datatypetestm;
select cidx, CCHAR8, REVERSE(CCHAR8) from datatypetestm;
select cidx, CCHAR9, REVERSE(CCHAR9) from datatypetestm;
select cidx, CCHAR255, REVERSE(CCHAR255) from datatypetestm;
select cidx, CVCHAR1, REVERSE(CVCHAR1) from datatypetestm;
select cidx, CVCHAR6, REVERSE(CVCHAR6) from datatypetestm;
select cidx, CVCHAR255, REVERSE(CVCHAR255) from datatypetestm;
select cidx, CCHAR1 from datatypetestm where REVERSE(CCHAR1) <> "a";
select cidx, CCHAR5 from datatypetestm where REVERSE(CCHAR5) <> "a";
select cidx, CCHAR9 from datatypetestm where REVERSE(CCHAR9) <> "a";
select cidx, CCHAR255 from datatypetestm where REVERSE(CCHAR255) <> "a";
select n_name, REVERSE(n_name) from nation where REVERSE(n_name) <> "a";
select n_comment, REVERSE(n_comment) from nation where REVERSE(n_comment) <> "a";
