select cidx, CDATETIME, TIME_TO_SEC(CDATETIME) from datatypetestm;
select cidx, CDATETIME, TIME_TO_SEC(CDATETIME) from datatypetestm;
select cidx, CDATETIME, TIME_TO_SEC(CDATETIME) from datatypetestm;
select cidx, CDATETIME, TIME_TO_SEC(CDATETIME) from datatypetestm;
select cidx, CDATETIME, TIME_TO_SEC(CDATETIME) from datatypetestm;
select cidx, CDATETIME, TIME_TO_SEC(CDATETIME) from datatypetestm;
select cidx, CDATETIME, TIME_TO_SEC(CDATETIME) from datatypetestm;
select cidx, CDATETIME, TIME_TO_SEC(CDATETIME) from datatypetestm;
select cidx, CDATETIME from datatypetestm where TIME_TO_SEC(CDATETIME) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where TIME_TO_SEC(CDATETIME) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where TIME_TO_SEC(CDATETIME) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where TIME_TO_SEC(CDATETIME) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where TIME_TO_SEC(CDATETIME) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where TIME_TO_SEC(CDATETIME) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where TIME_TO_SEC(CDATETIME) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where TIME_TO_SEC(CDATETIME) <> CDATETIME;
