select cidx, CDATE, WEEK(CDATE,0) from datatypetestm;
select cidx, CDATE, WEEK(CDATE,1) from datatypetestm;
select cidx, CDATE, WEEK(CDATE,2) from datatypetestm;
select cidx, CDATE, WEEK(CDATE,3) from datatypetestm;
select cidx, CDATE, WEEK(CDATE,4) from datatypetestm;
select cidx, CDATE, WEEK(CDATE,5) from datatypetestm;
select cidx, CDATE, WEEK(CDATE,6) from datatypetestm;
select cidx, CDATE, WEEK(CDATE,7) from datatypetestm;
select cidx, CDATETIME, WEEK(CDATETIME,0) from datatypetestm;
select cidx, CDATETIME, WEEK(CDATETIME,1) from datatypetestm;
select cidx, CDATETIME, WEEK(CDATETIME,2) from datatypetestm;
select cidx, CDATETIME, WEEK(CDATETIME,3) from datatypetestm;
select cidx, CDATETIME, WEEK(CDATETIME,4) from datatypetestm;
select cidx, CDATETIME, WEEK(CDATETIME,5) from datatypetestm;
select cidx, CDATETIME, WEEK(CDATETIME,6) from datatypetestm;
select cidx, CDATETIME, WEEK(CDATETIME,7) from datatypetestm;
select cidx, CDATE from datatypetestm where WEEK(CDATE,0) <> CDATE;
select cidx, CDATE from datatypetestm where WEEK(CDATE,1) <> CDATE;
select cidx, CDATE from datatypetestm where WEEK(CDATE,2) <> CDATE;
select cidx, CDATE from datatypetestm where WEEK(CDATE,3) <> CDATE;
select cidx, CDATE from datatypetestm where WEEK(CDATE,4) <> CDATE;
select cidx, CDATE from datatypetestm where WEEK(CDATE,5) <> CDATE;
select cidx, CDATE from datatypetestm where WEEK(CDATE,6) <> CDATE;
select cidx, CDATE from datatypetestm where WEEK(CDATE,7) <> CDATE;
select cidx, CDATETIME from datatypetestm where WEEK(CDATETIME,0) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where WEEK(CDATETIME,1) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where WEEK(CDATETIME,2) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where WEEK(CDATETIME,3) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where WEEK(CDATETIME,4) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where WEEK(CDATETIME,5) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where WEEK(CDATETIME,6) <> CDATETIME;
select cidx, CDATETIME from datatypetestm where WEEK(CDATETIME,7) <> CDATETIME;
