set autocommit=0;
select * from region where r_regionkey=1;
update region set r_comment='xxx' where r_regionkey=1;
select * from region where r_regionkey=1;
rollback;
select * from region where r_regionkey=1;
update region set r_comment='xxx' where r_regionkey=1;
select * from region where r_regionkey=1;
rollback;
select * from region where r_regionkey=1;
