SELECT ROW_NUMBER() OVER (PARTITION BY depname), salary, empno, depname from empsalary3 where empno < 10000;
SELECT ROW_NUMBER() OVER (PARTITION BY depname ORDER BY empno), salary, empno, depname from empsalary3 where empno < 10000;

SELECT ROW_NUMBER() OVER (PARTITION BY depname ORDER BY salary NULLS FIRST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT ROW_NUMBER() OVER (PARTITION BY depname ORDER BY salary NULLS LAST), salary, empno, depname from empsalary3 where empno < 10000;

SELECT ROW_NUMBER() OVER (PARTITION BY depname ORDER BY salary RANGE UNBOUNDED preceding), salary, empno, depname from empsalary3 where empno < 10000;
SELECT ROW_NUMBER() OVER (PARTITION BY depname ORDER BY empno ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT ROW_NUMBER() OVER (PARTITION BY depname ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT ROW_NUMBER() OVER (PARTITION BY depname ORDER BY  enroll_date ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT ROW_NUMBER() OVER (PARTITION BY depname ORDER BY  enroll_date ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT ROW_NUMBER() OVER (PARTITION BY depname ORDER BY  enroll_date RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT RANK() OVER (PARTITION BY depname), salary, empno, depname from empsalary3 where empno < 10000;
SELECT RANK() OVER (PARTITION BY depname ORDER BY empno), salary, empno, depname from empsalary3 where empno < 10000;

SELECT RANK() OVER (PARTITION BY depname ORDER BY salary NULLS FIRST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT RANK() OVER (PARTITION BY depname ORDER BY salary NULLS LAST), salary, empno, depname from empsalary3 where empno < 10000;

SELECT RANK() OVER (PARTITION BY depname ORDER BY salary RANGE UNBOUNDED preceding), salary, empno, depname from empsalary3 where empno < 10000;
SELECT RANK() OVER (PARTITION BY depname ORDER BY empno ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT RANK() OVER (PARTITION BY depname ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT RANK() OVER (PARTITION BY depname ORDER BY  enroll_date ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT RANK() OVER (PARTITION BY depname ORDER BY  enroll_date ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT RANK() OVER (PARTITION BY depname ORDER BY  enroll_date RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT DENSE_RANK() OVER (PARTITION BY depname ORDER BY empno), salary, empno, depname from empsalary3 where empno < 10000;

SELECT DENSE_RANK() OVER (PARTITION BY depname ORDER BY salary NULLS FIRST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT DENSE_RANK() OVER (PARTITION BY depname ORDER BY salary NULLS LAST), salary, empno, depname from empsalary3 where empno < 10000;

SELECT DENSE_RANK() OVER (PARTITION BY depname ORDER BY salary RANGE UNBOUNDED preceding), salary, empno, depname from empsalary3 where empno < 10000;
SELECT DENSE_RANK() OVER (PARTITION BY depname ORDER BY empno ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;	
SELECT DENSE_RANK() OVER (PARTITION BY depname ORDER BY  enroll_date ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT DENSE_RANK() OVER (PARTITION BY depname ORDER BY  enroll_date ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT DENSE_RANK() OVER (PARTITION BY depname ORDER BY  enroll_date RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT PERCENT_RANK() OVER (PARTITION BY depname ORDER BY empno), salary, empno, depname from empsalary3 where empno < 10000;
SELECT PERCENT_RANK() OVER (PARTITION BY depname ORDER BY salary NULLS FIRST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT PERCENT_RANK() OVER (PARTITION BY depname ORDER BY salary NULLS LAST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT PERCENT_RANK() OVER (PARTITION BY depname ORDER BY salary RANGE UNBOUNDED preceding), salary, empno, depname from empsalary3 where empno < 10000;
SELECT PERCENT_RANK() OVER (PARTITION BY depname ORDER BY empno ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT PERCENT_RANK() OVER (PARTITION BY depname ORDER BY  enroll_date ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT PERCENT_RANK() OVER (PARTITION BY depname ORDER BY  enroll_date ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT PERCENT_RANK() OVER (PARTITION BY depname ORDER BY  enroll_date RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;

SELECT CUME_DIST(salary) OVER (PARTITION BY depname ORDER BY empno), salary, empno, depname from empsalary3 where empno < 10000;
SELECT CUME_DIST(salary) OVER (PARTITION BY depname ORDER BY salary RANGE UNBOUNDED preceding), salary, empno, depname from empsalary3 where empno < 10000;
SELECT CUME_DIST(salary) OVER (PARTITION BY depname ORDER BY empno ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT CUME_DIST(salary) OVER (PARTITION BY depname ORDER BY  enroll_date ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT CUME_DIST(salary) OVER (PARTITION BY depname ORDER BY  enroll_date ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT CUME_DIST(salary) OVER (PARTITION BY depname ORDER BY  enroll_date RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
							
SELECT VARIANCE(salary) OVER (PARTITION BY depname), salary, empno, depname from empsalary3 where empno < 10000;
SELECT VARIANCE(salary) OVER (PARTITION BY depname ORDER BY empno), salary, empno, depname from empsalary3 where empno < 10000;
SELECT VARIANCE(salary) OVER (PARTITION BY depname ORDER BY salary NULLS FIRST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT VARIANCE(salary) OVER (PARTITION BY depname ORDER BY salary NULLS LAST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT VARIANCE(salary) OVER (PARTITION BY depname ORDER BY salary RANGE UNBOUNDED preceding), salary, empno, depname from empsalary3 where empno < 10000;
SELECT VARIANCE(salary) OVER (PARTITION BY depname ORDER BY empno ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT VARIANCE(salary) OVER (PARTITION BY depname ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT VARIANCE(salary) OVER (PARTITION BY depname ORDER BY  enroll_date ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT VARIANCE(salary) OVER (PARTITION BY depname ORDER BY  enroll_date ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT VARIANCE(salary) OVER (PARTITION BY depname ORDER BY  enroll_date RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT VAR_POP(salary) OVER (PARTITION BY depname), salary, empno, depname from empsalary3 where empno < 10000;
SELECT VAR_POP(salary) OVER (PARTITION BY depname ORDER BY empno), salary, empno, depname from empsalary3 where empno < 10000;
SELECT VAR_POP(salary) OVER (PARTITION BY depname ORDER BY salary NULLS FIRST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT VAR_POP(salary) OVER (PARTITION BY depname ORDER BY salary NULLS LAST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT VAR_POP(salary) OVER (PARTITION BY depname ORDER BY salary RANGE UNBOUNDED preceding), salary, empno, depname from empsalary3 where empno < 10000;
SELECT VAR_POP(salary) OVER (PARTITION BY depname ORDER BY empno ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT VAR_POP(salary) OVER (PARTITION BY depname ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT VAR_POP(salary) OVER (PARTITION BY depname ORDER BY  enroll_date ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT VAR_POP(salary) OVER (PARTITION BY depname ORDER BY  enroll_date ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT VAR_POP(salary) OVER (PARTITION BY depname ORDER BY  enroll_date RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT VAR_SAMP(salary) OVER (PARTITION BY depname), salary, empno, depname from empsalary3 where empno < 10000;
SELECT VAR_SAMP(salary) OVER (PARTITION BY depname ORDER BY empno), salary, empno, depname from empsalary3 where empno < 10000;
SELECT VAR_SAMP(salary) OVER (PARTITION BY depname ORDER BY salary NULLS FIRST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT VAR_SAMP(salary) OVER (PARTITION BY depname ORDER BY salary NULLS LAST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT VAR_SAMP(salary) OVER (PARTITION BY depname ORDER BY salary RANGE UNBOUNDED preceding), salary, empno, depname from empsalary3 where empno < 10000;
SELECT VAR_SAMP(salary) OVER (PARTITION BY depname ORDER BY empno ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT VAR_SAMP(salary) OVER (PARTITION BY depname ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT VAR_SAMP(salary) OVER (PARTITION BY depname ORDER BY  enroll_date ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT VAR_SAMP(salary) OVER (PARTITION BY depname ORDER BY  enroll_date ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT VAR_SAMP(salary) OVER (PARTITION BY depname ORDER BY  enroll_date RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT STDDEV(salary) OVER (PARTITION BY depname), salary, empno, depname from empsalary3 where empno < 10000;
SELECT STDDEV(salary) OVER (PARTITION BY depname ORDER BY empno), salary, empno, depname from empsalary3 where empno < 10000;
SELECT STDDEV(salary) OVER (PARTITION BY depname ORDER BY salary NULLS FIRST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT STDDEV(salary) OVER (PARTITION BY depname ORDER BY salary NULLS LAST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT STDDEV(salary) OVER (PARTITION BY depname ORDER BY salary RANGE UNBOUNDED preceding), salary, empno, depname from empsalary3 where empno < 10000;
SELECT STDDEV(salary) OVER (PARTITION BY depname ORDER BY empno ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT STDDEV(salary) OVER (PARTITION BY depname ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT STDDEV(salary) OVER (PARTITION BY depname ORDER BY  enroll_date ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT STDDEV(salary) OVER (PARTITION BY depname ORDER BY  enroll_date ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT STDDEV(salary) OVER (PARTITION BY depname ORDER BY  enroll_date RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT STDDEV_POP(salary) OVER (PARTITION BY depname), salary, empno, depname from empsalary3 where empno < 10000;
SELECT STDDEV_POP(salary) OVER (PARTITION BY depname ORDER BY empno), salary, empno, depname from empsalary3 where empno < 10000;
SELECT STDDEV_POP(salary) OVER (PARTITION BY depname ORDER BY salary NULLS FIRST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT STDDEV_POP(salary) OVER (PARTITION BY depname ORDER BY salary NULLS LAST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT STDDEV_POP(salary) OVER (PARTITION BY depname ORDER BY salary RANGE UNBOUNDED preceding), salary, empno, depname from empsalary3 where empno < 10000;
SELECT STDDEV_POP(salary) OVER (PARTITION BY depname ORDER BY empno ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT STDDEV_POP(salary) OVER (PARTITION BY depname ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT STDDEV_POP(salary) OVER (PARTITION BY depname ORDER BY  enroll_date ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT STDDEV_POP(salary) OVER (PARTITION BY depname ORDER BY  enroll_date ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;	
SELECT STDDEV_POP(salary) OVER (PARTITION BY depname ORDER BY  enroll_date RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT STDDEV_SAMP(salary) OVER (PARTITION BY depname), salary, empno, depname from empsalary3 where empno < 10000;
SELECT STDDEV_SAMP(salary) OVER (PARTITION BY depname ORDER BY empno), salary, empno, depname from empsalary3 where empno < 10000;
SELECT STDDEV_SAMP(salary) OVER (PARTITION BY depname ORDER BY salary NULLS FIRST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT STDDEV_SAMP(salary) OVER (PARTITION BY depname ORDER BY salary NULLS LAST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT STDDEV_SAMP(salary) OVER (PARTITION BY depname ORDER BY salary RANGE UNBOUNDED preceding), salary, empno, depname from empsalary3 where empno < 10000;
SELECT STDDEV_SAMP(salary) OVER (PARTITION BY depname ORDER BY empno ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT STDDEV_SAMP(salary) OVER (PARTITION BY depname ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT STDDEV_SAMP(salary) OVER (PARTITION BY depname ORDER BY  enroll_date ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT STDDEV_SAMP(salary) OVER (PARTITION BY depname ORDER BY  enroll_date ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT STDDEV_SAMP(salary) OVER (PARTITION BY depname ORDER BY  enroll_date RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT NTH_VALUE(empno, 2) OVER (PARTITION BY depname), salary, empno, depname from empsalary3 where empno < 10000;
SELECT NTH_VALUE(empno, 2) OVER (PARTITION BY depname ORDER BY empno), salary, empno, depname from empsalary3 where empno < 10000;
SELECT NTH_VALUE(empno, 2) OVER (PARTITION BY depname ORDER BY salary NULLS FIRST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT NTH_VALUE(empno, 2) OVER (PARTITION BY depname ORDER BY salary NULLS LAST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT NTH_VALUE(empno, 2) OVER (PARTITION BY depname ORDER BY salary RANGE UNBOUNDED preceding), salary, empno, depname from empsalary3 where empno < 10000;
SELECT NTH_VALUE(empno, 2) OVER (PARTITION BY depname ORDER BY empno ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT NTH_VALUE(empno, 2) OVER (PARTITION BY depname ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT NTH_VALUE(empno, 2) OVER (PARTITION BY depname ORDER BY  enroll_date ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT NTH_VALUE(empno, 2) OVER (PARTITION BY depname ORDER BY  enroll_date ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT NTH_VALUE(empno, 2) OVER (PARTITION BY depname ORDER BY  enroll_date RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT FIRST_VALUE(empno) OVER (PARTITION BY depname), salary, empno, depname from empsalary3 where empno < 10000;
SELECT FIRST_VALUE(empno) OVER (PARTITION BY depname ORDER BY empno), salary, empno, depname from empsalary3 where empno < 10000;
SELECT FIRST_VALUE(empno) OVER (PARTITION BY depname ORDER BY salary NULLS FIRST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT FIRST_VALUE(empno) OVER (PARTITION BY depname ORDER BY salary NULLS LAST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT FIRST_VALUE(empno) OVER (PARTITION BY depname ORDER BY salary RANGE UNBOUNDED preceding), salary, empno, depname from empsalary3 where empno < 10000;
SELECT FIRST_VALUE(empno) OVER (PARTITION BY depname ORDER BY empno ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT FIRST_VALUE(empno) OVER (PARTITION BY depname ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT FIRST_VALUE(empno) OVER (PARTITION BY depname ORDER BY  enroll_date ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT FIRST_VALUE(empno) OVER (PARTITION BY depname ORDER BY  enroll_date ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT FIRST_VALUE(empno) OVER (PARTITION BY depname ORDER BY  enroll_date RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT LAST_VALUE(empno) OVER (PARTITION BY depname), salary, empno, depname from empsalary3 where empno < 10000;
SELECT LAST_VALUE(empno) OVER (PARTITION BY depname ORDER BY empno), salary, empno, depname from empsalary3 where empno < 10000;
SELECT LAST_VALUE(empno) OVER (PARTITION BY depname ORDER BY salary NULLS FIRST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT LAST_VALUE(empno) OVER (PARTITION BY depname ORDER BY salary NULLS LAST), salary, empno, depname from empsalary3 where empno < 10000;
SELECT LAST_VALUE(empno) OVER (PARTITION BY depname ORDER BY salary RANGE UNBOUNDED preceding), salary, empno, depname from empsalary3 where empno < 10000;
SELECT LAST_VALUE(empno) OVER (PARTITION BY depname ORDER BY empno ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT LAST_VALUE(empno) OVER (PARTITION BY depname ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), salary, empno, depname from empsalary3 where empno < 10000;
SELECT LAST_VALUE(empno) OVER (PARTITION BY depname ORDER BY  enroll_date ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT LAST_VALUE(empno) OVER (PARTITION BY depname ORDER BY  enroll_date ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;
SELECT LAST_VALUE(empno) OVER (PARTITION BY depname ORDER BY  enroll_date RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING), salary, empno, enroll_date, depname from empsalary3 where empno < 10000;


