select cidx, CBIGINT, ACOS(CBIGINT) from datatypetestm;
select cidx, CDECIMAL1, ACOS(CDECIMAL1) from datatypetestm;
select cidx, CDECIMAL4, ACOS(CDECIMAL4) from datatypetestm;
select cidx, CDECIMAL4_2, ACOS(CDECIMAL4_2) from datatypetestm;
select cidx, CDECIMAL5, ACOS(CDECIMAL5) from datatypetestm;
select cidx, CDECIMAL9, ACOS(CDECIMAL9) from datatypetestm;
select cidx, CDECIMAL9_2, ACOS(CDECIMAL9_2) from datatypetestm;
select cidx, CDECIMAL10, ACOS(CDECIMAL10) from datatypetestm;
select cidx, CDECIMAL18, ACOS(CDECIMAL18) from datatypetestm;
select cidx, CDECIMAL18_2, ACOS(CDECIMAL18_2) from datatypetestm;
select cidx, CINTEGER, ACOS(CINTEGER) from datatypetestm;
select cidx, CSMALLINT, ACOS(CSMALLINT) from datatypetestm;
select cidx, CTINYINT, ACOS(CTINYINT) from datatypetestm;
select cidx, ACOS(0) from datatypetestm;
select cidx, ACOS(60) from datatypetestm;
select cidx, ACOS(90) from datatypetestm;
select cidx, ACOS(180) from datatypetestm;
select cidx, ACOS(360) from datatypetestm;
select cidx, CBIGINT from datatypetestm order by ACOS(CBIGINT), cidx;
select cidx, CDECIMAL1 from datatypetestm order by ACOS(CDECIMAL1), cidx;
select cidx, CDECIMAL4 from datatypetestm order by ACOS(CDECIMAL4), cidx;
select cidx, CDECIMAL4_2 from datatypetestm order by ACOS(CDECIMAL4_2), cidx;
select cidx, CDECIMAL5 from datatypetestm order by ACOS(CDECIMAL5), cidx;
select cidx, CDECIMAL9 from datatypetestm order by ACOS(CDECIMAL9), cidx;
select cidx, CDECIMAL9_2 from datatypetestm order by ACOS(CDECIMAL9_2), cidx;
select cidx, CDECIMAL10 from datatypetestm order by ACOS(CDECIMAL10), cidx;
select cidx, CDECIMAL18 from datatypetestm order by ACOS(CDECIMAL18), cidx;
select cidx, CDECIMAL18_2 from datatypetestm order by ACOS(CDECIMAL18_2), cidx;
select cidx, CINTEGER from datatypetestm order by ACOS(CINTEGER), cidx;
select cidx, CSMALLINT from datatypetestm order by ACOS(CSMALLINT), cidx;
select cidx, CTINYINT from datatypetestm order by ACOS(CTINYINT), cidx;
