select COUNT(CCHAR1) from datatypetestm;
select COUNT(CCHAR2) from datatypetestm;
select COUNT(CCHAR3) from datatypetestm;
select COUNT(CCHAR4) from datatypetestm;
select COUNT(CCHAR5) from datatypetestm;
select COUNT(CCHAR6) from datatypetestm;
select COUNT(CCHAR7) from datatypetestm;
select COUNT(CCHAR8) from datatypetestm;
select COUNT(CCHAR9) from datatypetestm;
select COUNT(CCHAR255) from datatypetestm;
select COUNT(CVCHAR1) from datatypetestm;
select COUNT(CVCHAR2) from datatypetestm;
select COUNT(CVCHAR3) from datatypetestm;
select COUNT(CVCHAR4) from datatypetestm;
select COUNT(CVCHAR5) from datatypetestm;
select COUNT(CVCHAR6) from datatypetestm;
select COUNT(CVCHAR7) from datatypetestm;
select COUNT(CVCHAR8) from datatypetestm;
select COUNT(CVCHAR255) from datatypetestm;
select cidx, CCHAR1, COUNT(CCHAR1) from datatypetestm group by cidx, CCHAR1 order by 1;
select cidx, CCHAR2, COUNT(CCHAR2) from datatypetestm group by cidx, CCHAR2 order by 1;
select cidx, CCHAR3, COUNT(CCHAR3) from datatypetestm group by cidx, CCHAR3 order by 1;
select cidx, CCHAR4, COUNT(CCHAR4) from datatypetestm group by cidx, CCHAR4 order by 1;
select cidx, CCHAR5, COUNT(CCHAR5) from datatypetestm group by cidx, CCHAR5 order by 1;
select cidx, CCHAR6, COUNT(CCHAR6) from datatypetestm group by cidx, CCHAR6 order by 1;
select cidx, CCHAR7, COUNT(CCHAR7) from datatypetestm group by cidx, CCHAR7 order by 1;
select cidx, CCHAR8, COUNT(CCHAR8) from datatypetestm group by cidx, CCHAR8 order by 1;
select cidx, CCHAR9, COUNT(CCHAR9) from datatypetestm group by cidx, CCHAR9 order by 1;
select cidx, CCHAR255, COUNT(CCHAR255) from datatypetestm group by cidx, CCHAR255 order by 1;
select cidx, CVCHAR1, COUNT(CVCHAR1) from datatypetestm group by cidx, CVCHAR1 order by 1;
select cidx, CVCHAR2, COUNT(CVCHAR2) from datatypetestm group by cidx, CVCHAR2 order by 1;
select cidx, CVCHAR3, COUNT(CVCHAR3) from datatypetestm group by cidx, CVCHAR3 order by 1;
select cidx, CVCHAR4, COUNT(CVCHAR4) from datatypetestm group by cidx, CVCHAR4 order by 1;
select cidx, CVCHAR5, COUNT(CVCHAR5) from datatypetestm group by cidx, CVCHAR5 order by 1;
select cidx, CVCHAR6, COUNT(CVCHAR6) from datatypetestm group by cidx, CVCHAR6 order by 1;
select cidx, CVCHAR7, COUNT(CVCHAR7) from datatypetestm group by cidx, CVCHAR7 order by 1;
select cidx, CVCHAR8, COUNT(CVCHAR8) from datatypetestm group by cidx, CVCHAR8 order by 1;
select cidx, CVCHAR255, COUNT(CVCHAR255) from datatypetestm group by cidx, CVCHAR255 order by 1;
