select COUNT(CBIGINT) from datatypetestm;
select COUNT(CDECIMAL1) from datatypetestm;
select COUNT(CDECIMAL4) from datatypetestm;
select COUNT(CDECIMAL4_2) from datatypetestm;
select COUNT(CDECIMAL5) from datatypetestm;
select COUNT(CDECIMAL9) from datatypetestm;
select COUNT(CDECIMAL9_2) from datatypetestm;
select COUNT(CDECIMAL10) from datatypetestm;
select COUNT(CDECIMAL18) from datatypetestm;
select COUNT(CDECIMAL18_2) from datatypetestm;
select COUNT(CINTEGER) from datatypetestm;
select COUNT(CSMALLINT) from datatypetestm;
select COUNT(CTINYINT) from datatypetestm;
select cidx, CBIGINT, COUNT(CBIGINT) from datatypetestm group by cidx, CBIGINT order by 1;
select cidx, CDECIMAL1, COUNT(CDECIMAL1) from datatypetestm group by cidx, CDECIMAL1 order by 1;
select cidx, CDECIMAL4, COUNT(CDECIMAL4) from datatypetestm group by cidx, CDECIMAL4 order by 1;
select cidx, CDECIMAL4_2, COUNT(CDECIMAL4_2) from datatypetestm group by cidx, CDECIMAL4_2 order by 1;
select cidx, CDECIMAL5, COUNT(CDECIMAL5) from datatypetestm group by cidx, CDECIMAL5 order by 1;
select cidx, CDECIMAL9, COUNT(CDECIMAL9) from datatypetestm group by cidx, CDECIMAL9 order by 1;
select cidx, CDECIMAL9_2, COUNT(CDECIMAL9_2) from datatypetestm group by cidx, CDECIMAL9_2 order by 1;
select cidx, CDECIMAL10, COUNT(CDECIMAL10) from datatypetestm group by cidx, CDECIMAL10 order by 1;
select cidx, CDECIMAL18, COUNT(CDECIMAL18) from datatypetestm group by cidx, CDECIMAL18 order by 1;
select cidx, CDECIMAL18_2, COUNT(CDECIMAL18_2) from datatypetestm group by cidx, CDECIMAL18_2 order by 1;
select cidx, CINTEGER, COUNT(CINTEGER) from datatypetestm group by cidx, CINTEGER order by 1;
select cidx, CSMALLINT, COUNT(CSMALLINT) from datatypetestm group by cidx, CSMALLINT order by 1;
select cidx, CTINYINT, COUNT(CTINYINT) from datatypetestm group by cidx, CTINYINT order by 1;
