select cidx, CDATE, DATE_FORMAT(CDATE,'%W %M %Y') from datatypetestm;
select cidx, CDATE, DATE_FORMAT(CDATE,'%H:%i:%s') from datatypetestm;
select cidx, CDATE, DATE_FORMAT(CDATE,'%D %y %a %d %m %b %j') from datatypetestm;
select cidx, CDATETIME, DATE_FORMAT(CDATETIME,'%W %M %Y') from datatypetestm;
select cidx, CDATETIME, DATE_FORMAT(CDATETIME,'%H:%i:%s') from datatypetestm;
select cidx, CDATETIME, DATE_FORMAT(CDATETIME,'%D %y %a %d %m %b %j') from datatypetestm;
select cidx, CDATE from datatypetestm order by DATE_FORMAT(CDATE,'%W %M %Y'), cidx;
select cidx, CDATE from datatypetestm order by DATE_FORMAT(CDATE,'%H:%i:%s'), cidx;
select cidx, CDATE from datatypetestm order by DATE_FORMAT(CDATE,'%D %y %a %d %m %b %j'), cidx;
select cidx, CDATETIME from datatypetestm order by DATE_FORMAT(CDATETIME,'%W %M %Y'), cidx;
select cidx, CDATETIME from datatypetestm order by DATE_FORMAT(CDATETIME,'%H:%i:%s'), cidx;
select cidx, CDATETIME from datatypetestm order by DATE_FORMAT(CDATETIME,'%D %y %a %d %m %b %j'), cidx;
