select cidx, CCHAR1, IFNULL(CCHAR1,'Yes') from datatypetestm;
select cidx, CCHAR2, IFNULL(CCHAR2,'Yes') from datatypetestm;
select cidx, CCHAR3, IFNULL(CCHAR3,'Yes') from datatypetestm;
select cidx, CCHAR4, IFNULL(CCHAR4,'Yes') from datatypetestm;
select cidx, CCHAR5, IFNULL(CCHAR5,'Yes') from datatypetestm;
select cidx, CCHAR6, IFNULL(CCHAR6,'Yes') from datatypetestm;
select cidx, CCHAR7, IFNULL(CCHAR7,'Yes') from datatypetestm;
select cidx, CCHAR8, IFNULL(CCHAR8,'Yes') from datatypetestm;
select cidx, CCHAR9, IFNULL(CCHAR9,'Yes') from datatypetestm;
select cidx, CCHAR255, IFNULL(CCHAR255,'Yes') from datatypetestm;
select cidx, CVCHAR1, IFNULL(CVCHAR1,'Yes') from datatypetestm;
select cidx, CVCHAR2, IFNULL(CVCHAR2,'Yes') from datatypetestm;
select cidx, CVCHAR3, IFNULL(CVCHAR3,'Yes') from datatypetestm;
select cidx, CVCHAR4, IFNULL(CVCHAR4,'Yes') from datatypetestm;
select cidx, CVCHAR5, IFNULL(CVCHAR5,'Yes') from datatypetestm;
select cidx, CVCHAR6, IFNULL(CVCHAR6,'Yes') from datatypetestm;
select cidx, CVCHAR7, IFNULL(CVCHAR7,'Yes') from datatypetestm;
select cidx, CVCHAR8, IFNULL(CVCHAR8,'Yes') from datatypetestm;
select cidx, CVCHAR255, IFNULL(CVCHAR255,'Yes') from datatypetestm;
select cidx, IFNULL('aloha','Yes') from datatypetestm;
select cidx, IFNULL('mahalo','Yes') from datatypetestm;
select cidx, IFNULL('','Yes') from datatypetestm;
select cidx, IFNULL(NULL,'Yes') from datatypetestm;
select cidx, CCHAR1 ,IFNULL(CCHAR1,'Yes') from datatypetestm order by cidx;
select cidx, CCHAR2 ,IFNULL(CCHAR2,'Yes') from datatypetestm order by cidx;
select cidx, CCHAR3 ,IFNULL(CCHAR3,'Yes') from datatypetestm order by cidx;
select cidx, CCHAR4 ,IFNULL(CCHAR4,'Yes') from datatypetestm order by cidx;
select cidx, CCHAR5 ,IFNULL(CCHAR5,'Yes') from datatypetestm order by cidx;
select cidx, CCHAR6 ,IFNULL(CCHAR6,'Yes') from datatypetestm order by cidx;
select cidx, CCHAR7 ,IFNULL(CCHAR7,'Yes') from datatypetestm order by cidx;
select cidx, CCHAR8 ,IFNULL(CCHAR8,'Yes') from datatypetestm order by cidx;
select cidx, CCHAR9 ,IFNULL(CCHAR9,'Yes') from datatypetestm order by cidx;
select cidx, CCHAR255 ,IFNULL(CCHAR255,'Yes') from datatypetestm order by cidx;
select cidx, CVCHAR1 ,IFNULL(CVCHAR1,'Yes') from datatypetestm order by cidx;
select cidx, CVCHAR2 ,IFNULL(CVCHAR2,'Yes') from datatypetestm order by cidx;
select cidx, CVCHAR3 ,IFNULL(CVCHAR3,'Yes') from datatypetestm order by cidx;
select cidx, CVCHAR4 ,IFNULL(CVCHAR4,'Yes') from datatypetestm order by cidx;
select cidx, CVCHAR5 ,IFNULL(CVCHAR5,'Yes') from datatypetestm order by cidx;
select cidx, CVCHAR6 ,IFNULL(CVCHAR6,'Yes') from datatypetestm order by cidx;
select cidx, CVCHAR7 ,IFNULL(CVCHAR7,'Yes') from datatypetestm order by cidx;
select cidx, CVCHAR8 ,IFNULL(CVCHAR8,'Yes') from datatypetestm order by cidx;
select cidx, CVCHAR255 ,IFNULL(CVCHAR255,'Yes') from datatypetestm order by cidx;
