select cidx, CBIGINT, LOG(CBIGINT) from datatypetestm;
select cidx, CDECIMAL1, LOG(CDECIMAL1) from datatypetestm;
select cidx, CDECIMAL4, LOG(CDECIMAL4) from datatypetestm;
select cidx, CDECIMAL4_2, LOG(CDECIMAL4_2) from datatypetestm;
select cidx, CDECIMAL5, LOG(CDECIMAL5) from datatypetestm;
select cidx, CDECIMAL9, LOG(CDECIMAL9) from datatypetestm;
select cidx, CDECIMAL9_2, LOG(CDECIMAL9_2) from datatypetestm;
select cidx, CDECIMAL10, LOG(CDECIMAL10) from datatypetestm;
select cidx, CDECIMAL18, LOG(CDECIMAL18) from datatypetestm;
select cidx, CDECIMAL18_2, LOG(CDECIMAL18_2) from datatypetestm;
select cidx, CINTEGER, LOG(CINTEGER) from datatypetestm;
select cidx, CSMALLINT, LOG(CSMALLINT) from datatypetestm;
select cidx, CTINYINT, LOG(CTINYINT) from datatypetestm;
select cidx, LOG(-1) from datatypetestm;
select cidx, LOG(0) from datatypetestm;
select cidx, LOG(2) from datatypetestm;
select cidx, LOG(2,265536) from datatypetestm;
select cidx, LOG(10,100) from datatypetestm;
select cidx, LOG(1,100) from datatypetestm;
select cidx, CBIGINT from datatypetestm order by LOG(CBIGINT), cidx;
select cidx, CDECIMAL1 from datatypetestm order by LOG(CDECIMAL1), cidx;
select cidx, CDECIMAL4 from datatypetestm order by LOG(CDECIMAL4), cidx;
select cidx, CDECIMAL4_2 from datatypetestm order by LOG(CDECIMAL4_2), cidx;
select cidx, CDECIMAL5 from datatypetestm order by LOG(CDECIMAL5), cidx;
select cidx, CDECIMAL9 from datatypetestm order by LOG(CDECIMAL9), cidx;
select cidx, CDECIMAL9_2 from datatypetestm order by LOG(CDECIMAL9_2), cidx;
select cidx, CDECIMAL10 from datatypetestm order by LOG(CDECIMAL10), cidx;
select cidx, CDECIMAL18 from datatypetestm order by LOG(CDECIMAL18), cidx;
select cidx, CDECIMAL18_2 from datatypetestm order by LOG(CDECIMAL18_2), cidx;
select cidx, CINTEGER from datatypetestm order by LOG(CINTEGER), cidx;
select cidx, CSMALLINT from datatypetestm order by LOG(CSMALLINT), cidx;
select cidx, CTINYINT from datatypetestm order by LOG(CTINYINT), cidx;
