select cidx, CBIGINT, LOG10(CBIGINT) from datatypetestm;
select cidx, CDECIMAL1, LOG10(CDECIMAL1) from datatypetestm;
select cidx, CDECIMAL4, LOG10(CDECIMAL4) from datatypetestm;
select cidx, CDECIMAL4_2, LOG10(CDECIMAL4_2) from datatypetestm;
select cidx, CDECIMAL5, LOG10(CDECIMAL5) from datatypetestm;
select cidx, CDECIMAL9, LOG10(CDECIMAL9) from datatypetestm;
select cidx, CDECIMAL9_2, LOG10(CDECIMAL9_2) from datatypetestm;
select cidx, CDECIMAL10, LOG10(CDECIMAL10) from datatypetestm;
select cidx, CDECIMAL18, LOG10(CDECIMAL18) from datatypetestm;
select cidx, CDECIMAL18_2, LOG10(CDECIMAL18_2) from datatypetestm;
select cidx, CINTEGER, LOG10(CINTEGER) from datatypetestm;
select cidx, CSMALLINT, LOG10(CSMALLINT) from datatypetestm;
select cidx, CTINYINT, LOG10(CTINYINT) from datatypetestm;
select cidx, LOG10(-1) from datatypetestm;
select cidx, LOG10(0) from datatypetestm;
select cidx, LOG10(2) from datatypetestm;
select cidx, LOG10(265536) from datatypetestm;
select cidx, LOG10(100) from datatypetestm;
select cidx, LOG10(-100) from datatypetestm;
select cidx, CBIGINT from datatypetestm order by LOG10(CBIGINT), cidx;
select cidx, CDECIMAL1 from datatypetestm order by LOG10(CDECIMAL1), cidx;
select cidx, CDECIMAL4 from datatypetestm order by LOG10(CDECIMAL4), cidx;
select cidx, CDECIMAL4_2 from datatypetestm order by LOG10(CDECIMAL4_2), cidx;
select cidx, CDECIMAL5 from datatypetestm order by LOG10(CDECIMAL5), cidx;
select cidx, CDECIMAL9 from datatypetestm order by LOG10(CDECIMAL9), cidx;
select cidx, CDECIMAL9_2 from datatypetestm order by LOG10(CDECIMAL9_2), cidx;
select cidx, CDECIMAL10 from datatypetestm order by LOG10(CDECIMAL10), cidx;
select cidx, CDECIMAL18 from datatypetestm order by LOG10(CDECIMAL18), cidx;
select cidx, CDECIMAL18_2 from datatypetestm order by LOG10(CDECIMAL18_2), cidx;
select cidx, CINTEGER from datatypetestm order by LOG10(CINTEGER), cidx;
select cidx, CSMALLINT from datatypetestm order by LOG10(CSMALLINT), cidx;
select cidx, CTINYINT from datatypetestm order by LOG10(CTINYINT), cidx;
