select cidx, CDECIMAL1, LOG2(CDECIMAL1) from datatypetestm;
select cidx, CDECIMAL4, LOG2(CDECIMAL4) from datatypetestm;
select cidx, CDECIMAL4_2, LOG2(CDECIMAL4_2) from datatypetestm;
select cidx, CDECIMAL5, LOG2(CDECIMAL5) from datatypetestm;
select cidx, CDECIMAL9, LOG2(CDECIMAL9) from datatypetestm;
select cidx, CDECIMAL9_2, LOG2(CDECIMAL9_2) from datatypetestm;
select cidx, CDECIMAL10, LOG2(CDECIMAL10) from datatypetestm;
select cidx, CDECIMAL18, LOG2(CDECIMAL18) from datatypetestm;
select cidx, CDECIMAL18_2, LOG2(CDECIMAL18_2) from datatypetestm;
select cidx, CINTEGER, LOG2(CINTEGER) from datatypetestm;
select cidx, CSMALLINT, LOG2(CSMALLINT) from datatypetestm;
select cidx, CTINYINT, LOG2(CTINYINT) from datatypetestm;
select cidx, LOG2(-1) from datatypetestm;
select cidx, LOG2(0) from datatypetestm;
select cidx, LOG2(2) from datatypetestm;
select cidx, LOG2(265536) from datatypetestm;
select cidx, LOG2(100) from datatypetestm;
select cidx, LOG2(-100) from datatypetestm;
select cidx, CBIGINT from datatypetestm order by LOG2(CBIGINT), cidx;
select cidx, CDECIMAL1 from datatypetestm order by LOG2(CDECIMAL1), cidx;
select cidx, CDECIMAL4 from datatypetestm order by LOG2(CDECIMAL4), cidx;
select cidx, CDECIMAL4_2 from datatypetestm order by LOG2(CDECIMAL4_2), cidx;
select cidx, CDECIMAL5 from datatypetestm order by LOG2(CDECIMAL5), cidx;
select cidx, CDECIMAL9 from datatypetestm order by LOG2(CDECIMAL9), cidx;
select cidx, CDECIMAL9_2 from datatypetestm order by LOG2(CDECIMAL9_2), cidx;
select cidx, CDECIMAL10 from datatypetestm order by LOG2(CDECIMAL10), cidx;
select cidx, CDECIMAL18 from datatypetestm order by LOG2(CDECIMAL18), cidx;
select cidx, CDECIMAL18_2 from datatypetestm order by LOG2(CDECIMAL18_2), cidx;
select cidx, CINTEGER from datatypetestm order by LOG2(CINTEGER), cidx;
select cidx, CSMALLINT from datatypetestm order by LOG2(CSMALLINT), cidx;
select cidx, CTINYINT from datatypetestm order by LOG2(CTINYINT), cidx;
