select MAX(CBIGINT) from datatypetestm;
select MAX(CDECIMAL1) from datatypetestm;
select MAX(CDECIMAL4) from datatypetestm;
select MAX(CDECIMAL4_2) from datatypetestm;
select MAX(CDECIMAL5) from datatypetestm;
select MAX(CDECIMAL9) from datatypetestm;
select MAX(CDECIMAL9_2) from datatypetestm;
select MAX(CDECIMAL10) from datatypetestm;
select MAX(CDECIMAL18) from datatypetestm;
select MAX(CDECIMAL18_2) from datatypetestm;
select MAX(CINTEGER) from datatypetestm;
select MAX(CSMALLINT) from datatypetestm;
select MAX(CTINYINT) from datatypetestm;
select cidx, CBIGINT, MAX(CBIGINT) from datatypetestm group by cidx, CBIGINT order by 1;
select cidx, CDECIMAL1, MAX(CDECIMAL1) from datatypetestm group by cidx, CDECIMAL1 order by 1;
select cidx, CDECIMAL4, MAX(CDECIMAL4) from datatypetestm group by cidx, CDECIMAL4 order by 1;
select cidx, CDECIMAL4_2, MAX(CDECIMAL4_2) from datatypetestm group by cidx, CDECIMAL4_2 order by 1;
select cidx, CDECIMAL5, MAX(CDECIMAL5) from datatypetestm group by cidx, CDECIMAL5 order by 1;
select cidx, CDECIMAL9, MAX(CDECIMAL9) from datatypetestm group by cidx, CDECIMAL9 order by 1;
select cidx, CDECIMAL9_2, MAX(CDECIMAL9_2) from datatypetestm group by cidx, CDECIMAL9_2 order by 1;
select cidx, CDECIMAL10, MAX(CDECIMAL10) from datatypetestm group by cidx, CDECIMAL10 order by 1;
select cidx, CDECIMAL18, MAX(CDECIMAL18) from datatypetestm group by cidx, CDECIMAL18 order by 1;
select cidx, CDECIMAL18_2, MAX(CDECIMAL18_2) from datatypetestm group by cidx, CDECIMAL18_2 order by 1;
select cidx, CINTEGER, MAX(CINTEGER) from datatypetestm group by cidx, CINTEGER order by 1;
select cidx, CSMALLINT, MAX(CSMALLINT) from datatypetestm group by cidx, CSMALLINT order by 1;
select cidx, CTINYINT, MAX(CTINYINT) from datatypetestm group by cidx, CTINYINT order by 1;
