select cidx, CBIGINT, TRUNCATE(CBIGINT,1) from datatypetestm;
select cidx, CBIGINT, TRUNCATE(CBIGINT,2) from datatypetestm;
select cidx, CBIGINT, TRUNCATE(CBIGINT,0) from datatypetestm;
select cidx, CBIGINT, TRUNCATE(CBIGINT,-2) from datatypetestm;
select cidx, CBIGINT, TRUNCATE(CBIGINT,-1) from datatypetestm;
select cidx, CDECIMAL1, TRUNCATE(CDECIMAL1,1) from datatypetestm;
select cidx, CDECIMAL1, TRUNCATE(CDECIMAL1,2) from datatypetestm;
select cidx, CDECIMAL1, TRUNCATE(CDECIMAL1,0) from datatypetestm;
select cidx, CDECIMAL1, TRUNCATE(CDECIMAL1,-2) from datatypetestm;
select cidx, CDECIMAL1, TRUNCATE(CDECIMAL1,-1) from datatypetestm;
select cidx, CDECIMAL4, TRUNCATE(CDECIMAL4,1) from datatypetestm;
select cidx, CDECIMAL4, TRUNCATE(CDECIMAL4,2) from datatypetestm;
select cidx, CDECIMAL4, TRUNCATE(CDECIMAL4,0) from datatypetestm;
select cidx, CDECIMAL4, TRUNCATE(CDECIMAL4,-2) from datatypetestm;
select cidx, CDECIMAL4, TRUNCATE(CDECIMAL4,-1) from datatypetestm;
select cidx, CDECIMAL4_2, TRUNCATE(CDECIMAL4_2,1) from datatypetestm;
select cidx, CDECIMAL4_2, TRUNCATE(CDECIMAL4_2,2) from datatypetestm;
select cidx, CDECIMAL4_2, TRUNCATE(CDECIMAL4_2,0) from datatypetestm;
select cidx, CDECIMAL4_2, TRUNCATE(CDECIMAL4_2,-2) from datatypetestm;
select cidx, CDECIMAL4_2, TRUNCATE(CDECIMAL4_2,-1) from datatypetestm;
select cidx, CDECIMAL5, TRUNCATE(CDECIMAL5,1) from datatypetestm;
select cidx, CDECIMAL5, TRUNCATE(CDECIMAL5,2) from datatypetestm;
select cidx, CDECIMAL5, TRUNCATE(CDECIMAL5,0) from datatypetestm;
select cidx, CDECIMAL5, TRUNCATE(CDECIMAL5,-2) from datatypetestm;
select cidx, CDECIMAL5, TRUNCATE(CDECIMAL5,-1) from datatypetestm;
select cidx, CDECIMAL9, TRUNCATE(CDECIMAL9,1) from datatypetestm;
select cidx, CDECIMAL9, TRUNCATE(CDECIMAL9,2) from datatypetestm;
select cidx, CDECIMAL9, TRUNCATE(CDECIMAL9,0) from datatypetestm;
select cidx, CDECIMAL9, TRUNCATE(CDECIMAL9,-2) from datatypetestm;
select cidx, CDECIMAL9, TRUNCATE(CDECIMAL9,-1) from datatypetestm;
select cidx, CDECIMAL9_2, TRUNCATE(CDECIMAL9_2,1) from datatypetestm;
select cidx, CDECIMAL9_2, TRUNCATE(CDECIMAL9_2,2) from datatypetestm;
select cidx, CDECIMAL9_2, TRUNCATE(CDECIMAL9_2,0) from datatypetestm;
select cidx, CDECIMAL9_2, TRUNCATE(CDECIMAL9_2,-2) from datatypetestm;
select cidx, CDECIMAL9_2, TRUNCATE(CDECIMAL9_2,-1) from datatypetestm;
select cidx, CDECIMAL10, TRUNCATE(CDECIMAL10,1) from datatypetestm;
select cidx, CDECIMAL10, TRUNCATE(CDECIMAL10,2) from datatypetestm;
select cidx, CDECIMAL10, TRUNCATE(CDECIMAL10,0) from datatypetestm;
select cidx, CDECIMAL10, TRUNCATE(CDECIMAL10,-2) from datatypetestm;
select cidx, CDECIMAL10, TRUNCATE(CDECIMAL10,-1) from datatypetestm;
select cidx, CDECIMAL18, TRUNCATE(CDECIMAL18,1) from datatypetestm;
select cidx, CDECIMAL18, TRUNCATE(CDECIMAL18,2) from datatypetestm;
select cidx, CDECIMAL18, TRUNCATE(CDECIMAL18,0) from datatypetestm;
select cidx, CDECIMAL18, TRUNCATE(CDECIMAL18,-2) from datatypetestm;
select cidx, CDECIMAL18, TRUNCATE(CDECIMAL18,-1) from datatypetestm;
select cidx, CDECIMAL18_2, TRUNCATE(CDECIMAL18_2,1) from datatypetestm;
select cidx, CDECIMAL18_2, TRUNCATE(CDECIMAL18_2,2) from datatypetestm;
select cidx, CDECIMAL18_2, TRUNCATE(CDECIMAL18_2,0) from datatypetestm;
select cidx, CDECIMAL18_2, TRUNCATE(CDECIMAL18_2,-2) from datatypetestm;
select cidx, CDECIMAL18_2, TRUNCATE(CDECIMAL18_2,-1) from datatypetestm;
select cidx, CINTEGER, TRUNCATE(CINTEGER,1) from datatypetestm;
select cidx, CINTEGER, TRUNCATE(CINTEGER,2) from datatypetestm;
select cidx, CINTEGER, TRUNCATE(CINTEGER,0) from datatypetestm;
select cidx, CINTEGER, TRUNCATE(CINTEGER,-2) from datatypetestm;
select cidx, CINTEGER, TRUNCATE(CINTEGER,-1) from datatypetestm;
select cidx, CSMALLINT, TRUNCATE(CSMALLINT,1) from datatypetestm;
select cidx, CSMALLINT, TRUNCATE(CSMALLINT,2) from datatypetestm;
select cidx, CSMALLINT, TRUNCATE(CSMALLINT,0) from datatypetestm;
select cidx, CSMALLINT, TRUNCATE(CSMALLINT,-2) from datatypetestm;
select cidx, CSMALLINT, TRUNCATE(CSMALLINT,-1) from datatypetestm;
select cidx, CTINYINT, TRUNCATE(CTINYINT,1) from datatypetestm;
select cidx, CTINYINT, TRUNCATE(CTINYINT,2) from datatypetestm;
select cidx, CTINYINT, TRUNCATE(CTINYINT,0) from datatypetestm;
select cidx, CTINYINT, TRUNCATE(CTINYINT,-2) from datatypetestm;
select cidx, CTINYINT, TRUNCATE(CTINYINT,-1) from datatypetestm;
select cidx, CBIGINT from datatypetestm order by TRUNCATE(CBIGINT,1), cidx;
select cidx, CBIGINT from datatypetestm order by TRUNCATE(CBIGINT,2), cidx;
select cidx, CBIGINT from datatypetestm order by TRUNCATE(CBIGINT,0), cidx;
select cidx, CBIGINT from datatypetestm order by TRUNCATE(CBIGINT,-2), cidx;
select cidx, CBIGINT from datatypetestm order by TRUNCATE(CBIGINT,-1), cidx;
select cidx, CDECIMAL1 from datatypetestm order by TRUNCATE(CDECIMAL1,1), cidx;
select cidx, CDECIMAL1 from datatypetestm order by TRUNCATE(CDECIMAL1,2), cidx;
select cidx, CDECIMAL1 from datatypetestm order by TRUNCATE(CDECIMAL1,0), cidx;
select cidx, CDECIMAL1 from datatypetestm order by TRUNCATE(CDECIMAL1,-2), cidx;
select cidx, CDECIMAL1 from datatypetestm order by TRUNCATE(CDECIMAL1,-1), cidx;
select cidx, CDECIMAL4 from datatypetestm order by TRUNCATE(CDECIMAL4,1), cidx;
select cidx, CDECIMAL4 from datatypetestm order by TRUNCATE(CDECIMAL4,2), cidx;
select cidx, CDECIMAL4 from datatypetestm order by TRUNCATE(CDECIMAL4,0), cidx;
select cidx, CDECIMAL4 from datatypetestm order by TRUNCATE(CDECIMAL4,-2), cidx;
select cidx, CDECIMAL4 from datatypetestm order by TRUNCATE(CDECIMAL4,-1), cidx;
select cidx, CDECIMAL4_2 from datatypetestm order by TRUNCATE(CDECIMAL4_2,1), cidx;
select cidx, CDECIMAL4_2 from datatypetestm order by TRUNCATE(CDECIMAL4_2,2), cidx;
select cidx, CDECIMAL4_2 from datatypetestm order by TRUNCATE(CDECIMAL4_2,0), cidx;
select cidx, CDECIMAL4_2 from datatypetestm order by TRUNCATE(CDECIMAL4_2,-2), cidx;
select cidx, CDECIMAL4_2 from datatypetestm order by TRUNCATE(CDECIMAL4_2,-1), cidx;
select cidx, CDECIMAL5 from datatypetestm order by TRUNCATE(CDECIMAL5,1), cidx;
select cidx, CDECIMAL5 from datatypetestm order by TRUNCATE(CDECIMAL5,2), cidx;
select cidx, CDECIMAL5 from datatypetestm order by TRUNCATE(CDECIMAL5,0), cidx;
select cidx, CDECIMAL5 from datatypetestm order by TRUNCATE(CDECIMAL5,-2), cidx;
select cidx, CDECIMAL5 from datatypetestm order by TRUNCATE(CDECIMAL5,-1), cidx;
select cidx, CDECIMAL9 from datatypetestm order by TRUNCATE(CDECIMAL9,1), cidx;
select cidx, CDECIMAL9 from datatypetestm order by TRUNCATE(CDECIMAL9,2), cidx;
select cidx, CDECIMAL9 from datatypetestm order by TRUNCATE(CDECIMAL9,0), cidx;
select cidx, CDECIMAL9 from datatypetestm order by TRUNCATE(CDECIMAL9,-2), cidx;
select cidx, CDECIMAL9 from datatypetestm order by TRUNCATE(CDECIMAL9,-1), cidx;
select cidx, CDECIMAL9_2 from datatypetestm order by TRUNCATE(CDECIMAL9_2,1), cidx;
select cidx, CDECIMAL9_2 from datatypetestm order by TRUNCATE(CDECIMAL9_2,2), cidx;
select cidx, CDECIMAL9_2 from datatypetestm order by TRUNCATE(CDECIMAL9_2,0), cidx;
select cidx, CDECIMAL9_2 from datatypetestm order by TRUNCATE(CDECIMAL9_2,-2), cidx;
select cidx, CDECIMAL9_2 from datatypetestm order by TRUNCATE(CDECIMAL9_2,-1), cidx;
select cidx, CDECIMAL10 from datatypetestm order by TRUNCATE(CDECIMAL10,1), cidx;
select cidx, CDECIMAL10 from datatypetestm order by TRUNCATE(CDECIMAL10,2), cidx;
select cidx, CDECIMAL10 from datatypetestm order by TRUNCATE(CDECIMAL10,0), cidx;
select cidx, CDECIMAL10 from datatypetestm order by TRUNCATE(CDECIMAL10,-2), cidx;
select cidx, CDECIMAL10 from datatypetestm order by TRUNCATE(CDECIMAL10,-1), cidx;
select cidx, CDECIMAL18 from datatypetestm order by TRUNCATE(CDECIMAL18,1), cidx;
select cidx, CDECIMAL18 from datatypetestm order by TRUNCATE(CDECIMAL18,2), cidx;
select cidx, CDECIMAL18 from datatypetestm order by TRUNCATE(CDECIMAL18,0), cidx;
select cidx, CDECIMAL18 from datatypetestm order by TRUNCATE(CDECIMAL18,-2), cidx;
select cidx, CDECIMAL18 from datatypetestm order by TRUNCATE(CDECIMAL18,-1), cidx;
select cidx, CDECIMAL18_2 from datatypetestm order by TRUNCATE(CDECIMAL18_2,1), cidx;
select cidx, CDECIMAL18_2 from datatypetestm order by TRUNCATE(CDECIMAL18_2,2), cidx;
select cidx, CDECIMAL18_2 from datatypetestm order by TRUNCATE(CDECIMAL18_2,0), cidx;
select cidx, CDECIMAL18_2 from datatypetestm order by TRUNCATE(CDECIMAL18_2,-2), cidx;
select cidx, CDECIMAL18_2 from datatypetestm order by TRUNCATE(CDECIMAL18_2,-1), cidx;
select cidx, CINTEGER from datatypetestm order by TRUNCATE(CINTEGER,1), cidx;
select cidx, CINTEGER from datatypetestm order by TRUNCATE(CINTEGER,2), cidx;
select cidx, CINTEGER from datatypetestm order by TRUNCATE(CINTEGER,0), cidx;
select cidx, CINTEGER from datatypetestm order by TRUNCATE(CINTEGER,-2), cidx;
select cidx, CINTEGER from datatypetestm order by TRUNCATE(CINTEGER,-1), cidx;
select cidx, CSMALLINT from datatypetestm order by TRUNCATE(CSMALLINT,1), cidx;
select cidx, CSMALLINT from datatypetestm order by TRUNCATE(CSMALLINT,2), cidx;
select cidx, CSMALLINT from datatypetestm order by TRUNCATE(CSMALLINT,0), cidx;
select cidx, CSMALLINT from datatypetestm order by TRUNCATE(CSMALLINT,-2), cidx;
select cidx, CSMALLINT from datatypetestm order by TRUNCATE(CSMALLINT,-1), cidx;
select cidx, CTINYINT from datatypetestm order by TRUNCATE(CTINYINT,1), cidx;
select cidx, CTINYINT from datatypetestm order by TRUNCATE(CTINYINT,2), cidx;
select cidx, CTINYINT from datatypetestm order by TRUNCATE(CTINYINT,0), cidx;
select cidx, CTINYINT from datatypetestm order by TRUNCATE(CTINYINT,-2), cidx;
select cidx, CTINYINT from datatypetestm order by TRUNCATE(CTINYINT,-1), cidx;
