select cidx, CCHAR1, CONCAT_WS(',',CCHAR1,CCHAR3,CCHAR7,'ALOHA') from datatypetestm;
select cidx, CCHAR1, CONCAT_WS(',',CCHAR1,CCHAR3) from datatypetestm;
select cidx, CCHAR1, CONCAT_WS(',',CCHAR1,CCHAR7) from datatypetestm;
select cidx, CCHAR1, CONCAT_WS(',',CCHAR1,'ALOHA') from datatypetestm;
select cidx, CCHAR2, CONCAT_WS(',',CCHAR2,CCHAR3,CCHAR7,'ALOHA') from datatypetestm;
select cidx, CCHAR2, CONCAT_WS(',',CCHAR2,CCHAR3) from datatypetestm;
select cidx, CCHAR2, CONCAT_WS(',',CCHAR2,CCHAR7) from datatypetestm;
select cidx, CCHAR2, CONCAT_WS(',',CCHAR2,'ALOHA') from datatypetestm;
select cidx, CCHAR3, CONCAT_WS(',',CCHAR3,CCHAR3,CCHAR7,'ALOHA') from datatypetestm;
select cidx, CCHAR3, CONCAT_WS(',',CCHAR3,CCHAR3) from datatypetestm;
select cidx, CCHAR3, CONCAT_WS(',',CCHAR3,CCHAR7) from datatypetestm;
select cidx, CCHAR3, CONCAT_WS(',',CCHAR3,'ALOHA') from datatypetestm;
select cidx, CCHAR4, CONCAT_WS(',',CCHAR4,CCHAR3,CCHAR7,'ALOHA') from datatypetestm;
select cidx, CCHAR4, CONCAT_WS(',',CCHAR4,CCHAR3) from datatypetestm;
select cidx, CCHAR4, CONCAT_WS(',',CCHAR4,CCHAR7) from datatypetestm;
select cidx, CCHAR4, CONCAT_WS(',',CCHAR4,'ALOHA') from datatypetestm;
select cidx, CCHAR5, CONCAT_WS(',',CCHAR5,CCHAR3,CCHAR7,'ALOHA') from datatypetestm;
select cidx, CCHAR5, CONCAT_WS(',',CCHAR5,CCHAR3) from datatypetestm;
select cidx, CCHAR5, CONCAT_WS(',',CCHAR5,CCHAR7) from datatypetestm;
select cidx, CCHAR5, CONCAT_WS(',',CCHAR5,'ALOHA') from datatypetestm;
select cidx, CCHAR6, CONCAT_WS(',',CCHAR6,CCHAR3,CCHAR7,'ALOHA') from datatypetestm;
select cidx, CCHAR6, CONCAT_WS(',',CCHAR6,CCHAR3) from datatypetestm;
select cidx, CCHAR6, CONCAT_WS(',',CCHAR6,CCHAR7) from datatypetestm;
select cidx, CCHAR6, CONCAT_WS(',',CCHAR6,'ALOHA') from datatypetestm;
select cidx, CCHAR7, CONCAT_WS(',',CCHAR7,CCHAR3,CCHAR7,'ALOHA') from datatypetestm;
select cidx, CCHAR7, CONCAT_WS(',',CCHAR7,CCHAR3) from datatypetestm;
select cidx, CCHAR7, CONCAT_WS(',',CCHAR7,CCHAR7) from datatypetestm;
select cidx, CCHAR7, CONCAT_WS(',',CCHAR7,'ALOHA') from datatypetestm;
select cidx, CCHAR8, CONCAT_WS(',',CCHAR8,CCHAR3,CCHAR7,'ALOHA') from datatypetestm;
select cidx, CCHAR8, CONCAT_WS(',',CCHAR8,CCHAR3) from datatypetestm;
select cidx, CCHAR8, CONCAT_WS(',',CCHAR8,CCHAR7) from datatypetestm;
select cidx, CCHAR8, CONCAT_WS(',',CCHAR8,'ALOHA') from datatypetestm;
select cidx, CCHAR9, CONCAT_WS(',',CCHAR9,CCHAR3,CCHAR7,'ALOHA') from datatypetestm;
select cidx, CCHAR9, CONCAT_WS(',',CCHAR9,CCHAR3) from datatypetestm;
select cidx, CCHAR9, CONCAT_WS(',',CCHAR9,CCHAR7) from datatypetestm;
select cidx, CCHAR9, CONCAT_WS(',',CCHAR9,'ALOHA') from datatypetestm;
select cidx, CCHAR255, CONCAT_WS(',',CCHAR255,CCHAR3,CCHAR7,'ALOHA') from datatypetestm;
select cidx, CCHAR255, CONCAT_WS(',',CCHAR255,CCHAR3) from datatypetestm;
select cidx, CCHAR255, CONCAT_WS(',',CCHAR255,CCHAR7) from datatypetestm;
select cidx, CCHAR255, CONCAT_WS(',',CCHAR255,'ALOHA') from datatypetestm;
select cidx, CVCHAR1, CONCAT_WS(',',CVCHAR1,CCHAR3,CCHAR7,'ALOHA') from datatypetestm;
select cidx, CVCHAR1, CONCAT_WS(',',CVCHAR1,CCHAR3) from datatypetestm;
select cidx, CVCHAR1, CONCAT_WS(',',CVCHAR1,CCHAR7) from datatypetestm;
select cidx, CVCHAR1, CONCAT_WS(',',CVCHAR1,'ALOHA') from datatypetestm;
select cidx, CVCHAR2, CONCAT_WS(',',CVCHAR2,CCHAR3,CCHAR7,'ALOHA') from datatypetestm;
select cidx, CVCHAR2, CONCAT_WS(',',CVCHAR2,CCHAR3) from datatypetestm;
select cidx, CVCHAR2, CONCAT_WS(',',CVCHAR2,CCHAR7) from datatypetestm;
select cidx, CVCHAR2, CONCAT_WS(',',CVCHAR2,'ALOHA') from datatypetestm;
select cidx, CVCHAR3, CONCAT_WS(',',CVCHAR3,CCHAR3,CCHAR7,'ALOHA') from datatypetestm;
select cidx, CVCHAR3, CONCAT_WS(',',CVCHAR3,CCHAR3) from datatypetestm;
select cidx, CVCHAR3, CONCAT_WS(',',CVCHAR3,CCHAR7) from datatypetestm;
select cidx, CVCHAR3, CONCAT_WS(',',CVCHAR3,'ALOHA') from datatypetestm;
select cidx, CVCHAR4, CONCAT_WS(',',CVCHAR4,CCHAR3,CCHAR7,'ALOHA') from datatypetestm;
select cidx, CVCHAR4, CONCAT_WS(',',CVCHAR4,CCHAR3) from datatypetestm;
select cidx, CVCHAR4, CONCAT_WS(',',CVCHAR4,CCHAR7) from datatypetestm;
select cidx, CVCHAR4, CONCAT_WS(',',CVCHAR4,'ALOHA') from datatypetestm;
select cidx, CVCHAR5, CONCAT_WS(',',CVCHAR5,CCHAR3,CCHAR7,'ALOHA') from datatypetestm;
select cidx, CVCHAR5, CONCAT_WS(',',CVCHAR5,CCHAR3) from datatypetestm;
select cidx, CVCHAR5, CONCAT_WS(',',CVCHAR5,CCHAR7) from datatypetestm;
select cidx, CVCHAR5, CONCAT_WS(',',CVCHAR5,'ALOHA') from datatypetestm;
select cidx, CVCHAR6, CONCAT_WS(',',CVCHAR6,CCHAR3,CCHAR7,'ALOHA') from datatypetestm;
select cidx, CVCHAR6, CONCAT_WS(',',CVCHAR6,CCHAR3) from datatypetestm;
select cidx, CVCHAR6, CONCAT_WS(',',CVCHAR6,CCHAR7) from datatypetestm;
select cidx, CVCHAR6, CONCAT_WS(',',CVCHAR6,'ALOHA') from datatypetestm;
select cidx, CVCHAR7, CONCAT_WS(',',CVCHAR7,CCHAR3,CCHAR7,'ALOHA') from datatypetestm;
select cidx, CVCHAR7, CONCAT_WS(',',CVCHAR7,CCHAR3) from datatypetestm;
select cidx, CVCHAR7, CONCAT_WS(',',CVCHAR7,CCHAR7) from datatypetestm;
select cidx, CVCHAR7, CONCAT_WS(',',CVCHAR7,'ALOHA') from datatypetestm;
select cidx, CVCHAR8, CONCAT_WS(',',CVCHAR8,CCHAR3,CCHAR7,'ALOHA') from datatypetestm;
select cidx, CVCHAR8, CONCAT_WS(',',CVCHAR8,CCHAR3) from datatypetestm;
select cidx, CVCHAR8, CONCAT_WS(',',CVCHAR8,CCHAR7) from datatypetestm;
select cidx, CVCHAR8, CONCAT_WS(',',CVCHAR8,'ALOHA') from datatypetestm;
select cidx, CVCHAR255, CONCAT_WS(',',CVCHAR255,CCHAR3,CCHAR7,'ALOHA') from datatypetestm;
select cidx, CVCHAR255, CONCAT_WS(',',CVCHAR255,CCHAR3) from datatypetestm;
select cidx, CVCHAR255, CONCAT_WS(',',CVCHAR255,CCHAR7) from datatypetestm;
select cidx, CVCHAR255, CONCAT_WS(',',CVCHAR255,'ALOHA') from datatypetestm;
select cidx, CCHAR1 from datatypetestm where CONCAT_WS(',',CCHAR1,CCHAR3,CCHAR7,'ALOHA') <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where CONCAT_WS(',',CCHAR1,CCHAR3) <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where CONCAT_WS(',',CCHAR1,CCHAR7) <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where CONCAT_WS(',',CCHAR1,'ALOHA') <> CCHAR1;
select cidx, CCHAR2 from datatypetestm where CONCAT_WS(',',CCHAR2,CCHAR3,CCHAR7,'ALOHA') <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where CONCAT_WS(',',CCHAR2,CCHAR3) <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where CONCAT_WS(',',CCHAR2,CCHAR7) <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where CONCAT_WS(',',CCHAR2,'ALOHA') <> CCHAR2;
select cidx, CCHAR3 from datatypetestm where CONCAT_WS(',',CCHAR3,CCHAR3,CCHAR7,'ALOHA') <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where CONCAT_WS(',',CCHAR3,CCHAR3) <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where CONCAT_WS(',',CCHAR3,CCHAR7) <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where CONCAT_WS(',',CCHAR3,'ALOHA') <> CCHAR3;
select cidx, CCHAR4 from datatypetestm where CONCAT_WS(',',CCHAR4,CCHAR3,CCHAR7,'ALOHA') <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where CONCAT_WS(',',CCHAR4,CCHAR3) <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where CONCAT_WS(',',CCHAR4,CCHAR7) <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where CONCAT_WS(',',CCHAR4,'ALOHA') <> CCHAR4;
select cidx, CCHAR5 from datatypetestm where CONCAT_WS(',',CCHAR5,CCHAR3,CCHAR7,'ALOHA') <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where CONCAT_WS(',',CCHAR5,CCHAR3) <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where CONCAT_WS(',',CCHAR5,CCHAR7) <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where CONCAT_WS(',',CCHAR5,'ALOHA') <> CCHAR5;
select cidx, CCHAR6 from datatypetestm where CONCAT_WS(',',CCHAR6,CCHAR3,CCHAR7,'ALOHA') <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where CONCAT_WS(',',CCHAR6,CCHAR3) <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where CONCAT_WS(',',CCHAR6,CCHAR7) <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where CONCAT_WS(',',CCHAR6,'ALOHA') <> CCHAR6;
select cidx, CCHAR7 from datatypetestm where CONCAT_WS(',',CCHAR7,CCHAR3,CCHAR7,'ALOHA') <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where CONCAT_WS(',',CCHAR7,CCHAR3) <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where CONCAT_WS(',',CCHAR7,CCHAR7) <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where CONCAT_WS(',',CCHAR7,'ALOHA') <> CCHAR7;
select cidx, CCHAR8 from datatypetestm where CONCAT_WS(',',CCHAR8,CCHAR3,CCHAR7,'ALOHA') <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where CONCAT_WS(',',CCHAR8,CCHAR3) <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where CONCAT_WS(',',CCHAR8,CCHAR7) <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where CONCAT_WS(',',CCHAR8,'ALOHA') <> CCHAR8;
select cidx, CCHAR9 from datatypetestm where CONCAT_WS(',',CCHAR9,CCHAR3,CCHAR7,'ALOHA') <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where CONCAT_WS(',',CCHAR9,CCHAR3) <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where CONCAT_WS(',',CCHAR9,CCHAR7) <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where CONCAT_WS(',',CCHAR9,'ALOHA') <> CCHAR9;
select cidx, CCHAR255 from datatypetestm where CONCAT_WS(',',CCHAR255,CCHAR3,CCHAR7,'ALOHA') <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where CONCAT_WS(',',CCHAR255,CCHAR3) <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where CONCAT_WS(',',CCHAR255,CCHAR7) <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where CONCAT_WS(',',CCHAR255,'ALOHA') <> CCHAR255;
select cidx, CVCHAR1 from datatypetestm where CONCAT_WS(',',CVCHAR1,CCHAR3,CCHAR7,'ALOHA') <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where CONCAT_WS(',',CVCHAR1,CCHAR3) <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where CONCAT_WS(',',CVCHAR1,CCHAR7) <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where CONCAT_WS(',',CVCHAR1,'ALOHA') <> CVCHAR1;
select cidx, CVCHAR2 from datatypetestm where CONCAT_WS(',',CVCHAR2,CCHAR3,CCHAR7,'ALOHA') <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where CONCAT_WS(',',CVCHAR2,CCHAR3) <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where CONCAT_WS(',',CVCHAR2,CCHAR7) <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where CONCAT_WS(',',CVCHAR2,'ALOHA') <> CVCHAR2;
select cidx, CVCHAR3 from datatypetestm where CONCAT_WS(',',CVCHAR3,CCHAR3,CCHAR7,'ALOHA') <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where CONCAT_WS(',',CVCHAR3,CCHAR3) <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where CONCAT_WS(',',CVCHAR3,CCHAR7) <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where CONCAT_WS(',',CVCHAR3,'ALOHA') <> CVCHAR3;
select cidx, CVCHAR4 from datatypetestm where CONCAT_WS(',',CVCHAR4,CCHAR3,CCHAR7,'ALOHA') <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where CONCAT_WS(',',CVCHAR4,CCHAR3) <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where CONCAT_WS(',',CVCHAR4,CCHAR7) <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where CONCAT_WS(',',CVCHAR4,'ALOHA') <> CVCHAR4;
select cidx, CVCHAR5 from datatypetestm where CONCAT_WS(',',CVCHAR5,CCHAR3,CCHAR7,'ALOHA') <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where CONCAT_WS(',',CVCHAR5,CCHAR3) <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where CONCAT_WS(',',CVCHAR5,CCHAR7) <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where CONCAT_WS(',',CVCHAR5,'ALOHA') <> CVCHAR5;
select cidx, CVCHAR6 from datatypetestm where CONCAT_WS(',',CVCHAR6,CCHAR3,CCHAR7,'ALOHA') <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where CONCAT_WS(',',CVCHAR6,CCHAR3) <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where CONCAT_WS(',',CVCHAR6,CCHAR7) <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where CONCAT_WS(',',CVCHAR6,'ALOHA') <> CVCHAR6;
select cidx, CVCHAR7 from datatypetestm where CONCAT_WS(',',CVCHAR7,CCHAR3,CCHAR7,'ALOHA') <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where CONCAT_WS(',',CVCHAR7,CCHAR3) <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where CONCAT_WS(',',CVCHAR7,CCHAR7) <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where CONCAT_WS(',',CVCHAR7,'ALOHA') <> CVCHAR7;
select cidx, CVCHAR8 from datatypetestm where CONCAT_WS(',',CVCHAR8,CCHAR3,CCHAR7,'ALOHA') <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where CONCAT_WS(',',CVCHAR8,CCHAR3) <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where CONCAT_WS(',',CVCHAR8,CCHAR7) <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where CONCAT_WS(',',CVCHAR8,'ALOHA') <> CVCHAR8;
select cidx, CVCHAR255 from datatypetestm where CONCAT_WS(',',CVCHAR255,CCHAR3,CCHAR7,'ALOHA') <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where CONCAT_WS(',',CVCHAR255,CCHAR3) <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where CONCAT_WS(',',CVCHAR255,CCHAR7) <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where CONCAT_WS(',',CVCHAR255,'ALOHA') <> CVCHAR255;
