select cidx, CCHAR1, SUBSTRING(CCHAR1,1) from datatypetestm;
select cidx, CCHAR1, SUBSTRING(CCHAR1,5) from datatypetestm;
select cidx, CCHAR1, SUBSTRING(CCHAR1,7) from datatypetestm;
select cidx, CCHAR1, SUBSTRING(CCHAR1,8) from datatypetestm;
select cidx, CCHAR1, SUBSTRING(CCHAR1,9) from datatypetestm;
select cidx, CCHAR1, SUBSTRING(CCHAR1 FROM 5) from datatypetestm;
select cidx, CCHAR1, SUBSTRING(CCHAR1 FROM 9) from datatypetestm;
select cidx, CCHAR1, SUBSTRING(CCHAR1,5,2) from datatypetestm;
select cidx, CCHAR1, SUBSTRING(CCHAR1,9,3) from datatypetestm;
select cidx, CCHAR1, SUBSTRING(CCHAR1 FROM 5 FOR 2) from datatypetestm;
select cidx, CCHAR1, SUBSTRING(CCHAR1 FROM 9 FOR 3) from datatypetestm;
select cidx, CCHAR2, SUBSTRING(CCHAR2,1) from datatypetestm;
select cidx, CCHAR2, SUBSTRING(CCHAR2,5) from datatypetestm;
select cidx, CCHAR2, SUBSTRING(CCHAR2,7) from datatypetestm;
select cidx, CCHAR2, SUBSTRING(CCHAR2,8) from datatypetestm;
select cidx, CCHAR2, SUBSTRING(CCHAR2,9) from datatypetestm;
select cidx, CCHAR2, SUBSTRING(CCHAR2 FROM 5) from datatypetestm;
select cidx, CCHAR2, SUBSTRING(CCHAR2 FROM 9) from datatypetestm;
select cidx, CCHAR2, SUBSTRING(CCHAR2,5,2) from datatypetestm;
select cidx, CCHAR2, SUBSTRING(CCHAR2,9,3) from datatypetestm;
select cidx, CCHAR2, SUBSTRING(CCHAR2 FROM 5 FOR 2) from datatypetestm;
select cidx, CCHAR2, SUBSTRING(CCHAR2 FROM 9 FOR 3) from datatypetestm;
select cidx, CCHAR3, SUBSTRING(CCHAR3,1) from datatypetestm;
select cidx, CCHAR3, SUBSTRING(CCHAR3,5) from datatypetestm;
select cidx, CCHAR3, SUBSTRING(CCHAR3,7) from datatypetestm;
select cidx, CCHAR3, SUBSTRING(CCHAR3,8) from datatypetestm;
select cidx, CCHAR3, SUBSTRING(CCHAR3,9) from datatypetestm;
select cidx, CCHAR3, SUBSTRING(CCHAR3 FROM 5) from datatypetestm;
select cidx, CCHAR3, SUBSTRING(CCHAR3 FROM 9) from datatypetestm;
select cidx, CCHAR3, SUBSTRING(CCHAR3,5,2) from datatypetestm;
select cidx, CCHAR3, SUBSTRING(CCHAR3,9,3) from datatypetestm;
select cidx, CCHAR3, SUBSTRING(CCHAR3 FROM 5 FOR 2) from datatypetestm;
select cidx, CCHAR3, SUBSTRING(CCHAR3 FROM 9 FOR 3) from datatypetestm;
select cidx, CCHAR4, SUBSTRING(CCHAR4,1) from datatypetestm;
select cidx, CCHAR4, SUBSTRING(CCHAR4,5) from datatypetestm;
select cidx, CCHAR4, SUBSTRING(CCHAR4,7) from datatypetestm;
select cidx, CCHAR4, SUBSTRING(CCHAR4,8) from datatypetestm;
select cidx, CCHAR4, SUBSTRING(CCHAR4,9) from datatypetestm;
select cidx, CCHAR4, SUBSTRING(CCHAR4 FROM 5) from datatypetestm;
select cidx, CCHAR4, SUBSTRING(CCHAR4 FROM 9) from datatypetestm;
select cidx, CCHAR4, SUBSTRING(CCHAR4,5,2) from datatypetestm;
select cidx, CCHAR4, SUBSTRING(CCHAR4,9,3) from datatypetestm;
select cidx, CCHAR4, SUBSTRING(CCHAR4 FROM 5 FOR 2) from datatypetestm;
select cidx, CCHAR4, SUBSTRING(CCHAR4 FROM 9 FOR 3) from datatypetestm;
select cidx, CCHAR5, SUBSTRING(CCHAR5,1) from datatypetestm;
select cidx, CCHAR5, SUBSTRING(CCHAR5,5) from datatypetestm;
select cidx, CCHAR5, SUBSTRING(CCHAR5,7) from datatypetestm;
select cidx, CCHAR5, SUBSTRING(CCHAR5,8) from datatypetestm;
select cidx, CCHAR5, SUBSTRING(CCHAR5,9) from datatypetestm;
select cidx, CCHAR5, SUBSTRING(CCHAR5 FROM 5) from datatypetestm;
select cidx, CCHAR5, SUBSTRING(CCHAR5 FROM 9) from datatypetestm;
select cidx, CCHAR5, SUBSTRING(CCHAR5,5,2) from datatypetestm;
select cidx, CCHAR5, SUBSTRING(CCHAR5,9,3) from datatypetestm;
select cidx, CCHAR5, SUBSTRING(CCHAR5 FROM 5 FOR 2) from datatypetestm;
select cidx, CCHAR5, SUBSTRING(CCHAR5 FROM 9 FOR 3) from datatypetestm;
select cidx, CCHAR6, SUBSTRING(CCHAR6,1) from datatypetestm;
select cidx, CCHAR6, SUBSTRING(CCHAR6,5) from datatypetestm;
select cidx, CCHAR6, SUBSTRING(CCHAR6,7) from datatypetestm;
select cidx, CCHAR6, SUBSTRING(CCHAR6,8) from datatypetestm;
select cidx, CCHAR6, SUBSTRING(CCHAR6,9) from datatypetestm;
select cidx, CCHAR6, SUBSTRING(CCHAR6 FROM 5) from datatypetestm;
select cidx, CCHAR6, SUBSTRING(CCHAR6 FROM 9) from datatypetestm;
select cidx, CCHAR6, SUBSTRING(CCHAR6,5,2) from datatypetestm;
select cidx, CCHAR6, SUBSTRING(CCHAR6,9,3) from datatypetestm;
select cidx, CCHAR6, SUBSTRING(CCHAR6 FROM 5 FOR 2) from datatypetestm;
select cidx, CCHAR6, SUBSTRING(CCHAR6 FROM 9 FOR 3) from datatypetestm;
select cidx, CCHAR7, SUBSTRING(CCHAR7,1) from datatypetestm;
select cidx, CCHAR7, SUBSTRING(CCHAR7,5) from datatypetestm;
select cidx, CCHAR7, SUBSTRING(CCHAR7,7) from datatypetestm;
select cidx, CCHAR7, SUBSTRING(CCHAR7,8) from datatypetestm;
select cidx, CCHAR7, SUBSTRING(CCHAR7,9) from datatypetestm;
select cidx, CCHAR7, SUBSTRING(CCHAR7 FROM 5) from datatypetestm;
select cidx, CCHAR7, SUBSTRING(CCHAR7 FROM 9) from datatypetestm;
select cidx, CCHAR7, SUBSTRING(CCHAR7,5,2) from datatypetestm;
select cidx, CCHAR7, SUBSTRING(CCHAR7,9,3) from datatypetestm;
select cidx, CCHAR7, SUBSTRING(CCHAR7 FROM 5 FOR 2) from datatypetestm;
select cidx, CCHAR7, SUBSTRING(CCHAR7 FROM 9 FOR 3) from datatypetestm;
select cidx, CCHAR8, SUBSTRING(CCHAR8,1) from datatypetestm;
select cidx, CCHAR8, SUBSTRING(CCHAR8,5) from datatypetestm;
select cidx, CCHAR8, SUBSTRING(CCHAR8,7) from datatypetestm;
select cidx, CCHAR8, SUBSTRING(CCHAR8,8) from datatypetestm;
select cidx, CCHAR8, SUBSTRING(CCHAR8,9) from datatypetestm;
select cidx, CCHAR8, SUBSTRING(CCHAR8 FROM 5) from datatypetestm;
select cidx, CCHAR8, SUBSTRING(CCHAR8 FROM 9) from datatypetestm;
select cidx, CCHAR8, SUBSTRING(CCHAR8,5,2) from datatypetestm;
select cidx, CCHAR8, SUBSTRING(CCHAR8,9,3) from datatypetestm;
select cidx, CCHAR8, SUBSTRING(CCHAR8 FROM 5 FOR 2) from datatypetestm;
select cidx, CCHAR8, SUBSTRING(CCHAR8 FROM 9 FOR 3) from datatypetestm;
select cidx, CCHAR9, SUBSTRING(CCHAR9,1) from datatypetestm;
select cidx, CCHAR9, SUBSTRING(CCHAR9,5) from datatypetestm;
select cidx, CCHAR9, SUBSTRING(CCHAR9,7) from datatypetestm;
select cidx, CCHAR9, SUBSTRING(CCHAR9,8) from datatypetestm;
select cidx, CCHAR9, SUBSTRING(CCHAR9,9) from datatypetestm;
select cidx, CCHAR9, SUBSTRING(CCHAR9 FROM 5) from datatypetestm;
select cidx, CCHAR9, SUBSTRING(CCHAR9 FROM 9) from datatypetestm;
select cidx, CCHAR9, SUBSTRING(CCHAR9,5,2) from datatypetestm;
select cidx, CCHAR9, SUBSTRING(CCHAR9,9,3) from datatypetestm;
select cidx, CCHAR9, SUBSTRING(CCHAR9 FROM 5 FOR 2) from datatypetestm;
select cidx, CCHAR9, SUBSTRING(CCHAR9 FROM 9 FOR 3) from datatypetestm;
select cidx, CCHAR255, SUBSTRING(CCHAR255,1) from datatypetestm;
select cidx, CCHAR255, SUBSTRING(CCHAR255,5) from datatypetestm;
select cidx, CCHAR255, SUBSTRING(CCHAR255,7) from datatypetestm;
select cidx, CCHAR255, SUBSTRING(CCHAR255,8) from datatypetestm;
select cidx, CCHAR255, SUBSTRING(CCHAR255,9) from datatypetestm;
select cidx, CCHAR255, SUBSTRING(CCHAR255 FROM 5) from datatypetestm;
select cidx, CCHAR255, SUBSTRING(CCHAR255 FROM 9) from datatypetestm;
select cidx, CCHAR255, SUBSTRING(CCHAR255,5,2) from datatypetestm;
select cidx, CCHAR255, SUBSTRING(CCHAR255,9,3) from datatypetestm;
select cidx, CCHAR255, SUBSTRING(CCHAR255 FROM 5 FOR 2) from datatypetestm;
select cidx, CCHAR255, SUBSTRING(CCHAR255 FROM 9 FOR 3) from datatypetestm;
select cidx, CVCHAR1, SUBSTRING(CVCHAR1,1) from datatypetestm;
select cidx, CVCHAR1, SUBSTRING(CVCHAR1,5) from datatypetestm;
select cidx, CVCHAR1, SUBSTRING(CVCHAR1,7) from datatypetestm;
select cidx, CVCHAR1, SUBSTRING(CVCHAR1,8) from datatypetestm;
select cidx, CVCHAR1, SUBSTRING(CVCHAR1,9) from datatypetestm;
select cidx, CVCHAR1, SUBSTRING(CVCHAR1 FROM 5) from datatypetestm;
select cidx, CVCHAR1, SUBSTRING(CVCHAR1 FROM 9) from datatypetestm;
select cidx, CVCHAR1, SUBSTRING(CVCHAR1,5,2) from datatypetestm;
select cidx, CVCHAR1, SUBSTRING(CVCHAR1,9,3) from datatypetestm;
select cidx, CVCHAR1, SUBSTRING(CVCHAR1 FROM 5 FOR 2) from datatypetestm;
select cidx, CVCHAR1, SUBSTRING(CVCHAR1 FROM 9 FOR 3) from datatypetestm;
select cidx, CVCHAR2, SUBSTRING(CVCHAR2,1) from datatypetestm;
select cidx, CVCHAR2, SUBSTRING(CVCHAR2,5) from datatypetestm;
select cidx, CVCHAR2, SUBSTRING(CVCHAR2,7) from datatypetestm;
select cidx, CVCHAR2, SUBSTRING(CVCHAR2,8) from datatypetestm;
select cidx, CVCHAR2, SUBSTRING(CVCHAR2,9) from datatypetestm;
select cidx, CVCHAR2, SUBSTRING(CVCHAR2 FROM 5) from datatypetestm;
select cidx, CVCHAR2, SUBSTRING(CVCHAR2 FROM 9) from datatypetestm;
select cidx, CVCHAR2, SUBSTRING(CVCHAR2,5,2) from datatypetestm;
select cidx, CVCHAR2, SUBSTRING(CVCHAR2,9,3) from datatypetestm;
select cidx, CVCHAR2, SUBSTRING(CVCHAR2 FROM 5 FOR 2) from datatypetestm;
select cidx, CVCHAR2, SUBSTRING(CVCHAR2 FROM 9 FOR 3) from datatypetestm;
select cidx, CVCHAR3, SUBSTRING(CVCHAR3,1) from datatypetestm;
select cidx, CVCHAR3, SUBSTRING(CVCHAR3,5) from datatypetestm;
select cidx, CVCHAR3, SUBSTRING(CVCHAR3,7) from datatypetestm;
select cidx, CVCHAR3, SUBSTRING(CVCHAR3,8) from datatypetestm;
select cidx, CVCHAR3, SUBSTRING(CVCHAR3,9) from datatypetestm;
select cidx, CVCHAR3, SUBSTRING(CVCHAR3 FROM 5) from datatypetestm;
select cidx, CVCHAR3, SUBSTRING(CVCHAR3 FROM 9) from datatypetestm;
select cidx, CVCHAR3, SUBSTRING(CVCHAR3,5,2) from datatypetestm;
select cidx, CVCHAR3, SUBSTRING(CVCHAR3,9,3) from datatypetestm;
select cidx, CVCHAR3, SUBSTRING(CVCHAR3 FROM 5 FOR 2) from datatypetestm;
select cidx, CVCHAR3, SUBSTRING(CVCHAR3 FROM 9 FOR 3) from datatypetestm;
select cidx, CVCHAR4, SUBSTRING(CVCHAR4,1) from datatypetestm;
select cidx, CVCHAR4, SUBSTRING(CVCHAR4,5) from datatypetestm;
select cidx, CVCHAR4, SUBSTRING(CVCHAR4,7) from datatypetestm;
select cidx, CVCHAR4, SUBSTRING(CVCHAR4,8) from datatypetestm;
select cidx, CVCHAR4, SUBSTRING(CVCHAR4,9) from datatypetestm;
select cidx, CVCHAR4, SUBSTRING(CVCHAR4 FROM 5) from datatypetestm;
select cidx, CVCHAR4, SUBSTRING(CVCHAR4 FROM 9) from datatypetestm;
select cidx, CVCHAR4, SUBSTRING(CVCHAR4,5,2) from datatypetestm;
select cidx, CVCHAR4, SUBSTRING(CVCHAR4,9,3) from datatypetestm;
select cidx, CVCHAR4, SUBSTRING(CVCHAR4 FROM 5 FOR 2) from datatypetestm;
select cidx, CVCHAR4, SUBSTRING(CVCHAR4 FROM 9 FOR 3) from datatypetestm;
select cidx, CVCHAR5, SUBSTRING(CVCHAR5,1) from datatypetestm;
select cidx, CVCHAR5, SUBSTRING(CVCHAR5,5) from datatypetestm;
select cidx, CVCHAR5, SUBSTRING(CVCHAR5,7) from datatypetestm;
select cidx, CVCHAR5, SUBSTRING(CVCHAR5,8) from datatypetestm;
select cidx, CVCHAR5, SUBSTRING(CVCHAR5,9) from datatypetestm;
select cidx, CVCHAR5, SUBSTRING(CVCHAR5 FROM 5) from datatypetestm;
select cidx, CVCHAR5, SUBSTRING(CVCHAR5 FROM 9) from datatypetestm;
select cidx, CVCHAR5, SUBSTRING(CVCHAR5,5,2) from datatypetestm;
select cidx, CVCHAR5, SUBSTRING(CVCHAR5,9,3) from datatypetestm;
select cidx, CVCHAR5, SUBSTRING(CVCHAR5 FROM 5 FOR 2) from datatypetestm;
select cidx, CVCHAR5, SUBSTRING(CVCHAR5 FROM 9 FOR 3) from datatypetestm;
select cidx, CVCHAR6, SUBSTRING(CVCHAR6,1) from datatypetestm;
select cidx, CVCHAR6, SUBSTRING(CVCHAR6,5) from datatypetestm;
select cidx, CVCHAR6, SUBSTRING(CVCHAR6,7) from datatypetestm;
select cidx, CVCHAR6, SUBSTRING(CVCHAR6,8) from datatypetestm;
select cidx, CVCHAR6, SUBSTRING(CVCHAR6,9) from datatypetestm;
select cidx, CVCHAR6, SUBSTRING(CVCHAR6 FROM 5) from datatypetestm;
select cidx, CVCHAR6, SUBSTRING(CVCHAR6 FROM 9) from datatypetestm;
select cidx, CVCHAR6, SUBSTRING(CVCHAR6,5,2) from datatypetestm;
select cidx, CVCHAR6, SUBSTRING(CVCHAR6,9,3) from datatypetestm;
select cidx, CVCHAR6, SUBSTRING(CVCHAR6 FROM 5 FOR 2) from datatypetestm;
select cidx, CVCHAR6, SUBSTRING(CVCHAR6 FROM 9 FOR 3) from datatypetestm;
select cidx, CVCHAR7, SUBSTRING(CVCHAR7,1) from datatypetestm;
select cidx, CVCHAR7, SUBSTRING(CVCHAR7,5) from datatypetestm;
select cidx, CVCHAR7, SUBSTRING(CVCHAR7,7) from datatypetestm;
select cidx, CVCHAR7, SUBSTRING(CVCHAR7,8) from datatypetestm;
select cidx, CVCHAR7, SUBSTRING(CVCHAR7,9) from datatypetestm;
select cidx, CVCHAR7, SUBSTRING(CVCHAR7 FROM 5) from datatypetestm;
select cidx, CVCHAR7, SUBSTRING(CVCHAR7 FROM 9) from datatypetestm;
select cidx, CVCHAR7, SUBSTRING(CVCHAR7,5,2) from datatypetestm;
select cidx, CVCHAR7, SUBSTRING(CVCHAR7,9,3) from datatypetestm;
select cidx, CVCHAR7, SUBSTRING(CVCHAR7 FROM 5 FOR 2) from datatypetestm;
select cidx, CVCHAR7, SUBSTRING(CVCHAR7 FROM 9 FOR 3) from datatypetestm;
select cidx, CVCHAR8, SUBSTRING(CVCHAR8,1) from datatypetestm;
select cidx, CVCHAR8, SUBSTRING(CVCHAR8,5) from datatypetestm;
select cidx, CVCHAR8, SUBSTRING(CVCHAR8,7) from datatypetestm;
select cidx, CVCHAR8, SUBSTRING(CVCHAR8,8) from datatypetestm;
select cidx, CVCHAR8, SUBSTRING(CVCHAR8,9) from datatypetestm;
select cidx, CVCHAR8, SUBSTRING(CVCHAR8 FROM 5) from datatypetestm;
select cidx, CVCHAR8, SUBSTRING(CVCHAR8 FROM 9) from datatypetestm;
select cidx, CVCHAR8, SUBSTRING(CVCHAR8,5,2) from datatypetestm;
select cidx, CVCHAR8, SUBSTRING(CVCHAR8,9,3) from datatypetestm;
select cidx, CVCHAR8, SUBSTRING(CVCHAR8 FROM 5 FOR 2) from datatypetestm;
select cidx, CVCHAR8, SUBSTRING(CVCHAR8 FROM 9 FOR 3) from datatypetestm;
select cidx, CVCHAR255, SUBSTRING(CVCHAR255,1) from datatypetestm;
select cidx, CVCHAR255, SUBSTRING(CVCHAR255,5) from datatypetestm;
select cidx, CVCHAR255, SUBSTRING(CVCHAR255,7) from datatypetestm;
select cidx, CVCHAR255, SUBSTRING(CVCHAR255,8) from datatypetestm;
select cidx, CVCHAR255, SUBSTRING(CVCHAR255,9) from datatypetestm;
select cidx, CVCHAR255, SUBSTRING(CVCHAR255 FROM 5) from datatypetestm;
select cidx, CVCHAR255, SUBSTRING(CVCHAR255 FROM 9) from datatypetestm;
select cidx, CVCHAR255, SUBSTRING(CVCHAR255,5,2) from datatypetestm;
select cidx, CVCHAR255, SUBSTRING(CVCHAR255,9,3) from datatypetestm;
select cidx, CVCHAR255, SUBSTRING(CVCHAR255 FROM 5 FOR 2) from datatypetestm;
select cidx, CVCHAR255, SUBSTRING(CVCHAR255 FROM 9 FOR 3) from datatypetestm;
select cidx, CCHAR1 from datatypetestm where SUBSTRING(CCHAR1,1) <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where SUBSTRING(CCHAR1,5) <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where SUBSTRING(CCHAR1,7) <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where SUBSTRING(CCHAR1,8) <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where SUBSTRING(CCHAR1,9) <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where SUBSTRING(CCHAR1 FROM 5) <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where SUBSTRING(CCHAR1 FROM 9) <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where SUBSTRING(CCHAR1,5,2) <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where SUBSTRING(CCHAR1,9,3) <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where SUBSTRING(CCHAR1 FROM 5 FOR 2) <> CCHAR1;
select cidx, CCHAR1 from datatypetestm where SUBSTRING(CCHAR1 FROM 9 FOR 3) <> CCHAR1;
select cidx, CCHAR2 from datatypetestm where SUBSTRING(CCHAR2,1) <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where SUBSTRING(CCHAR2,5) <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where SUBSTRING(CCHAR2,7) <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where SUBSTRING(CCHAR2,8) <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where SUBSTRING(CCHAR2,9) <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where SUBSTRING(CCHAR2 FROM 5) <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where SUBSTRING(CCHAR2 FROM 9) <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where SUBSTRING(CCHAR2,5,2) <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where SUBSTRING(CCHAR2,9,3) <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where SUBSTRING(CCHAR2 FROM 5 FOR 2) <> CCHAR2;
select cidx, CCHAR2 from datatypetestm where SUBSTRING(CCHAR2 FROM 9 FOR 3) <> CCHAR2;
select cidx, CCHAR3 from datatypetestm where SUBSTRING(CCHAR3,1) <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where SUBSTRING(CCHAR3,5) <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where SUBSTRING(CCHAR3,7) <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where SUBSTRING(CCHAR3,8) <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where SUBSTRING(CCHAR3,9) <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where SUBSTRING(CCHAR3 FROM 5) <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where SUBSTRING(CCHAR3 FROM 9) <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where SUBSTRING(CCHAR3,5,2) <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where SUBSTRING(CCHAR3,9,3) <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where SUBSTRING(CCHAR3 FROM 5 FOR 2) <> CCHAR3;
select cidx, CCHAR3 from datatypetestm where SUBSTRING(CCHAR3 FROM 9 FOR 3) <> CCHAR3;
select cidx, CCHAR4 from datatypetestm where SUBSTRING(CCHAR4,1) <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where SUBSTRING(CCHAR4,5) <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where SUBSTRING(CCHAR4,7) <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where SUBSTRING(CCHAR4,8) <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where SUBSTRING(CCHAR4,9) <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where SUBSTRING(CCHAR4 FROM 5) <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where SUBSTRING(CCHAR4 FROM 9) <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where SUBSTRING(CCHAR4,5,2) <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where SUBSTRING(CCHAR4,9,3) <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where SUBSTRING(CCHAR4 FROM 5 FOR 2) <> CCHAR4;
select cidx, CCHAR4 from datatypetestm where SUBSTRING(CCHAR4 FROM 9 FOR 3) <> CCHAR4;
select cidx, CCHAR5 from datatypetestm where SUBSTRING(CCHAR5,1) <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where SUBSTRING(CCHAR5,5) <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where SUBSTRING(CCHAR5,7) <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where SUBSTRING(CCHAR5,8) <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where SUBSTRING(CCHAR5,9) <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where SUBSTRING(CCHAR5 FROM 5) <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where SUBSTRING(CCHAR5 FROM 9) <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where SUBSTRING(CCHAR5,5,2) <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where SUBSTRING(CCHAR5,9,3) <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where SUBSTRING(CCHAR5 FROM 5 FOR 2) <> CCHAR5;
select cidx, CCHAR5 from datatypetestm where SUBSTRING(CCHAR5 FROM 9 FOR 3) <> CCHAR5;
select cidx, CCHAR6 from datatypetestm where SUBSTRING(CCHAR6,1) <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where SUBSTRING(CCHAR6,5) <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where SUBSTRING(CCHAR6,7) <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where SUBSTRING(CCHAR6,8) <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where SUBSTRING(CCHAR6,9) <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where SUBSTRING(CCHAR6 FROM 5) <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where SUBSTRING(CCHAR6 FROM 9) <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where SUBSTRING(CCHAR6,5,2) <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where SUBSTRING(CCHAR6,9,3) <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where SUBSTRING(CCHAR6 FROM 5 FOR 2) <> CCHAR6;
select cidx, CCHAR6 from datatypetestm where SUBSTRING(CCHAR6 FROM 9 FOR 3) <> CCHAR6;
select cidx, CCHAR7 from datatypetestm where SUBSTRING(CCHAR7,1) <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where SUBSTRING(CCHAR7,5) <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where SUBSTRING(CCHAR7,7) <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where SUBSTRING(CCHAR7,8) <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where SUBSTRING(CCHAR7,9) <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where SUBSTRING(CCHAR7 FROM 5) <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where SUBSTRING(CCHAR7 FROM 9) <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where SUBSTRING(CCHAR7,5,2) <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where SUBSTRING(CCHAR7,9,3) <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where SUBSTRING(CCHAR7 FROM 5 FOR 2) <> CCHAR7;
select cidx, CCHAR7 from datatypetestm where SUBSTRING(CCHAR7 FROM 9 FOR 3) <> CCHAR7;
select cidx, CCHAR8 from datatypetestm where SUBSTRING(CCHAR8,1) <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where SUBSTRING(CCHAR8,5) <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where SUBSTRING(CCHAR8,7) <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where SUBSTRING(CCHAR8,8) <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where SUBSTRING(CCHAR8,9) <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where SUBSTRING(CCHAR8 FROM 5) <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where SUBSTRING(CCHAR8 FROM 9) <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where SUBSTRING(CCHAR8,5,2) <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where SUBSTRING(CCHAR8,9,3) <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where SUBSTRING(CCHAR8 FROM 5 FOR 2) <> CCHAR8;
select cidx, CCHAR8 from datatypetestm where SUBSTRING(CCHAR8 FROM 9 FOR 3) <> CCHAR8;
select cidx, CCHAR9 from datatypetestm where SUBSTRING(CCHAR9,1) <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where SUBSTRING(CCHAR9,5) <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where SUBSTRING(CCHAR9,7) <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where SUBSTRING(CCHAR9,8) <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where SUBSTRING(CCHAR9,9) <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where SUBSTRING(CCHAR9 FROM 5) <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where SUBSTRING(CCHAR9 FROM 9) <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where SUBSTRING(CCHAR9,5,2) <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where SUBSTRING(CCHAR9,9,3) <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where SUBSTRING(CCHAR9 FROM 5 FOR 2) <> CCHAR9;
select cidx, CCHAR9 from datatypetestm where SUBSTRING(CCHAR9 FROM 9 FOR 3) <> CCHAR9;
select cidx, CCHAR255 from datatypetestm where SUBSTRING(CCHAR255,1) <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where SUBSTRING(CCHAR255,5) <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where SUBSTRING(CCHAR255,7) <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where SUBSTRING(CCHAR255,8) <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where SUBSTRING(CCHAR255,9) <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where SUBSTRING(CCHAR255 FROM 5) <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where SUBSTRING(CCHAR255 FROM 9) <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where SUBSTRING(CCHAR255,5,2) <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where SUBSTRING(CCHAR255,9,3) <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where SUBSTRING(CCHAR255 FROM 5 FOR 2) <> CCHAR255;
select cidx, CCHAR255 from datatypetestm where SUBSTRING(CCHAR255 FROM 9 FOR 3) <> CCHAR255;
select cidx, CVCHAR1 from datatypetestm where SUBSTRING(CVCHAR1,1) <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where SUBSTRING(CVCHAR1,5) <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where SUBSTRING(CVCHAR1,7) <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where SUBSTRING(CVCHAR1,8) <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where SUBSTRING(CVCHAR1,9) <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where SUBSTRING(CVCHAR1 FROM 5) <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where SUBSTRING(CVCHAR1 FROM 9) <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where SUBSTRING(CVCHAR1,5,2) <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where SUBSTRING(CVCHAR1,9,3) <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where SUBSTRING(CVCHAR1 FROM 5 FOR 2) <> CVCHAR1;
select cidx, CVCHAR1 from datatypetestm where SUBSTRING(CVCHAR1 FROM 9 FOR 3) <> CVCHAR1;
select cidx, CVCHAR2 from datatypetestm where SUBSTRING(CVCHAR2,1) <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where SUBSTRING(CVCHAR2,5) <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where SUBSTRING(CVCHAR2,7) <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where SUBSTRING(CVCHAR2,8) <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where SUBSTRING(CVCHAR2,9) <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where SUBSTRING(CVCHAR2 FROM 5) <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where SUBSTRING(CVCHAR2 FROM 9) <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where SUBSTRING(CVCHAR2,5,2) <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where SUBSTRING(CVCHAR2,9,3) <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where SUBSTRING(CVCHAR2 FROM 5 FOR 2) <> CVCHAR2;
select cidx, CVCHAR2 from datatypetestm where SUBSTRING(CVCHAR2 FROM 9 FOR 3) <> CVCHAR2;
select cidx, CVCHAR3 from datatypetestm where SUBSTRING(CVCHAR3,1) <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where SUBSTRING(CVCHAR3,5) <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where SUBSTRING(CVCHAR3,7) <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where SUBSTRING(CVCHAR3,8) <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where SUBSTRING(CVCHAR3,9) <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where SUBSTRING(CVCHAR3 FROM 5) <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where SUBSTRING(CVCHAR3 FROM 9) <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where SUBSTRING(CVCHAR3,5,2) <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where SUBSTRING(CVCHAR3,9,3) <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where SUBSTRING(CVCHAR3 FROM 5 FOR 2) <> CVCHAR3;
select cidx, CVCHAR3 from datatypetestm where SUBSTRING(CVCHAR3 FROM 9 FOR 3) <> CVCHAR3;
select cidx, CVCHAR4 from datatypetestm where SUBSTRING(CVCHAR4,1) <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where SUBSTRING(CVCHAR4,5) <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where SUBSTRING(CVCHAR4,7) <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where SUBSTRING(CVCHAR4,8) <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where SUBSTRING(CVCHAR4,9) <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where SUBSTRING(CVCHAR4 FROM 5) <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where SUBSTRING(CVCHAR4 FROM 9) <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where SUBSTRING(CVCHAR4,5,2) <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where SUBSTRING(CVCHAR4,9,3) <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where SUBSTRING(CVCHAR4 FROM 5 FOR 2) <> CVCHAR4;
select cidx, CVCHAR4 from datatypetestm where SUBSTRING(CVCHAR4 FROM 9 FOR 3) <> CVCHAR4;
select cidx, CVCHAR5 from datatypetestm where SUBSTRING(CVCHAR5,1) <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where SUBSTRING(CVCHAR5,5) <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where SUBSTRING(CVCHAR5,7) <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where SUBSTRING(CVCHAR5,8) <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where SUBSTRING(CVCHAR5,9) <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where SUBSTRING(CVCHAR5 FROM 5) <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where SUBSTRING(CVCHAR5 FROM 9) <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where SUBSTRING(CVCHAR5,5,2) <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where SUBSTRING(CVCHAR5,9,3) <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where SUBSTRING(CVCHAR5 FROM 5 FOR 2) <> CVCHAR5;
select cidx, CVCHAR5 from datatypetestm where SUBSTRING(CVCHAR5 FROM 9 FOR 3) <> CVCHAR5;
select cidx, CVCHAR6 from datatypetestm where SUBSTRING(CVCHAR6,1) <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where SUBSTRING(CVCHAR6,5) <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where SUBSTRING(CVCHAR6,7) <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where SUBSTRING(CVCHAR6,8) <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where SUBSTRING(CVCHAR6,9) <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where SUBSTRING(CVCHAR6 FROM 5) <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where SUBSTRING(CVCHAR6 FROM 9) <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where SUBSTRING(CVCHAR6,5,2) <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where SUBSTRING(CVCHAR6,9,3) <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where SUBSTRING(CVCHAR6 FROM 5 FOR 2) <> CVCHAR6;
select cidx, CVCHAR6 from datatypetestm where SUBSTRING(CVCHAR6 FROM 9 FOR 3) <> CVCHAR6;
select cidx, CVCHAR7 from datatypetestm where SUBSTRING(CVCHAR7,1) <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where SUBSTRING(CVCHAR7,5) <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where SUBSTRING(CVCHAR7,7) <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where SUBSTRING(CVCHAR7,8) <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where SUBSTRING(CVCHAR7,9) <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where SUBSTRING(CVCHAR7 FROM 5) <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where SUBSTRING(CVCHAR7 FROM 9) <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where SUBSTRING(CVCHAR7,5,2) <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where SUBSTRING(CVCHAR7,9,3) <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where SUBSTRING(CVCHAR7 FROM 5 FOR 2) <> CVCHAR7;
select cidx, CVCHAR7 from datatypetestm where SUBSTRING(CVCHAR7 FROM 9 FOR 3) <> CVCHAR7;
select cidx, CVCHAR8 from datatypetestm where SUBSTRING(CVCHAR8,1) <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where SUBSTRING(CVCHAR8,5) <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where SUBSTRING(CVCHAR8,7) <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where SUBSTRING(CVCHAR8,8) <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where SUBSTRING(CVCHAR8,9) <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where SUBSTRING(CVCHAR8 FROM 5) <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where SUBSTRING(CVCHAR8 FROM 9) <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where SUBSTRING(CVCHAR8,5,2) <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where SUBSTRING(CVCHAR8,9,3) <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where SUBSTRING(CVCHAR8 FROM 5 FOR 2) <> CVCHAR8;
select cidx, CVCHAR8 from datatypetestm where SUBSTRING(CVCHAR8 FROM 9 FOR 3) <> CVCHAR8;
select cidx, CVCHAR255 from datatypetestm where SUBSTRING(CVCHAR255,1) <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where SUBSTRING(CVCHAR255,5) <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where SUBSTRING(CVCHAR255,7) <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where SUBSTRING(CVCHAR255,8) <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where SUBSTRING(CVCHAR255,9) <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where SUBSTRING(CVCHAR255 FROM 5) <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where SUBSTRING(CVCHAR255 FROM 9) <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where SUBSTRING(CVCHAR255,5,2) <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where SUBSTRING(CVCHAR255,9,3) <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where SUBSTRING(CVCHAR255 FROM 5 FOR 2) <> CVCHAR255;
select cidx, CVCHAR255 from datatypetestm where SUBSTRING(CVCHAR255 FROM 9 FOR 3) <> CVCHAR255;
