alter table customer add column c_name8 char(8);
alter table customer add column c_name50 varchar(50); 
alter table customer add column c_name100 varchar(100); 
alter table customer add column c_name150 varchar(150); 
alter table customer add column c_name200 varchar(200); 
alter table customer add column c_name250 varchar(250); 
alter table customer add column c_name300 varchar(300); 
alter table customer add column c_name350 varchar(350); 
alter table customer add column c_name400 varchar(400); 
alter table customer add column c_name1000 varchar(1000); 
alter table customer add column c_name2000 varchar(2000); 
alter table customer add column c_name4000 varchar(4000); 

update customer set c_name8=c_name;
update customer set c_name50=c_name;
update customer set c_name100=c_name;
update customer set c_name150=c_name;
update customer set c_name200=c_name;
update customer set c_name250=c_name;
update customer set c_name300=c_name;
update customer set c_name350=c_name;
update customer set c_name400=c_name;
update customer set c_name1000=c_name;
update customer set c_name2000=c_name;
update customer set c_name4000=c_name;
