
#Nested levels 2 to 7
SELECT LENGTH(SUBSTRING(CDATE, SIGN(CINTEGER))) FROM DATATYPETESTM;
SELECT LENGTH(CONCAT(SUBSTRING(CDATE, SIGN(CINTEGER)),'hELLO, wORLD')) FROM DATATYPETESTM;
SELECT POWER(LENGTH(CONCAT(SUBSTRING(CDATE, SIGN(CINTEGER)),'hELLO, wORLD')),3) as col1 FROM DATATYPETESTM;
SELECT CSMALLINT + POWER(LENGTH(CONCAT(SUBSTRING(CDATE, SIGN(CINTEGER)),'hELLO, wORLD')),3) as col1 FROM DATATYPETESTM;
SELECT SIGN(CSMALLINT + POWER(LENGTH(CONCAT(SUBSTRING(CDATE, SIGN(CINTEGER)),'hELLO, wORLD')),3)) as col1 FROM DATATYPETESTM;
#
SELECT CIDX FROM DATATYPETESTM WHERE LENGTH(SUBSTRING(CDATE, SIGN(CINTEGER))) = 10;
SELECT CIDX FROM DATATYPETESTM WHERE LENGTH(CONCAT(SUBSTRING(CDATE, SIGN(CINTEGER)),'hELLO, wORLD')) = 12;
SELECT CIDX FROM DATATYPETESTM WHERE POWER(LENGTH(CONCAT(SUBSTRING(CDATE, SIGN(CINTEGER)),'hELLO, wORLD')),3) = 1728;
SELECT CIDX FROM DATATYPETESTM WHERE CSMALLINT + POWER(LENGTH(CONCAT(SUBSTRING(CDATE, SIGN(CINTEGER)),'hELLO, wORLD')),3) > 43412;
SELECT CIDX FROM DATATYPETESTM WHERE SIGN(CSMALLINT + POWER(LENGTH(CONCAT(SUBSTRING(CDATE, SIGN(CINTEGER)),'hELLO, wORLD')),3)) = 1;
