select count(*) from (select c_temp from wide.wide2) a ;
select count(*) from (select c9 from wide.wide2) a ;
select count(*) from (select c16 from wide.wide2) a ;
select count(*) from (select c18 from wide.wide2) a ;
select count(*) from (select c20 from wide.wide2) a ;
select count(*) from wide.wide2 a join wide.wide2 b using (c_temp) ;
select count(*) from wide.wide2 a join wide.wide2 b using (c9) ;
select count(*) from wide.wide2 a join wide.wide2 b using (c16) ;
select count(*) from wide.wide2 a join wide.wide2 b using (c18) ;
select count(*) from wide.wide2 a join wide.wide2 b using (c20) ;
select count(distinct(c_temp)) from wide.wide2;
select count(distinct(c9)) from wide.wide2;
select count(distinct(c16)) from wide.wide2;
select count(distinct(c18)) from wide.wide2;
select count(distinct(c19)) from wide.wide2;
select count(distinct(c)) from (select c_temp c from wide.wide2 a join wide.wide2 b using (c_temp) ) a;
select count(distinct(c)) from (select c9 c from wide.wide2 a join wide.wide2 b using (c9) ) a;
select count(distinct(c)) from (select c16 c from wide.wide2 a join wide.wide2 b using (c16) ) a;
select count(distinct(c)) from (select c18 c from wide.wide2 a join wide.wide2 b using (c18) ) a;
select count(distinct(c)) from (select c19 c from wide.wide2 a join wide.wide2 b using (c19) ) a;
select f, count(*) from ( select length(c_temp) f from wide.wide2) a group by f order by f desc;
select f, count(*) from ( select length(c9) f from wide.wide2) a group by f order by f desc;
select f, count(*) from ( select length(c16) f from wide.wide2) a group by f order by f desc;
select f, count(*) from ( select length(c18) f from wide.wide2) a group by f order by f desc;
select f, count(*) from ( select length(c19) f from wide.wide2) a group by f order by f desc;
select f, count(*) from ( select c_temp, avg(length(c_temp)) f from wide.wide2 group by 1) a group by f order by f desc;
select f, count(*) from ( select c9, avg(length(c9)) f from wide.wide2 group by 1) a group by f order by f desc;
select f, count(*) from ( select c16, avg(length(c16)) f from wide.wide2 group by 1) a group by f order by f desc;
select f, count(*) from ( select c18, avg(length(c18)) f from wide.wide2 group by 1) a group by f order by f desc;
select f, count(*) from ( select c19, avg(length(c19)) f from wide.wide2 group by 1) a group by f order by f desc;
select count(*) from ( select c_temp from wide.wide2 union all select c_temp from wide.wide2) a;
select count(*) from ( select c9 from wide.wide2 union all select c9 from wide.wide2) a;
select count(*) from ( select c16 from wide.wide2 union all select c16 from wide.wide2) a;
select count(*) from ( select c18 from wide.wide2 union all select c18 from wide.wide2) a;
select count(*) from ( select c19 from wide.wide2 union all select c19 from wide.wide2) a;
select count(*) from ( select c_temp from wide.wide2 union select c_temp from wide.wide2) a;
select count(*) from ( select c9 from wide.wide2 union select c9 from wide.wide2) a;
select count(*) from ( select c16 from wide.wide2 union select c16 from wide.wide2) a;
select count(*) from ( select c18 from wide.wide2 union select c18 from wide.wide2) a;
select count(*) from ( select c19 from wide.wide2 union select c19 from wide.wide2) a;
select * from (select c_temp from wide.wide2 order by 1 limit 5) a ;
select * from (select c9 from wide.wide2 order by 1 limit 5) a ;
select * from (select c16 from wide.wide2 order by 1 limit 5) a ;
select * from (select c18 from wide.wide2 order by 1 limit 5) a ;
select * from (select c19 from wide.wide2 order by 1 limit 5) a ;
