select cidx, CBIGINT, TAN(CBIGINT) from datatypetestm;
select cidx, CDECIMAL1, TAN(CDECIMAL1) from datatypetestm;
select cidx, CDECIMAL4, TAN(CDECIMAL4) from datatypetestm;
select cidx, CDECIMAL4_2, TAN(CDECIMAL4_2) from datatypetestm;
select cidx, CDECIMAL5, TAN(CDECIMAL5) from datatypetestm;
select cidx, CDECIMAL9, TAN(CDECIMAL9) from datatypetestm;
select cidx, CDECIMAL9_2, TAN(CDECIMAL9_2) from datatypetestm;
select cidx, CDECIMAL10, TAN(CDECIMAL10) from datatypetestm;
select cidx, CDECIMAL18, TAN(CDECIMAL18) from datatypetestm;
select cidx, CDECIMAL18_2, TAN(CDECIMAL18_2) from datatypetestm;
select cidx, CINTEGER, TAN(CINTEGER) from datatypetestm;
select cidx, CSMALLINT, TAN(CSMALLINT) from datatypetestm;
select cidx, CTINYINT, TAN(CTINYINT) from datatypetestm;
select cidx, TAN(0) from datatypetestm;
select cidx, TAN(60) from datatypetestm;
select cidx, TAN(90) from datatypetestm;
select cidx, TAN(180) from datatypetestm;
select cidx, TAN(360) from datatypetestm;
select cidx, CBIGINT from datatypetestm order by TAN(CBIGINT), cidx;
select cidx, CDECIMAL1 from datatypetestm order by TAN(CDECIMAL1), cidx;
select cidx, CDECIMAL4 from datatypetestm order by TAN(CDECIMAL4), cidx;
select cidx, CDECIMAL4_2 from datatypetestm order by TAN(CDECIMAL4_2), cidx;
select cidx, CDECIMAL5 from datatypetestm order by TAN(CDECIMAL5), cidx;
select cidx, CDECIMAL9 from datatypetestm order by TAN(CDECIMAL9), cidx;
select cidx, CDECIMAL9_2 from datatypetestm order by TAN(CDECIMAL9_2), cidx;
select cidx, CDECIMAL10 from datatypetestm order by TAN(CDECIMAL10), cidx;
select cidx, CDECIMAL18 from datatypetestm order by TAN(CDECIMAL18), cidx;
select cidx, CDECIMAL18_2 from datatypetestm order by TAN(CDECIMAL18_2), cidx;
select cidx, CINTEGER from datatypetestm order by TAN(CINTEGER), cidx;
select cidx, CSMALLINT from datatypetestm order by TAN(CSMALLINT), cidx;
select cidx, CTINYINT from datatypetestm order by TAN(CTINYINT), cidx;
