drop table if exists table100_char;

create table `table100_char` (`char_1` char(1),
`char_9` char(9),
`varchar_8` varchar(8),
`char_4` char(4),
`varchar_4` varchar(4),
`varchar_1` varchar(1),
`varchar_2` varchar(2),
`char_8` char(8),
`varchar_9` varchar(9),
`char_255` char(255),
`char_2` char(2),
`varchar_255` varchar(255)) engine=infinidb ;

insert into table100_char values 
('go', 't', 'from', null, 'c', 'b', 'go', 'd', 'q', null, null, 'q'),
('hey', 't', null, 'x', 'r', 'g', null, null, 'k', 'o', 'a', null),
('h', 'didn\'t', null, 'l', 'x', 'if', null, 'e', 'can\'t', 's', null, 'l'),
('v', 'all', 'did', 'n', 'v', null, 'have', 'p', 'g', 'x', 'l', null),
('this', null, 'can\'t', 'yeah', null, 'all', 'f', 'good', 'i', 'v', null, null),
('u', null, null, 'a', 'as', null, 'why', null, 'z', 'g', 'p', 'f'),
(null, 'out', 'have', null, null, null, 'w', 'u', null, 'a', 'go', null),
('just', 'i\'m', 'a', 'now', 'can', null, null, 'didn\'t', 'r', null, 'l', 'f'),
('w', 'u', null, null, 'all', 'he\'s', 'n', 'e', null, 'b', null, 'the'),
('b', 'to', 'really', 'j', null, 'z', 'h', 'w', 'r', null, 'n', 'who'),
('like', 'p', 'd', 'x', 'got', 'l', 'm', 'that\'s', 'n', 'w', 'e', null),
(null, 'c', 'u', 'from', 'q', null, null, 'n', 't', 'b', null, 's'),
('i', 'we', 'j', null, 'q', 'v', null, 'c', 's', null, 'k', 'a'),
(null, 't', 'got', 'got', 'r', 'the', 'l', null, 'z', 'here', 'j', 'o'),
('you\'re', 'f', 'o', null, null, 'l', 'what', 'e', null, null, 'i', 'that\'s'),
('s', 'some', 'don\'t', 'o', null, 'your', 'for', 'good', 'q', 'l', 'w', null),
('from', null, 'h', 'and', 'c', 'j', null, null, 'x', null, 't', 'a'),
(null, null, 'j', 'f', null, 'some', 'l', 'be', 'b', 's', 'they', null),
('who', 'l', 'r', null, 't', 'a', null, 'l', null, 'a', 'z', 'i\'m'),
(null, 'z', 'ok', 'she', 'because', 'k', 'z', 'u', 's', null, null, 'o'),
('h', 'x', 'n', 'd', 'p', 'q', null, 'z', 't', null, 'who', 'o'),
('e', 'but', 'w', 'g', null, 'i', 'your', 'u', null, null, 'the', 'j'),
('b', null, 'v', 's', 'when', null, 'n', 'hey', 'x', null, null, null),
('just', 'm', 'he', 'o', 'v', null, 'n', 'didn\'t', 'j', 'x', 'v', 'will'),
(null, 'c', 'get', 'her', 'w', null, 'y', 'e', 'so', 'w', null, 'him'),
('at', 'get', 'd', 'the', null, 'p', null, 'c', 'p', 'h', 'p', null),
('c', 'b', 'we', 'her', 'e', 'k', 'v', 'q', null, 'i', 'j', 'f'),
(null, null, 'it', 'or', 'a', 'i', 'you', 'f', 'he', null, null, 'g'),
('we', 'i', 'r', null, 'j', 'a', 'y', 'a', 's', null, 'p', 'q'),
('c', 'he', 'v', null, null, 'she', 'g', 'it\'s', null, 'o', 'good', 'f'),
('g', 'or', 'l', null, 'j', 'v', 'i', 'b', null, 'e', 'f', 'come'),
('i\'ll', null, 'c', 'r', 'c', 'r', 'x', null, null, null, null, 'm'),
('l', null, 's', 'b', 'z', 'k', 'l', null, 'i', 's', 'don\'t', 'l'),
('f', 'v', null, 'h', null, 'b', null, 'would', 'y', 'b', 't', 'k'),
('f', 'x', 's', null, 'mean', null, 'f', null, 'n', null, 'on', 'who'),
('u', null, 'z', 'z', null, null, 'u', 'n', null, null, null, 'come'),
('of', 'from', null, 's', 'g', 'a', 'i', null, null, 'right', 's', null),
('h', 'about', 'g', 's', 'n', null, 't', 'it\'s', 't', null, null, null),
('had', null, 's', 'x', null, 'd', 'j', 'who', 'o', 'f', 'h', null),
(null, 'b', 'know', 'a', 'l', null, 'his', null, 'get', 'know', 'k', null),
(null, 'l', 'think', 'just', 'y', 'l', 'e', null, 'z', null, 'j', 'b'),
(null, null, 'x', null, 'd', 'g', 'o', null, 'w', null, null, 'a'),
(null, 'c', 'l', 'a', 'c', 'l', null, 'well', 'm', null, 'y', null),
('m', 'r', 'on', null, 'k', null, null, 'z', 'f', 'd', 's', null),
('a', 'n', 'x', null, 'h', 'come', null, null, 'i', 'did', 'x', 'k'),
(null, 'i', 'k', null, null, 'have', 'q', 'got', 'this', null, 'about', 'or'),
('are', null, 'g', 'h', 'w', 'back', 'x', 'y', null, 'o', 'oh', 'h'),
('on', 'k', 'a', 'is', 'with', 'him', null, 'e', 'u', 's', 'l', null),
(null, 'are', null, 'get', null, 'now', 'didn\'t', 'really', 'q', 'k', null, null),
(null, 'o', 'n', 'u', 'm', 'i', 'some', 'i', 'w', 'u', null, 'mean'),
(null, 's', null, null, 'do', 'r', 's', 'm', 'z', 'q', 'm', null),
(null, null, null, 'will', 'say', null, 'h', 'p', 'will', 'a', 'you', 'c'),
('k', 'c', null, null, 'h', null, 's', 'c', 'been', 't', 'b', 'm'),
(null, null, 'and', 'a', 'a', 'l', 'd', 'one', 'j', null, 'o', 'r'),
('get', 'x', null, 'y', 'b', 'was', 'b', 'q', 'o', 'g', null, 'your'),
('q', 'up', null, 'the', 'm', null, 'j', 'that', 's', 'i', 'or', 'n'),
('a', 'he\'s', 'k', 'x', 'if', null, 'yes', 'be', 'd', 'about', 'd', 'v'),
('don\'t', 'e', 'i', 'on', 'a', 'if', 'i\'m', 'h', 'd', 'all', 'but', 'say'),
('w', 'my', null, 'you', 'y', null, 'o', 'b', null, 'he\'s', 'well', 'm'),
('m', 'l', 'c', 'go', 'if', 'then', null, 'get', 'she', 'z', 'w', 'f'),
('his', null, 'u', 'w', 's', 'h', 'not', null, 'no', null, 't', 'it\'s'),
(null, 'z', 'i', 'what', 'k', 'm', null, 'b', 'i', 's', 'g', 'right'),
('n', 'are', 'b', 'i', 'v', null, 'my', null, null, 'q', 'l', 'l'),
('r', 'g', 'b', 'going', null, 'k', 'were', 'because', null, 'in', 'u', null),
('b', 'look', 'going', 'yeah', 'z', null, 's', 'and', 'l', 'v', 'r', 'a'),
(null, 's', null, null, 'that', 'm', null, 'to', null, 'd', 'o', null),
(null, null, 'n', 'yeah', 'k', 'n', 'f', 'up', null, 'm', 'k', null),
('n', 'h', null, 'o', 'but', null, 'p', null, 'd', 'didn\'t', 'was', 'w'),
('i', null, null, 'one', null, null, null, 't', 'n', null, 'do', null),
('a', 'hey', 'why', 'q', 'p', 't', 'i', 'c', null, 'n', 'p', 'g'),
('u', null, 'h', 'y', 'p', 'o', 'n', 's', null, 'm', 'will', 'what'),
('p', 'd', 'z', 'l', 't', 'because', 'look', null, 'really', null, 'i', 'so'),
('n', null, null, null, 'z', 'u', null, 'g', 'p', 'that\'s', 'now', 'p'),
('they', 'it\'s', 'l', 'j', 'y', 'p', null, null, null, 'for', 'g', 'know'),
(null, 'a', 'that\'s', 'u', 'no', 'l', null, 'r', 'ok', 'k', null, 'b'),
('mean', 'x', 'u', null, null, 'b', 'we', 't', 'r', 'm', 'q', 'b'),
('q', 'yeah', 'v', 'l', 'w', 'j', null, 'n', 'c', 'j', 'y', null),
('is', 'you', 'y', 'k', 'c', null, 'think', 'o', 'hey', 'be', 'a', null),
('e', 'something', 'f', 'd', 'don\'t', 'g', null, 'd', 'f', 'come', 'for', null),
('w', 'g', 'can\'t', 'm', 'how', 'h', 'k', 'a', 'about', 'j', 'he\'s', 'l'),
('d', 'r', null, null, null, 'i', null, 'u', 'of', 'w', 'l', 'g'),
('z', 'do', 'but', 'g', null, 'h', null, null, 'h', null, 'x', null),
('b', 'e', 'j', 'z', 'l', 'i\'ll', 'o', null, 'm', 'ok', 'g', 'n'),
('h', null, null, 'k', 'y', 'q', 'q', null, 'in', 'i', 'say', 'because'),
('y', null, null, 'one', 'then', null, null, null, null, 'with', null, 'e'),
(null, 'with', 'z', 'going', null, null, 'because', 'z', null, 'be', 'p', null),
('he', 'i', null, null, 'she', null, null, null, 'something', 'b', 'me', null),
(null, 'p', null, 'l', null, null, 'e', 'n', 'z', 'go', null, 's'),
('o', 'k', null, 'c', 'h', null, 't', 'l', 'x', null, 'z', 'h'),
('b', 'all', 'f', 'v', 'something', 'h', 'have', 'mean', 'a', 's', 'a', 'are'),
('something', 'x', 'k', 'did', 'i', 'c', 'z', null, null, 'yeah', 'what', 'l'),
('he', null, null, 'going', null, null, 'u', null, 'on', 'e', 'u', 'who'),
('y', null, 'w', 'v', 'a', null, 'a', 'j', 'h', 'x', 'm', 'p'),
(null, 'right', 'k', 'w', 'a', 'j', 'k', 'f', 'o', 'i', 'x', null),
('e', 'j', null, 'from', null, 'you\'re', 'l', 'z', 'f', null, null, 'k'),
('g', 'out', 'are', 'q', 'z', 'i', 'go', 'b', 'z', 'because', 'h', 'really'),
(null, 'had', 'he', null, 'i\'m', 'so', 'mean', null, null, 'i', 'have', 'y'),
('r', 'e', 'j', 'h', 'had', 'z', 'l', null, 'y', 'mean', null, 'q'),
('r', 'd', 'd', null, 'x', 'm', 'c', 'g', 'z', 'r', null, 'e'),
('up', 'q', 'd', null, 'x', 'have', null, 'w', 'it', 'v', null, null);

