#Char to numeric type conversion
SELECT (LENGTH(CCHAR7) + '2')/2 FROM DATATYPETESTM;
SELECT (LENGTH(CCHAR7) - '2')/2 FROM DATATYPETESTM;
SELECT (LENGTH(CCHAR7) * '2')/2 FROM DATATYPETESTM;
SELECT (LENGTH(CCHAR7) / '2')/2 FROM DATATYPETESTM;
SELECT CIDX FROM DATATYPETESTM WHERE (LENGTH(CCHAR7) + '2')/2 = 2;
SELECT CIDX FROM DATATYPETESTM WHERE (LENGTH(CCHAR7) - '2')/2 = 1;
SELECT CIDX FROM DATATYPETESTM WHERE (LENGTH(CCHAR7) * '2')/2 = 3;
SELECT CIDX FROM DATATYPETESTM WHERE (LENGTH(CCHAR7) / '2')/2 = 0.25;
SELECT POWER('12',2) FROM DATATYPETESTM;
SELECT POWER(12,'2') FROM DATATYPETESTM;
SELECT POWER('12','2') FROM DATATYPETESTM;
SELECT POWER(CCHAR1,2) FROM DATATYPETESTM;
SELECT POWER(CCHAR9,2) FROM DATATYPETESTM;
SELECT POWER(CVCHAR1,2) FROM DATATYPETESTM;
SELECT POWER(CVCHAR8,2) FROM DATATYPETESTM;
SELECT CIDX FROM DATATYPETESTM WHERE POWER(CCHAR1,2) = 0;
SELECT CIDX FROM DATATYPETESTM WHERE POWER(CCHAR9,2) = 0;
SELECT CIDX FROM DATATYPETESTM WHERE POWER(CVCHAR1,2) = 0;
SELECT CIDX FROM DATATYPETESTM WHERE POWER(CVCHAR8,2) = 0;
#
#Numeric to char type conversion
SELECT CONCAT(CCHAR5, 3.14) FROM DATATYPETESTM;
SELECT CONCAT(CCHAR5, CTINYINT) FROM DATATYPETESTM;
SELECT CIDX FROM DATATYPETESTM WHERE CONCAT(CCHAR5, 3.14) = 'zzzzz3.14';
SELECT CIDX FROM DATATYPETESTM WHERE CONCAT(CCHAR5, CTINYINT) ='vvvvv123';
#nested functions;
SELECT POWER(SUBSTR(CONCAT(CCHAR5, CTINYINT),4),2) FROM DATATYPETESTM;
SELECT CIDX FROM DATATYPETESTM WHERE POWER(SUBSTR(CONCAT(CCHAR5, CTINYINT),4),2) = 625;
SELECT SIGN(SUBSTR(LENGTH(CONCAT(CCHAR5, CTINYINT, SIGN(CINTEGER), 123)) * CTINYINT,2,3)) as col1 FROM DATATYPETESTM;
SELECT CIDX FROM DATATYPETESTM WHERE ISNULL(SIGN(SUBSTR(LENGTH(CONCAT(CCHAR5, CTINYINT, SIGN(CINTEGER), 123)) * CTINYINT,2,3)));




