#Multiple function
SELECT CIDX, LENGTH(CVCHAR7) + SIGN(CINTEGER) + INSTR(CDATE,31) - 2 as test FROM DATATYPETESTM;
#
SELECT CIDX FROM DATATYPETESTM WHERE LENGTH(CVCHAR7) + SIGN(CINTEGER) + INSTR(CDATE,31) - 2 = 6;
