#Single function
SELECT CSMALLINT + SIGN(CINTEGER) - 2 FROM DATATYPETESTM;
SELECT CSMALLINT + LENGTH(CVCHAR7) - 2 FROM DATATYPETESTM;
SELECT CSMALLINT + INSTR(CDATE,'12') - 2 FROM DATATYPETESTM;
#
SELECT CIDX FROM DATATYPETESTM WHERE CSMALLINT + SIGN(CINTEGER) - 2 <= 32767;
SELECT CIDX FROM DATATYPETESTM WHERE CSMALLINT + LENGTH(CVCHAR7) - 2 > 0;
SELECT CIDX FROM DATATYPETESTM WHERE CSMALLINT + INSTR(CDATE,'12') - 2 = 32767;

