select AVG(CBIGINT) from datatypetestm;
select AVG(CDECIMAL1) from datatypetestm;
select AVG(CDECIMAL4) from datatypetestm;
select AVG(CDECIMAL4_2) from datatypetestm;
select AVG(CDECIMAL5) from datatypetestm;
select AVG(CDECIMAL9) from datatypetestm;
select AVG(CDECIMAL9_2) from datatypetestm;
select AVG(CDECIMAL10) from datatypetestm;
select AVG(CDECIMAL18) from datatypetestm;
select AVG(CDECIMAL18_2) from datatypetestm;
select AVG(CINTEGER) from datatypetestm;
select AVG(CSMALLINT) from datatypetestm;
select AVG(CTINYINT) from datatypetestm;
select cidx, CBIGINT, AVG(CBIGINT) from datatypetestm group by cidx, CBIGINT;
select cidx, CDECIMAL1, AVG(CDECIMAL1) from datatypetestm group by cidx, CDECIMAL1;
select cidx, CDECIMAL4, AVG(CDECIMAL4) from datatypetestm group by cidx, CDECIMAL4;
select cidx, CDECIMAL4_2, AVG(CDECIMAL4_2) from datatypetestm group by cidx, CDECIMAL4_2;
select cidx, CDECIMAL5, AVG(CDECIMAL5) from datatypetestm group by cidx, CDECIMAL5;
select cidx, CDECIMAL9, AVG(CDECIMAL9) from datatypetestm group by cidx, CDECIMAL9;
select cidx, CDECIMAL9_2, AVG(CDECIMAL9_2) from datatypetestm group by cidx, CDECIMAL9_2;
select cidx, CDECIMAL10, AVG(CDECIMAL10) from datatypetestm group by cidx, CDECIMAL10;
select cidx, CDECIMAL18, AVG(CDECIMAL18) from datatypetestm group by cidx, CDECIMAL18;
select cidx, CDECIMAL18_2, AVG(CDECIMAL18_2) from datatypetestm group by cidx, CDECIMAL18_2;
select cidx, CINTEGER, AVG(CINTEGER) from datatypetestm group by cidx, CINTEGER;
select cidx, CSMALLINT, AVG(CSMALLINT) from datatypetestm group by cidx, CSMALLINT;
select cidx, CTINYINT, AVG(CTINYINT) from datatypetestm group by cidx, CTINYINT;
