select cidx, CBIGINT, COT(CBIGINT) from datatypetestm;
select cidx, CDECIMAL1, COT(CDECIMAL1) from datatypetestm;
select cidx, CDECIMAL4, COT(CDECIMAL4) from datatypetestm;
select cidx, CDECIMAL4_2, COT(CDECIMAL4_2) from datatypetestm;
select cidx, CDECIMAL5, COT(CDECIMAL5) from datatypetestm;
select cidx, CDECIMAL9, COT(CDECIMAL9) from datatypetestm;
select cidx, CDECIMAL9_2, COT(CDECIMAL9_2) from datatypetestm;
select cidx, CDECIMAL10, COT(CDECIMAL10) from datatypetestm;
select cidx, CDECIMAL18, COT(CDECIMAL18) from datatypetestm;
select cidx, CDECIMAL18_2, COT(CDECIMAL18_2) from datatypetestm;
select cidx, CINTEGER, COT(CINTEGER) from datatypetestm;
select cidx, CSMALLINT, COT(CSMALLINT) from datatypetestm;
select cidx, CTINYINT, COT(CTINYINT) from datatypetestm;
select cidx, COT(0) from datatypetestm;
select cidx, COT(60) from datatypetestm;
select cidx, COT(90) from datatypetestm;
select cidx, COT(180) from datatypetestm;
select cidx, COT(360) from datatypetestm;
select cidx, CBIGINT from datatypetestm order by COT(CBIGINT), cidx;
select cidx, CDECIMAL1 from datatypetestm order by COT(CDECIMAL1), cidx;
select cidx, CDECIMAL4 from datatypetestm order by COT(CDECIMAL4), cidx;
select cidx, CDECIMAL4_2 from datatypetestm order by COT(CDECIMAL4_2), cidx;
select cidx, CDECIMAL5 from datatypetestm order by COT(CDECIMAL5), cidx;
select cidx, CDECIMAL9 from datatypetestm order by COT(CDECIMAL9), cidx;
select cidx, CDECIMAL9_2 from datatypetestm order by COT(CDECIMAL9_2), cidx;
select cidx, CDECIMAL10 from datatypetestm order by COT(CDECIMAL10), cidx;
select cidx, CDECIMAL18 from datatypetestm order by COT(CDECIMAL18), cidx;
select cidx, CDECIMAL18_2 from datatypetestm order by COT(CDECIMAL18_2), cidx;
select cidx, CINTEGER from datatypetestm order by COT(CINTEGER), cidx;
select cidx, CSMALLINT from datatypetestm order by COT(CSMALLINT), cidx;
select cidx, CTINYINT from datatypetestm order by COT(CTINYINT), cidx;
