select cidx, CBIGINT+2 from datatypetestm;
select cidx, CBIGINT-2 from datatypetestm;
select cidx, CBIGINT*2 from datatypetestm;
select cidx, CBIGINT/2 from datatypetestm;
select cidx, CBIGINT+2.4 from datatypetestm;
select cidx, CBIGINT-2.4 from datatypetestm;
select cidx, CBIGINT*2.4 from datatypetestm;
select cidx, CBIGINT/2.4 from datatypetestm;
select cidx, CDECIMAL1+2 from datatypetestm;
select cidx, CDECIMAL1-2 from datatypetestm;
select cidx, CDECIMAL1*2 from datatypetestm;
select cidx, CDECIMAL1/2 from datatypetestm;
select cidx, CDECIMAL1+2.4 from datatypetestm;
select cidx, CDECIMAL1-2.4 from datatypetestm;
select cidx, CDECIMAL1*2.4 from datatypetestm;
select cidx, CDECIMAL1/2.4 from datatypetestm;
select cidx, CDECIMAL4+2 from datatypetestm;
select cidx, CDECIMAL4-2 from datatypetestm;
select cidx, CDECIMAL4*2 from datatypetestm;
select cidx, CDECIMAL4/2 from datatypetestm;
select cidx, CDECIMAL4+2.4 from datatypetestm;
select cidx, CDECIMAL4-2.4 from datatypetestm;
select cidx, CDECIMAL4*2.4 from datatypetestm;
select cidx, CDECIMAL4/2.4 from datatypetestm;
select cidx, CDECIMAL4_2+2 from datatypetestm;
select cidx, CDECIMAL4_2-2 from datatypetestm;
select cidx, CDECIMAL4_2*2 from datatypetestm;
select cidx, CDECIMAL4_2/2 from datatypetestm;
select cidx, CDECIMAL4_2+2.4 from datatypetestm;
select cidx, CDECIMAL4_2-2.4 from datatypetestm;
select cidx, CDECIMAL4_2*2.4 from datatypetestm;
select cidx, CDECIMAL4_2/2.4 from datatypetestm;
select cidx, CDECIMAL5+2 from datatypetestm;
select cidx, CDECIMAL5-2 from datatypetestm;
select cidx, CDECIMAL5*2 from datatypetestm;
select cidx, CDECIMAL5/2 from datatypetestm;
select cidx, CDECIMAL5+2.4 from datatypetestm;
select cidx, CDECIMAL5-2.4 from datatypetestm;
select cidx, CDECIMAL5*2.4 from datatypetestm;
select cidx, CDECIMAL5/2.4 from datatypetestm;
select cidx, CDECIMAL9+2 from datatypetestm;
select cidx, CDECIMAL9-2 from datatypetestm;
select cidx, CDECIMAL9*2 from datatypetestm;
select cidx, CDECIMAL9/2 from datatypetestm;
select cidx, CDECIMAL9+2.4 from datatypetestm;
select cidx, CDECIMAL9-2.4 from datatypetestm;
select cidx, CDECIMAL9*2.4 from datatypetestm;
select cidx, CDECIMAL9/2.4 from datatypetestm;
select cidx, CDECIMAL9_2+2 from datatypetestm;
select cidx, CDECIMAL9_2-2 from datatypetestm;
select cidx, CDECIMAL9_2*2 from datatypetestm;
select cidx, CDECIMAL9_2/2 from datatypetestm;
select cidx, CDECIMAL9_2+2.4 from datatypetestm;
select cidx, CDECIMAL9_2-2.4 from datatypetestm;
select cidx, CDECIMAL9_2*2.4 from datatypetestm;
select cidx, CDECIMAL9_2/2.4 from datatypetestm;
select cidx, CDECIMAL10+2 from datatypetestm;
select cidx, CDECIMAL10-2 from datatypetestm;
select cidx, CDECIMAL10*2 from datatypetestm;
select cidx, CDECIMAL10/2 from datatypetestm;
select cidx, CDECIMAL10+2.4 from datatypetestm;
select cidx, CDECIMAL10-2.4 from datatypetestm;
select cidx, CDECIMAL10*2.4 from datatypetestm;
select cidx, CDECIMAL10/2.4 from datatypetestm;
select cidx, CDECIMAL18+2 from datatypetestm;
select cidx, CDECIMAL18-2 from datatypetestm;
select cidx, CDECIMAL18*2 from datatypetestm;
select cidx, CDECIMAL18/2 from datatypetestm;
select cidx, CDECIMAL18+2.4 from datatypetestm;
select cidx, CDECIMAL18-2.4 from datatypetestm;
select cidx, CDECIMAL18*2.4 from datatypetestm;
select cidx, CDECIMAL18/2.4 from datatypetestm;
select cidx, CDECIMAL18_2+2 from datatypetestm;
select cidx, CDECIMAL18_2-2 from datatypetestm;
select cidx, CDECIMAL18_2*2 from datatypetestm;
select cidx, CDECIMAL18_2/2 from datatypetestm;
select cidx, CDECIMAL18_2+2.4 from datatypetestm;
select cidx, CDECIMAL18_2-2.4 from datatypetestm;
select cidx, CDECIMAL18_2*2.4 from datatypetestm;
select cidx, CDECIMAL18_2/2.4 from datatypetestm;
select cidx, CINTEGER+2 from datatypetestm;
select cidx, CINTEGER-2 from datatypetestm;
select cidx, CINTEGER*2 from datatypetestm;
select cidx, CINTEGER/2 from datatypetestm;
select cidx, CINTEGER+2.4 from datatypetestm;
select cidx, CINTEGER-2.4 from datatypetestm;
select cidx, CINTEGER*2.4 from datatypetestm;
select cidx, CINTEGER/2.4 from datatypetestm;
select cidx, CSMALLINT+2 from datatypetestm;
select cidx, CSMALLINT-2 from datatypetestm;
select cidx, CSMALLINT*2 from datatypetestm;
select cidx, CSMALLINT/2 from datatypetestm;
select cidx, CSMALLINT+2.4 from datatypetestm;
select cidx, CSMALLINT-2.4 from datatypetestm;
select cidx, CSMALLINT*2.4 from datatypetestm;
select cidx, CSMALLINT/2.4 from datatypetestm;
select cidx, CTINYINT+2 from datatypetestm;
select cidx, CTINYINT-2 from datatypetestm;
select cidx, CTINYINT*2 from datatypetestm;
select cidx, CTINYINT/2 from datatypetestm;
select cidx, CTINYINT+2.4 from datatypetestm;
select cidx, CTINYINT-2.4 from datatypetestm;
select cidx, CTINYINT*2.4 from datatypetestm;
select cidx, CTINYINT/2.4 from datatypetestm;
select cidx, CBIGINT from datatypetestm order by CBIGINT+2, cidx;
select cidx, CBIGINT from datatypetestm order by CBIGINT-2, cidx;
select cidx, CBIGINT from datatypetestm order by CBIGINT*2, cidx;
select cidx, CBIGINT from datatypetestm order by CBIGINT/2, cidx;
select cidx, CBIGINT from datatypetestm order by CBIGINT+2.4, cidx;
select cidx, CBIGINT from datatypetestm order by CBIGINT-2.4, cidx;
select cidx, CBIGINT from datatypetestm order by CBIGINT*2.4, cidx;
select cidx, CBIGINT from datatypetestm order by CBIGINT/2.4, cidx;
select cidx, CDECIMAL1 from datatypetestm order by CDECIMAL1+2, cidx;
select cidx, CDECIMAL1 from datatypetestm order by CDECIMAL1-2, cidx;
select cidx, CDECIMAL1 from datatypetestm order by CDECIMAL1*2, cidx;
select cidx, CDECIMAL1 from datatypetestm order by CDECIMAL1/2, cidx;
select cidx, CDECIMAL1 from datatypetestm order by CDECIMAL1+2.4, cidx;
select cidx, CDECIMAL1 from datatypetestm order by CDECIMAL1-2.4, cidx;
select cidx, CDECIMAL1 from datatypetestm order by CDECIMAL1*2.4, cidx;
select cidx, CDECIMAL1 from datatypetestm order by CDECIMAL1/2.4, cidx;
select cidx, CDECIMAL4 from datatypetestm order by CDECIMAL4+2, cidx;
select cidx, CDECIMAL4 from datatypetestm order by CDECIMAL4-2, cidx;
select cidx, CDECIMAL4 from datatypetestm order by CDECIMAL4*2, cidx;
select cidx, CDECIMAL4 from datatypetestm order by CDECIMAL4/2, cidx;
select cidx, CDECIMAL4 from datatypetestm order by CDECIMAL4+2.4, cidx;
select cidx, CDECIMAL4 from datatypetestm order by CDECIMAL4-2.4, cidx;
select cidx, CDECIMAL4 from datatypetestm order by CDECIMAL4*2.4, cidx;
select cidx, CDECIMAL4 from datatypetestm order by CDECIMAL4/2.4, cidx;
select cidx, CDECIMAL4_2 from datatypetestm order by CDECIMAL4_2+2, cidx;
select cidx, CDECIMAL4_2 from datatypetestm order by CDECIMAL4_2-2, cidx;
select cidx, CDECIMAL4_2 from datatypetestm order by CDECIMAL4_2*2, cidx;
select cidx, CDECIMAL4_2 from datatypetestm order by CDECIMAL4_2/2, cidx;
select cidx, CDECIMAL4_2 from datatypetestm order by CDECIMAL4_2+2.4, cidx;
select cidx, CDECIMAL4_2 from datatypetestm order by CDECIMAL4_2-2.4, cidx;
select cidx, CDECIMAL4_2 from datatypetestm order by CDECIMAL4_2*2.4, cidx;
select cidx, CDECIMAL4_2 from datatypetestm order by CDECIMAL4_2/2.4, cidx;
select cidx, CDECIMAL5 from datatypetestm order by CDECIMAL5+2, cidx;
select cidx, CDECIMAL5 from datatypetestm order by CDECIMAL5-2, cidx;
select cidx, CDECIMAL5 from datatypetestm order by CDECIMAL5*2, cidx;
select cidx, CDECIMAL5 from datatypetestm order by CDECIMAL5/2, cidx;
select cidx, CDECIMAL5 from datatypetestm order by CDECIMAL5+2.4, cidx;
select cidx, CDECIMAL5 from datatypetestm order by CDECIMAL5-2.4, cidx;
select cidx, CDECIMAL5 from datatypetestm order by CDECIMAL5*2.4, cidx;
select cidx, CDECIMAL5 from datatypetestm order by CDECIMAL5/2.4, cidx;
select cidx, CDECIMAL9 from datatypetestm order by CDECIMAL9+2, cidx;
select cidx, CDECIMAL9 from datatypetestm order by CDECIMAL9-2, cidx;
select cidx, CDECIMAL9 from datatypetestm order by CDECIMAL9*2, cidx;
select cidx, CDECIMAL9 from datatypetestm order by CDECIMAL9/2, cidx;
select cidx, CDECIMAL9 from datatypetestm order by CDECIMAL9+2.4, cidx;
select cidx, CDECIMAL9 from datatypetestm order by CDECIMAL9-2.4, cidx;
select cidx, CDECIMAL9 from datatypetestm order by CDECIMAL9*2.4, cidx;
select cidx, CDECIMAL9 from datatypetestm order by CDECIMAL9/2.4, cidx;
select cidx, CDECIMAL9_2 from datatypetestm order by CDECIMAL9_2+2, cidx;
select cidx, CDECIMAL9_2 from datatypetestm order by CDECIMAL9_2-2, cidx;
select cidx, CDECIMAL9_2 from datatypetestm order by CDECIMAL9_2*2, cidx;
select cidx, CDECIMAL9_2 from datatypetestm order by CDECIMAL9_2/2, cidx;
select cidx, CDECIMAL9_2 from datatypetestm order by CDECIMAL9_2+2.4, cidx;
select cidx, CDECIMAL9_2 from datatypetestm order by CDECIMAL9_2-2.4, cidx;
select cidx, CDECIMAL9_2 from datatypetestm order by CDECIMAL9_2*2.4, cidx;
select cidx, CDECIMAL9_2 from datatypetestm order by CDECIMAL9_2/2.4, cidx;
select cidx, CDECIMAL10 from datatypetestm order by CDECIMAL10+2, cidx;
select cidx, CDECIMAL10 from datatypetestm order by CDECIMAL10-2, cidx;
select cidx, CDECIMAL10 from datatypetestm order by CDECIMAL10*2, cidx;
select cidx, CDECIMAL10 from datatypetestm order by CDECIMAL10/2, cidx;
select cidx, CDECIMAL10 from datatypetestm order by CDECIMAL10+2.4, cidx;
select cidx, CDECIMAL10 from datatypetestm order by CDECIMAL10-2.4, cidx;
select cidx, CDECIMAL10 from datatypetestm order by CDECIMAL10*2.4, cidx;
select cidx, CDECIMAL10 from datatypetestm order by CDECIMAL10/2.4, cidx;
select cidx, CDECIMAL18 from datatypetestm order by CDECIMAL18+2, cidx;
select cidx, CDECIMAL18 from datatypetestm order by CDECIMAL18-2, cidx;
select cidx, CDECIMAL18 from datatypetestm order by CDECIMAL18*2, cidx;
select cidx, CDECIMAL18 from datatypetestm order by CDECIMAL18/2, cidx;
select cidx, CDECIMAL18 from datatypetestm order by CDECIMAL18+2.4, cidx;
select cidx, CDECIMAL18 from datatypetestm order by CDECIMAL18-2.4, cidx;
select cidx, CDECIMAL18 from datatypetestm order by CDECIMAL18*2.4, cidx;
select cidx, CDECIMAL18 from datatypetestm order by CDECIMAL18/2.4, cidx;
select cidx, CDECIMAL18_2 from datatypetestm order by CDECIMAL18_2+2, cidx;
select cidx, CDECIMAL18_2 from datatypetestm order by CDECIMAL18_2-2, cidx;
select cidx, CDECIMAL18_2 from datatypetestm order by CDECIMAL18_2*2, cidx;
select cidx, CDECIMAL18_2 from datatypetestm order by CDECIMAL18_2/2, cidx;
select cidx, CDECIMAL18_2 from datatypetestm order by CDECIMAL18_2+2.4, cidx;
select cidx, CDECIMAL18_2 from datatypetestm order by CDECIMAL18_2-2.4, cidx;
select cidx, CDECIMAL18_2 from datatypetestm order by CDECIMAL18_2*2.4, cidx;
select cidx, CDECIMAL18_2 from datatypetestm order by CDECIMAL18_2/2.4, cidx;
select cidx, CINTEGER from datatypetestm order by CINTEGER+2, cidx;
select cidx, CINTEGER from datatypetestm order by CINTEGER-2, cidx;
select cidx, CINTEGER from datatypetestm order by CINTEGER*2, cidx;
select cidx, CINTEGER from datatypetestm order by CINTEGER/2, cidx;
select cidx, CINTEGER from datatypetestm order by CINTEGER+2.4, cidx;
select cidx, CINTEGER from datatypetestm order by CINTEGER-2.4, cidx;
select cidx, CINTEGER from datatypetestm order by CINTEGER*2.4, cidx;
select cidx, CINTEGER from datatypetestm order by CINTEGER/2.4, cidx;
select cidx, CSMALLINT from datatypetestm order by CSMALLINT+2, cidx;
select cidx, CSMALLINT from datatypetestm order by CSMALLINT-2, cidx;
select cidx, CSMALLINT from datatypetestm order by CSMALLINT*2, cidx;
select cidx, CSMALLINT from datatypetestm order by CSMALLINT/2, cidx;
select cidx, CSMALLINT from datatypetestm order by CSMALLINT+2.4, cidx;
select cidx, CSMALLINT from datatypetestm order by CSMALLINT-2.4, cidx;
select cidx, CSMALLINT from datatypetestm order by CSMALLINT*2.4, cidx;
select cidx, CSMALLINT from datatypetestm order by CSMALLINT/2.4, cidx;
select cidx, CTINYINT from datatypetestm order by CTINYINT+2, cidx;
select cidx, CTINYINT from datatypetestm order by CTINYINT-2, cidx;
select cidx, CTINYINT from datatypetestm order by CTINYINT*2, cidx;
select cidx, CTINYINT from datatypetestm order by CTINYINT/2, cidx;
select cidx, CTINYINT from datatypetestm order by CTINYINT+2.4, cidx;
select cidx, CTINYINT from datatypetestm order by CTINYINT-2.4, cidx;
select cidx, CTINYINT from datatypetestm order by CTINYINT*2.4, cidx;
select cidx, CTINYINT from datatypetestm order by CTINYINT/2.4, cidx;
