# This is the modified version of:
# https://stackoverflow.com/questions/73935448/installing-and-linking-to-apache-arrow-inside-cmake

# Build the Arrow C++ libraries.
include(ExternalProject)

set(ARROW_PREFIX "${CMAKE_CURRENT_BINARY_DIR}/external/arrow")
set(ARROW_STATIC_LIBRARY_DIR "${ARROW_PREFIX}/lib")
set(ARROW_STATIC_LIB_FILENAME
    "${CMAKE_STATIC_LIBRARY_PREFIX}arrow${CMAKE_STATIC_LIBRARY_SUFFIX}")
set(ARROW_STATIC_LIB "${ARROW_STATIC_LIBRARY_DIR}/${ARROW_STATIC_LIB_FILENAME}")
set(PARQUET_STATIC_LIB_FILENAME
    "${CMAKE_STATIC_LIBRARY_PREFIX}parquet${CMAKE_STATIC_LIBRARY_SUFFIX}")
set(PARQUET_STATIC_LIB "${ARROW_STATIC_LIBRARY_DIR}/${PARQUET_STATIC_LIB_FILENAME}")
link_directories("${ARROW_STATIC_LIBRARY_DIR}")

set(ARROW_BINARY_DIR "${ARROW_PREFIX}/bin")
set(ARROW_CMAKE_ARGS "-DCMAKE_INSTALL_PREFIX=${ARROW_PREFIX}"
        "-DCMAKE_INSTALL_LIBDIR=lib"
        "-DARROW_BUILD_STATIC=ON"
        "-DARROW_BUILD_SHARED=OFF"
        "-DARROW_DEPENDENCY_SOURCE=BUNDLED"
        "-DARROW_DEPENDENCY_USE_SHARED=OFF"
        "-DARROW_DATASET=ON"
        "-DARROW_PARQUET=ON"
        "-DARROW_FILESYSTEM=ON")
set(ARROW_INCLUDE_DIR "${ARROW_PREFIX}/include")

set(ARROW_BUILD_BYPRODUCTS "${ARROW_STATIC_LIB}" "${PARQUET_STATIC_LIB}")

externalproject_add(external_arrow
        URL https://github.com/apache/arrow/archive/refs/tags/apache-arrow-12.0.1.tar.gz
        URL_HASH SHA256=f01b76a42ceb30409e7b1953ef64379297dd0c08502547cae6aaafd2c4a4d92e
        SOURCE_SUBDIR cpp
        BINARY_DIR "${ARROW_BINARY_DIR}"
        CMAKE_ARGS "${ARROW_CMAKE_ARGS}"
        BUILD_BYPRODUCTS "${ARROW_BUILD_BYPRODUCTS}")

set(ARROW_LIBRARY_TARGET arrow_static)
set(PARQUET_LIBRARY_TARGET parquet_static)

file(MAKE_DIRECTORY "${ARROW_INCLUDE_DIR}")
add_library(${ARROW_LIBRARY_TARGET} STATIC IMPORTED)
add_library(${PARQUET_LIBRARY_TARGET} STATIC IMPORTED)
set_target_properties(${ARROW_LIBRARY_TARGET}
        PROPERTIES INTERFACE_INCLUDE_DIRECTORIES ${ARROW_INCLUDE_DIR}
        IMPORTED_LOCATION ${ARROW_STATIC_LIB})
set_target_properties(${PARQUET_LIBRARY_TARGET}
        PROPERTIES INTERFACE_INCLUDE_DIRECTORIES ${ARROW_INCLUDE_DIR}
        IMPORTED_LOCATION ${PARQUET_STATIC_LIB})

add_dependencies(external_arrow external_thrift)
add_dependencies(${ARROW_LIBRARY_TARGET} external_arrow)
